### ISSUE TITLE
CSGO - Server go offline by himself

### ISSUE THREAD

**Issue by OverlOrDGT** [dgibbs64/linuxgsm#1009]
Hi,
I am having a problem with cs go, all the time i press "./csgoserver start" it turn's on, and immediately go offline, i dont know whats hapening since no error happens...
Can someone help pls?!

**Comment by UltimateByte** [comment]
Hi,

Hibernatio ? 
GSLT ,?

**Comment by cedarlug** [comment]
Run with `./csgoserver debug` and post the output (to pastebin)
Post the output of `./csgoserver details` (to pastebin and link here)

Too little information provided for us to be more helpful.

**Comment by OverlOrDGT** [comment]
There it is...

http://pastebin.com/3Me9v9ad
http://pastebin.com/FQDt3pvu

**Comment by marvinl97** [comment]
@OverlOrDGT Please revoke your token quickly! https://steamcommunity.com/dev/managegameservers
You didn't censor it in the log!


Apparently port 27015 is already in use? Do you have any other servers running on this port?
`netstat -atunp | grep 27015`

**Comment by OverlOrDGT** [comment]
Nothing, i just have ts3, cs and a rust server

**Comment by marvinl97** [comment]
Could you try running it with?
`ip="0.0.0.0"`

**Comment by OverlOrDGT** [comment]
now he stills on, but somehow i cant see it online on steam but i add the port on iptables

**Comment by OverlOrDGT** [comment]
it works fine now
thx for help

**Comment by marvinl97** [comment]
Your welcome! :)
But what was the final solution/step?
