### ISSUE TITLE
Add -autoupdate feature

### ISSUE THREAD

**Issue by dgibbs64** [dgibbs64/linuxgsm#127]
-autoupdate can be added to update the servers as soon as an update is released on SteamCMD. It may be worth adding the switch to all servers that support it

**Comment by iNilo** [comment]
I'm looking into this currently, was this actually added ?

` -autoupdate -steam_dir <insert steam path>/ -steamcmd_script <name for update script>.txt`

<name for update script>.txt

`login anonymous

force_install_dir <insert steam path>/<rest of the path to the cs folder>/cs/

app_update 740 validate

exit`

**Comment by UltimateByte** [comment]
@iNilo I'm not sure if this autoupdate is still a thing.
I personally like to cronjob it. You can even cronjob it every 30 minutes or every hour or whatever you like as long as it isn't too short. 
https://github.com/GameServerManagers/LinuxGSM/wiki/Update

**Comment by iNilo** [comment]
@UltimateByte very true, so was I but its nicer to do it from within the server process itself.
1) plugin notices an update
2) plugin waits for match/round/map to finish and warns players
3) plugin communicates with other servers and advises players to move to another server (which have updated)
4) plugin does a hard countdown (30s before shutdown)
5) plugin kicks the users with a message that the server is shutting down for an update.

Its much nicer for players then just to nuke the server with a cronjob and a mass timeout.

It would be very nice that lgsm generates the lines & the update file. which then can be turned off & on within the config/main script.

the current way (cronjobs) is perfectly fine, however it could be more user friendly using plugins with kick messages and _restart

**Comment by iNilo** [comment]
To followup, this is a functional sourcemod plugin that has this functionality (partially)
https://github.com/Sarabveer/SM-Plugins/blob/master/sw_auto_steam_update/scripting/auto_steam_update.sp

**Comment by UltimateByte** [comment]
Mh... It seems quite hard to me to integrate a plugin to LGSM's behavior. However, a similar idea had been proposed
Here: https://github.com/GameServerManagers/LinuxGSM/issues/674
And especially here: https://github.com/GameServerManagers/LinuxGSM/pull/890

I'd be happy to work on this 890 thing, with custom text and so on.

**Comment by iNilo** [comment]
The plugins are for server administrators, I'd rather see support for the command line then for the plugins itself.

Making LGSM generate an update script, with appropriate command line addons such as `-autoupdate -steam_dir` is much more feasible than supporting sourcemod plugins

**Comment by UltimateByte** [comment]
Well, and then how would you run the script without a cronjob ?
LGSM is already an update script, so i don't really get your idea.
What i see then is more of a console command sent if an update is found an a timer as proposed in #890.
Would be nice to really implement rcon at some point so that even games like rust with no console could benefit from it.

**Comment by iNilo** [comment]
The idea is that rather than relying on cronjob, use the native builtin functionality of updating csgo servers. 

more like ./csgoserver generateupdatescripts 
and then inside ./csgoserver 
use_external_update_scripts = true.

**Comment by UltimateByte** [comment]
And how exactly srcds would know it should have to use this script ? That's what i don't get.
For me autoupdate would happen at srcds level, so i don't see how it would use an external script, LGSM or not.

**Comment by iNilo** [comment]
its build into the CSGO/TF2/... srcds.

`-autoupdate - Attempts to auto-update the server when an update comes out. You MUST use -steam_dir and -steamcmd_script`

I found this issue and I thought it was added, nothing more to it?

**Comment by UltimateByte** [comment]
So just just append -autoupdate to start parms then it will update as soon as possible. This is what i thought for the beginning. Then how does this autoupdate starts a script upon updates ? Does it have to have a specific name ? Location ?

**Comment by walliski** [comment]
:+1: for adding built in support for autoupdate

When you add the autoupdate to your command line arguments when starting the server you also need to provide steamcmd with a script to run. This script basically tells steamcmd to update a server in a specific folder. However this script is not available by default in LGSM?

Would be good to use autoupdate at least for CS:GO, since it updates automatically when a server is empty, but not else...
