### ISSUE TITLE
[arma3server] More option friendly 

### ISSUE THREAD

**Issue by jlatour88** [dgibbs64/linuxgsm#193]
Iv looked over ur great linux manager and I must say I'm very impressed. It has alot of great features. However i have a request if it isnt to much to ask. If u like it maybe ul include it. 
I'm currently using a version of an updated arma 2 start/stop/update/ect script and it's OK but it's lacking on features. But its got a pretty easy to understand editable section where u add ur mods and extra parameters.
 Il post the code snippet below. 
Let me know if this is somthing that can possibly be added with the way ur scripts is setup. 
http://forums.bistudio.com/showthread.php?135490-Linux-dedicated-server-run-with-mods

**Comment by dgibbs64** [comment]
mod suport has been added to arma3server. Hopefully this should make things easier
