### ISSUE TITLE
[Fortress Forever] Creation

### ISSUE THREAD

**Issue by Xylemon** [dgibbs64/linuxgsm#228]
Fortress Forever will be releasing on Steam very soon (currently on Steam in beta form). If you could add support for it after release that would be great. It is on SDK Base 2006 however just like NeoTokyo, so it may not have proper Linux server support. We shall see when it releases completely.

**Comment by dgibbs64** [comment]
Taken another look at this since FF has moved to Steampipe. There are no Linux Binarys for this server on SteamCMD. Will have to wait until they decide to re-create them on SteamCMD

**Comment by Xylemon** [comment]
I talked to one of the FF devs not too long ago. They tried hacking around with the SDK 2006 Linux Binaries to work with the new Steampipe system and they couldn't get them to work. It's very unlikely we'll get a Linux server unless they switch over to SDK 2013 (which they really need to stop squeezing every bit of life out of SDK Base 2006).

**Comment by dgibbs64** [comment]
SDK Base 2006 is why Hidden: Source doesn't work well anymore :(. I wish someone would continue development with that mod

**Comment by Xylemon** [comment]
Yeah, it's a damn shame.
