### ISSUE TITLE
[LGSM] Servers to update on start

### ISSUE THREAD

**Issue by dgibbs64** [dgibbs64/linuxgsm#244]
A suggestion from @Rob-123 to have an option for servers to update as part of the start routine. 

I think this should be a optional setting that can be turned on if the admin wants.

    updateonstart=yes

**Comment by medic917** [comment]
Where is updateonstart=yes in the script?
I don't see it on the latest script.

Did you implement the  https://steamdb.info ?

**Comment by Scarsz** [comment]
This is an enhancement request, meaning it's not yet in the script.

Sounds like a good idea personally, could replace the update & start command with noupdate & start

**Comment by dgibbs64** [comment]
https://github.com/dgibbs64/linuxgsm/commit/c1ad3e6716dbb1da3ab3f66da74d1464d8b36101 feature now added
