### ISSUE TITLE
[TeamFortressClassic] Stuck in update loop

### ISSUE THREAD

**Issue by Xylemon** [dgibbs64/linuxgsm#274]
On other games like Killing Floor, updating is fine and reports the following:

[  OK  ] Update kf-server: Checking for update: SteamCMD

No update available:
	Current version: 460851
	Available version: 460851
	https://steamdb.info/app/215360/

But when done with TFC, this happens:

[ WARN ] Update tfc-server: No appmanifest_90 +app_set_config 90 mod tfc.acf fou
[ INFO ] Update tfc-server: Forcing update to correct issue
[ .... ] Update tfc-server: Updating Chuck Bronson's Prestige and Well-Mannered 
[  OK  ] Update tfc-server: Updating Chuck Bronson's Prestige and Well-Mannered Debate Lounge [BETA]

And keeps updating over and over until the the server admin stops the script.

**Comment by Scarsz** [comment]
OS/arch

**Comment by dgibbs64** [comment]
Interesting issue. It probably has something to do with how gold source games handling app manifest files differently. I will look in to a fix for this.....Gold source games are a big pain in my back side most of the time.

**Comment by dgibbs64** [comment]
I have been unable to download the server files again. I have updated this issue https://github.com/ValveSoftware/halflife/issues/1583#issuecomment-73278666 however its not promising.

**Comment by Xylemon** [comment]
Considering Valve still has broken custom sprays in GoldSrc games, I too am doubtful they'll fix the issue. Thanks for trying to get the source of this problem.

**Comment by dgibbs64** [comment]
Im planning on bypassing the update checker for goldsrc games. SteamCMD is still pretty broken for goldsrc. at least you will be able to run the update-restart feature for these servers. Stay tuned for updates

**Comment by dgibbs64** [comment]
merging with issue #323
