### ISSUE TITLE
[mumbleserver] Update

### ISSUE THREAD

**Issue by dgibbs64** [dgibbs64/linuxgsm#280]
I will be updating both these scripts to bring them back in line with all the others as they are massively out of date.

**Comment by AlienXAXS** [comment]
Hey @dgibbs64,
I have created some dodgy PHP code that scans the TS3 download repo and returns the latest version number.

To return only the version number:
https://www.agngaming.com/github/ts3version/?vonly=1

To return how many versions and the latest:
https://www.agngaming.com/github/ts3version

If you're interested in this for some sort of ./ts3server update command let me know :)

**Comment by AlienXAXS** [comment]
Okay i got it now :D

Check this URL for the latest x64 version:
https://www.agngaming.com/github/ts3version/index.php?bit=amd64

Check this URL for the latest i386 version:
https://www.agngaming.com/github/ts3version/index.php?bit=i386

They are returning JSON, first value being the version number, 2nd value being the download link.

I hope this helps you better your scripts :)

**Comment by dgibbs64** [comment]
That's brilliant. I will look at using the code for this update. I recommend you create a github repo so I can use the code on my domain also, there may be quite a few people interested in using that code :-)

**Comment by AlienXAXS** [comment]
Here you go:
https://github.com/AlienXAXS/Teamspeak3_LatestVersion/blob/master/index.php

**Comment by dgibbs64** [comment]
Awesome. im currently working on updating ts3server. This will be a feature I will be working on :D

**Comment by dgibbs64** [comment]
ts3server has now been intergrated however no update feature just yet (on my do-to list)

**Comment by Xylemon** [comment]
Can there be some type of debug option for TS3? My server keeps crashing and I'm not quite sure the cause.

**Comment by dgibbs64** [comment]
Ts3 does not work the same way as the other servers do (no tmux). so not currently. THey do have pretty decent logs though so check them out

**Comment by Xylemon** [comment]
Well that's why I asked because I saw nothing in the logs. Everything looks normal except that at one point it just seems to stop, very odd.
