### ISSUE TITLE
Half-Life WON2 Server Support

### ISSUE THREAD

**Issue by Xylemon** [dgibbs64/linuxgsm#294]
This a bit of a weird one to do, and I may look into writing these scripts myself. Basically WON2 is a continuation of the WON/CD version of Half-Life. There are Linux servers that I need to investigate because I've been having trouble getting them to run on 64-bit systems.

**Comment by dgibbs64** [comment]
If you want to write for it go ahead :)

**Comment by dgibbs64** [comment]
I will not be adding support for this myself
