### ISSUE TITLE
[gmodserver] Server is crashing

### ISSUE THREAD

**Issue by nikkimas** [dgibbs64/linuxgsm#295]
It worked a few days, but then it suddenly didn't.
I installed it fresh, several times.
This is from the debug.log: http://pastebin.com/gWR86sbN

Hope you can help me

**Comment by dgibbs64** [comment]
What's the output of ./gmodserver details?

**Comment by nikkimas** [comment]
that was a fast answer :D  
http://pastebin.com/uzdznnQy

**Comment by dgibbs64** [comment]
Debian 8... Interesting I cannot see any obvious reason why you are getting a set fault. Try reinstalling the dependencies . Might work but apart from that I'm not sure.

**Comment by nikkimas** [comment]
okay, how do I do that? Google research showed me different things, and I don't want to brake anything

**Comment by dgibbs64** [comment]
apt-get remove etc etc :). Seg faults are very hard to diagnose as it dont give you much to go off. Also try validate as well....might help

**Comment by Scarsz** [comment]
`sudo apt-get purge ia32-libs lib32gcc1 tmux gdb mailutils postfix ca-certificates lib32gcc1 -y;sudo apt-get install ia32-libs lib32gcc1 tmux gdb mailutils postfix ca-certificates lib32gcc1 -y`

**Comment by dgibbs64** [comment]
yup that should work. However already be careful then removing stuff :)

**Comment by nikkimas** [comment]
Okay, I did that, but it returned an Error message http://pastebin.com/NhNHDm5Z

**Comment by Scarsz** [comment]
`sudo apt-get purge default-jre -y;sudo apt-get install openjdk-8-jre-headless lib32gcc1 tmux gdb mailutils postfix ca-certificates lib32gcc1 -y;

**Comment by nikkimas** [comment]
Okay, I think my Server hates me:

E: Unable to locate package openjdk-8-jre-headless

**Comment by Scarsz** [comment]
What shows up from `apt-cache search java headless`

**Comment by nikkimas** [comment]
This: http://pastebin.com/ymvB7V01

**Comment by Scarsz** [comment]
sudo apt-get purge ant default-jre -y && sudo apt-get install openjdk-7-jre-headless lib32gcc1 tmux gdb mailutils postfix ca-certificates lib32gcc1 -y

**Comment by nikkimas** [comment]
It still does not work. And @dgibbs64 I asked my Server provider, and he told me its not Debian 8 but Debian 7

**Comment by dgibbs64** [comment]
Odd as thats what is being picked up from your server details. It looks like your server has something pretty messed up on it. Ideally reloading the server would be good. I also recommend using Ubuntu LTS or CentOS 7 as they are the most compatible.

**Comment by Montclair** [comment]
We had seg faults as well with our L4D2 server on Debian. We tried everything to fix it and the only solution that worked was gong to Ubuntu 14.

**Comment by dgibbs64** [comment]
Debian does not seem to be the best distro for some game servers. Mainly because of the older software it uses. You cannot go wrong with Ubuntu however and CentOS 7 also works well
