### ISSUE TITLE
error while loading shared libraries: libgcc_s.so.1: Centos 6.5

### ISSUE THREAD

**Issue by Swerone** [dgibbs64/linuxgsm#308]
Hello, after installed centos 6,5 i have problem using the installer.
Its work fine on ubuntu and have saved med mutch time.
Whats the problem?
```
=================================
Counter Strike: Global Offensive
Linux Game Server Manager
by Daniel Gibbs
http://danielgibbs.co.uk
=================================

Installing SteamCMD
=================================
Steam already installed!

Installing Counter Strike: Global Offensive Server
=================================
/home/csgoserver/cs2/steamcmd/linux32/steamcmd: error while loading shared libraries: libgcc_s.so.1: cannot open shared object file: No such file or directory

=================================
Was the install successful? [y/N]^C
```

**Comment by dgibbs64** [comment]
I dont think you have installed the prerequisites correctly.

**Comment by Forge-Media** [comment]
I got the same error, I installed another dependency which solved this just need to find the link

**Comment by Swerone** [comment]
I solved it by running "yum install libgcc_s.so.1" and install libgcc_s.so.1 i have followed the tot.

But thanks and have a nice day

**Comment by Swerone** [comment]
I solved it by running "yum install libgcc_s.so.1" and install libgcc_s.so.1 i have followed the tot.

But thanks and have a nice day

**Comment by Swerone** [comment]
I solved it by running "yum install libgcc_s.so.1" and install libgcc_s.so.1 i have followed the tot.

But thanks and have a nice day

**Comment by Swerone** [comment]
I solved it by running "yum install libgcc_s.so.1" and install libgcc_s.so.1 i have followed the tot.

But thanks and have a nice day

**Comment by Swerone** [comment]
I solved it by running "yum install libgcc_s.so.1" and install libgcc_s.so.1 i have followed the tot.

But thanks and have a nice day

**Comment by Swerone** [comment]
I solved it by running "yum install libgcc_s.so.1" and install libgcc_s.so.1 i have followed the tot.

But thanks and have a nice day

**Comment by Swerone** [comment]
I solved it by running "yum install libgcc_s.so.1" and install libgcc_s.so.1 i have followed the tot.

But thanks and have a nice day

**Comment by Swerone** [comment]
I solved it by running "yum install libgcc_s.so.1" and install libgcc_s.so.1 i have followed the tot.

But thanks and have a nice day

**Comment by Swerone** [comment]
I solved it by running "yum install libgcc_s.so.1" and install libgcc_s.so.1 i have followed the tot.

But thanks and have a nice day

**Comment by Swerone** [comment]
Hahha i dident see your comment but thanks Forge-Media

**Comment by dgibbs64** [comment]
added this to docs
