### ISSUE TITLE
[arma3server] requesting support for -mod= parameter

### ISSUE THREAD

**Issue by rickt** [dgibbs64/linuxgsm#310]
i added a comment to issue #270 but now realise i should have opened a separate issue (since it had already been closed). 

i am requesting full support for the -mod= parameter to the arma3server binary. this is how we add additional "@modules" to the server. in the docs and issue comments for your [wonderful!!] script, the -mod parameter is used, but only with a single mod, such as

-mod=ExtDB

this is fine, and it works. however, an arma requirement is that multiple mods are separated by semi-colons. i know, i know, this is ridiculous, but this is what Bohemia gives us. many server admins run their arma servers with many mods, especially the @cba_a3 and @task_force_radio mods (which is what i require). 

i've tried many methods to try and integrate multiple mods into the fn_parms of arma3server, all to no avail. i've tried escaping the semicolon using backslash. i've tried single quotes within the existing parameter double quotes, i've tried more double quotes (obviously escaping them). but nothing has worked. i've tried putting the mods i need into a variable and using -mod=${mod}, and other variations therein. all my usual unix-y tricks have failed me. i've performed an exhaustive search of the githib project and have come up with naught.

as an example of an arma3 server binary running with multiple mods enabled, here's how i run one of my current servers (not managed with your arma3server script, sadly):

`/home/arma3/arma3server -bepath=/home/arma3/battleye -cfg=/home/arma3/basic.cfg -config=/home/arma3/public.cfg -noSound -name=public -mod=/home/arma3;@a3mp;@agm;@bornholm;@caf_ag;@cba_a3;@clf_mods;@task_force_radio; -port=2302 -exThreads=7`

its quite rare that arma3 dedicated servers are brought up with no mods or only a single mod (extDB for example), so the functionality i'm requesting is certainly not unusual.

would it be possible for semi-colon separated modules in the form of the above `-mod=@foo;@bar;` parameter to be supported?

thank you so much in advance,
@rickt

**Comment by Scarsz** [comment]
Would it be possible? Yes
Do I myself know how to do it (without doing any tests/research)? No

See if this Stack link helps you out any
http://stackoverflow.com/questions/18272804/assigning-a-value-having-semicolon-to-a-variable-in-bash

**Comment by dgibbs64** [comment]
Arma 3 is a server I still don't fully understand. I will have to spend a bit of time on this. There are quite a few things I need tgo do with mods for ARMA 3 as they are very popular.

**Comment by aikidoka** [comment]
I found that the following additions work for my config file:

>fn_parms(){
>parms=" -ip=${ip} -config=${servercfg} **-mod=${mods}**"
>}

`#### Advanced Variables ####`

`# ARMA 3 Settings`
>**mods="mods/\@cba_a3\;mods/\@task_force_radio"**

I am forking this repo in order to create some changes for the ARMA 3 configs. I have also added a config directory and the network config file, I will add those to my fork. These were needed as I have several instances running on my server, since I develop missions and test them there.

**Comment by dgibbs64** [comment]
@aikidoka thats great news. I dont run an ARMA 3 server so you adding this is ideal.

**Comment by dgibbs64** [comment]
This feature is now merged

**Comment by nikkimas** [comment]
hey, sry for reopening this, but I can't install mods. Do I have to change something in the config or do permission stuff (I think I did the stuff that is written in the arma3server file about chmod). The mods are not loading properly. Can anyone Help?

**Comment by aikidoka** [comment]
Please post the output from:
`ls -laR` in the arma3server user home folder 
&
a copy of your `arma3-server-console.log` file as [pastebin](http://pastebin.com/) links? 

Hopefully it's an easy fix.

**Comment by nikkimas** [comment]
Of Course.

ls -laR:
      http://pastebin.com/btG9gNgV

arma3-server-console.log:
      http://pastebin.com/SuC85baJ

**Comment by aikidoka** [comment]
Couple of points:

Looks like you set the permissions for /mods as 777 not 775 (this could create a security issue)

CBA did load, but the other two mods (list in the mods dir) didn't load. I should have asked for this before, but send the `mods=""` line from the arma3server script.

**Comment by nikkimas** [comment]
I tried a lot of thing, so thats why its 777 ^^
mods="mods/\@cba_a3\;

**Comment by aikidoka** [comment]
ok, the mods in the mods line did load, so it's working. if you're trying to load the other two mods, you'll need to add them like: `mods="mods/\@cba_a3\;mods/\@xCam\;mods/\@inidbi\;"`

However, I've read briefly about those mods (xcam does look cool)... I believe those are Windows only mods; [iniDBi was ported to linux](https://github.com/newtondev/inidb-linux).

**Comment by nikkimas** [comment]
hmm, that explains a lot. I'll try it with ACE3 and let you know if it works.
it should be `mods="mods/\@cba_a3\;mods/\@ace\;` right?

**Comment by nikkimas** [comment]
nope, does not work. Shall I send some logs again?

**Comment by aikidoka** [comment]
yes, you're escaping the special characters `@ ;` with the backslash `\`

I'm not sure, but for clean config code sake, be sure to close the line with the `"`

And one more thing, linux is case-sensitive. since BI didn't write anything into their code to allow for case-insensitivity (as is the case on Windows), can sometimes run into problems with that for this server.

**Comment by aikidoka** [comment]
yeah, pastebin the console log

**Comment by nikkimas** [comment]
I hope you mean the console log in `/home/arma3server/log/console/arma3-server-console.log`

http://pastebin.com/Fd6JuAvT

**Comment by aikidoka** [comment]
not sure why the HLC errors are popping up, might be related to the older version of ace (current is 3.2.1) and the newer arma 3 release (1.48). I've no clue on that, but the mod did load: 

`19:08:07                  Advanced Combat Environment 3.1.1 |                 @ace |      false |             GAME DIR | 2a71c3ceffe325a1bb3962edd21858aa242d9f54 |  22f03ced | /home/arma3server/serverfiles/mods/@ace`

`19:08:07                      Community Base Addons v1.1.23 |              @cba_a3 |      false |             GAME DIR | 6e8bb771784d88b872afe978d7e2f2eebf86900c |  6f16089c | /home/arma3server/serverfiles/mods/@cba_a3`

so we know the lgsm script is working correctly. 

you should check that your files are not corrupted and updated. that console log is your best friend with the arma3server. generally it's filled with noise, but good for issues like this.

**Comment by nikkimas** [comment]
hmm. I updatet all mods on both client and Server. But when I try to join I'm getting kicked. There are no Errors now (at least I can't spot any) but it still does not work. http://pastebin.com/82hG3WPY
Can you help my anyways?

**Comment by nikkimas** [comment]
If anyone has this issue:
1. `chmod -R 775 /home/arma3server/serverfiles/mods` (or where ever your mods folder is).
2. some addons have `key` folders. Copy the files to `/home/arma3server/serverfiles/keys` (or where ever your ArmA installation is)
