### ISSUE TITLE
[l4d1Server] LAN servers are restricted to local clients (class C)

### ISSUE THREAD

**Issue by faflfama** [dgibbs64/linuxgsm#311]
Hi,
I just set up a server, which then Starts fine. When I try to connect it shows "LAN servers are restricted to local clients (class C)". I tried to set sv_lan "0", but that didnt help. Did I do something wrong?

Fabian D.

**Comment by faflfama** [comment]
No solution?

**Comment by dgibbs64** [comment]
Not sure on this one. I will investigate when I can. However there may be solutions around as this isn't a script issue.

**Comment by faflfama** [comment]
Thanks for the answer, alt least Im glad I didnt do sth wrong.

**Comment by faflfama** [comment]
Solved it for me:
Copied a steamclient.so from a working L4D2 and copied it to "steamcmd/linux32" and ".steam/sdk32". After that the server started normally.

**Comment by nikolaydan** [comment]
This bug is depending of OS, I tried different Linux distribs and server worked with Ubuntu 14.10 and CentOS 7.1.
I had this error with Ubuntu 14.04, Centos 6, Centos 7.0, Debian 7.

I used EXACTLY the same files (i used .tar archive and tried same archive on different OS).
