### ISSUE TITLE
[TF2] Server not updating after update-restart

### ISSUE THREAD

**Issue by andrewc2** [dgibbs64/linuxgsm#319]
Started server in debug mode.

MasterRequestRestart
Your server needs to be restarted in order to receive the latest update.

./tf2server update
No Update Available. Current version: 529790 Available Version: 529790

Deleted /functions/ and tried to update again, same result.

**Comment by Scarsz** [comment]
What command did you exactly do? `./tf2server debug`?

**Comment by andrewc2** [comment]
Yes sorry should have stated that.

**Comment by dgibbs64** [comment]
I have made a couple of changes to the updater to try and resolve this issue. Please let me know how you get on b8312d1

**Comment by dgibbs64** [comment]
Also see https://github.com/dgibbs64/linuxgsm/issues/301

**Comment by dgibbs64** [comment]
Merging this one
