### ISSUE TITLE
Cannot connect to steam public

### ISSUE THREAD

**Issue by DooMFeaR** [dgibbs64/linuxgsm#320]
Cannot connect to steam public. Tried everyday for the last week. :( 
 Thank you in advance!

![untitled](https://cloud.githubusercontent.com/assets/11584706/6764901/1116c30c-cfd0-11e4-8ca6-e36b107609f6.png)

**Comment by Scarsz** [comment]
This might seem dumb but do you have some sort of firewall like iptables blocking SteamCMD?

**Comment by dgibbs64** [comment]
That would be my guess. I haven't seen this issue before

**Comment by DooMFeaR** [comment]
@Scarsz , The firewall was the first thing I checked when I got that error. Updating SteamCMD worked flawlessly.

**Comment by DooMFeaR** [comment]
Can someone help me out?
![untitled](https://cloud.githubusercontent.com/assets/11584706/6781706/3ef1160c-d178-11e4-8d3a-e010b51dcd43.png)

**Comment by Scarsz** [comment]
Try this?

```
iptables -A INPUT -p udp -m udp --sport 27000:27030 --dport 1025:65355 -j ACCEPT
iptables -A INPUT -p udp -m udp --sport 4380 --dport 1025:65355 -j ACCEPT
```

**Comment by DooMFeaR** [comment]
@Scarsz . I tried, still not working :(. What ports should I have opened in the router?

**Comment by dgibbs64** [comment]
Im guessing you have confirmed its your firewall by turning it for for a couple of mins to test?

**Comment by DooMFeaR** [comment]
I removed my router and connect the cable directly to my server... Still nothing :(
