### ISSUE TITLE
[LGSM] Improved Updater

### ISSUE THREAD

**Issue by dgibbs64** [dgibbs64/linuxgsm#323]
I will be making adjustments to the updater to add the following

* Update restart requirement detection - This will merge "update" and "update-restart". The idea is that if the server is online and an update is required the server will restart during update. If there is an update but the server is offline there is no requirement to restart. (implemented)

* Get Gold source update checker working. This is a little more complicated than others

* The updater will check logs first to see if the server requests a restart as this was causing an issue with servers not being able to get update info from steamcmd. (implemented)

**Comment by dgibbs64** [comment]
https://github.com/dgibbs64/linuxgsm/commit/904df3a3b92560b0f517997367e42d99f06712b3

**Comment by dgibbs64** [comment]
Gold Source servers now bypass fn_steamcmdcheck as a fix. To get Gold Source servers working fully would require a lot of work that I don't think is currently feasable. However this will at least get the updater working again.

**Comment by zcythe** [comment]
Hi, I am using multiple config file approach for multiple game instance on a same server.
I have a cronjob set to run every 15min to check if there is an update available.

The first update command in the cronjob run nicely. The first game instance get updated and restart itself without any hassle. 

However, the next few game instance which run the lgsm update will found the game server files is updated and do nothing. Those instances are still running on older version of game server files resources which loaded in memory (I guess).
 
Is there anyway to restart all the game instance that using the same game server file once an update is done?
