### ISSUE TITLE
arma3server -port command line setting

### ISSUE THREAD

**Issue by aikidoka** [dgibbs64/linuxgsm#325]
After getting the -mod setting working, I started (tried) moving my other ARMA 3 instances over to linuxgsm for exclusive control. However, I've run into a big problem with how the port settings are configured. 

Since the 1.22 build, ARMA 3 port settings have been moved exclusively to the command line port setting. This was removed in update #251, but it has to be added back.

>STEAM ports in Arma 3 build 1.22.125469 or newer are hardcoded as now linked to game-port of the server instance (+1 query +2 report to master)

I understand this creates a lot of issues with how the monitoring works and currently limits port usage to the default ports only.

I am going to start working on the issue, so that linuxgsm supports multiple instances on a single server. It may make sense to try and integrate the #270 suggestions into these changes, but first thing first - the port setting, then monitoring, then hopefully the enhancements.

**Comment by dgibbs64** [comment]
Thanks for this I will move this over. SOon
