### ISSUE TITLE
[LGSM] Auto-restart feature

### ISSUE THREAD

**Issue by Xylemon** [dgibbs64/linuxgsm#327]
Something I truly miss while using the scripts is the lack of an auto-restart feature. There have been quite a few times with these scripts where my server has been down for a day or two and I had no idea.  This would be really useful in keeping a server up as much as possible.

**Comment by dgibbs64** [comment]
Use crontab? Monitor or restart would work. Thats all auto-restart would do.

**Comment by Xylemon** [comment]
Couldn't this functionality be written into the scripts though? I'll use crontab for now, but I'm just saying having it actually in the scripts would be nice.

**Comment by dgibbs64** [comment]
Crontab is designed to be used for time based stuff and is an ideal solution. The other solution is to have to leave the script running in the background constantly which is not something I want to start doing.
