### ISSUE TITLE
Unable to access 'getting started' on webpage

### ISSUE THREAD

**Issue by DerfOh** [dgibbs64/linuxgsm#329]
Hi! Just giving you a heads up that there is a 404 error when trying to access 'getting started' on your application web page, furthermore the other link on your page goes to a PHP error:

>MediaWiki 1.23.9
>LocalSettings.php not found.
>Please set up the wiki first.

**Comment by dgibbs64** [comment]
Yup the wiki is pretty broken. Havnt had any time to fix. Will be in the next few days :-)

**Comment by altembo** [comment]
fyi: the link on the orange button ("getting started) works fine instead ([click me](http://gameservermanagers.com))

**Comment by dgibbs64** [comment]
Wiki is online again however will be moving to github wiki soon
