### ISSUE TITLE
csgoserver email test failure

### ISSUE THREAD

**Issue by rent52** [dgibbs64/linuxgsm#330]
Well, this is what I get

csgoserver@ip-***-**-**-54:~$ ./csgoserver email-test
[ .... ] Email csgo-server: Sending notification to fernandotieppo@outlook.com/h                                                                                                                                                             ome/csgoserver/functions/fn_email: line 40: mail: command not found
[  OK  ] Email csgo-server: Sending notification to fernandotieppo@outlook.com
csgoserver@ip-**-**-**-54:~$

**Comment by Scarsz** [comment]
Install postfix
