### ISSUE TITLE
always Checking session: FAIL arma3server monitor by crontab on tmux 1.9a

### ISSUE THREAD

**Issue by macchky** [dgibbs64/linuxgsm#331]
but manually executes "arma3server monitor" is succeeded

**Comment by macchky** [comment]
rebooting solved issue ....

**Comment by Scarsz** [comment]
What exactly is the problem here? Monitor doesn't work with crontab?

**Comment by macchky** [comment]
I updated tmux 1.8 to 1.9a, this require rebooting pc...
before rebooting "tmux list-sessions" by cron getting error "failed to connect to server: Connection refused" so monitor always "Checking session: FAIL".

After reboot problem is solved.

**Comment by dgibbs64** [comment]
Thanks for the info. Closing this.
