### ISSUE TITLE
ts3server install command bug 

### ISSUE THREAD

**Issue by Takmashido** [dgibbs64/linuxgsm#335]
According to the install instrucations' page on github the command "./ts3server install" does'nt work.
Here what I've got : 
./ts3server install
loading fn_functions...©ponse... 200 OK
loading fn_messages...©ponse... 200 OK
loading fn_getopt...©ponse... 200 OK
Usage: ./ts3server {start|stop|restart|backup|monitor|email-test|details|backup}

**Comment by gOOvER** [comment]
Thats the aswer:

"Usage: ./ts3server {start|stop|restart|backup|monitor|email-test|details|backup}"

;)

There is no install for TS3 ;)

**Comment by Takmashido** [comment]
Ok but maybe the install instructions could be correted ?

**Comment by gOOvER** [comment]
hmmmm, i don't see any install Intructions for TS3 on Github. The only thing:

Installer (SteamCMD)

But as you see: SteamCMD ;)

**Comment by Takmashido** [comment]
I meaned according to this [page](https://github.com/dgibbs64/linuxgsm/wiki/Install#Teamspeak-3)

**Comment by gOOvER** [comment]
Ok, your right. 

https://github.com/dgibbs64/linuxgsm/tree/master/functions

I see no fuction for installing TS3

**Comment by dgibbs64** [comment]
I will add clarification on this :-) when I'm back home

**Comment by dgibbs64** [comment]
There is no install option however there is an update function. Ouphs my error on the documentation. I will amend this. :)

**Comment by dgibbs64** [comment]
;-)  #337
