### ISSUE TITLE
fn_update_check: line 288: syntax error: unexpected end of file

### ISSUE THREAD

**Issue by Takmashido** [dgibbs64/linuxgsm#336]
The update script seems to be bugged
fn_update_check: line 288: syntax error: unexpected end of file

**Comment by gOOvER** [comment]
Do you upload it by hand??? Maybe an "Enter" is missig or you save it wrong. For me it works without problems.

When you are on Linux install dos2unix and convert the file.

Then restart it again ;)

**Comment by Takmashido** [comment]
I did'nt upload it by hand, the script downloaded it directly from github. dos2unix does'nt solve the problem and an "Enter" at the end too.

**Comment by gOOvER** [comment]
Which command do you use, when erroro occour??

**Comment by Takmashido** [comment]
./insserver update 
I tried with starbound server and but same error too but it's the same function for all scipts so.
Maybe someone could try to backup fn_update_check and delete it so that the script download it again for seeing if the same error occurs

**Comment by dgibbs64** [comment]
Interesting. I was working on this last night and I thought it was working. Delete the functions dir and try again. If it still fails again it may be my fault :-)

**Comment by Takmashido** [comment]
I deleted the functions folder and it failed again ^^.

**Comment by dgibbs64** [comment]
Thanks I will investigate

**Comment by dgibbs64** [comment]
Should now work. Delete functions again and let me know :)

**Comment by Takmashido** [comment]
Yes it works now :D
