### ISSUE TITLE
CentOS 7 FAQ Update

### ISSUE THREAD

**Issue by nikolaydan** [dgibbs64/linuxgsm#339]
There are to need to add Centos 7 tutorial lines in chapters as Running on Boot and Automation due to changes in cron package on CentOS 7 and autoboot via systemd service.

**Comment by dgibbs64** [comment]
You shoudl be able to make edits to the Wiki. Please feel free to update the details :)

**Comment by dgibbs64** [comment]
Closing lack of activity
