### ISSUE TITLE
[TeamSpeak3] Update returned false latest version and tried to downgrade

### ISSUE THREAD

**Issue by xFaNaTiix** [dgibbs64/linuxgsm#343]
./ts3server update

loading fn_update_check...OK
[  OK  ] Update ts3-server: Checking for update: teamspeak.com

Update available:
        Current build: 3.0.11.2
        Available build: 3.0.11

Applying update...
[  OK  ] Stopping ts3-server: Teamspeak 3 Server
loading fn_update_dl...OK
[  OK  ] Update ts3-server: Updating Teamspeak 3 Server
downloading teamspeak3-server_linux-amd64-3.0.11.tar.gz...OK
extracting teamspeak3-server_linux-amd64-3.0.11.tar.gz...OK
copying to /home/ellis/teamspeak3-server_linux-amd64...FAIL - Exit status 1
cp: ‘/home/ellis/teamspeak3-server_linux-amd64/CHANGELOG’ and ‘/home/ellis/teamspeak3-server_linux-amd64/CHANGELOG’ are the same file
cp: ‘/home/ellis/teamspeak3-server_linux-amd64/doc’ and ‘/home/ellis/teamspeak3-server_linux-amd64/doc’ are the same file
cp: ‘/home/ellis/teamspeak3-server_linux-amd64/files’ and ‘/home/ellis/teamspeak3-server_linux-amd64/files’ are the same file
cp: ‘/home/ellis/teamspeak3-server_linux-amd64/libts3db_mariadb.so’ and ‘/home/ellis/teamspeak3-server_linux-amd64/libts3db_mariadb.so’ are the same file
cp: ‘/home/ellis/teamspeak3-server_linux-amd64/libts3db_mysql.so’ and ‘/home/ellis/teamspeak3-server_linux-amd64/libts3db_mysql.so’ are the same file
cp: ‘/home/ellis/teamspeak3-server_linux-amd64/libts3db_sqlite3.so’ and ‘/home/ellis/teamspeak3-server_linux-amd64/libts3db_sqlite3.so’ are the same file
cp: ‘/home/ellis/teamspeak3-server_linux-amd64/LICENSE’ and ‘/home/ellis/teamspeak3-server_linux-amd64/LICENSE’ are the same file
cp: ‘/home/ellis/teamspeak3-server_linux-amd64/licensekey.dat’ and ‘/home/ellis/teamspeak3-server_linux-amd64/licensekey.dat’ are the same file
cp: ‘/home/ellis/teamspeak3-server_linux-amd64/logs’ and ‘/home/ellis/teamspeak3-server_linux-amd64/logs’ are the same file
cp: ‘/home/ellis/teamspeak3-server_linux-amd64/query_ip_blacklist.txt’ and ‘/home/ellis/teamspeak3-server_linux-amd64/query_ip_blacklist.txt’ are the same file
cp: ‘/home/ellis/teamspeak3-server_linux-amd64/query_ip_whitelist.txt’ and ‘/home/ellis/teamspeak3-server_linux-amd64/query_ip_whitelist.txt’ are the same file
cp: ‘/home/ellis/teamspeak3-server_linux-amd64/redist’ and ‘/home/ellis/teamspeak3-server_linux-amd64/redist’ are the same file
cp: ‘/home/ellis/teamspeak3-server_linux-amd64/redistributables’ and ‘/home/ellis/teamspeak3-server_linux-amd64/redistributables’ are the same file
cp: ‘/home/ellis/teamspeak3-server_linux-amd64/serverkey.dat’ and ‘/home/ellis/teamspeak3-server_linux-amd64/serverkey.dat’ are the same file
cp: ‘/home/ellis/teamspeak3-server_linux-amd64/serverquerydocs’ and ‘/home/ellis/teamspeak3-server_linux-amd64/serverquerydocs’ are the same file
cp: ‘/home/ellis/teamspeak3-server_linux-amd64/sql’ and ‘/home/ellis/teamspeak3-server_linux-amd64/sql’ are the same file
cp: ‘/home/ellis/teamspeak3-server_linux-amd64/ts3-server.ini’ and ‘/home/ellis/teamspeak3-server_linux-amd64/ts3-server.ini’ are the same file
cp: ‘/home/ellis/teamspeak3-server_linux-amd64/ts3server_linux_amd64’ and ‘/home/ellis/teamspeak3-server_linux-amd64/ts3server_linux_amd64’ are the same file
cp: ‘/home/ellis/teamspeak3-server_linux-amd64/ts3server_minimal_runscript.sh’ and ‘/home/ellis/teamspeak3-server_linux-amd64/ts3server_minimal_runscript.sh’ are the same file
cp: ‘/home/ellis/teamspeak3-server_linux-amd64/ts3server.sqlitedb’ and ‘/home/ellis/teamspeak3-server_linux-amd64/ts3server.sqlitedb’ are the same file
cp: ‘/home/ellis/teamspeak3-server_linux-amd64/ts3server_startscript.sh’ and ‘/home/ellis/teamspeak3-server_linux-amd64/ts3server_startscript.sh’ are the same file
cp: ‘/home/ellis/teamspeak3-server_linux-amd64/tsdns’ and ‘/home/ellis/teamspeak3-server_linux-amd64/tsdns’ are the same file

**Comment by dgibbs64** [comment]
Thanks for this. Will have to investigate how to fix this

**Comment by dgibbs64** [comment]
Found the issue and should now be fixed. Please let me know if that resolved the issue. Thanks
https://github.com/dgibbs64/linuxgsm/commit/ff81a85f8ba7e5275c741a9a06575b2de553f0e2

**Comment by Advkt** [comment]
As of yesterday I attempted to update. The server reverted to version 3.3 from version 3.11

**Comment by dgibbs64** [comment]
http://dl.4players.de/ts/releases/?C=M;O=D

I see the issue. They have added a new file to version 3.0.3. This has cause the date to update. This is a pain. Will need to think how to improve this issue

**Comment by dgibbs64** [comment]
I think I have a way to resolve this. I will remove the dots from version number and if higher number its a new version.

**Comment by Advkt** [comment]
Might be an issue if they decide, in a very unlikely scenario, to increment past 9 in the last version section, e.g. 3.11.11. Also if they move to 3.2.1 or 4.0 

Would it be possible to split by full stops and compare each number? So, if you had v4.1.2 verse v3.11.2 it would compare as 4 > 3, find it true and update. With 3.11.2 verse 3.0.3 it would find the first version number equal, check the next and find 11 as the larger/newer value and not update.

**Comment by dgibbs64** [comment]
I have been looking at this last night. Its a pain in the arse. I will be trying various things to figure our the best option. Either way its gunna be complicated because of the version numbers.

But that sounds like a good idea comparing each number between the dots to narrow down the versions until only one is left

**Comment by dgibbs64** [comment]
This issue should now be resolved found a good way to sort the version numbers
https://github.com/dgibbs64/linuxgsm/commit/400b9d346546b5a26db76f617ab4eb5abfc536a5

Please test and let me know if you find anymore issues. Thanks
