### ISSUE TITLE
[sdtdserver] GLIBC fix required

### ISSUE THREAD

**Issue by dgibbs64** [dgibbs64/linuxgsm#347]
I have not out in a GLIBC fix for this server

**Comment by dgibbs64** [comment]
I have just tried to copy the files to the locale directory however this did not work. A fix may not work for this server.

**Comment by chriskoepf** [comment]
GLIBC fix?  Is there a problem somewhere?

**Comment by dgibbs64** [comment]
https://github.com/dgibbs64/linuxgsm/wiki/Glibc

**Comment by dgibbs64** [comment]
Unable to do this one. Closing.
