### ISSUE TITLE
Most Scripts fail to Start and don’t work at all (with fix)

### ISSUE THREAD

**Issue by DSDV** [dgibbs64/linuxgsm#350]
hello guys,
I had a problem about several month now that most (all I tested) scripts work fine until you try to start the server “[FAIL] Starting Server …” was the message ever single time.
The Solution is as simple as I can be.
My first step after login on to my server is starting a tmux session so that I can multitask!
And most of you know also the solution for that problem.
Tmux can’t start tmux sessions out of itself so you can’t use DGscripts when you’re in a tmux session  ;)

Just wanna post it cause I took me sadly several month to recognize it :/
(Seems I am not a advanced linux user xD)

have a nice day guys

**Comment by dgibbs64** [comment]
Lol o dear you tried to start a tmux session in a tmux session. LGSM is designed to start tmux for you, so the server runs in the background. 

This is the first time I have heard anyone trying to do this.

**Comment by Scarsz** [comment]
Personally, I don't understand why you would start a tmux session immediately.

**Comment by DSDV** [comment]
yeah i know its realy stupid :( 
and @Scarz i dont use muy console often so mostly i log in afeter a few days to run updates of the OS so i start tmux and can multitask also update my gameserers check my ngingx logs etc 
and dont have to start seperate putty sessions :P

**Comment by DSDV** [comment]
A friend described it as a typical Layer8 Problem xD

**Comment by dgibbs64** [comment]
Tmuxception?
http://i1.kym-cdn.com/photos/images/original/000/531/557/a88.jpg

**Comment by DSDV** [comment]
btw http://gameservermanagers.com/dl/sbserver doenst work :/

**Comment by dgibbs64** [comment]
Fixed :-)
