### ISSUE TITLE
[sbserver] Starbound fail to update

### ISSUE THREAD

**Issue by DSDV** [dgibbs64/linuxgsm#355]
Hi,
i try to update my starbound server and it it brings error in line 26 because of "}" ???

./sbserver update
[ .... ] Update sb-server: Checking for update
[  OK  ] Update sb-server: Checking for update: Server logs: No update requested
[  OK  ] Update sb-server: Checking for update: SteamCMD

Update available:
        Current build: 596755
        Available build: 605205

        https://steamdb.info/app/211820/

Applying update...
/home/steamcmd/functions/fn_update_dl: Zeile 26: Syntaxfehler beim unerwarteten Wort »}«
/home/steamcmd/functions/fn_update_dl: Zeile 26: `}'

how to fix this ?

with best +DS_DV+

**Comment by dgibbs64** [comment]
Removed the functions dir and test again. Then let me know if it is still an issue or not

**Comment by DSDV** [comment]
oh that worked thanks :D

**Comment by dgibbs64** [comment]
:) Any issues always remove the functions dir and try again. Fixes many issues :)
