### ISSUE TITLE
SteamCMD not always getting updates

### ISSUE THREAD

**Issue by dgibbs64** [dgibbs64/linuxgsm#356]
Im getting reports that update checker is not always working because SteamCMD is not returning the latest version details. Will need to find out why this is

**Comment by ImChip** [comment]
same here 

Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK
 Update state (0x5) validating, progress: 12,49 (1275158569 / 10211222143)
 Update state (0x61) downloading, progress: 0,06 (5920830 / 10211222143)
Error! App '740' state is 0x402 after update job.
Warning! SteamCMD did not complete the download, retrying: Attempt 2:

**Comment by Advkt** [comment]
Think that's a different issue, Chip. Specifically this issue is that the update check doesn't detect that there's a new version rather than failing once its begun. 

Bar doing it manually is there a force update command? Would be useful to have if it doesn't yet exist.

**Comment by dgibbs64** [comment]
Yeah I may have to implement a force update to bypass the check if people are getting the issue

**Comment by dgibbs64** [comment]
http://steamcommunity.com/groups/linuxgsm/discussions/0/620712999966267752/

**Comment by dgibbs64** [comment]
I belive this is now resolved with a recent update https://github.com/dgibbs64/linuxgsm/commit/078a5ccbd8659ddd0506287feac7d0e77aa600a4
