### ISSUE TITLE
[arma3 epochmod] Server Request

### ISSUE THREAD

**Issue by JamieKG** [dgibbs64/linuxgsm#357]
Hi ive been trying to use this to run a arma 3 epochmod server but it needs more arguments and I think some library path to be linked how would I go about adding them ?

**Comment by PhilPhonic** [comment]
What exactly is the problem?
I had an Arma 3 Epoch server running with lgsm

**Comment by dgibbs64** [comment]
https://github.com/ryanrolds/arma3epoch

found this. No idea if it could be merged in to LGSM though.

**Comment by dgibbs64** [comment]
Better overall mod support would be great. However I know very little and the documentation for ARMA 3 is complex. Would need a dedicated LGSM arma 3 developer i think.

**Comment by PhilPhonic** [comment]
If he'd describe the problem a little more detailed, I probably could help.

**Comment by JamieKG** [comment]
Hi I dont use Linux to host arma3 servers any more but when I did with Epoch you had to export a library path at start up form Epoch's start script https://github.com/EpochModTeam/Epoch/blob/master/Server_Install_Pack/epoch_linux_startscript.sh#L18

Thanks JamieKG
