### ISSUE TITLE
Update-restart function disappeared ?

### ISSUE THREAD

**Issue by UltimateByte** [dgibbs64/linuxgsm#361]
Got no update-restart function with the new script version (gmod), is that on purpose ?

**Comment by Scarsz** [comment]
https://github.com/dgibbs64/linuxgsm/commit/904df3a3b92560b0f517997367e42d99f06712b3

If you run an update against an already online server it will restart automatically

**Comment by UltimateByte** [comment]
Then tutorials need to be updated when you have a moment as the update-restart doesn't work anymore. :)
