### ISSUE TITLE
[BUG] sdtd monitor query fails

### ISSUE THREAD

**Issue by PointWolf-Dev** [dgibbs64/linuxgsm#3619]
I## Basic info

* **Distro:** [Distro:   CentOS Linux 8]
* **Game:** [SDTD]
* **Command:** [Monitor]
* **LinuxGSM version:** [ v21.3.2]

## Further Information

Unable to run the monitor command as it shows my the query as failed:
[sdtdserver@games ~]$ ./sdtdserver monitor
[  OK  ] Monitoring sdtdserver: Checking session: OK
[ .... ] Monitoring sdtdserver: Querying port: gsquery: 95.216.16.217:26900 : 0/[ FAIL ] Monitoring sdtdserver: Querying port: gsquery: 95.216.16.217:26900 : 0/1: FAIL

## To Reproduce

I am unsure as this is a fresh install on a dedicated server. 

Server Resource
================================================================================
CPU
Model:      Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
Cores:      8
Frequency:  3803.346MHz
Avg Load:   0.24, 0.30, 0.33

Memory
Mem:       total  used  free         cached  available
Physical:  32GB    14GB  18GB         13GB    18GB
Swap:      16GB    0B    16GB

Storage
Filesystem:     /dev/md2
Total:                           1.8T
Used:                            17G
Available:      1.7T

Network
IP:             0.0.0.0
Internet IP:    95.216.16.217

Game Server Resource Usage
================================================================================
CPU Used:  31.6%
Mem Used:  42%           13395MB

Storage
Total:          16G
Serverfiles:    15G

7 Days To Die Server Details
================================================================================
Server name:      NuperSatural - WoW - The Great Plague 10k
App ID:           294420
Server IP:        0.0.0.0:26900
Internet IP:      95.216.16.217:26900
Server password:  NOT SET
Maxplayers:       25
Game mode:        GameModeSurvival
Game world:       The.Great.Plague.10k
Master server:    not listed
Status:           STARTED

**Comment by parasyte** [comment]
I just setup a monitor because the game crashed, and I want to be notified the next time it happens. But the monitor cannot connect to the query port because the server does not listen on the port at all:

```
Useful port diagnostic command:
ss -tuplwn | grep 7DaysToDieServe

DESCRIPTION  PORT   PROTOCOL  LISTEN
Game         26900  udp       0
Game+2       26902  udp       2
Query        26900  tcp       0
Web Admin    8080   tcp       0
Telnet       8081   tcp       1
```

```
$ ss -tuplwn | grep 7DaysToDieServe
udp    UNCONN  0       0                   0.0.0.0:26902          0.0.0.0:*      users:(("7DaysToDieServe",pid=142064,fd=27))
udp    UNCONN  0       0                      [::]:26902             [::]:*      users:(("7DaysToDieServe",pid=142064,fd=31))
tcp    LISTEN  0       4096              127.0.0.1:8081           0.0.0.0:*      users:(("7DaysToDieServe",pid=142064,fd=23))
```

This might be a bug introduced by the game developers, but this definitely has nothing to do with how long the server has been running.

**Comment by parasyte** [comment]
I was able to fix the issue with the listening port. In my case, the game could not find `steamclient.so`. Updating the game files fixed it. Probably because the next server start fixed some hard links for steamcmd.

```
DESCRIPTION  PORT   PROTOCOL  LISTEN
Game         26900  udp       1
Game+2       26902  udp       2
Query        26900  tcp       1
Web Admin    8080   tcp       0
Telnet       8081   tcp       1
```

```
$ ss -tuplwn | grep 7DaysToDieServe
udp    UNCONN  768     0                   0.0.0.0:26900          0.0.0.0:*      users:(("7DaysToDieServe",pid=160356,fd=208))
udp    UNCONN  0       0                   0.0.0.0:26902          0.0.0.0:*      users:(("7DaysToDieServe",pid=160356,fd=27))
udp    UNCONN  0       0                      [::]:26902             [::]:*      users:(("7DaysToDieServe",pid=160356,fd=31))
tcp    LISTEN  0       4096              127.0.0.1:8081           0.0.0.0:*      users:(("7DaysToDieServe",pid=160356,fd=23))
tcp    LISTEN  0       4096                0.0.0.0:26900          0.0.0.0:*      users:(("7DaysToDieServe",pid=160356,fd=214))
```

Even with the query port listening, `monitor` never gets a response from the server. I confirmed that no packets are sent back with `tcpdump`. I also tried sending the `protocol-valve` stuff with netcat and socat, and the server just will not respond at all to the query.

**Comment by parasyte** [comment]
Whew! I got it working. It looks like 7 Days to Die no longer supports the UDP `protocol-valve` for gamedig or gsquery, so you have to switch the monitor mode to TCP to get it working.

E.g. I added this line to my `common.cfg`:

```ini
querymode="5"
```

And now it's all good:

```
$ ./sdtdserver monitor                                        
[  OK  ] Monitoring sdtdserver: Checking session: OK                              
[  OK  ] Monitoring sdtdserver: Querying port: tcp: 0.0.0.0:26900 : 0/1: OK 
```

This should really be changed in the default config: https://github.com/GameServerManagers/LinuxGSM/blob/fdfeae1fcdccb89f55e41ca33e964bbcb035d2ce/lgsm/config-default/config-lgsm/sdtdserver/_default.cfg#L137-L144
