### ISSUE TITLE
Bug GDB GmodServer

### ISSUE THREAD

**Issue by NahimBlack** [dgibbs64/linuxgsm#363]
Hello I am french sorry if I write badly, but I have a problem on my Ubuntu Server 12.04 - 64 Bit, I start ordering ./scrds run, and then I get the error:

Segmentation fault (core dumped)  

warning: Can't read pathname for load map: Input/output error. 

Can you help me? Please :'(

**Comment by Scarsz** [comment]
Check if the user you're trying to run the server with has read/write access to the entire serverfiles folder

**Comment by dgibbs64** [comment]
https://github.com/dgibbs64/linuxgsm/issues/370
