### ISSUE TITLE
Cant start the csgo server

### ISSUE THREAD

**Issue by wundeer** [dgibbs64/linuxgsm#365]
./csgoserver start
[ .... ] Starting Public 2: usage: pipe-pane [-o] [-t target-pane] [command]
[ FAIL ] Starting Public 2: Unable to start : Tmux returned the following error:

usage: new-session [-d] [-n window-name] [-s session-name] [-t target-session] [-x width] [-y height] [command]

csgo is part of the tty group.

        tty:x:5:csgo

No known fix currently.
http://gameservermanagers.com/issues

**Comment by dgibbs64** [comment]
Tmux is doing something odd. Output of ./csgoserver details please

**Comment by wundeer** [comment]
Distro Details
================================================================================
Distro:   "CentOS release 6.6 (Final)"
Arch:   x86_64
Kernel:   2.6.32-504.8.1.el6.x86_64
Hostname:   zulu434.startdedicated.net
tmux:   tmux 1.6
GLIBC:   2.12

Performance
================================================================================
Uptime:   1d, 7h, 4m
Avg Load:   0.56, 0.26, 0.27

Mem:   total    used   free
Physical:   15696   15518  177
Swap:   2047   0      2047

Disk Usage
================================================================================
Disk available:   1.3T
Serverfiles:   9.6G
/home/csgo/Public1/functions/fn_details: line 56: [: /home/csgo/Public1/serverfiles/csgo/cfg/Public: binary operator expected

Counter Strike: Global Offensive Server Details
================================================================================
Server name:
Server IP:   188.138.91.82:27015
Status:   OFFLINE

Service name:   Public 1
User:   csgo
Location:   /home/csgo/Public1
Config file:   /home/csgo/Public1/serverfiles/csgo/cfg/Public 1.cfg

Backups
================================================================================
No Backups created

Command-line Parameters
================================================================================
./srcds_run -game csgo -usercon -strictportbind -ip 188.138.91.82 -port 27015 +clientport 27005 +tv_port 27020 -tickrate 128 +map de_dust2 +servercfgfile Public 1.cfg -maxplayers_override 16 +mapgroup random_classic +game_mode 0 +game_type 0 +host_workshop_collection  +workshop_start_map  -authkey

Ports
================================================================================
Change ports by editing the command-line
parameters in csgoserver.

Useful port diagnostic command:
netstat -atunp | grep srcds_linux

DESCRIPTION  DIRECTION  PORT   PROTOCOL
> Game/RCON  INBOUND    27015  tcp/udp
> SourceTV   INBOUND    27020  udp
< Client     OUTBOUND   27005  udp

Status: OFFLINE

**Comment by dgibbs64** [comment]
Delete the functions dir and test for me. If still the same let me know

**Comment by dgibbs64** [comment]
also i dont reccomend useing spaces in file names. can do odd things sometimes /home/csgo/Public1/serverfiles/csgo/cfg/Public 1.cfg

**Comment by wundeer** [comment]
After i deleted the functions and renamed the space it did work! Thanks!

**Comment by dgibbs64** [comment]
YAY good news!
