### ISSUE TITLE
CS:GO Server Maps/Tickrate

### ISSUE THREAD

**Issue by michmour** [dgibbs64/linuxgsm#366]
Hello!
Thanks for your awsome scripts!
I would like to know how can i change tags and change to 128.

**Comment by xFaNaTiix** [comment]
For tags you have to add:
sv_tags "your,tags,seperated,with,kommata"
to your server config

And to change the tickrate, just change it in the script:
https://github.com/dgibbs64/linuxgsm/blob/master/CounterStrikeGlobalOffensive/csgoserver#L32

**Comment by michmour** [comment]
Could you tell me where the srcopt located?

**Comment by Scarsz** [comment]
It's the main file that you use to start the server. It's wherever you put it.
