### ISSUE TITLE
[Garry's Mod Server] Bug GDB 'Segmentation Fault'

### ISSUE THREAD

**Issue by NahimBlack** [dgibbs64/linuxgsm#370]
Hello, I have acquired a ubuntu 12.04 server, 16GB ram
and I installed a gmod server, and I decide to put the map 'rp_rockford_v1b'

I start with the command ./scrds_run

and the crash and puts me this error Server:

Engine hunk overflow!
Engine hunk overflow!

Engine hunk overflow!

Segmentation fault (core dumped)

warning: Can't read pathname for load map: Input/output error.
debug.cmds:5: Error in sourced command file:
No function contains program counter for selected frame.
email debug.log to linux@valvesoftware.com
Sat May  9 13:20:27 EDT 2015: Server restart in 10 seconds
Sat May  9 13:20:30 EDT 2015: Server Quit

Can you help me?

**Comment by Scarsz** [comment]
If it's an option update to 14.04, much more stable and I've never had problems with srcds on it.

**Comment by dgibbs64** [comment]
Yes im afraid something funky is happening with gmod server and your distro and it may not be easy to fix. I recommend Googling around to see if there is anything on this error. Failing that a newer distro like 14.04 LTS is a good idea.

**Comment by Scarsz** [comment]
I should actually point out that Ubuntu 15.04 was released, better to use that over 14.04.

**Comment by dgibbs64** [comment]
14.04 is long term support. Which I normally a better idea for servers

**Comment by Scarsz** [comment]
I've never generally had a problem with the latest version of Ubuntu when compared against a LTS version, I guess I've just never ran across a problem where LTS would have been better to have.
