### ISSUE TITLE
Add option to forcefully use root

### ISSUE THREAD

**Issue by Scarsz** [dgibbs64/linuxgsm#381]
Whenever I test out LGSM it runs in a stock, cloned virtual machine with only the root user available. In order for me to just run the script as root I have to throw a wrench into fn_check_root. I propose something like having a file in the same folder as the script "iknowwhatimdoing" that's checked inside of fn_check_root. If that file exists, skip the root check, if it doesn't exist, continue as normal.

**Comment by dgibbs64** [comment]
Is there any particular reason why you cannot create a non root user? I would rather not put code in to bypass as people will start using it (normally less experienced users)

**Comment by Scarsz** [comment]
There is no particular reason that I can't, it's just a bit of an annoyance. I would recommend just not documenting it (aside from this issue, obviously) so people who have actually looked into running the script as root would see that there is a bypass available, it's just not listed anywhere, thus keeping it for more advanced users

**Comment by dgibbs64** [comment]
I'm afraid I will not be making any changes on this one. Using root is not a best practice and I don't want to give the option to do this even if its not published. As developers we need to practice what we preach. So stop being lazy and just create a standard user. ;-)
