### ISSUE TITLE
CS:GO Can't install Source or Metamod

### ISSUE THREAD

**Issue by Sqveeze** [dgibbs64/linuxgsm#384]
Hello,

I have a problem with CS:GO. I can't install meta or sourcemod. There's no errors or anything in the console, but i noticed that when i open putty, and then login to the vps and i open the console its laggs like hell. Like i wrote 10 char as fast as i can, and the putty window is display only 2-3 char till then and its continue to display all characters i was typing. I also have a TF2 server and there i was able to install both mod. How can i solve this?

**Comment by dgibbs64** [comment]
Errmmmm. if it lags your VPS might not be powerful enough to run the servers. Try checking the system resources using tools like top, htop, iotop and sar.

Also I cannot really help with Sourcemod etc as I don't use them myself. I recommend visiting there official sites to double check the documentation and find any issues similar to yours https://github.com/dgibbs64/linuxgsm/wiki/FAQ#how-can-i-install-insert-name-mod

**Comment by xMqt** [comment]
Was having the same issue while trying to install some CS:GO servers.
Valve made some server-sided changes and some of these plugins were broken. Metamod should be ok but I advise you to update both Metamod and Sourcemod with last snapshots which have been updated 2 hours ago:

http://www.metamodsource.net/snapshots
https://www.sourcemod.net/snapshots.php

**Comment by Sqveeze** [comment]
@dgibbs the vps is not lagging, only the game console. Dunno why.

@xMqt Thanks i will try snapshots, however at the version compatibility pages i see the latest stable is working with cs:go. Nvm maybe they forgot to update it. Oh and metamod was not ok. First i tried that because metamod is required for sm and yeah it was not working. 

Thanks for the answer guys, i will report back my results.

**Comment by Sqveeze** [comment]
Well, snapshots works with CS:GO buuuuut when i install them and login to the game, entering eg: as CT the game server restart cause the sm or mm causes a fatal error. Looks like CS:GO is not for modding... i just halt this project untill valveshit do something that doesn't kill mods after each day with a shitty update
#csgoshit

**Comment by iamdual** [comment]
Same problem.
