### ISSUE TITLE
[CS:GO] Regarding updating from past versions of GSM.

### ISSUE THREAD

**Issue by Advkt** [dgibbs64/linuxgsm#386]
Just wondering if there's a specific process in terms of updating I should follow if our server was set up initially before the complete switch-over to github. That is, what files should I be replacing and what files should I leave alone?

**Comment by Scarsz** [comment]
Rename the top-most folder (the one that has srcds_linux inside of it) to "serverfiles", download csgoserver into the same folder where serverfiles is so the top most folder should have "serverfiles" and the script, inside of the serverfiles folder being the topmost folder of the actual server

*whatever name you want*
- csgoserver
- serverfiles/
    - csgo
        - cfg
        - etc.
    - etc.

**Comment by Advkt** [comment]
Just to clarify, the server is already managed the LinuxGSM however it's an older version from around February. Should I redownload the csgoserver file, delete the functions folder and allow it to repopulate or is there a different process I should follow?

**Comment by Scarsz** [comment]
Delete the script as well as the functions folder to get a completely fresh install

**Comment by Advkt** [comment]
That did the trick, thank you, Scarsz.
