### ISSUE TITLE
[LGSM] Warn when Steam username is not defined

### ISSUE THREAD

**Issue by athairus** [dgibbs64/linuxgsm#387]
I had foolishly commented out the username and password variables in the main script, and spent more time than I'd like to admit trying to figure out how to get SteamCMD to even log in so I could run the server. It turned out that putting the variable back and giving it its default value of "anonymous" fixed it. A warning would have been nice.

**Comment by Scarsz** [comment]
Why even change the SteamCMD variables for the TF2 server in the first place? The TF2 server obviously doesn't require a valid license because it's free

But, I guess, it would be useful to have a notification that comes up saying that there's no valid username variable

**Comment by athairus** [comment]
It was just a mistake on my part that resulted in almost an hour of debugging and digging through logs. Just want to save someone else the trouble.

**Comment by Scarsz** [comment]
https://github.com/dgibbs64/linuxgsm/commit/bad8b25b3636ea01b2d76b5d3288722db9d49416

**Comment by dgibbs64** [comment]
What was not working. Was it the updater?

**Comment by athairus** [comment]
SteamCMD would hang logging in, something along the lines of `logging in with user ''...`

**Comment by dgibbs64** [comment]
Thanks. The code @Scarsz committed would need to go in a few other places as well. I recommend @Scarsz that you create a new function file called fn_check_steamcmd_login and call the function in the following function files:

fn_install_serverfiles
fn_update_check
fn_validate

That should catch any chance of attempting to login to SteamCMDwithout a username

**Comment by Scarsz** [comment]
It would basically do this

`./steamcmd.sh +login +force...`

**Comment by Scarsz** [comment]
@dgibbs64 https://github.com/dgibbs64/linuxgsm/pull/388

**Comment by dgibbs64** [comment]
This feature is now fully merged
