### ISSUE TITLE
libstdc++.so.6 fix not working

### ISSUE THREAD

**Issue by UltimateByte** [dgibbs64/linuxgsm#389]
Just installed a new server, the fix for that lib doesn't work. I also had some reports on my website's tutorial that some people had an error for that file missing into the console.

If you have a moment, please check that at some point, that command is applied by your script : 
cp steamcmd/linux32/libstdc++.so.6 serverfiles/

It solves the issue in 100% of the cases for me. 
Should i also mention that i'm running Debian 8 now.

Thanks in advance.

**Comment by UltimateByte** [comment]
Well, it works without the need of copying the file on a brand new Debian 8 vps x64, but still not on my dedicated Debian 8 x64 server...
I cant figure out why.

**Comment by dgibbs64** [comment]
the GLIBC fix is only required on servers that have a version of GLIBC less than the server version. I dont think you would need any fix for Debian 8. Maybe you havnt installed the dependencies on your VPS.

https://github.com/dgibbs64/linuxgsm/wiki/Glibc

**Comment by UltimateByte** [comment]
Gosh, you're so right, i missed a few ones.
http://image.noelshack.com/fichiers/2015/29/1437328051-libs-missing.png
I don't even know how it's possible, maybe during my 48h server migration i forgot that a few months ago, but i had the same issue with debian 7, and i'm very sure that i installed the dependencies you provided on the previous server... I double, triple checked that because i was new with linux.
Unless you updated the dependencies list at the same time than the (nice) website update, i don't know how it's possible.

OK so now let's try making a fresh server !
=> 2 minutes later... Setting up gmodserver with good IP and ports.
=> Well... it's working without any tweak.
=> Proof that i've been a douchebag
=> Or that you added missing dependencies

I'm wondering, what's this fix that i see at every install then, if it doesn't solve that issue.

BTW, thanks ! I'm sorry for the loss of time !

**Comment by UltimateByte** [comment]
It also solves some missing libraries messages at launch... You made my day ! Thanks a lot :)

**Comment by dgibbs64** [comment]
No problem. I'm eventually going to add something to warn people if they are missing a dependency
