### ISSUE TITLE
Add option to suppress console warning

### ISSUE THREAD

**Issue by athairus** [dgibbs64/linuxgsm#395]
After launching the console dozens of times, I think these lessons are burned into my head:
- I should not press CTRL+C
- I should exit by pressing CTRL+B, D

I'd be nice if I didn't have to type `y, Enter` every time I want to open the console up.

Alternatively, just have Y be the default option so I can just press enter to continue.

**Comment by dgibbs64** [comment]
added the default y in a while ago.
