### ISSUE TITLE
Tab completion for the main script

### ISSUE THREAD

**Issue by athairus** [dgibbs64/linuxgsm#397]
The commands available when invoking the main script should be tab-completable to save some typing.

**Comment by dgibbs64** [comment]
This would be a great feature that I will investigate at some point when time permits.

**Comment by dgibbs64** [comment]
I have just looked in to this and it requires the complete command and the editing of the user profile. Quite a bit of messing around by the looks of things becuase of this I wil not be implamenting this. However there are shortened options available to use such as ./csgoserver st for start. I will however need to document these better for users.

**Comment by UltimateByte** [comment]
@dgibbs64 Good idea. I updated the wiki. https://github.com/dgibbs64/linuxgsm/wiki/Command-list

**Comment by dgibbs64** [comment]
Just updated the getopts function this will now display for users (currently in development branch)
