### ISSUE TITLE
[TF2] Support "custom" directory for cfg files

### ISSUE THREAD

**Issue by athairus** [dgibbs64/linuxgsm#398]
I find that everything is much cleaner if every change you make to the server is not mixed in with the default files. This is a request for putting `tf2server.cfg` in `custom/tf2server/cfg/` by default.

**Comment by dgibbs64** [comment]
Would the same work for maps and plugins etc? I'm not overly keen on changing the server files from there default as this could add confusion to users

**Comment by athairus** [comment]
I haven't confirmed that Sourcemod will handle the new SteamPipe way of doing things, but when it comes to maps and other cfg files, yes it should work just fine.
