### ISSUE TITLE
Insurgency Tmux error can't start server.

### ISSUE THREAD

**Issue by Shipwreck50** [dgibbs64/linuxgsm#401]
Insurgency server won't start

[esltest@ns305922 ~]$ ./insserver start
[ FAIL ] Starting ins-server: Unable to start Esl2 test Server|WTFNation: Tmux error:

Command
=================================
tmux new-session -d -s ins-server ./srcds_linux -game insurgency -strictportbind -ip 91.121.222.194 -port 27016 +clientport 27018 +tv_port 27017 +map ministry +servercfgfile ins-server.cfg -maxplayers 12

Error
=================================
create session failed: ./srcds_linux -game insurgency -strictportbind -ip 91.121.222.194 -port 27016 +clientport 27018 +tv_port 27017 +map ministry +servercfgfile ins-server.cfg -maxplayers 12: Operation not permitted

Fix
=================================
No known fix currently. Please log an issue.
http://gameservermanagers.com/issues

**Comment by dgibbs64** [comment]
LOL. You and your tmux errors. Never known a server have so many issues with tmux. I will message you when I'm free to have a chat :-). There is an issue you may be able to help me with as well.

**Comment by Shipwreck50** [comment]
Aha I fixed it it was the server in need of an update.

I too need to speak to you about something else

 

Regards 

 

Shipwreck50

**Comment by dgibbs64** [comment]
@Shipwreck50 Could you take a look at this issue and give me your opinion?https://github.com/dgibbs64/linuxgsm/issues/362 Will be free over the weekend to catch up :)
