### ISSUE TITLE
color codes in email

### ISSUE THREAD

**Issue by marvinl97** [dgibbs64/linuxgsm#404]
Are the color codes in the email intended?
They don't work for emails, only for bash/shell, I guess?

e.g.
` [34mDistro:   [0mUbuntu 14.04.2 LTS`

https://github.com/dgibbs64/linuxgsm/blob/master/functions/fn_details

EDIT: Oh, It was also mentioned in another issue #394 ._.

**Comment by dgibbs64** [comment]
Somthing I need to work on :)

**Comment by dgibbs64** [comment]
I have overhauled the details function. I will sort out the email section soon

**Comment by dgibbs64** [comment]
Just fixed :)
