### ISSUE TITLE
[ARMA3] Support for headless clients

### ISSUE THREAD

**Issue by NemesisRE** [dgibbs64/linuxgsm#407]
Would it be possible to add in the arma3server script something like "headlessclient=yes/no" to spawn a Headless client besides the server?

It should use the server password if set from the server config and as IP 127.0.0.1 startup parameters would be then like this:

```-client -connect =127.0.0.1 -port=${port_from_cfg} -pass=${password_from_cfg} -mod=${mods}```

https://community.bistudio.com/wiki/Arma_3_Headless_Client

And I would like to thank you for your great work it is awesome!

regards
Steven

**Comment by dgibbs64** [comment]
This may be possible. Whats the point exactly of the headlessclient?

**Comment by NemesisRE** [comment]
Arma Servers use only 2 CPU Cores and max of 2GB ram, to get a higher performance without switching to 64bit binary, as a "Quickfix" they provided headless clients which can takeover the AI calculations from the server.

**Comment by dgibbs64** [comment]
Got ya. I'm sure I could implement this. However it won't be a top priority currently. If someone it willing to add this in sooner I would be happy to merge :-)

**Comment by PhilPhonic** [comment]
Hi,

I did a small bash-script exactly for this.
first parameter is start, stop, restart
second parameter (optional) name of headless client to start multiple.
> ./hc start
> ./hc start HC2
> ./hc start HC3

Just place it inside /home/arma3server and make it executable

find the script here: http://pastebin.com/QuUJgYH8

**Comment by acidburn101** [comment]
I have 4 Headless Clients for one arma instance setup, quite nice and simple to use. 
I basicly just copied the bash script and added the -client and -connect to the param line aswell as my mods. 
Works absolutly fine, serivce name though need to be different from original. 
servicename="arma3-server-headlessclient1"

I love this LGSM Library saved my lots of hours of work! Thx @dgibbs64

**Comment by dgibbs64** [comment]
@PhilPhonic might be a good idea to place your script in to a GithubRepo. I will be closing this issue now
