### ISSUE TITLE
How to delete server?

### ISSUE THREAD

**Issue by Sqveeze** [dgibbs64/linuxgsm#409]
Hello, i want to delete one of my game server from the VPS, but without reinstalling the whole system. How can i do it? I mean i know i can delete the server folder, but there's any other file somewhere in the system or something in chkconfig that i need to remove?

**Comment by Scarsz** [comment]
No

**Comment by Sqveeze** [comment]
So i just have to delete the folder? That's all?

**Comment by Scarsz** [comment]
Your system will perform the exact way it did before installing a game server if you remove the topmost folder, yes.

**Comment by dgibbs64** [comment]
Also remove any cronjobs for that serve rif you have any
