### ISSUE TITLE
Update on start New Feature doesnt work on Latest TF2 update

### ISSUE THREAD

**Issue by medic917** [dgibbs64/linuxgsm#414]
Anyone else try the new script with the updateonstart="yes" option?
I configured it and it does check for updates on start, but it gives false information and says it doesn't need updates when it does.

Found out on my first TF2 update for my TF2 servers using this new feature.

**Comment by medic917** [comment]
Here is a screen shot. It seems like the database it uses is outdated or slow on updates.
http://i.snag.gy/LlWX6.jpg

**Comment by dgibbs64** [comment]
Damn it wrong issue. I meant fixed issue #413

**Comment by dgibbs64** [comment]
This isn't an issue as such in that you do get the latest update. 

What happens is that the script found a restart request in the logs and applies the update. The script then continues to use SteamCMD to check for updates...by this time the server has just updated so the SteamCMD check states there is no update which is now true as it just updated.

I will make alterations so make this less confusing on the front end :)

**Comment by dgibbs64** [comment]
Fixed related issue I found https://github.com/dgibbs64/linuxgsm/commit/4a5e4cffb64d56e15a69e63d1642f37158559050

**Comment by dgibbs64** [comment]
This should fix the issue https://github.com/dgibbs64/linuxgsm/commit/d69b8672c6990dd366413ee708fae3b2a6414a07
