### ISSUE TITLE
[Gmod] Error 

### ISSUE THREAD

**Issue by TrAiZerZ** [dgibbs64/linuxgsm#415]
I have this error in gmod console
No addons ...
New server, first time.

____________________
./srcds_linux: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
Add "-debug" to the ./srcds_run command line to generate a debug.log to help with solving this problem
mercredi 3 juin 2015, 21:23:53 (UTC+0200): Server restart in 10 seconds
./srcds_linux: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
Add "-debug" to the ./srcds_run command line to generate a debug.log to help with solving this problem
mercredi 3 juin 2015, 21:24:03 (UTC+0200): Server restart in 10 seconds
_____________________

**Comment by dgibbs64** [comment]
I think you might not of read the installation instructions correctly

https://github.com/dgibbs64/linuxgsm/wiki/Dependencies

**Comment by TrAiZerZ** [comment]
Where ? I don't found. And i'm french and i don't speak very good english :/

2015-06-03 22:48 GMT+02:00 Daniel Gibbs <notifications@github.com>:

**Comment by dgibbs64** [comment]
https://github.com/dgibbs64/linuxgsm/wiki/Dependencies#Source-Engine
