### ISSUE TITLE
ut2004 server did not appear in internet list

### ISSUE THREAD

**Issue by matpersonne** [dgibbs64/linuxgsm#422]
My server work on debian 64 and everything is ok i can start server i can access to the webadmin.

in debug mod i have this: 
 
    [ INFO ] Debug ut2k4-server: Stopping any running servers 
    [  OK  ] Stopping ut2k4-server: mat
    [  OK  ] Debug ut2k4-server: Starting debug
    Executing Class Engine.ServerCommandlet
    Browse:        DM-Rankin?Name=Player?Class=Engine.Pawn?Character=Jakob?team=255?game=XGame.xDeathMatch
    Collecting garbage
    Purging garbage
    Garbage: objects: 36590->36585; refs: 462714
    Game class is 'xDeathMatch'
    Bringing Level DM-Rankin.myLevel up for play (25) appSeconds: 4.407942...
    center pointLoading Admins & Groups
    Kick and Ban Privileges Loaded
    Maps & Game Privileges Loaded
    Admins & Groups Management Loaded
    Extra Privileges Loaded
    GameInfo::InitGame : bEnableStatLogging True
    MasterServerGameStats initializing
    UdpServerQuery(crt): Port 7787 successfully bound.
    Resolving master0.gamespy.com...
    Defaulting to false
    Defaulting to false
    Resolving ut2004master1.epicgames.com...
    Loading Available Maps
    Loading Game Types
    xWebAdmin.UTServerAdmin Initialized on port 8080
    MasterServerUplink: Resolved ut2004master1.epicgames.com as 199.255.40.173.
    AInternetLink Resolve failed: Can't find host master0.gamespy.com (HOST_NOT_FOUND)
    UdpGameSpyUplink: Failed to resolve master server address, aborting.
    MasterServerUplink: Connection to ut2004master1.epicgames.com established.
    Approval APPROVED
    Master server requests heartbeat 0 with code 1796
    Master server requests heartbeat 1 with code 1796
    Master server requests heartbeat 2 with code 1796
    Master server assigned our MatchID: 65051474

but my server isn't in the internet list of server...
what can I do? Thx

**Comment by dgibbs64** [comment]
Might be a firewall wall possibly ensure that all the required ports are open

**Comment by dgibbs64** [comment]
Can this be closed?

**Comment by matpersonne** [comment]
hello,
I open all port on INBOUND and Outbound but It didn't work...
You can close it , I think the problem is on my server but thanks a lot.

2015-06-22 12:01 GMT+02:00 Daniel Gibbs <notifications@github.com>:

> Can this be closed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dgibbs64/linuxgsm/issues/422#issuecomment-114056085>.
>



-- 


*Mathieu BRAME*

Étudiant en  informatique (université catholique de Lille)

*brame.mathieu@gmail.com <brame.mathieu@gmail.com>*
06.23.13.74.33
