### ISSUE TITLE
[LGSM] fn_start (possibly others) fail when service name has single/double quotes

### ISSUE THREAD

**Issue by Zigalishous** [dgibbs64/linuxgsm#423]
pzserver is not part of the tty group.

        tty:x:5:

Run the following command with root privileges.

        usermod -G tty pzserver

After running command and attempt to start:

tmux error:
usage: new-session [-AdDP] [-F format] [-n window-name] [-s session-name] [-t target-session] [-x width] [-y height] [command]

**Comment by Scarsz** [comment]
Can you give us the surrounding lines where they tmux error is when starting?

**Comment by ZigBomb** [comment]
Elaborate?

./pzserver start
: Tmux error:ting Zig's Zomboid Panic : Unable to start

Command
=================================
tmux new-session -d -s Zig's Zomboid Panic  ./projectzomboid-dedi-server.sh

Error
=================================
usage: new-session [-AdDP] [-F format] [-n window-name] [-s session-name] [-t target-session] [-x width] [-y height] [command]

Fix
=================================
No known fix currently. Please log an issue.
http://gameservermanagers.com/issues

**Comment by ZigBomb** [comment]
It begins when ./pzserver start.

**Comment by Scarsz** [comment]
`rm -rf functions; ./pzserver start`

**Comment by ZigBomb** [comment]
Still failed.

**Comment by Scarsz** [comment]
Error this time?

**Comment by ZigBomb** [comment]
There wasn't an error, but it failed to start.

**Comment by ZigBomb** [comment]
[ FAIL ] Starting Zig's Zomboid Panic : Unable to start

**Comment by ZigBomb** [comment]
Now when I attempt to start it I get another error.


duplicate session: Zig's Zomboid Panic

**Comment by Scarsz** [comment]
`rm -rf functions; ./pzserver stop`

**Comment by ZigBomb** [comment]
Uh, still getting an error regarding 
duplicate session: Zig's Zomboid Panic
after using that command.

**Comment by Scarsz** [comment]
I must be blanking out on something.

Are there any sessions listed on `tmux list-sessions`? If so, kill them and try again

**Comment by ZigBomb** [comment]
Do you have any other means of contact besides github itself?

**Comment by Scarsz** [comment]
You can add my Skype, yes. truelabrinth

**Comment by Scarsz** [comment]
Problem is at line 117 of fn_start (https://github.com/dgibbs64/linuxgsm/blob/master/functions/fn_start#L117)

```
tmux new-session -d -s "Zig's Zomboid Panic " "./projectzomboid-dedi-server.sh " 2> "/home/pzserver/log/script/.Zig's Zomboid Panic -tmux-error.tmp"
```

`"/home/pzserver/log/script/.Zig's Zomboid Panic -tmux-error.tmp"`

Error occurs when a server's ${servicename} has (multiple?) non-escaped single (or double quotes)

**Comment by dgibbs64** [comment]
Was this issue resolved? Can this be closed?

**Comment by Scarsz** [comment]
No

**Comment by Zigalishous** [comment]
Solved.
