### ISSUE TITLE
./csgoserver: line 105: syntax error near unexpected token `}'

### ISSUE THREAD

**Issue by rand0med** [dgibbs64/linuxgsm#427]
Hello,

I'm running a fully patched CentOS 6.6 64 bit server with all dependencies installed. I've setup a fresh VM with nothing else running on the box. I ran the csgoserver install script which completed without an issue. I ran the command ./csgoserver start and received the foillowing error:

./csgoserver: line 105: syntax error near unexpected token `}'
./csgoserver: line 105: `}'

Here is the full script File:

```
#!/bin/bash
# Counter Strike: Global Offensive
# Server Management Script
# Author: Daniel Gibbs
# Website: http://gameservermanagers.com
# Version: 090515

#### Variables ####

# Notification Email
# (on|off)
emailnotification="off"
email="example.com"

# Steam login
steamuser="anonymous"
steampass=""

# Start Variables
# https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive_Dedicated_Servers#Starting_the_Server
# [Game Modes]           gametype    gamemode
# Arms Race                  1            0
# Classic Casual             0            0
# Classic Competitive        0            1
# Demolition                 1            1
# Deathmatch                 1            2
gamemode="1"
gametype="2"
defaultmap="de_train"
mapgroup="random_classic"
maxplayers="16"
tickrate="128"
port="27015"
sourcetvport="27020"
clientport="27005"
ip="0.0.0.0"
updateonstart="no"
# Optional: Workshop Parameters
# https://developer.valvesoftware.com/wiki/CSGO_Workshop_For_Server_Operators
# To get an authkey visit - http://steamcommunity.com/dev/apikey
# authkey=""
# ws_collection_id=""
# ws_start_map=""

# https://developer.valvesoftware.com/wiki/Command_Line_Options#Source_Dedicated_Server
fn_parms(){
parms="-game csgo -usercon -strictportbind -ip ${ip} -port ${port} +clientport ${clientport} +tv_port ${sourcetvport} -tickrate ${tickrate} +map ${defaultmap} +servercfgfile ${servercfg} -maxplayers_override ${maxplayers} +mapgroup ${mapgroup} +game_mode ${gamemode} +game_type ${gametype} +host_workshop_collection ${ws_collection_id} +workshop_start_map ${ws_start_map} -authkey ${authkey}"
}

#### Advanced Variables ####

# Steam
appid="740"

# Server Details
servicename="csgo-server"
gamename="Counter Strike: Global Offensive"
engine="source"

# Directories
rootdir="$(cd "$(dirname "${BASH_SOURCE[0]}" )" && pwd )"
selfname="$(basename $0)"
lockselfname=".${servicename}.lock"
filesdir="${rootdir}/serverfiles"
systemdir="${filesdir}/csgo"
executabledir="${filesdir}"
executable="./srcds_run"
servercfgdir="${systemdir}/cfg"
servercfg="${servicename}.cfg"
servercfgfullpath="${servercfgdir}/${servercfg}"
defaultcfg="${servercfgdir}/server.cfg"
backupdir="${rootdir}/backups"

# Logging
logdays="7"
gamelogdir="${systemdir}/logs"
scriptlogdir="${rootdir}/log/script"
consolelogdir="${rootdir}/log/console"

scriptlog="${scriptlogdir}/${servicename}-script.log"
consolelog="${consolelogdir}/${servicename}-console.log"
emaillog="${scriptlogdir}/${servicename}-email.log"

scriptlogdate="${scriptlogdir}/${servicename}-script-$(date '+%d-%m-%Y-%H-%M-%S').log"
consolelogdate="${consolelogdir}/${servicename}-console-$(date '+%d-%m-%Y-%H-%M-%S').log"

##### Script #####
# Do not edit

fn_runfunction(){
# Functions are downloaded and run with this function
if [ ! -f "${rootdir}/functions/${functionfile}" ]; then
	cd "${rootdir}"
	if [ ! -d "functions" ]; then
		mkdir functions
	fi
	cd functions
	echo -e "loading ${functionfile}...\c"
	wget -N /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/functions/${functionfile} 2>&1 | grep -F HTTP | cut -c45-
	chmod +x "${functionfile}"
	cd "${rootdir}"
	sleep 1
i
source "${rootdir}/functions/${functionfile}"
}

fn_functions(){
# Functions are defined in fn_functions.
functionfile="${FUNCNAME}"
fn_runfunction
}

fn_functions

getopt=$1
fn_getopt
```

The error seems to point to the } right after the fn_functions option, but I'm not sure what the issue is in order to solve. Please advise.

**Comment by Scarsz** [comment]
Redownload csgoserver. It looks to me like the version that you have has a misspelled "fi" in it, leaving just the I, but in the most latest server release that typo isn't there.

**Comment by rand0med** [comment]
Redownloaded the file. on first run it gave an error related to being a part of the tty group, which i fixed following the instructions, upon the second attempt at running i received another error. Pasting results:

[csgoserver@localhost ~]$ ./csgoserver start
loading fn_start...OK
loading fn_check_systemdir...OK
loading fn_check_ip...OK
loading fn_check_logs...OK
[ INFO ] Starting csgo-server: Applying 730 steam_appid.txt Fix.
loading fn_details_config...OK
loading fn_logs...OK
[ .... ] Starting csgo-server: onshosting.com CSGO Deathmatch 128 tickloading fn_check_tmux...OK
loading fn_check_steamcmd...OK
tmux: error while loading shared libraries: libevent-2.0.so.5: cannot open shared object file: No such file or directory
/home/csgoserver/functions/fn_start: line 119: [: : integer expression expected
tmux: error while loading shared libraries: libevent-2.0.so.5: cannot open shared object file: No such file or directory
/home/csgoserver/functions/fn_start: line 122: [: : integer expression expected
tmux: error while loading shared libraries: libevent-2.0.so.5: cannot open shared object file: No such file or directory
[ FAIL ] Starting csgo-server: Unable to start onshosting.com CSGO Deathmatch 128 tick: Tmux error:

Command
=================================
tmux new-session -d -s "csgo-server" "./srcds_run -game csgo -usercon -strictportbind -ip 172.16.1.103 -port 27015 +clientport 27005 +tv_port 27020 -tickrate 64 +map de_dust2 +servercfgfile csgo-server.cfg -maxplayers_override 16 +mapgroup random_classic +game_mode 0 +game_type 0 +host_workshop_collection  +workshop_start_map  -authkey "

Error
=================================
tmux: error while loading shared libraries: libevent-2.0.so.5: cannot open shared object file: No such file or directory

Fix
=================================
csgoserver is not part of the tty group.

        tty:x:5:

Run the following command with root privileges.

        usermod -G tty csgoserver

http://gameservermanagers.com/tmux-op-perm

[csgoserver@localhost ~]$ su root
Password:
[root@localhost csgoserver]#  usermod -G tty csgoserver
[root@localhost csgoserver]# su csgoserver
[csgoserver@localhost ~]$ ./csgoserver start
[ .... ] Starting csgo-server: onshosting.com CSGO Deathmatch 128 ticktmux: error while loading shared libraries: libevent-2.0.so.5: cannot open shared object file: No such file or directory
/home/csgoserver/functions/fn_start: line 119: [: : integer expression expected
tmux: error while loading shared libraries: libevent-2.0.so.5: cannot open shared object file: No such file or directory
/home/csgoserver/functions/fn_start: line 122: [: : integer expression expected
tmux: error while loading shared libraries: libevent-2.0.so.5: cannot open shared object file: No such file or directory
[ FAIL ] Starting csgo-server: Unable to start onshosting.com CSGO Deathmatch 128 tick: Tmux error:

Command
=================================
tmux new-session -d -s "csgo-server" "./srcds_run -game csgo -usercon -strictportbind -ip 172.16.1.103 -port 27015 +clientport 27005 +tv_port 27020 -tickrate 64 +map de_dust2 +servercfgfile csgo-server.cfg -maxplayers_override 16 +mapgroup random_classic +game_mode 0 +game_type 0 +host_workshop_collection  +workshop_start_map  -authkey "

Error
=================================
tmux: error while loading shared libraries: libevent-2.0.so.5: cannot open shared object file: No such file or directory

Fix
=================================
No known fix currently. Please log an issue.
http://gameservermanagers.com/issues

[csgoserver@localhost ~]$

Package libevent-1.4.13-4.el6.x86_64 already installed and latest version
Nothing to do
[root@localhost csgoserver]#

**Comment by Scarsz** [comment]
ln -s /usr/local/lib/libevent-2.0.so.5 /usr/lib64/libevent-2.0.so.5

**Comment by rand0med** [comment]
[csgoserver@localhost root]$ su root
Password:
[root@localhost ~]# ln -s /usr/local/lib/libevent-2.0.so.5 /usr/lib64/libevent-2                                                                                                                        .0.so.5
[root@localhost ~]# su csgoserver
[csgoserver@localhost root]$ cd /home/csgoserver/
[csgoserver@localhost ~]$ ./csgoserver start
[  OK  ] Starting csgo-server: onshosting.com CSGO Deathmatch 128 tick


Looks like creating the symbolic link worked. Thanks!
