### ISSUE TITLE
Thought of making this a AIO Game Management System?

### ISSUE THREAD

**Issue by SaturnsVoid** [dgibbs64/linuxgsm#428]
Have you thought about making LGSM into a AIO GMS? 

You could have a web panel that allows you to change settings, read logs, start/stop/restart servers, maybe even keep track of usage for each server?

**Comment by dgibbs64** [comment]
http://rokket.info/ is doing just that with LGSM. I recommend looking in to helping with Rokket project if you are interested. You would need to contact @aaroniker
