### ISSUE TITLE
[Enhancement] Selfupdate /Merge

### ISSUE THREAD

**Issue by DSDV** [dgibbs64/linuxgsm#431]
HI,
i recently checked all my serverscripts for updated version.

So i thought about making a cron job for updating them butr im to stupid :/

So is it possible to make a script/cronjob wich chekcs the GSMS for Updates and Merges them if ther is?

with best +DS_DV+

**Comment by dgibbs64** [comment]
Yeah just do it the same as update cronjob but replace update with update-functions. However once per week only is a good idea as update-functions just deletes the functions to be re downloaded.
