### ISSUE TITLE
Checking return code on commands

### ISSUE THREAD

**Issue by blha303** [dgibbs64/linuxgsm#435]
After each command in bash, the return code can be tested with [$?](http://stackoverflow.com/a/90435). A command can also run dependent on another command succeeding with &&. This would be particularly useful if, as in the below screenshot, a directory wasn't created, and all the subsequent processes failed.

![image](http://s.b303.me/L1S7.png)

**Comment by dgibbs64** [comment]
Yeah I use $? in some instances but not here. It shouldn't really fail in this area. However I had made some changes that I think I have now fixed. Hopefully so the issue should no longer be there
