### ISSUE TITLE
Can I make a server for accepting cracked players?

### ISSUE THREAD

**Issue by Fazelesswhite** [dgibbs64/linuxgsm#439]
hey guys! Ive already made a server but it doesnt seem to be accepting people with cracked version of counter strike 1.6, how do I do this? Thanks!

**Comment by xFaNaTiix** [comment]
We aren't supporting pirated versions, sorry.

> Non-steam versions of the games ARE pirated and this would be the only reason to use non-steam versions. Simply purchase the game via steam. Steam has two massive sales a year with 75% of most of there titles there is really no excuse for pirating these games. http://steampowered.com

**Comment by Fazelesswhite** [comment]
Okay
