### ISSUE TITLE
[Garry's Mod] Server fails to update.

### ISSUE THREAD

**Issue by essentialpapa** [dgibbs64/linuxgsm#440]
Hi Daniel,
Before I begin bringing up the issue I'm facing, I'd like to say thanks for creating such a great server management tool. It has been very useful and is definitely an upgrade from what I was using previously!

According to steamdb.info, there was a new update. When I go to update I get a message saying "[ FAIL ] Update gmod-server: Checking for update: SteamCMD: Not returning version info". If I try to update again it appears that it successfully returns version info without errors. It also says that there are no updates currently available and that the current and available version is 642749. When players attempt to connect to my server, they all receive a message saying that it is an older version.

Thanks,
Essentialpapa.

**Comment by dgibbs64** [comment]
Hello. Thanks for the kink message. Firstly make sure you have the latest version of gmodserver running on your server. check the server version in the main script and delete the functions dir. You may just need to update your script. Let me know the outcome of this first. :)
