### ISSUE TITLE
[sd2dserver] A12 update broken script

### ISSUE THREAD

**Issue by x32825** [dgibbs64/linuxgsm#441]
Just letting you know, 7DaysToDie just had a big update that changed the way its launched etc.

http://7daystodie.com/mini-bikes-physics-bears-a12/

EDIT:

Fixed changing these settings in sdtdserver, had to put exact config line otherwise it wouldn't do anything stating Specified config file "/home/sdtd1/serverfiles/sdtd-server.xml" does not exist.

```
parms="-configfile=/home/sdtd1/serverfiles/sdtd-server.xml -dedicated" 

changed from 

parms="-configfile=\"${servercfgfullpath}\" -dedicated"
```
```
executable="./startserver.sh" 

changed from 

executable="./7DaysToDie.sh"
````

**Comment by dgibbs64** [comment]
Fix released

https://github.com/dgibbs64/linuxgsm/commit/4095d3202328a90053046dd512095caa85e784cc
