### ISSUE TITLE
Insurgency server configs errors

### ISSUE THREAD

**Issue by Khailz** [dgibbs64/linuxgsm#442]
Seems that auto-install cannot create the config files needed.

Creating Configs
=================================
downloading lgsm-default.cfg...OK
creating ins-server.cfg config file.
cp: cannot stat ‘/home/insserver/serverfiles/insurgency/cfg/server.cfg’: No such file or directory
creating server.cfg.
touch: cannot touch ‘’: No such file or directory
creating redirect.
server.cfg > ins-server.cfg.
/home/insserver/functions/fn_install_config: line 96: : No such file or directory
sed: can't read /home/insserver/serverfiles/insurgency/cfg/ins-server.cfg: No such file or directory
sed: can't read /home/insserver/serverfiles/insurgency/cfg/ins-server.cfg: No such file or directory

**Comment by dgibbs64** [comment]
Do you have the most up to date version?

**Comment by Khailz** [comment]
I'm using the commands straight from the site

**Comment by dgibbs64** [comment]
Thanks.

    ./insserver update-functions 

I have released an update that should fix this :)

**Comment by Khailz** [comment]
Great Thank you! :)
