### ISSUE TITLE
When I change my gamemode, the server stops querying on the port

### ISSUE THREAD

**Issue by Wafflezzz** [dgibbs64/linuxgsm#443]
My server breaks when I change my gamemode to anything other than sandbox
the manager can't query its port or something like that

**Comment by dgibbs64** [comment]
Which server?

**Comment by Wafflezzz** [comment]
My gmod server

**Comment by Wafflezzz** [comment]
It works now :smile:

**Comment by Wafflezzz** [comment]
Im not sure what I did lol but it works now
