### ISSUE TITLE
[Mumble] Install command does not exist

### ISSUE THREAD

**Issue by geekpobre** [dgibbs64/linuxgsm#444]
When i try to use the mumbleserver script to setup a server it fail on
```bash
./mumbleserver install
```
with a message
```bash
Usage: ./mumbleserver {start|stop|restart|update-functions|monitor|email-test|backup|console|debug}
```

I also noticed the functions folder only have fn_functions, fn_getopt and fn_messages while the TeamSpeak script has dozen of fn files, including some with install in the name. I don't know it it's working as intended or not but looks strange to me.

**Comment by Scarsz** [comment]
Look at the instructions for how to install Mumble servers, it's difficult to do it automatically

**Comment by dgibbs64** [comment]
You have reminded me about this I need to sort the mumble instructions on the new site. Ouphs
