### ISSUE TITLE
[Garry's Mod]'/home/gmodserver/serverfiles/garrysmod/cfg/server.cfg' not present; not executing.

### ISSUE THREAD

**Issue by Wafflezzz** [dgibbs64/linuxgsm#445]
My Garry's Mod server won't execute the server.cfg file, this is what it says:
'/home/gmodserver/serverfiles/garrysmod/cfg/server.cfg' not present; not executing.
I have checked /home/gmodserver/serverfiles/garrysmod/cfg/server.cfg is the right directory and cfg file, but it won't work run for some reason! 

ALSO
Whenever I load my workshop content, the server starts, then crashes

**Comment by dgibbs64** [comment]
Sounds like the installer needs re running. run ./gmodserver update-functions and try the installer again.

**Comment by Wafflezzz** [comment]
It works, thanks!
