### ISSUE TITLE
[Garry's Mod]./srcds_run: line 372:  7034 Segmentation fault      $HL_CMD

### ISSUE THREAD

**Issue by Wafflezzz** [dgibbs64/linuxgsm#446]
I know I have opened quite a few "tickets" and I'm sorry, but my server won't start when it loads my workshop content, when I disable the workshop content it works just fine, this is the error I get then it crashes
./srcds_run: line 372:  7034 Segmentation fault      $HL_CMD

**Comment by Wafflezzz** [comment]
Its worked now I have deleted an addon which was causing it

**Comment by FlashModz** [comment]
whats Add-ons ?
