### ISSUE TITLE
[csserver] SERVER NAME MISSING!

### ISSUE THREAD

**Issue by jlagger** [dgibbs64/linuxgsm#452]
I installed Counter-Strike 1.6 server by default.
When I try to run it, getting this error:
> [  OK  ] Starting cs-server: SERVER NAME MISSING!

Server start but it ignore port variable and running on zero port:
> csserver  2843     1  0 02:04 ?        00:00:00 tmux new-session -d -s cs-server ./hlds_run -game cstrike -strictportbind -ip 10.10.0.38 -port 0 +clientport 27004 +map de_dust2 -maxplayers 16
> csserver  2844  2843  0 02:04 pts/2    00:00:00 /bin/sh ./hlds_run -game cstrike -strictportbind -ip 10.10.0.38 -port 0 +clientport 27004 +map de_dust2 -maxplayers 16
> csserver  2859  2844  7 02:04 pts/2    00:00:09 ./hlds_linux -game cstrike -strictportbind -ip 10.10.0.38 -port 0 +clientport 27004 +map de_dust2 -maxplayers 16

If I'm runnig it manually, that's **ok**.

Two days ago this script work fine on Fedora 20. But today it's not working on Fedora 22.

I think that problem in refactoring variables name. 
Csserver script have variables:
> servicename="cs-server"
> gamename="LugaMuga"
> engine="goldsource"

But fn_start and another scripts try use **${servername}** variable.

Can you help me?

**Comment by dgibbs64** [comment]
You changed an Advanced Variable which has broken part of the script.

servicename="cs-server"
gamename="Counter Strike 1.6"
engine="goldsource"

the game is Counter Strike 1.6 not LugaMuga

**Comment by jlagger** [comment]
You were right. I return defalt value and reinstall server, and it's work. 
Thank you!

Can you add comments to csserver script, which marking variables recommended do not change?
Because I think I'm not the last person who made the error.
