### ISSUE TITLE
Memory Leak Garry's Mod

### ISSUE THREAD

**Issue by TakeMeNL** [dgibbs64/linuxgsm#453]
I don't know how but when i run Garry' s Mod on LGSM in CentOS 6.4 64bit
it just ate all my ram. I have a dedicated server and need to force restart every time.
Atm i got 5gb ram 2gb swap and it just ate it like candy cousin my server to get stuck.

**Comment by Scarsz** [comment]
Memory leaks involving the literal server software FacePunch provides is basically out of our control, we just maintain the scripts to make using that software easier.
