### ISSUE TITLE
[Any] Cant disable console logging

### ISSUE THREAD

**Issue by Hinexs** [dgibbs64/linuxgsm#454]
What i must do?

**Comment by dgibbs64** [comment]
This has never been requested before. Is there a reason why you want to disable console logging?

**Comment by Hinexs** [comment]
High load on the hdd when i running more then one server (cos Im use stats plugint on both servers) and when my server under ddos attack (main reason)

Tech. support of my hosting said that i must disable logging to reduse I/O processes.

P.s sorry for bad eng. =)

**Comment by dgibbs64** [comment]
I have an idea on this one

try changing this variable in the main script file...Not sure if it will work but give it a go and let me know

    consolelog="/dev/null"

**Comment by dgibbs64** [comment]
Did this work?

**Comment by Hinexs** [comment]
server crashes

P.s Maybe its becauyse I use gameME stats, i dont know
