### ISSUE TITLE
[csserver] ./csserver: line 98: fn_getopt: command not found

### ISSUE THREAD

**Issue by flippas** [dgibbs64/linuxgsm#455]
Please check the script cs 1.6, currently it does not work!

**Comment by dgibbs64** [comment]
Care you explain why it is not working? I cannot look at an issue if you don't tell me the problem.

**Comment by flippas** [comment]
server@xxx:~$ ./csserver install
./csserver: line 98: fn_getopt: command not found
server@xxx:~$

**Comment by flippas** [comment]
the script does not complete

**Comment by flippas** [comment]
I have a script of your old version , it is a very different and work

**Comment by dgibbs64** [comment]
looks like a permissions issue maybe. As the script has not been able to download the functions it requires. Ensure that /home/csserver is owned by the correct user.

**Comment by flippas** [comment]
the script is in the root user with the rights 777. The issue is when you start . sorry for my language of the curve )

**Comment by dgibbs64** [comment]
http://gameservermanagers.com/lgsm/csserver/

Read the installation instructions to get the script to work, as you have not followed them.

https://github.com/dgibbs64/linuxgsm/wiki/FAQ#can-i-run-a-server-as-root

**Comment by flippas** [comment]
like anything, thank you, I think on the current root does not start , but he is also at the root of the user server does not start ...
