### ISSUE TITLE
CS:GO

### ISSUE THREAD

**Issue by ScottSmudger** [dgibbs64/linuxgsm#458]
I'm using this script for my CS:GO servers.

After installing it and starting the game the console gives this notification:

MasterRequestRestart
Your server needs to be restarted in order to receive the latest update.

Apparently this is quite a bug for server updating.

Two articles here:
http://forums.steampowered.com/forums/showthread.php?t=2897968
http://forums.steampowered.com/forums/showthread.php?t=2894570

**Comment by dgibbs64** [comment]
Try ./csgoserver update.

**Comment by ScottSmudger** [comment]
I did do that for both servers (share the same files). SteamCMD reported they were up-to-date as i had just installed them. One worked one didn't. Restarted again and I believe they are both working now. Maybe just a weird occurrence or it could be something to look into. Also, do you know a command line parameter or cfg setting to,change the name of console.log file ?

**Comment by Scarsz** [comment]
https://github.com/dgibbs64/linuxgsm/blob/bbb3fb16ba5e5e0042d9489a4630079f39ac3710/CounterStrikeGlobalOffensive/csgoserver#L81
