### ISSUE TITLE
Can't install CS:GO Server or TS3 Server

### ISSUE THREAD

**Issue by BrendanTA** [dgibbs64/linuxgsm#459]
Ubuntu 14.04 Created the user and everything...

./ts3server install
    loading fn_functions...chmod: cannot access 'fn_functions': No such file or directory
./ts3server: line 62: /home/ts3server/functions/fn_functions: No such file or directory
./ts3server: line 74: fn_getopt: command not found

**Comment by pokypine** [comment]
How did you solve this?

**Comment by BrendanTA** [comment]
I solved it by using CentOS 7
I have a complete command guide step by step I made for it if you want it.

**Comment by pokypine** [comment]
I solved it by adding --no-check-certificate to line 109

**Comment by BrendanTA** [comment]
Thanks :)
