### ISSUE TITLE
[insserver] Insurgency always fails to start

### ISSUE THREAD

**Issue by kennux** [dgibbs64/linuxgsm#460]
I hosted multiple insurgency server, some very long time ago with the linuxgsm. Since a insurgency update (i dont remember which) i am unable to use linuxgsm to host a insurgency server on linux.

Installation works perfectly (while install it says installed glibc 2.13, needed 2.15 but it installs 2.15. Maybe the fix doesnt work?), but when i try to start it:

```
kennux@Debian-78-wheezy-64-minimal:~/insserver/public$ ./insserver start
    loading fn_check_logs...OK
    loading fn_insfix...OK
    loading fn_details_config...OK
    loading fn_logs...OK
[ .... ] Starting ins-server: Insurgency Server    loading fn_check_tmux...OK
    loading fn_check_steamcmd...OK
session not found: ins-server
[ FAIL ] Starting ins-server: Unable to start Insurgency Server
```

Same in the logs. Nowhere a more detailed error message.
System information:

```
root@Debian-78-wheezy-64-minimal ~ # tmux -V
tmux 1.6
root@Debian-78-wheezy-64-minimal ~ # uname -a
Linux Debian-78-wheezy-64-minimal 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u1 x86_64 GNU/Linux
```

The strange thing is, when i run lgsm in debug mode everything works fine:
```
Insurgency Debug
============================

Distro: Debian 7.8
Arch: x86_64
Kernel: 3.2.0-4-amd64
Hostname: Debian-78-wheezy-64-minimal

Start parameters:
./srcds_linux -game insurgency -strictportbind -ip 5.9.156.38 -port 27015 +clientport 27005 +tv_port 27020 +map ministry +servercfgfile ins-server.cfg -maxplayers 16 -debug

Use for identifying server issues only!
Press CTRL+c to drop out of debug mode.
Warning! If ins-server is already running it will be stopped.

[................................]

Connection to Steam servers successful.
   Public IP is 5.9.156.38.
Assigned anonymous gameserver Steam ID [A:1:2201013248(5718)].
VAC secure mode is activated.
```

**Comment by dgibbs64** [comment]
https://github.com/dgibbs64/linuxgsm/wiki/Tmux#create-session-failed-operation-not-permitted

See if this helps?

**Comment by kennux** [comment]
I currently run the servers (with a static runscript created from the command generated by ./insserver debug) and some other tools on tmux fine with my non-root user.
Tried adding my user to the tty group. Didnt help.

**Comment by dgibbs64** [comment]
I'm afraid the issue is not obvious to me. There is something odd happening but I cannot tell what. Normally if debug works but start fails there is an issue with tmux. :-/
