### ISSUE TITLE
[ts3] Failure! i686 is an unsupported architecture

### ISSUE THREAD

**Issue by DCEM** [dgibbs64/linuxgsm#461]
Hi,

I get the following error when I try to install the ts3 server:
Failure! i686 is an unsupported architecture

It's proberbly a 32bit/64bit isse...
I hope you can help.

Greetings,
David

**Comment by dgibbs64** [comment]
What distro are you running? can you run ./ts3server details please

**Comment by DCEM** [comment]
Sure:
Distro Details:
Distro:   CentOS release 6.6 (Final)
Arch:   i686
Kernel:   3.18.9-jb1
tmux:   tmux 1.6
GLIBC:   2.12

**Comment by dgibbs64** [comment]
I see the problem. I will release a fix when I'm back home :-)

**Comment by dgibbs64** [comment]
Should be fixed.

https://github.com/dgibbs64/linuxgsm/commit/3c33d33f80789d8e34ee1b614a0657b1458c472f

./ts3server update-functions

and try again. Please confirm working. Thanks :)
