### ISSUE TITLE
[hldmcserver]

### ISSUE THREAD

**Issue by wiet** [dgibbs64/linuxgsm#464]
wget http://danielgibbs.co.uk/dl/hldmcserver

HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/dgibbs64/linuxgameservers/master/HalfLifeDeathmatchClassic/hldmcserver [following]
--2015-07-29 07:03:32--  https://raw.githubusercontent.com/dgibbs64/linuxgameservers/master/HalfLifeDeathmatchClassic/hldmcserver
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.31.17.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.31.17.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-07-29 07:03:33 ERROR 404: Not Found.

Please can you fix it? Time to back oldshool :D

**Comment by dgibbs64** [comment]
Fixed http://gameservermanagers.com/lgsm/dmcserver/
