### ISSUE TITLE
Doesnt restart by cron

### ISSUE THREAD

**Issue by originalwhitestar** [dgibbs64/linuxgsm#465]
Hello, I tried making so, that the server restarts everytime 5AM inside cron, syslog said the command ran successfully, but the server didnt restart(atleast the server logs dont say so), but when I run the command manually, it works fine, even gets logged. this is what I got in crontab:

```
0 5 * * * su - user '/path/to/server restart' > /dev/null 2>&1
```

**Comment by dgibbs64** [comment]
I cannot see anything wrong with that cronjob. I recommend testing by creating cronjobs to run a couple of mins after you set it and test.

**Comment by originalwhitestar** [comment]
I did that already multiple times before too, it still said that the cron was successfull(syslog said so in ubuntu) but the server didnt restart at all, and it wasnt logged.

**Comment by dgibbs64** [comment]
It's Ctrl+b, d not ctrl, b+d many people type the command wrong. 

I recommend trying your bash script with another command. E.g time
sh

#/bin/bash
date > /tmp/date

If that doesn't work there is some thing wrong with cron. The script is used by a lot of people without issue so its more likely some issue on your server

LGSM also uses tmux not screen.

**Comment by dgibbs64** [comment]
Also to ensure you have not made an error make sure you follow the instructions to the letter and test to rule out user error ;-)

**Comment by originalwhitestar** [comment]
some scripts of be worked without #bin/bash, but I reupdated it, which didnt work on root, crontab works fine on user though, I guess I have to use that.

I also could swear the server was running with screen, sorry, since my friend had on his server the console automaticly in screen, so I literally press CTRL + b - let go - and then d? because that didnt work for me either.
