### ISSUE TITLE
[insserver] CUtlRBTree overflow!

### ISSUE THREAD

**Issue by Hinexs** [dgibbs64/linuxgsm#468]
Is there anybody who faced with this?

**Comment by Scarsz** [comment]
Can you give the exact error as it's shown?

**Comment by Hinexs** [comment]
It happened when server changing map:


---- Host_Changelevel ----
[PartyTeamMgr] Grace period started.
L 08/05/2015 - 18:16:46: [META] Loaded 0 plugins (1 already loaded)
L 08/05/2015 - 18:16:46: Log file closed
Server logging data to file logs/L094_242_059_166_27015_201508051816_000.log
L 08/05/2015 - 18:16:46: Log file started (file "logs/L094_242_059_166_27015_201508051816_000.log") (game "/home/insserver/serverfiles/insurgency") (version "6088")
L 08/05/2015 - 18:16:46: Loading map "panj"
L 08/05/2015 - 18:16:46: server cvars start
L 08/05/2015 - 18:16:46: "sv_maxspeed" = "1000.000000"
L 08/05/2015 - 18:16:46: "sm_adminslist_version" = "1.0"
L 08/05/2015 - 18:16:46: "spec_allow_bots" = "0"
L 08/05/2015 - 18:16:46: "sv_rollangle" = "0"
L 08/05/2015 - 18:16:46: "ins_teamsize" = "0"
L 08/05/2015 - 18:16:46: "sv_cheats" = "0"
L 08/05/2015 - 18:16:46: "r_VehicleViewDampen" = "1"
L 08/05/2015 - 18:16:46: "metamod_version" = "1.11.0-dev+985V"
L 08/05/2015 - 18:16:46: "mp_allowNPCs" = "1"
L 08/05/2015 - 18:16:46: "sv_deadtalk_team" = "1"
L 08/05/2015 - 18:16:46: "mp_timer_voting" = "25"
L 08/05/2015 - 18:16:46: "gameme_webpage" = "http://www.gameme.com"
L 08/05/2015 - 18:16:46: "mp_maxgames" = "1"
L 08/05/2015 - 18:16:46: "sv_stopspeed_prone" = "45"
L 08/05/2015 - 18:16:46: "mp_flashlight" = "0"
L 08/05/2015 - 18:16:46: "mp_maxrounds" = "5"
L 08/05/2015 - 18:16:46: "sv_tags" = "gameME,pub,russia,whiskey"
L 08/05/2015 - 18:16:46: "sv_stepsize" = "18"
L 08/05/2015 - 18:16:46: "mp_teamlist" = "hgrunt;scientist"
L 08/05/2015 - 18:16:46: "sv_alltalk" = "1"
L 08/05/2015 - 18:16:46: "mp_timer_pregame" = "10"
L 08/05/2015 - 18:16:46: "mp_footsteps" = "1"
L 08/05/2015 - 18:16:46: "mp_supply_rate_losing_team_low" = "1"
L 08/05/2015 - 18:16:46: "sv_noclipaccelerate" = "5"
L 08/05/2015 - 18:16:46: "mp_timer_preround_switch" = "30"
L 08/05/2015 - 18:16:46: "sv_hud_deathmessages" = "0"
L 08/05/2015 - 18:16:46: "sv_wateraccelerate" = "10"
L 08/05/2015 - 18:16:46: "mp_autocrosshair" = "1"
L 08/05/2015 - 18:16:46: "sourcemod_version" = "1.8.0-dev+5533"
L 08/05/2015 - 18:16:46: "sv_rollspeed" = "200"
L 08/05/2015 - 18:16:46: "sv_airaccelerate" = "10"
L 08/05/2015 - 18:16:46: "mp_teams_unbalance_limit" = "1"
L 08/05/2015 - 18:16:46: "mp_timelimit" = "0"
L 08/05/2015 - 18:16:46: "sv_deadtalk" = "0"
L 08/05/2015 - 18:16:46: "sv_alltalk_dead" = "0"
L 08/05/2015 - 18:16:46: "mp_minteamplayers" = "1"
L 08/05/2015 - 18:16:46: "mp_fadetoblack" = "0"
L 08/05/2015 - 18:16:46: "sm_gamevoting_version" = "1.7"
L 08/05/2015 - 18:16:46: "gameme_plugin_version" = "4.5.1"
L 08/05/2015 - 18:16:46: "sv_waterfriction" = "1"
L 08/05/2015 - 18:16:46: "sv_steamgroup" = ""
L 08/05/2015 - 18:16:46: "mp_friendlyfire_explosives" = "0"
L 08/05/2015 - 18:16:46: "mp_lobbytime" = "10"
L 08/05/2015 - 18:16:46: "sv_hud_targetindicator" = "1"
L 08/05/2015 - 18:16:46: "mp_cp_capture_time" = "30"
L 08/05/2015 - 18:16:46: "mp_cp_speedup_max" = "4"
L 08/05/2015 - 18:16:46: "mp_supply_rate_losing_team_high" = "2"
L 08/05/2015 - 18:16:46: "coop" = "0"
L 08/05/2015 - 18:16:46: "sv_hud_scoreboard_show_score_dead" = "1"
L 08/05/2015 - 18:16:46: "nextlevel" = "panj skirmish"
L 08/05/2015 - 18:16:46: "mp_coop_lobbysize" = "6"
L 08/05/2015 - 18:16:46: "sv_stopspeed" = "75.000000"
L 08/05/2015 - 18:16:46: "sv_specaccelerate" = "5"
L 08/05/2015 - 18:16:46: "deathmatch" = "1"
L 08/05/2015 - 18:16:46: "ins_bot_difficulty" = "1"
L 08/05/2015 - 18:16:46: "tv_enable" = "0"
L 08/05/2015 - 18:16:46: "sw_auto_steam_update_version" = "0.1"
L 08/05/2015 - 18:16:46: "sm_advertisements_version" = "0.6"
L 08/05/2015 - 18:16:46: "mp_supply_rate_winning_team_high" = "2"
L 08/05/2015 - 18:16:46: "mp_switchteams_each_round" = "2"
L 08/05/2015 - 18:16:46: "mp_timer_postround" = "15"
L 08/05/2015 - 18:16:46: "sv_hud_scoreboard_show_score" = "0"
L 08/05/2015 - 18:16:46: "sv_nwi_banlist" = "1"
L 08/05/2015 - 18:16:46: "mp_falldamage" = "0"
L 08/05/2015 - 18:16:46: "mp_freezetime" = "15"
L 08/05/2015 - 18:16:46: "mp_extract_point" = "0"
L 08/05/2015 - 18:16:46: "mp_cp_speedup_rate" = "0.26"
L 08/05/2015 - 18:16:46: "mp_respawnwavetime_min" = "20"
L 08/05/2015 - 18:16:46: "sv_voiceenable" = "1"
L 08/05/2015 - 18:16:46: "sv_bounce" = "0"
L 08/05/2015 - 18:16:46: "mp_spawnprotectontime" = "30"
L 08/05/2015 - 18:16:46: "mp_weaponstay" = "0"
L 08/05/2015 - 18:16:46: "sm_information_version" = "3.6"
L 08/05/2015 - 18:16:46: "mp_winlimit_coop" = "1"
L 08/05/2015 - 18:16:46: "mp_scrambleteams_auto" = "0"
L 08/05/2015 - 18:16:46: "mp_friendlyfire" = "1"
L 08/05/2015 - 18:16:46: "sv_noclipspeed" = "5"
L 08/05/2015 - 18:16:46: "sv_allchat" = "1"
L 08/05/2015 - 18:16:46: "mp_joinwaittime" = "20"
L 08/05/2015 - 18:16:46: "mp_roundlives" = "0"
L 08/05/2015 - 18:16:46: "sm_motdgd_userid" = "561"
L 08/05/2015 - 18:16:46: "sv_map_voting" = "1"
L 08/05/2015 - 18:16:46: "mp_supply_token_max" = "20"
L 08/05/2015 - 18:16:46: "sm_permamute_version" = "0.1"
L 08/05/2015 - 18:16:46: "mp_supply_token_bot_base" = "18"
L 08/05/2015 - 18:16:46: "mp_scrambleteams_auto_windifference" = "3"
L 08/05/2015 - 18:16:46: "sm_nextmap" = ""
L 08/05/2015 - 18:16:46: "sm_console_welcome_version" = "1.1.2"
L 08/05/2015 - 18:16:46: "mp_ambush_single_point_max" = "10"
L 08/05/2015 - 18:16:46: "mp_timer_postgame" = "10"
L 08/05/2015 - 18:16:46: "mp_respawnwavetime_max" = "30"
L 08/05/2015 - 18:16:46: "sv_footsteps" = "1"
L 08/05/2015 - 18:16:46: "mp_timer_preround" = "15"
L 08/05/2015 - 18:16:46: "mp_cp_deteriorate_time" = "0"
L 08/05/2015 - 18:16:46: "mp_searchdestroy_single_cache_max" = "12"
L 08/05/2015 - 18:16:46: "tv_relaypassword" = ""
L 08/05/2015 - 18:16:46: "mp_teamplay" = "0"
L 08/05/2015 - 18:16:46: "mp_supply_token_base" = "10"
L 08/05/2015 - 18:16:46: "sv_specnoclip" = "1"
L 08/05/2015 - 18:16:46: "sv_friction" = "4"
L 08/05/2015 - 18:16:46: "mp_switchteams_reset_supply" = "1"
L 08/05/2015 - 18:16:46: "sv_contact" = "mihailfs@gmail.com"
L 08/05/2015 - 18:16:46: "scc_version" = "2.0.0.$Rev$"
L 08/05/2015 - 18:16:46: "sm_motdgd_version" = "2.3.2"
L 08/05/2015 - 18:16:46: "mp_roundtime" = "300"
L 08/05/2015 - 18:16:46: "sv_hud_deathmessages_spectator" = "0"
L 08/05/2015 - 18:16:46: "mp_timer_preround_first" = "15"
L 08/05/2015 - 18:16:46: "mp_switchteams_each_game" = "0"
L 08/05/2015 - 18:16:46: "scp_version" = "1.1.5A"
L 08/05/2015 - 18:16:46: "mp_fraglimit" = "0"
L 08/05/2015 - 18:16:46: "sm_updater_version" = "1.2.2"
L 08/05/2015 - 18:16:46: "mp_forcerespawn" = "1"
L 08/05/2015 - 18:16:46: "decalfrequency" = "10"
L 08/05/2015 - 18:16:46: "hpk_lite_version" = "1.0.0.1"
L 08/05/2015 - 18:16:46: "sv_accelerate" = "10"
L 08/05/2015 - 18:16:46: "mp_winlimit" = "3"
L 08/05/2015 - 18:16:46: "sv_gravity" = "800"
L 08/05/2015 - 18:16:46: "sv_password" = ""
L 08/05/2015 - 18:16:46: "ins_bot_change_difficulty" = "1"
L 08/05/2015 - 18:16:46: "mp_supply_rate_winning_team_low" = "1"
L 08/05/2015 - 18:16:46: "sv_deadvoice" = "0"
L 08/05/2015 - 18:16:46: "tv_password" = ""
L 08/05/2015 - 18:16:46: "sv_specspeed" = "3"
L 08/05/2015 - 18:16:46: server cvars end
CUtlRBTree overflow!
CUtlRBTree overflow!

**Comment by Scarsz** [comment]
Is the system's memory low? That error is usually from not being able to use any more memory

**Comment by Hinexs** [comment]
1Gb
htop usually show 800/1000

**Comment by Scarsz** [comment]
That's likely what your problem is, then, try increasing the amount of memory the server can use and try again

**Comment by DJPlaya** [comment]
I have a TF2 Server with 260+ Plugins and its even not using 1 GB Ram.
This Crash is a pretty difficult one, it can be caused by nearly anything.
On the Inet, some say its the Map/Ram/ConVars/missing Files/Model or Material Problem etc. but the truth is that no one knows.
I personally think that its the precaching of Recources that contain Parameters not existing in the Game, like if some Model is using "CS_ENT" instead of "C_SENT" and with that overflowing the Table.
