### ISSUE TITLE
How do i auto install it(want to create a PHP panel) [question]

### ISSUE THREAD

**Issue by nizarnizario** [dgibbs64/linuxgsm#471]
Hi,

I'm building a game panel for steam based games , 
and i'm using linuxgsm with ssh to remote install servers;
is there a solution to auto install it? (i mean skip the YES prompts , and maybe change ports if used -not a real issue-)

**Comment by dgibbs64** [comment]
./csgoserver auto-install

**Comment by nizarnizario** [comment]
thx, (so ; it skips the Yes...)
what about ports?

**Comment by nizarnizario** [comment]
anyone?

**Comment by dgibbs64** [comment]
Ports have to be manually changed. They stay the default until you change it.

**Comment by nizarnizario** [comment]
thank you :)
