### ISSUE TITLE
[LGSM] Email on update

### ISSUE THREAD

**Issue by dgibbs64** [dgibbs64/linuxgsm#472]
Email when an update is applied

**Comment by dgibbs64** [comment]
will need to look at this with #566

**Comment by jaredballou** [comment]
FYI: I use some Steam API stuff that may be helpful. See https://github.com/jaredballou/insurgency-tools/blob/master/server.php - that takes an array of servers, gets their version info, and then compares it against what the Steam API says the latest version is. Can also look at $GAMEDIR/steam.inf for the PatchVersion variable if you want to just cut out the Steam API stuff, and simply compare a version number. Let me know if you want a hand with this.

**Comment by dgibbs64** [comment]
This feature has now been implemented. However I would like to improve over time.

**Comment by dgibbs64** [comment]
Closing this now as Im happy this works
