### ISSUE TITLE
[twserver] Server Request

### ISSUE THREAD

**Issue by marvinl97** [dgibbs64/linuxgsm#477]
## Teeworlds
* Steam Store: http://store.steampowered.com/app/380840/
* appid: 380840
* Server Setup: https://www.teeworlds.com/?page=docs&wiki=server_setup
* Server Commands: https://www.teeworlds.com/?page=docs&wiki=server_commands
* Server Settings https://www.teeworlds.com/?page=docs&wiki=server_settings
* Repository: https://github.com/teeworlds/teeworlds
* is supporting "autoexec.cfg"

possible ways for start parameter:
>./teeworlds_srv -f server.cfg "sv_bindaddr 0.0.0.0" "sv_port 8304" "sv_max_clients 16"
>./teeworlds_srv "exec server.cfg" "sv_bindaddr 0.0.0.0" "sv_port 8304" "sv_max_clients 16"
>./teeworlds_srv "exec server.cfg;sv_bindaddr 0.0.0.0;sv_port 8304;sv_max_clients 16"
source: https://www.teeworlds.com/forum/viewtopic.php?id=8503

I tried a bit but I'm not good enough to add a game ._.

**Comment by SingingTree** [comment]
I'm having a little look at this and am going to collect notes here for my benefit, or in case someone wishes to pick this up in future:
* Look like the game requires and account to grab (no anonymous login)

**Comment by SingingTree** [comment]
I've had a run at this. I haven't got the default config sorted yet, but will try and tackle that next.
