### ISSUE TITLE
Option to check what crashed.

### ISSUE THREAD

**Issue by TheConsciousness** [dgibbs64/linuxgsm#479]
My GMOD server is much more stable using this setup, but I'm still having one problem: not knowing what is causing crashes. The server has crashed back to back 2 times in a row, but server/script logs only show the last props that were spawned. How would I go about finding error messages?

**Comment by dgibbs64** [comment]
the logs should go back around 7 days by default

**Comment by TheConsciousness** [comment]
True, but those error logs: console (disabled), script, and server do not contain any information about server crashing. Without linuxgsm, the errors would be contained in the log files, however they are no longer handled when GMod is ran through this.

**Comment by dgibbs64** [comment]
/home/gmodserver/logs/server is just a symbolic link to the gmod server logs that is generated by the gmod server. By default the gmod server logs are here /home/gmodserver/serverfiles/garrysmod/logs

Maybe there is a parameter you should be running? or logging is not enabled in your config? What do you think is different for your logs not to show. The scripts are designed to run vanilla servers by default and have logging enabled so shouldn't be any different from running without LGSM.

Also this will get console logs to work if its not http://stackoverflow.com/a/25952511

**Comment by TheConsciousness** [comment]
Awesome, I got Tmux updated. I noticed that console logging was mentioned to be turned off in the console log files, is there a setting in linuxgsm or is console logging enabled through command line?

**Comment by dgibbs64** [comment]
Console logging just starts working when you have the correct version of tmux

https://github.com/dgibbs64/linuxgsm/wiki/Tmux#tmux-18
