### ISSUE TITLE
[Arma 3 Server] crontab

### ISSUE THREAD

**Issue by borg333** [dgibbs64/linuxgsm#480]
Ubuntu 14 server
When i add cron job for testing in crontab

*/1 * * * * /home/arma3server/arma3server update > /home/arma3server/serverfiles/restarter/update

in 'update' log file i have 

-e     loading ...Bad Request

If i use sh script for restarting

#/bin/bash
cd /home/arma3server
./arma3server restart
echo "server restarting"

then i'll get 

./arma3server: 51: ./arma3server: Bad substitution
-e     loading ...Bad Request
chmod: cannot access ‘’: No such file or directory
./arma3server: 96: ./arma3server: source: not found
./arma3server: 108: ./arma3server: fn_getopt: not found
server restarting

but if i do the same via console, it is ok, server runing/restarting and e.t.c

With 'start' 'stop' 'restart' 'monitor' the same. What i doing wrong? In CentOS 7 it's ok
Thanks in advance.

**Comment by andreblue** [comment]
Can you try to do it with /home/arma3server/arma3server restart 
Thats how i have mine running.

**Comment by ReMuSRaCinG** [comment]
this is my cronjob

and this work for me for restart all 4 hours

0 0,4,8,12,16,20 * * * /bin/bash /home/arma3server/arma3server restart    

use this to update the server at 00:00

0 0 * * * /bin/bash /home/arma3server/arma3server update
