### ISSUE TITLE
[Unreal Tournament - Pre Alpha] Server Request

### ISSUE THREAD

**Issue by Breakmaster90** [dgibbs64/linuxgsm#482]
I hope you can make this for that awesome game.

https://wiki.unrealengine.com/Servers_(Unreal_Tournament)

**Comment by dgibbs64** [comment]
I would like to do this. I'm away currently so may be a while.

**Comment by SaturnsVoid** [comment]
Hope this happens! Love your scripts, makes running servers so simple!

**Comment by UltimateByte** [comment]
I didn't even know about this game ! Could be great, i add this onto my checklist !

**Comment by UltimateByte** [comment]
Well, i just tried the game, and i think its pre alpha name is very well chosen.
Ugly, stupid key binding, stupid mouse acceleration that you can't disable (discovored things in that order). Not to mention you have to install that stupid Epic Games Launcher...
I'm a bit sad right now.
And the server setup and maintenance seems to be a complete mess according to your link and everything i found...

**Comment by UltimateByte** [comment]
I really feel like their server system is a complete mess.
I'm un-assigning and closing this for now hoping somebody feels like it's doable. I personally don't. I'm also very sad to see how unreal tournament went with that game... It used to be a hardcore FPS game, now it feels like a unfinished toy.
