### ISSUE TITLE
[ArkServer] Port 27015

### ISSUE THREAD

**Issue by ReMuSRaCinG** [dgibbs64/linuxgsm#483]
ARK: Survivial Evolved Debug
============================

Distro: Debian 8.2
Arch: x86_64
Kernel: 3.16.0-4-amd64
Hostname: Debian-82-jessie-64-LAMP

Start parameters:
./ShooterGameServer Port=7778?QueryPort=27015?TheIsland?listen?SessionName=[GER]ArkNation|FastXP|FastTaming|?ServerPassword=?ServerAdminPassword=avicularia -server

Use for identifying server issues only!
Press CTRL+c to drop out of debug mode.
Warning! If ark-server is already running it will be stopped.

Continue? [y/N]y
[ INFO ] Debug ark-server: Stopping any running servers
[ FAIL ] Stopping ark-server: [GER]ArkNation|FastXP|FastTaming| is already stopped
[  OK  ] Debug ark-server: Starting debug
Using binned.
4.5.1-0+UE4 7038 3077 402 4
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
CreateBoundSocket: ::bind couldn't find an open port between 27015 and 27015
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
CreateBoundSocket: ::bind couldn't find an open port between 27015 and 27015

what can i do to fix this??

**Comment by Scarsz** [comment]
What's the output of `netstat -tulpn | grep :27015`

Note that only one ARK:SE server can be running at once

**Comment by ReMuSRaCinG** [comment]
I fixes i add Port= and QueryPort= to Start Script amd delete the other in
the setting file
Am 27.09.2015 09:22 schrieb "Scarsz" <notifications@github.com>:
