### ISSUE TITLE
[ArkServer] GameUserSettings Always overwrite

### ISSUE THREAD

**Issue by ReMuSRaCinG** [dgibbs64/linuxgsm#484]
HI i edit the GameUserSettings and always after the server restart are my GameUserSetting are set to Default??

Any Fix for This

**Comment by Cuppycake** [comment]
Having this issue as well. 

I edited the initial files and started the server. Everything stuck and the server title is what I wanted it at the time.

Now I edit the server title and it never shows the new title on restart. 
Pulling the same file back out from FTP shows my changes still present but they seem to not apply.

**Comment by ReMuSRaCinG** [comment]
I found my Problem i use this | in my Name a change to this - and now works ark can Not read the Letter |
