### ISSUE TITLE
[Project Zomboid]

### ISSUE THREAD

**Issue by lnxprof** [dgibbs64/linuxgsm#485]
Project zomboid apparently no longer uses the beta branch of the appid 10800 any more, rendering the pzserver script defunct.

According to this link: 
https://steamcommunity.com/sharedfiles/filedetails/?id=514493377
the new appid is 380870.

There also appears to be a new server startup script included in the server base.

**Comment by KuroTsuto** [comment]
It also not longer requires a Steam account with ownership of the game to obtain the server - it can be retrieved from SteamCMD with the anonymous user

**Comment by dgibbs64** [comment]
I am unable to resolve this currently as I'm away and wont be able to do this for a few weeks. If anyone is able to fix this before then I can merge it.

**Comment by SingingTree** [comment]
I'll try and take a look at this today.
