### ISSUE TITLE
[Arma3] Missing directory causing segfault w/ fix

### ISSUE THREAD

**Issue by lnxprof** [dgibbs64/linuxgsm#488]
Arma 3 dumps core with recent updates:

`/home/arma3server/functions/fn_debug: line 63: 20150 Segmentation fault (core dumped) ${executable} ${parms}`

See [the steam discussion](http://steamcommunity.com/groups/linuxgsm/discussions/0/490121928340799753/) for all the details, and the fix:
   `mkdir -p "/home/arma3server/.local/share/Arma\ 3"`

**Comment by sapphirecz** [comment]
Hey lnxprof,

I cant confirm this fix really worked for me.

Thanks for sharing.

sapphire

**Comment by lnxprof** [comment]
"cant" or "can" confirm?

**Comment by sapphirecz** [comment]
Sorry, my bad - correct is "can"

**Comment by lnxprof** [comment]
Děkuji

**Comment by dgibbs64** [comment]
Is this somthing I need to write in to LGSM or do you think this will be fixed?

**Comment by aikidoka** [comment]
I just helped someone with this issue, on a fresh install. 

I suggest adding the `mkdir -p "/home/arma3server/.local/share/Arma\ 3"` to `fn_arma3config()`.

I'm not sure if BI will fix it; as they have tickets related to it, but no solutions/fixes added.

**Comment by dgibbs64** [comment]
Added fix
https://github.com/dgibbs64/linuxgsm/commit/46a812604ff18063ee1472906930ff85fb31ebc5
