### ISSUE TITLE
Cannot install ArmA3 DEV branch

### ISSUE THREAD

**Issue by djbarney** [dgibbs64/linuxgsm#490]
Hi, the linuxgsm script installed everything perfectly, but I wanted to update to the DEV branch of the server. The dedicated server is not available as DEV version yet, but as I understand it I should be able to install it by downloading the full A3 install ...

Below from ... https://forums.bistudio.com/topic/139003-tutorial-how-to-run-arma3-on-a-dedicated-server/

https://community.bistudio.com/wiki/Arma_3_Dedicated_Server ... does not mention any of this ?

------------------------

SELECTING DEVELOPMENT OR STABLE BUILD

Edit the ArmA3_Steam_Updater.cmd and run it

To select Development version

    SET A3BRANCH=107410 -beta development

To roll back to stable build

    SET A3BRANCH=107410

To use the Dedicated server package (Stable branch only)
This has a smaller diskspace footprint than the full client installs

    SET A3BRANCH=233780 -beta
    In your root install, make sure your steamappid.txt file entry is 107410 (Do not use 233780)

Important Feature
since 12th March 2013
the development branch and the stable branch versions are no longer compatible. this means:

    Only DEV clients can connect to a DEV server
    Only Stable clients can connect to stable servers

Important Feature
since ? 2014
A dedicated server package is now available which has a smaller disk space footprint than the full client install
Most if not all client only required files have been removed. Graphics, sounds etc
This package is only available on the stable branch.
Use SET A3BRANCH=233780 -beta
Leave the steamappid.txt file entry as 107410 

----------------------------

Console output ...

-----------------------------

[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.
Logging in user 'djbarneyA3' to Steam Public...Logged in OK
Waiting for license info...OK
ERROR! Failed to install app '107410' (No subscription)
[  OK  ] Update arma3-server: Updating djbarney-arma3server
Redirecting stderr to '/home/temporalcoldwar24_gmail_com/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.
Logging in user 'djbarneyA3' to Steam Public...Logged in OK
Waiting for license info...OK
ERROR! Failed to install app '107410' (No subscription)
[ .... ] Update arma3-server: Checking for update: SteamCMDgrep: : No such file or directory
[ FAIL ] Update arma3-server: Checking for update: SteamCMD: Not returning version infotemporalcoldwar24_gmail_com@djbarney-arma3server
:~$ 
temporalcoldwar24_gmail_com@djbarney-arma3server:~$ fg
vim arma3server
[1]+  Stopped                 vim arma3server
temporalcoldwar24_gmail_com@djbarney-arma3server:~$ mc
temporalcoldwar24_gmail_com@djbarney-arma3server:~$ 
temporalcoldwar24_gmail_com@djbarney-arma3server:~$ ./arma3server validate
[ WARN ] Validate arma3-server: Validating may overwrite some customised files.
https://developer.valvesoftware.com/wiki/SteamCMD#Validate
[  OK  ] Validate arma3-server: Checking server filesRedirecting stderr to '/home/temporalcoldwar24_gmail_com/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.
Logging in user 'djbarneyA3' to Steam Public...Logged in OK
Waiting for license info...OK
ERROR! Failed to install app '107410' (No subscription)
temporalcoldwar24_gmail_com@djbarney-arma3server:~$ 

------------------------------

I have set my username and password.

(Thanks for linuxgsm ! :)

**Comment by dgibbs64** [comment]
No subscription for ARMA 3 in your account suggesting you dont own a copy of it.
    
    ERROR! Failed to install app '107410' (No subscription)

Am i right in saying that the beta server release is under appid 107410 and not 233780?

    # Steam
    # Stable
    appid="233780"
    # Development
    # appid="233780 -beta development"
