### ISSUE TITLE
Restarting the server makes the system report it through email as crash

### ISSUE THREAD

**Issue by originalwhitestar** [dgibbs64/linuxgsm#491]
Hello there, I made the server automaticly restart everytime 5AM using the method in the wiki(crontab + ./gmodserver restart)

and I everytime get an email telling me the process is not running, is that fixable?

**Comment by ConversionGaming** [comment]
Hi, you've gotten further than me! I can't seem to configure mine to send me an email. Is there dependencies missing. Do i need to host a mail server?

**Comment by dgibbs64** [comment]
@ConversionGaming you need to make sure you have installed postfix. There is a little configuration required for this.

@originalwhitestar I think that you must be running the restart at exactly the same time as you are running a monitor. Try setting the restart at 5:01 as im guessing the monitor runs at exactly 5:00 as well

**Comment by dgibbs64** [comment]
an overhaul of the notificatino feature is due #566. Will close this issue.
