### ISSUE TITLE
[GMOD] Server running, but not accessible

### ISSUE THREAD

**Issue by TheConsciousness** [dgibbs64/linuxgsm#492]
I've had this happen to me two times in the past month or so, but 'gmodserver details' shows the server being online and active, while nobody can connect to the server and game trackers show it as being offline. At this time, CPU usage hovers around 90-100% as well. The server had an uptime of 9 days and all logs show nothing but normal user activity before they get cut off halfway within lines like so:
>L 10/09/2015 - 06:49:18: [ULX] AndrewS<STEAM_0000> spawned model models/hunter/tubes/tube2x2x8.mdl
>L 10/09/2015 - 06:49:18: [ULX] AndrewS<STEAM_0000> spaw

What could be the issue if logs are showing nothing out of the ordinary?

**Comment by Scarsz** [comment]
You might need to check if that prop can/will cause fatal errors or
crashing, as some props do that.

**Comment by dgibbs64** [comment]
I cannot assist however just make sure monitor is working correctly to get the server back online if it crashes.
