### ISSUE TITLE
[CSGO] Multiple csgo servers

### ISSUE THREAD

**Issue by gelleby** [dgibbs64/linuxgsm#495]
What is the best way on getting multiple csgo servers.

Copying the csgoserver directory multiple times or running multiple instances from one directory?

Adding a script to the csgo server, for example:
```
port="27015"
sourcetvport="27020"
if [[ $2 == "war1" ]]; then
	port="27015"
	sourcetvport="27115"
fi
if [[ $2 == "war2" ]]; then
	port="27016"
	sourcetvport="27116"
fi
if [[ $2 == "war3" ]]; then
	port="27017"
	sourcetvport="27117"
fi
if [[ $2 == "war4" ]]; then
	port="27018"
	sourcetvport="27118"
fi
```
Or running a "startall" script, for example:
```

#!/bin/bash
/home/steam/csgoserver1 start
/home/steam/csgoserver2 start
/home/steam/csgoserver3 start
/home/steam/csgoserver4 start
/home/steam/csgoserver5 start
/home/steam/csgoserver6 start
```

That last one didnt really work on my end as it only started the first csgoserver and not the rest.
Or am I looking at this the wrong way?

What path is common for steam?

Thanks for help :)

**Comment by andreblue** [comment]
Are you running the server from the same serverfiles directory? Or are they each in their own? Did you also edit the service name in the csgoserver script? That could cause a conflict with it also

**Comment by gelleby** [comment]
I'm doing both and wondering what option is the best.
I did not only edit the service name, I applied more scripting and logs for all 6 csgo servers.

The issue was indeed due to the service name conflict.

But I'm still wondering what option is best.
My opinion is that with running 6 csgo servers from directory, u only have to update 1 folder.
And that's a plus...

**Comment by andreblue** [comment]
If it is all the same then one should be fine but if you are running different gamemodes or modes then you may want to run it in seperate ones.

**Comment by ScottSmudger** [comment]
Regardless this will all work in the same directory.
Just change the service-name variable and the port(s) that the server will use the script will create separate log files for each server based on the service name.

There is no need to separate them, even if you have multiple game modes.
Plus, in the same directory is a lot easier if you ever have custom content. You can also use the autoexec.cfg file to execute the same cvars on multiple servers as they will probably have commonalities.
