### ISSUE TITLE
CS GO Server Changes

### ISSUE THREAD

**Issue by busheezy** [dgibbs64/linuxgsm#500]
http://csgo-servers.1073505.n5.nabble.com/Notice-of-changes-to-CS-GO-Game-Server-Operation-td10261.html

There will be some changes to cs go servers soon and I figured I would let you know ahead of time.

Thanks for all of your work,
Ryan

**Comment by ScottSmudger** [comment]
This isn't something that can be implemented into the scripts.

This is something the server owner should look into.

**Comment by dgibbs64** [comment]
Reading in to this further it looks like its going to be a pain for CS:GO server owners at first at least. I dont think I need to make any changes yet. I may need to update documentation when this is further on down the time. However for now I will not action any changes. Thanks for the info @busheezy I will keep an eye on this one.

**Comment by busheezy** [comment]
This is required now.  All servers are required to have the token so I figured it would be implemented into the script to be put into the server cfg.

**Comment by dgibbs64** [comment]
I have updated LGSM csgo and tf2 scripts last night.

**Comment by busheezy** [comment]
Thank you.
