### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by Pink3vil** [dgibbs64/linuxgsm#501]
Hello,

The Problem: I can't start my server. Every time I try (assuming -debug is used), the following error is spewed:

[CODE]
Segmentation fault (core dumped)
BFD: Attention: /home/garrysmodserver/srcds/core est tronqué: taille attendue du cœur du fichier >= 1610387456, obtenu: 1024000.
Cannot access memory at address 0xf77d1928
Cannot access memory at address 0xf77d1924
Python Exception Cannot access memory at address 0xffaf8b10:
debug.cmds:1: Error in sourced command file:
Cannot access memory at address 0xffaf8b10
email debug.log to linux@valvesoftware.com
mardi 20 octobre 2015, 03:17:43 (UTC+0200): Server Quit
[/CODE]

The Attempts ;

Installing ia32-libs and the like. The packages do not exist in my repository (probably because I'm running 32-bit)
Deleting the file and trying again. srcds redownloaded it but it was still truncated
Running the update tool with -verify_all (redownloads a bunch of things but does not fix the problem)
Running "-command update" with various -game parameters ("garrysmod", "tf", etc)
Add Ram to server
Launch in Sandbox normal
Install build-essential
But don't work i have a segmentation fault

In the old thread ...

[QUOTE=Jetsurf;34939274]Then why the hell would you run Linux at all? The Linux servers are always up to date...

The problem is garry forgot a few of the .so libraries in the linux version. Download:
[URL]http://jetsurf.breakpointservers.com/lin_mac_bins.rar[/URL]

and copy the contents to /serverdir/orangebox/bin and try starting your server then

If you feel safer downloading "Garry's official" ones, here is another link
[URL]http://dl.dropbox.com/u/3590255/Temp/linux-131.zip[/URL]

Hope that helps[/QUOTE]
[url]https://facepunch.com/showthread.php?t=1163479[/url]

[QUOTE=Python1320;33757064][code]00:51:02 http://dl.dropbox.com/u/3590255/Temp/linux-131.zip
00:51:38 let's see
00:52:08 I remember i added these ones to my gmod installation
00:52:29 garry, yep works now
00:52:34 * luastoned (~luastoned@luastoned.com) has joined #gmod
00:52:47 * Ideal-Hosting has quit (Ping timeout)
00:52:58 yay a solution!
00:53:09 patch derps
00:53:18 not as bad as 1.2 for skyrim tho
00:54:54 ok I'm gonna patch this up then
00:55:04 you can use those dropbox bins for the time being[/code][/QUOTE]
[url]https://www.facepunch.com/threads/1148247[/url]

But all links is down ? How to have new link of this version and where install this download ?

Thank all
Escuse me for my bad english :)

THREAD : https://facepunch.com/showthread.php?t=1490418&p=48940558#post48940558

**Comment by ScottSmudger** [comment]
Segmentation fault appears when you try and upload the executable that the server is using.

The script downloads it all for you so you shouldn't need to do this.

But if you are uploading some files manually use the FTP client WinSCP.

**Comment by ScottSmudger** [comment]
Contacted me on steam, fixed.

Wasn't using "./gmodserver install" -_-

**Comment by Pink3vil** [comment]
Don't work ...
