### ISSUE TITLE
Error on install: cannot access `fn_functions': No such file or directory

### ISSUE THREAD

**Issue by gilimanjaro** [dgibbs64/linuxgsm#502]
I got the following error when trying an install:

```
   loading fn_functions...chmod: cannot access `fn_functions': No such file or directory
./tf2server: line 86: /home/tf2server/functions/fn_functions: No such file or directory
./tf2server: line 98: fn_getopt: command not found
```

Little bit of investigation led me to add '--no-check-certificate' to the wget command in the tf2server script. But that's probably not a desirable solution right?

**Comment by ScottSmudger** [comment]
delete the "functions" folder and run the script again

**Comment by dgibbs64** [comment]
Correct. What distro are you running? It must be an older one. I want to add the option in to use --no-check-certificate for the older distros but I need to know which ones

**Comment by pokypine** [comment]
I'm having the same errors except in the csgoserver install.

Tried the following with no resolution:

1) Tried manually creating the functions/fn_functions directory.

2) Tried what ScottSmudger said, removing the functions directory. No help.

What else can I try?

**Comment by pokypine** [comment]
I have not completed installation yet, but I did get past this error by adding "--no-check-certificate" to line 109 of csgoserver script.

**Comment by dgibbs64** [comment]
Please can you confirm what your distro is

**Comment by dgibbs64** [comment]
LGSM has partly moved to curl which may resolve the issue. However wget is still used in places. I recommend upgrading the distro of as suggested adding --no-check-certificate to any wget commands
