### ISSUE TITLE
ARK Server admin commands

### ISSUE THREAD

**Issue by Cuppycake** [dgibbs64/linuxgsm#503]
I have looked everywhere and tried everything I've found online about this. But I am still unable to find anywhere to put an admin password in to start using admin commands via the console. Most things I find online are regarding host control panels. Any help would be amazing!

**Comment by reesey275** [comment]
You have multiple options available to accomplish this.    You can either create a text file in this location "/ShooterGame/Saved/AllowedCheaterSteamIDs.txt" (remove quotes) or you can edit "/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini" and add a line under [ServerSettings]
ServerAdminPassword=IUASBDUYIUAGVF


Hope this helps.

**Comment by ScottSmudger** [comment]
It would be nice knowing what game this is for.
Usually this is just an rcon password set in the command line of the script.

You can just manually edit the script to add the password in like I have done or set it in your server CFG, which you should really avoid doing.

Maybe Dan should start add this parameter in his scripts

e.g. for CS:GO "rcon_password"

**Comment by Cuppycake** [comment]
@reesey275 Thank you so much this worked perfectly! :)
