### ISSUE TITLE
[GMOD] Graceful shutdown not working properly

### ISSUE THREAD

**Issue by EXH3Y** [dgibbs64/linuxgsm#508]
When stopping a Garry's Mod server, the script gets stucked in an endless loop:

    [ .... ] Stopping gmod-server: Attempting graceful shutdown: 453

Gmod does not quit but tries to restart which leads to fn_stop (waiting for the server to exit) to never leave the loop.
I don't know if this is a common error but maybe there are others out there experiencing the same problem.

I found a way arround this by editing the exit condition of the while loop in fn_stop (line 131):

    while [ "${pid}" != "0" -a $counter -lt 120]; do
    ...

I think there are better solutions but it works like expected and exits the loop after 120 seconds if a graceful shutdown is not possible, just killing the tmux session.

**Comment by dgibbs64** [comment]
Thanks for highlighting this. Your solution will work. I will fix this.

**Comment by dgibbs64** [comment]
https://github.com/dgibbs64/linuxgsm/commit/5d3469c7b8ba4854f7dcb96bc1745a9ba3d1e035
