### ISSUE TITLE
[Arma3] Error on start, debug working fine

### ISSUE THREAD

**Issue by lburdzy** [dgibbs64/linuxgsm#510]
A while ago I updated my server setup and can't get the script to work. When i run it with `arma3server start` it gives me the following output:

```
./new_arma3server start
[ .... ] Starting arma3-server: UNAVAILABLEfailed to connect to server: Connection refused
[ FAIL ] Starting arma3-server: Unable to start UNAVAILABLE
```

However when i run debug the server starts fine. Any idea why this might be?

**Comment by dgibbs64** [comment]
https://github.com/dgibbs64/linuxgsm/issues/331

related issue. reboot might fix it.

**Comment by lburdzy** [comment]
Nope, it's been that way since several reboots ago, and during this time I've been running my server in debug mode in tmux (I have version 1.9). It seems to run fine that way. Actually I've been using older script version (ver. 030515), and on it server runs, but does not load any mods (probably related to me putting all mods inside mod folder, anyway nevermind). Today I started testing new version and it won't start at all. 
I am running Debian 8 Stable on VPS.

**Comment by lburdzy** [comment]
I removed functions folder and re-installed server. Got same result while trying to run vanilla server. Any idea what can be the reason?

**Comment by lburdzy** [comment]
Ok, it started working after I changed filename of script to arma3server. Issue closed
