### ISSUE TITLE
Improve options message

### ISSUE THREAD

**Issue by dgibbs64** [dgibbs64/linuxgsm#513]
Im working on improving the options messages to have descriptions.

Here is an example of before and after as it is currently. Do you think this looks good or should there be other changes?
Before
![http://i.imgur.com/x6LMUw7.png](http://i.imgur.com/x6LMUw7.png)
After
![http://imgur.com/kHBnfvO](http://i.imgur.com/kHBnfvO.png)

**Comment by Advkt** [comment]
Looks very presentable to me.

**Comment by sscs12345** [comment]
Damn good! Keep it up! :D

**Comment by dgibbs64** [comment]
Released updated options menu 
https://github.com/dgibbs64/linuxgsm/commit/c254db950a126d8170c4044fb33b6dffc43bcf54
