### ISSUE TITLE
[Question] Monitor

### ISSUE THREAD

**Issue by Advkt** [dgibbs64/linuxgsm#517]
If we chose to not install the monitor (gsquery.py) in the initial install of the server what's the most practical way to install it afterwards?

**Comment by dgibbs64** [comment]
wget https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/GameServerQuery/gsquery.py to the main dir of your server.

**Comment by Advkt** [comment]
Cheers, is the intended usage to call it via a crontab routinely?

**Comment by dgibbs64** [comment]
yup :)

**Comment by Advkt** [comment]
Much obliged, thank you.
