### ISSUE TITLE
[insserver] start gamemode

### ISSUE THREAD

**Issue by PhilPhonic** [dgibbs64/linuxgsm#529]
Hi,
if you want to start the Insurgency server with a specific gamemode, you have to pass this in startup parameters:
> +map "mapname gamemode"

The quotationmarks are important. If you don't pass them, the gamemode is ignored.

In lgsm startscript these quotationmarks are not passed:
> defaultmap="mapname gamemode"
> parms="-game insurgency -strictportbind -ip ${ip} -port ${port} +clientport ${clientport} +tv_port ${sourcetvport} +map ${defaultmap} +servercfgfile ${servercfg} -maxplayers ${maxplayers}"

So I changed the defaultmap varible to:
> defaultmap="\"mapname gamemode\""

If you start the server in debug-mode, this works. For "normal" start it does not work. The quotationmarks get lost in tmux.

I changed the defaultmap varible to:
> defaultmap="\\\\\"mapname gamemode\\\\\""

Now, "normal" start works, but debug mode does not work anymore. That's because the backslashes are passed to the game executable and can't be interpreted.
> +map \"mapname gamemode\"

Perhaps you have an idea to get both "normal"- and debug-startup to work without having to change the defaultmap variable.

Phil

**Comment by dgibbs64** [comment]
Yeah seen this issue with insurgency. Haven't figured out how to resolve this yet. Its a bit of a ball ache.

**Comment by dgibbs64** [comment]
Thanks for fixing this one :+1:
