### ISSUE TITLE
Docker plans?

### ISSUE THREAD

**Issue by RogerSik** [dgibbs64/linuxgsm#532]
Hello,

are there plans for docker images? 

Would be a great thing to limit memory usage with docker and the good server setup from linuxgsm.

I want to have multiple game server on one server. But some game server like very ram and use it as much as they can and other game server is going empty.

**Comment by raum-IO** [comment]
+1

**Comment by pereirtc** [comment]
i was thinking about this a few days ago.

linuxgsm + docker would be a game changer.

**Comment by johnjelinek** [comment]
see here: https://hub.docker.com/r/johnjelinek/csgoserver/

**Comment by dgibbs64** [comment]
I have played with docker and i think ot will work but I have no official plans for it. Mainly due to time limits. However I welcome anyone to try themselves to adapt lgsm to work with docker.
