### ISSUE TITLE
Escaped Directory names

### ISSUE THREAD

**Issue by JimTR** [dgibbs64/linuxgsm#534]
I have a problem with certain directory paths (i.e ones with spaces in)  lgsm does not escape the spaces so the script tries to use a non valid path for its data from this line 
rootdir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" 
Example 
returned rootdir = /home/arma/games/Arma 3 (invalid path)
actual rootdir = /home/arma/games/Arma\ 3
I know this is no biggy but it may be worth putting in the install documentation that using a directory with a space in it does not work as expected

**Comment by dgibbs64** [comment]
A recent change may of resolved this issue.

rootdir="$(dirname $(readlink -f "${BASH_SOURCE[0]}"))"

@jaredballou may be able to confirm this as he made the alteration.

**Comment by dgibbs64** [comment]
Need to test this then close

**Comment by dgibbs64** [comment]
Completed various tests. Hopfully the changes will stop this issue. However let me know if you spot anything else

https://github.com/dgibbs64/linuxgsm/commit/2e3c4fe18f43e595d2d59299099fe7242373f35d

https://github.com/dgibbs64/linuxgsm/commit/dfbcee27ebba6cd820d9fb9916a945ac67f4428c

https://github.com/dgibbs64/linuxgsm/commit/ff1a3e7a8eaa50b0bf47592d2991263166141831
