### ISSUE TITLE
Server-Console.log

### ISSUE THREAD

**Issue by NewGothic** [dgibbs64/linuxgsm#535]
Hi i have the Problem with Tmux its dont logg the Console in the log file.
I yuse CentOs7 but i dont use Ubunto :(  

css-server-console.log:
Console logging disabled: Bug in tmux 1.8 breaks logging
http://gameservermanagers.com/tmux-upgrade
Currently installed: tmux 1.8

**Comment by dgibbs64** [comment]
Does this work?

https://gist.github.com/rothgar/cecfbd74597cc35a6018

**Comment by dgibbs64** [comment]
or maybe this?
https://gist.github.com/Root-shady/d48d5282651634f464af

**Comment by NewGothic** [comment]
i was test it and now i have a next problem but i have install the development tools for CentOs 7


[root@gameservers libevent-2.0.21-stable]# ./configure && make
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/root/libevent-2.0.21-stable':
configure: error: C compiler cannot create executables
See `config.log' for more details

**Comment by dgibbs64** [comment]
Any luck with this?
