### ISSUE TITLE
[L4D2] Server public IP is not same with my IP

### ISSUE THREAD

**Issue by TGMaster** [dgibbs64/linuxgsm#536]
It just happended 1 week ago.

I can't connect to the ip 118.69.101.218, and IP 58.186.59.76 is still can

But I can't see my server on the steam group servers list. How can I fix this error? 

![untitled](https://cloud.githubusercontent.com/assets/12139525/11322434/fbb9ae2e-911d-11e5-8896-db04dad552a1.jpg)

**Comment by MikeyUMF** [comment]
In you startup configuration try adding +net_public_adr xxx.xxx.xxx.xxx , that will force the server to use the public ip you input in the x. 
![screen shot 2015-11-23 at 4 01 58 pm](https://cloud.githubusercontent.com/assets/15988267/11349714/95ea568c-91fb-11e5-9c7d-5842ad738814.png)

**Comment by TGMaster** [comment]
@MikeyUMF  The problem is solved. Thanks for your help! I am very appreciate that. Have a nice day.

**Comment by TGMaster** [comment]
@MikeyUMF your way can make both my IPs have the same one. But I don't know why my server is still not on the "steam group servers" list. I'm sure that I type the group ID correctly.
THANKS
