### ISSUE TITLE
Server down? gameservermanagers.com is "ERR_NAME_NOT_RESOLVED"

### ISSUE THREAD

**Issue by karololszak** [dgibbs64/linuxgsm#537]
Some DNS problems of some sort, anyway I can't get through to the server, and my vps can neither.

Confirmed by http://isup.me/gameservermanagers.com as well

**Comment by dgibbs64** [comment]
Will be fixed soon. Thanks for reporting this

**Comment by karololszak** [comment]
It works now :)
