### ISSUE TITLE
ARK Server Startup question(s)

### ISSUE THREAD

**Issue by Cuppycake** [dgibbs64/linuxgsm#539]
Sometimes after stopping the server either for an update or just a general restart it will take forever to appear in the server listings. I know their are some issues with syncing times but sometimes I'm talking over an hour. Using ./arkserver monitor and ./arkserver details all show the server as online and ok. 

Sometimes stopping and starting helps but less times than more this works. Is this an issue with 
my server, syncing to the ark server, or something else? 

The box has 8gb in it and I believe the server needs around 6gb at startup then uses less while the 
server is running. We have no issues with lag or performance when the server is running with players on. 

Just trying to figure it out a bit before I start ripping into things lol.
Thanks

**Comment by dgibbs64** [comment]
I think this is more of an issue with ARK server rather than the LGSM script. I recommend trying on the official forums for this one as they know more than me.
