### ISSUE TITLE
ARK server update stopping after one try

### ISSUE THREAD

**Issue by cptskyhawk** [dgibbs64/linuxgsm#540]
Having this problem consistently with either update or force-update -- any ideas? I can run it again and again but it just downloads a little bit more each time:

```
steamuser@steamvm:/storage$ ./arkserver force-update
[  OK  ] Update ark-server: Updating arkserver
Redirecting stderr to '/home/steamuser/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x61) downloading, progress: 0.27 (79322774 / 29011247757)
Error! App '376030' state is 0x402 after update job.
CWorkThreadPool::~CWorkThreadPool: work complete queue not empty, 8 items discarded.
CWorkThreadPool::~CWorkThreadPool: work processing queue not empty: 386 items discarded.
steamuser@steamvm:/storage
```

**Comment by dgibbs64** [comment]
This is a big with steamCMD I reccomend a Google around for this one to see it you find anything. Validation may possibly resolve this though. Let me know if you find anything :-)

**Comment by cptskyhawk** [comment]
Nope -- been googling about it for months now. :P  Nobody seems to have anything but questions.  I have my own script that validates as well -- doesn't fix the problem.  I eventually had to make script that just re-runs the same command over and over again if the previous one fails, just to get it to work, however, this constant stop/restart method means an update takes HOURS, sometimes days, instead of 30min or so for people who don't have this problem:

```
$updateArkCmd

while [ $? -ne 0 ]
do
	$updateArkCmd
done
```

**Comment by dgibbs64** [comment]
Could be an issue with your server maybe the dependencies required for steamcmd are damaged. It's worth trying on a fresh install

**Comment by dgibbs64** [comment]
I could do with finding out a list of error codes for SteamCMD e.g  0x402 This may help figure out the issues such as this. Then I could write error handling in a bit better

**Comment by UltimateByte** [comment]
I've been googleing this. The vast majority of people getting this error just need to restart the process until it works. Could be due to some packet loss. You'd better re-run a "validate" after such a painful download though.

Closing this, feel free to re-open if needed.

Have a nice admin time !
