### ISSUE TITLE
Not receiving emails

### ISSUE THREAD

**Issue by npd1124** [dgibbs64/linuxgsm#541]
I have installed both the ts3 server manager and arma3 server manager, whenever I run ./arma3server email-test or ./ts3server email-test it says that the email is sent but I am not receiving them in my inbox. I can not for the life of me pinpoint the issue. I have checked every possible folder on my email (spam, etc..) but cannot find any traces of a sent email. If you point me in the right direction to fix this issue it would be greatly appreciated.

**Comment by dgibbs64** [comment]
could be an issue with postfix on your server.

try using the mail command to email yourself.

also mailq command will tell you if the email has left your server. But basically its probably some kind of postfix issue.
