### ISSUE TITLE
New Steam Game Server Account Management

### ISSUE THREAD

**Issue by AzaZPPL** [dgibbs64/linuxgsm#543]
Since the last update there is something called Steam Game Server Account Management.
You must add a few values in the startup command.
+sv_setsteamaccount LOGIN_TOKEN and -net_port_try 1

You can get the login token from http://steamcommunity.com/dev/managegameservers

**Comment by dgibbs64** [comment]
I will be adding this in to the script soon. :-)

**Comment by busheezy** [comment]
Ahh, thanks.  Was going to do a PR but I'd rather you do it. :P

**Comment by dgibbs64** [comment]
https://github.com/dgibbs64/linuxgsm/commit/8ee871452ec8a0721f36be7044dcc151388e8bdb
