### ISSUE TITLE
[GMOD] Attempting graceful shutdown on every restart

### ISSUE THREAD

**Issue by UltimateByte** [dgibbs64/linuxgsm#544]
Hi there,

Setting up new gmod servers.
On every ./gmodserver restart, "i get Attempting graceful shutdown:1 :2 :3 ..." and it never ends. I have to do ctrl + c. Then if i do ./gmodserver console, i can see the server actually rebooted.
Any idea of what's going on ?

**Comment by UltimateByte** [comment]
I've seen this : https://github.com/dgibbs64/linuxgsm/issues/508

Seems not to be enough for a proper shutdown.
I don't really get why it does that.

**Comment by dgibbs64** [comment]
The server should force a shutdown after 30 seconds if a graceful shutdown was not successful.

**Comment by UltimateByte** [comment]
I've never waited 30s yet, always ctrl + C to end it. Any idea of why is it doing a graceful shutdown ? It does it with the latest version of lgsm, but not ot the previous one (got many servers on the same machine).

**Comment by dgibbs64** [comment]
Yeah a graceful shutdown is designed to give the server time to correctly turn off. All LGSM does is send the quit command to the server which is a lot cleaner than simply killing the process. Commonly as graceful shutdown only takes a few seconds. But im guessing that your garrys mod server is taking a long time or not responding to the quit command.

Maybe try opening up the console in on terminal and stopping the server in another to see what happens.

**Comment by UltimateByte** [comment]
OK thanks for the info.

You put me on the way.
The "quit" command makes a segmentation fault...
GARRY !!!!!!!!
-________-

**Comment by UltimateByte** [comment]
Conclusion from gmod's github : that issue happens only when you're using a collection, even on windows. It should be fixed at the next gmod update.
