### ISSUE TITLE
CURL not installed 

### ISSUE THREAD

**Issue by D1etZ** [dgibbs64/linuxgsm#556]
Hi im getting this error when i try to install cs go server 

./csgoserver install
    fetching functions/fn_functions...FAIL

Curl is not installed!

im on debian 8 linux is there any solition for this thx in advance

**Comment by dgibbs64** [comment]
Firstly is curl installed? If so there is a line of code to comment out in csgoserver. Search for the error in the file and comment out. That will bypass it. I will have to investigate further when I'm back home

**Comment by UltimateByte** [comment]
Hi there. Is curl needed now ?

**Comment by D1etZ** [comment]
Thx for responding dgibbs64 i already fiixed it like ultimatebyte says "Edit : Confirm that apt-get install curl solves the "issue" ;)"

**Comment by dgibbs64** [comment]
Yup I have changed form wget to curl. This is becuase it handles errors better

**Comment by UltimateByte** [comment]
Okay !
Don't forget to update dependencies on server pages :)

**Comment by dgibbs64** [comment]
i have  :)

**Comment by UltimateByte** [comment]
<3
