### ISSUE TITLE
[SOLVED] Problem after clean install

### ISSUE THREAD

**Issue by moritzknorr** [dgibbs64/linuxgsm#557]
Hello,

thanks for your awesome tool!
Since steam requires the token, i setup a new v-server and started an installation from scratch.
I get the following errors:
* [S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
* [S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
* [S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
* Could not establish connection to Steam servers.

Do you have any idea, what i can do?

[log.txt](https://github.com/dgibbs64/linuxgsm/files/62320/log.txt)

**Comment by dgibbs64** [comment]
https://github.com/dgibbs64/linuxgsm/wiki/FAQ#s_api-fail-steamapi_init-failed-steamapi_issteamrunning-failed

**Comment by moritzknorr** [comment]
Ill get the following error, when i try to connect.

http://imgur.com/UBRWDaO

**Comment by UltimateByte** [comment]
sv_lan 0 ?

**Comment by moritzknorr** [comment]
is set.
I think the last line of the log file is relevant.
L 12/16/2015 - 09:51:54: server_cvar: "sv_alltalk" "1"
Stopping 0 worker threads
Starting 1 worker threads
1 threads. 745,269 ticks
exec: couldn't exec gamemode_casual_server.cfg
Commentary: Could not find commentary data file 'maps/de_dust2_commentary.txt'.
Initializing Steam libraries for secure Internet server
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 730
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Setting breakpad minidump AppID = 740
Logging into Steam gameserver account with logon token '6D42FABExxxxxxxxxxxxxxxxxxxxxxxx'
FillInMachineIDInfo took a total of 3 milliseconds
Could not establish connection to Steam servers.

**Comment by UltimateByte** [comment]
I'd be more worried about this : 

"./srcds_run: 1: ./srcds_run: gdb: not found
WARNING: Please install gdb first."

Is gdb installed ?
Also, any firewall to configure ?

Ignore the "[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed" as long as it's not pointing out a missing .so file. This error is "normal" (in a valve's perspective...).

**Comment by moritzknorr** [comment]
I installed gdb, thank you.
I started again with a fresh os and counter the same error.

The port is opened to external access, as you can see here:
http://imgur.com/GdeQoEv

Here is a new log file.
http://pastebin.com/M2jvXgAf

**Comment by UltimateByte** [comment]
Not using Debian 8 ? Affraid ? ^^
It's perfectly stable for me (and i got many many stuff onto it).

What about the other ports ?
I assume port 27015 should be enough for server query and connexion with steam, but who knows... 

port="27015"
sourcetvport="27020"
clientport="27005"


Also, this line could be the problem : 
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.

Maybe you're gonna have to find it and copy it to the right location.

I wanted a few CS GO servers BTW, i got some time this morning, let me a moment to make a coffe, eat something, and i'll test a fresh server too on my Debian 8 and see what happens !

**Comment by UltimateByte** [comment]
Well, after a correction of my IP that i mistyped (L-O-L), it seems to work. 
Yep, i confirm it works by connecting to it and killing some bots...
I'm not sure why it wouldn't work for you.

Did you create a new user for this server, and make the installation at the root of the home directory of that user ?

**Comment by UltimateByte** [comment]
For your information, here is where i find steamclient.so

csgotrain@lrob:~$ find -name steamclient.so
./.steam/sdk32/steamclient.so
./serverfiles/bin/steamclient.so
./steamcmd/linux32/steamclient.so

**Comment by moritzknorr** [comment]
Hi UltimateByte,
thanks for your effort and support. :)

I am using Debian 7 Wheezy. But it worked before the login-token update.
```
PRETTY_NAME="Debian GNU/Linux 7 (wheezy)"
NAME="Debian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support/"
BUG_REPORT_URL="http://bugs.debian.org/"
```

My search is finding exactly your files.
```
csgoserver@lvps91-250-##-##:~$ find -name steamclient.so
./steamcmd/linux32/steamclient.so
./.steam/sdk32/steamclient.so
./serverfiles/bin/steamclient.so
```

Here are my iptable rules:
```
-A INPUT -j SteamServers
-A INPUT -p udp -m udp --dport 27015 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 27015 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 27020 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 27005 -j ACCEPT
```

**Comment by UltimateByte** [comment]
You're welcome, we're all in the same boat of game server admins :p 
Yeah, i just discovered this token crap... Is your GSLT status fine ? 
Because your config seems perfectly fine.

**Comment by moritzknorr** [comment]
i solved the problem...

When generating the GSLT-Token (here: https://steamcommunity.com/dev/managegameservers) i used 740 as app-id, instead of 730. I though i had to use the 740, since it is the new id.
http://imgur.com/TpfJ0AO

I think i lack the experience of the server mechanics.
Nevertheless, it works fow now. :)

Thank you so much for your support.
Your hint with the gslt status led me to try the other app-id

**Comment by UltimateByte** [comment]
Nice ! No worries, server mechanics will come, and there's always new issues to solve anyways... :p 
I actually didn't remember the CS GO ID, so i used the one suggested on the GSLT registration page that was 730 ! I guess i've been lucky on this one... ^^

**Comment by moritzknorr** [comment]
the thing is, when you install csgo, it installs the app-id 740...

**Comment by dgibbs64** [comment]
Do I need to change the csgo appid?

**Comment by dgibbs64** [comment]
Am i right in saying that the GSLT required you select 730 (https://steamdb.info/app/730/) instead of 740 (https://steamdb.info/app/740/)?

If so it may be worth me adding some documentation about this

**Comment by UltimateByte** [comment]
Yes, the install appid is 740 but the GSLT appid is 730. Valve...

**Comment by dgibbs64** [comment]
https://github.com/dgibbs64/linuxgsm/wiki/Game-Server-Login-Token#generate-a-token the wiki now advised to use appid 740 for CSGO. CLosing this
