### ISSUE TITLE
7DTD Server - Monitor/Shutdown with telnet on network ip address

### ISSUE THREAD

**Issue by RogerSik** [dgibbs64/linuxgsm#558]
Hello,

the 7dtd server is with telnet accessible over 127.0.0.1 but the linuxgsm is always looking with telnet on the network address (in my case 192.168.1.21) because he reach nothing he do a gracefully shutdown.

It is possible to add that he access with telnet the address 127.0.0.1

Monitoring is because of that also failing. :(

Greetings
Roger

**Comment by RogerSik** [comment]
As system is Ubuntu 15.10 Server used.

**Comment by dgibbs64** [comment]
the script should already to this. it will attempt to use localhost first. Failing that try the network address.
https://github.com/dgibbs64/linuxgsm/blob/master/functions/fn_stop#L67

**Comment by RogerSik** [comment]
Test with telnet localhost 


    ~/ telnet localhost 8081
    Trying ::1...
    Trying 127.0.0.1...
    Connected to localhost.
    Escape character is '^]'.
    *** Connected with 7DTD server.
    *** Server version: Alpha 13.3 (b5) Compatibility Version: Alpha 13.3
    *** Dedicated server only build

    Server IP:   Any
    Server port: 26900
    Max players: 8
    Game mode:   GameModeSurvivalMP
    World:       Random Gen
    Game name:   World1
    Difficulty:  2

    Press 'help' to get a list of all commands. Press 'exit' to end session.

    2015-12-17T06:48:56 694,349 INF Started thread TelnetClientReceive_127.0.0.1:43388
    2015-12-17T06:48:56 694,349 INF Started thread TelnetClientSend_127.0.0.1:43388
    exit
    Connection closed by foreign host.

So and now with sdtdserver stop

    ./sdtdserver stop
    [ WARN ] Stopping sdtd-server: Attempting graceful shutdown via telnet: localhost failed
    [ FAIL ] Stopping sdtd-server: Attempting graceful shutdown via telnet
    
     Telnet output:
     spawn telnet 192.168.1.21 8081
     Trying 192.168.1.21...
     telnet: Unable to connect to remote host: Connection refused
     Timeout or EOF

     [  OK  ] Stopping sdtd-server: 7DTD Server

**Comment by RogerSik** [comment]
It works now. I had to set the telnet password to "true" and now is everything fine. 

It is possible to set a different password?

**Comment by UltimateByte** [comment]
Did you figure it out ? Closing for now, feel free to give the answer anyway, or re-open if needed.
Have a good admin time !
