### ISSUE TITLE
Update checking not working

### ISSUE THREAD

**Issue by bloxgate** [dgibbs64/linuxgsm#559]
Just tried to update my gmod server with the update command, it said the server was up to date when it wasn't. I had to validate the game for it to actually update.

**Comment by UltimateByte** [comment]
Exact same. It's not the first time, but i think it's more a gmod issue.

**Comment by dgibbs64** [comment]
Yeah seen this a few times with SteamCMD. Never fully figured out why that is. My guess is that SteamCMD is only checking a cache for an update and not actually checking with SteamCMD servers.

**Comment by UltimateByte** [comment]
Maybe any update should be followed by a validate ? Unless validate can cause problems such as losing server customization.

**Comment by robingroppe** [comment]
Have that issue with CsGo too.

**Comment by UltimateByte** [comment]
I've been experiencing this issue with CSS too, you just reminded it to me.
As @dgibbs64 said, it's a SteamCMD issue. One more mistake from Valve.

**Comment by dgibbs64** [comment]
Applied the following fix that should help
https://github.com/dgibbs64/linuxgsm/commit/23f73547c2d1fadeafe75c2798c613f9ec51eef9

**Comment by dgibbs64** [comment]
I will close this for now. However please let me know if the issue returns after the fix :)
