### ISSUE TITLE
[GMOD] Support for GSLT

### ISSUE THREAD

**Issue by UltimateByte** [dgibbs64/linuxgsm#560]
Garry's Mod now supports GSLT.

If you're willing to, you can implement it into the script as you did perfectly for CSGO.

1) Make a variable :
gslt=""

2) Add the launch option :
+sv_setsteamaccount ${gslt}

Would be perfect <3

**Comment by UltimateByte** [comment]
Source : 
http://www.garrysmod.com/2015/12/16/december-2015-update/
"Added support for Steam game server accounts"

**Comment by dgibbs64** [comment]
OK course. Im guessing its and optional and not enforced?

**Comment by UltimateByte** [comment]
You guess right :)
