### ISSUE TITLE
[arma3] Mode extDB and life_server

### ISSUE THREAD

**Issue by Dids91** [dgibbs64/linuxgsm#563]
to already start a big thank you for your configuration i'm french sry for my english text ^^

can you give me the procedure for charging modes extDB and life_server ?

it should create a folder mods ?
What command lines set in mod= ?

thank you man

**Comment by dgibbs64** [comment]
Any ARMA 3 experts here would be helpful :)

**Comment by UltimateByte** [comment]
Google seems helpful with this, at least for extDB.

https://forums.bistudio.com/topic/169723-extdb-arma3-extension-linuxwindows/
https://github.com/Torndeco/extDB2/wiki/Setup:-Linux-Static-Build

For the life mode, it seems like the community doesn't like to share it very much.

**Comment by Dids91** [comment]
fix apt-get install libtbb2:i386 in ubuntus 64

**Comment by UltimateByte** [comment]
Is libtbb2:i386 required for those mods ?

**Comment by Dids91** [comment]
extDB2

**Comment by UltimateByte** [comment]
Thx for the info
