### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by bhsgoclub** [dgibbs64/linuxgsm#564]
During the auto install A few items failed to download, Below is the install log

HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/dgibbs64/linuxgameservers/master/Gar                                                     rysMod/gmodserver [following]
--2015-12-20 05:10:52--  https://raw.githubusercontent.com/dgibbs64/linuxgameser                                                     vers/master/GarrysMod/gmodserver
Resolving raw.githubusercontent.com... 23.235.39.133
Connecting to raw.githubusercontent.com|23.235.39.133|:443... connected.
WARNING: certificate common name “www.github.com” doesn’t match requested host n                                                     ame “raw.githubusercontent.com”.
HTTP request sent, awaiting response... 200 OK
Length: 3593 (3.5K) [text/plain]
Saving to: “gmodserver”

100%[======================================>] 3,593       --.-K/s   in 0s

2015-12-20 05:10:53 (720 MB/s) - “gmodserver” saved [3593/3593]

[gmodserver@ns5001351 ~]$ chmod +x gmodserver
[gmodserver@ns5001351 ~]$ ./gmodserver install
    fetching functions/fn_functions...OK
    fetching functions/fn_messages...OK
    fetching functions/fn_getopt...OK
    fetching functions/fn_install...OK
    fetching functions/fn_check_root...OK
    fetching functions/fn_install_header...OK
=================================
Garry's Mod
Linux Game Server Manager
by Daniel Gibbs
http://gameservermanagers.com
=================================
    fetching functions/fn_install_serverdir...OK

Server Directory
=================================

/home/gmodserver

Continue [y/N]y
=================================
Garry's Mod
Linux Game Server Manager
by Daniel Gibbs
http://gameservermanagers.com
=================================
    fetching functions/fn_install_steamcmd...OK

Installing SteamCMD
=================================
mkdir: created directory `steamcmd'
downloading steamcmd_linux.tar.gz...OK
linux32/
linux32/libstdc++.so.6
linux32/steamcmd
steamcmd.sh
steam.sh
removed `steamcmd_linux.tar.gz'
    fetching functions/fn_install_serverfiles...OK

Installing Garry's Mod Server
=================================
mkdir: created directory `/home/gmodserver/serverfiles'
    fetching functions/fn_check_steamuser...OK
Redirecting stderr to '/home/gmodserver/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x61) downloading, progress: 0.28 (10812139 / 3808559918)
 Update state (0x61) downloading, progress: 6.90 (262695447 / 3808559918)
 Update state (0x61) downloading, progress: 11.27 (429270096 / 3808559918)
 Update state (0x61) downloading, progress: 23.37 (889924433 / 3808559918)
 Update state (0x61) downloading, progress: 29.65 (1129322806 / 3808559918)
 Update state (0x61) downloading, progress: 37.27 (1419355728 / 3808559918)
 Update state (0x61) downloading, progress: 45.42 (1729917996 / 3808559918)
 Update state (0x61) downloading, progress: 53.15 (2024427162 / 3808559918)
 Update state (0x61) downloading, progress: 61.74 (2351225800 / 3808559918)
 Update state (0x61) downloading, progress: 70.89 (2699811220 / 3808559918)
 Update state (0x61) downloading, progress: 79.62 (3032516398 / 3808559918)
 Update state (0x61) downloading, progress: 89.16 (3395756138 / 3808559918)
 Update state (0x61) downloading, progress: 94.66 (3605077174 / 3808559918)
 Update state (0x61) downloading, progress: 94.66 (3605077174 / 3808559918)
 Update state (0x61) downloading, progress: 94.66 (3605077174 / 3808559918)
 Update state (0x61) downloading, progress: 94.66 (3605077174 / 3808559918)
 Update state (0x61) downloading, progress: 94.66 (3605077174 / 3808559918)
 Update state (0x61) downloading, progress: 94.66 (3605077174 / 3808559918)
 Update state (0x61) downloading, progress: 94.66 (3605077174 / 3808559918)
 Update state (0x61) downloading, progress: 94.66 (3605077174 / 3808559918)
 Update state (0x61) downloading, progress: 94.66 (3605077174 / 3808559918)
 Update state (0x61) downloading, progress: 94.66 (3605077174 / 3808559918)
 Update state (0x61) downloading, progress: 94.66 (3605077174 / 3808559918)
 Update state (0x61) downloading, progress: 94.66 (3605077174 / 3808559918)
 Update state (0x61) downloading, progress: 94.66 (3605077174 / 3808559918)
 Update state (0x61) downloading, progress: 94.66 (3605077174 / 3808559918)
 Update state (0x61) downloading, progress: 98.35 (3745870192 / 3808559918)
 Update state (0x61) downloading, progress: 100.00 (2170395552 / 2170395552)
Success! App '4020' fully installed.

=================================
Was the install successful? [Y/n]y
    fetching functions/fn_install_steamfix...OK

Applying steamclient.so fix
=================================
mkdir: created directory `/home/gmodserver/.steam'
mkdir: created directory `/home/gmodserver/.steam/sdk32'
`/home/gmodserver/steamcmd/linux32/steamclient.so' -> `/home/gmodserver/.steam/s                                                     dk32/steamclient.so'

Applying libsteam.so fix
=================================
cp: cannot stat `/home/gmodserver/serverfiles/bin/libsteam.so': No such file or                                                      directory
Failure! Cannot start apply libsteam.so fix.
    fetching functions/fn_install_glibcfix...OK

GLIBC Fix required
============================
Warning! Garry's Mod requires GLIBC_2.15 or above

Currently installed: GLIBC_2.12
Required: => GLIBC_2.15

The installer will now detect and download the required files to allow Garry's M                                                     od server to run on a distro with less than GLIBC_2.15.
note: This will NOT upgrade GLIBC on your system.

http://gameservermanagers.com/glibcfix

loading required files...
ERROR: certificate common name “www.github.com” doesn’t match requested host nam                                                     e “raw.githubusercontent.com”.
To connect to raw.githubusercontent.com insecurely, use ‘--no-check-certificate’                                                     .
ERROR: certificate common name “www.github.com” doesn’t match requested host nam                                                     e “raw.githubusercontent.com”.
To connect to raw.githubusercontent.com insecurely, use ‘--no-check-certificate’                                                     .
ERROR: certificate common name “www.github.com” doesn’t match requested host nam                                                     e “raw.githubusercontent.com”.
To connect to raw.githubusercontent.com insecurely, use ‘--no-check-certificate’                                                     .
`/home/gmodserver/steamcmd/linux32/libstdc++.so.6' -> `/home/gmodserver/serverfi                                                     les/libstdc++.so.6'
    fetching functions/fn_install_logs...OK

Creating log directorys
=================================
mkdir: created directory `/home/gmodserver/log'
mkdir: created directory `/home/gmodserver/log/script'
mkdir: created directory `/home/gmodserver/log/console'
`/home/gmodserver/log/server' -> `/home/gmodserver/serverfiles/garrysmod/logs'
`/home/gmodserver/log/steamcmd' -> `/home/gmodserver/Steam/logs'
    fetching functions/fn_install_gsquery...OK

GameServerQuery
============================
Do you want to install GameServerQuery? [Y/n]y
downloading gsquery.py...chmod: cannot access `gsquery.py': No such file or directory
    fetching functions/fn_install_config...OK

Creating Configs
=================================
downloading lgsm-default.cfg...creating gmod-server.cfg config file.
cp: cannot stat `/home/gmodserver/serverfiles/garrysmod/cfg/lgsm-default.cfg': No such file or directory
creating server.cfg.
creating redirect.
server.cfg > gmod-server.cfg.

Configuring Garry's Mod Server
=================================
Enter server name: Uthrandir Server Network
Enter rcon password: f43l0rnf0r35t
changing hostname.
sed: can't read /home/gmodserver/serverfiles/garrysmod/cfg/gmod-server.cfg: No such file or directory
changing rconpassword.
sed: can't read /home/gmodserver/serverfiles/garrysmod/cfg/gmod-server.cfg: No such file or directory

    fetching functions/fn_install_complete...OK
=================================
Install Complete!

To start server type:
./gmodserver start

**Comment by bhsgoclub** [comment]
Actually, Doing a bit of digging I relized that my version of wgit was not updated, Updating and reinstalling has solved this issue.

**Comment by UltimateByte** [comment]
Currently installed: GLIBC_2.12
What distro uses that ?!

apt-get update
apt-get upgrade

**Comment by bhsgoclub** [comment]
Yeah. I just took over as the server maintainer. I did not realize how outdated this was.

**Comment by dgibbs64** [comment]
Please send output of ./gmodserver details as this is useful to me. I will probably move this over to curl anyway.

**Comment by bhsgoclub** [comment]
I actually had updated and fixed this, I was using wgit version 1.12 which does not have SNI extension and GitHub uses it. After updating to the current version of wgit I was able to just do ./gmodserver install to install the missing files.
