### ISSUE TITLE
Map issue

### ISSUE THREAD

**Issue by D1etZ** [dgibbs64/linuxgsm#565]
Hi,

i am trying to install different new maps on my cs go server the maps are am_ but when i try to switch to this map from de_dust2 ,server auto restarts so i cant join the map is there anything i need to change in my command line to make this maps work ?

thx in advance

**Comment by dgibbs64** [comment]
I recommend posting the question here
http://steamcommunity.com/groups/linuxgsm

as I dont believe it is a script issue.
