### ISSUE TITLE
[LGSM] Streamlining functions and naming convention

### ISSUE THREAD

**Issue by dgibbs64** [dgibbs64/linuxgsm#571]
I have been looking at how the function files are being called when running commands to see if they are being called in a way that makes sense. I have found that the order is not the best and that a reshuffle may be in order.

For example Start command
#Standard functions
fn_functions
fn_messages
fn_getopt

#Main function for command
fn_start
#Checks 
fn_check_root
fn_check_systemdir
fn_check_ip
fn_check_logs
#Fixes
fn_arma3fix
fn_details_config
fn_logs
#More checks
fn_check_tmux
fn_check_steamcmd

The first area I will look at is bringing simular features together such as checks. I want all checks to be run before doing anything. If one of these failes it should be before anything happens. I plan to have a new function called fn_checks that brings all checks together rather than scattered around LGSM.

**Comment by dgibbs64** [comment]
Running though this process I am redefining functions better based on what they do. So far i have the following:

fn_core: functions that will always run first e.g fn_core_functions
fn_command: primary command function e.g fn_command_start
fn_check: Runs checks that will either halt on or fix an issue. e.g fn_check_root
fn_fix: Applies a server specific fix. e.g. fn_fix_arma3
fn_info: retrieves information from a source fn_info_distro

**Comment by dgibbs64** [comment]
Another consideration is to also the naming of the functions

Firstly to add the .sh extension to the functions to define they are bash as python may start to be included. Plus when opening them Windows does not know what to do with them since lacking an extension which is an inconvenience to me.

Secondly I may remove fn_ from the start. Again becuase of an inconvinience when looking for a function I cannot simply press the first letter of the function name to filter down as they all begin with fn_

So proposed function changes may look like this

    core_messages.sh
    command_start.sh
    check_root.sh
    fix_arma3.sh
    info_distro.sh

**Comment by UltimateByte** [comment]
As i told you, seems like  a huge work of renaming everything, but it sounds really good !
At first, i found a bit strange that script files didn't have extensions, then i saw many others like that, so i thought it wasn't a big deal and was more convenient, but it's up to you, seems more conventional to have it.

**Comment by dgibbs64** [comment]
Yeah past me thought it was best to not have an extension. However I have changed my mind. Renaming is easy as im using sublime text. But with the rename I'm also restructuring how certain functions work. One example is that all checks run at the Start of a command via a new function called fn_check. Fn_check will look at the and execute only the required checks. This willsave having check functions all over the place. Instead each command function only requires fn_check at the Start.....If that doesn't make sense it will when I make the changes. 

Ultimately the end game is to simplify and streamline development.

**Comment by dgibbs64** [comment]
This is nearly ready to move to master. see functions-renaming-merge fork for this.

**Comment by dgibbs64** [comment]
command_update.sh is empty this will need to be addressed. No issues caused by this currently

**Comment by dgibbs64** [comment]
Pull request completed for checks https://github.com/dgibbs64/linuxgsm/pull/592

**Comment by UltimateByte** [comment]
Good job !

**Comment by dgibbs64** [comment]
I am happy with the changes now. The re-naming went very well. It will continue over time as required and development continues, becuase of this I will close
