### ISSUE TITLE
insurgency App '237410' state is 0x202 after update job

### ISSUE THREAD

**Issue by Jan02** [dgibbs64/linuxgsm#572]
Error! App '237410' state is 0x202 after update job.

insserver@vps216546:~$ ./insserver start
    fetching functions/fn_check_logs...OK
    fetching functions/fn_insfix...OK
    fetching functions/fn_details_config...OK
    fetching functions/fn_logs...OK
[ .... ] Starting ins-server: Co-op Elite France Low ping    fetching functions/fn_check_tmux...OK
    fetching functions/fn_check_steamcmd...OK
failed to connect to server: Connection refused

**Comment by Jan02** [comment]
This error means you have run out of available disk space.

**Comment by Nakilon** [comment]
`steamcmd` can say this at the end of validation even with 2GB free

**Comment by Nakilon** [comment]
`steamcmd` also gives this error if you my a mistake update one game into another game's folder, like I messed with 730 and 740
