### ISSUE TITLE
insurgency cannot start server with nwi/coop_elite ?

### ISSUE THREAD

**Issue by Jan02** [dgibbs64/linuxgsm#574]
I try to start the server with playlist nwi/coop_elite but it doesn't use that playlist when the server starts

**Comment by UltimateByte** [comment]
Hello,

Does it helps you ?
https://steamcommunity.com/sharedfiles/filedetails/?id=461776759

**Comment by Jan02** [comment]
@UltimateByte not really, I am already using sv_playlist "nwi/coop_elite" in the config file
