### ISSUE TITLE
[SOLVED] Problem when starting server

### ISSUE THREAD

**Issue by fennekbe** [dgibbs64/linuxgsm#577]
I followed all steps. When I type ./csgoserver start I get the following error. Anyone knows what I should do?

[csgoserver@37-97-144-187 ~]$ ./csgoserver start
[ .... ] Starting csgo-server: QByte.be War Servertmux: error while loading shared libraries: libevent-2.0.so.5: cannot open shared object file: No such file or directory
/home/csgoserver/functions/fn_start: line 132: [: : integer expression expected
tmux: error while loading shared libraries: libevent-2.0.so.5: cannot open shared object file: No such file or directory
/home/csgoserver/functions/fn_start: line 136: [: : integer expression expected
tmux: error while loading shared libraries: libevent-2.0.so.5: cannot open shared object file: No such file or directory
[ FAIL ] Starting csgo-server: Unable to start QByte.be War Server: Tmux error:

Command
=================================
tmux new-session -d -s "csgo-server" "./srcds_run -game csgo -usercon -strictportbind -ip 37.97.144.187 -port 27015 +clientport 27005 +tv_port 27020 +sv_setsteamaccount 9109F88BE9B1F11B2924BF16EF88896B -tickrate 64 +map de_dust2 +servercfgfile csgo-server.cfg -maxplayers_override 16 +mapgroup random_classic +game_mode 0 +game_type 0 +host_workshop_collection  +workshop_start_map  -authkey "

Error
=================================
tmux: error while loading shared libraries: libevent-2.0.so.5: cannot open shared object file: No such file or directory

Fix
=================================
No known fix currently. Please log an issue.
http://gameservermanagers.com/issues

**Comment by UltimateByte** [comment]
Hi there,

Sorry for your issue.
What distro are you using ?
Is everything updated ? (apt-get update / upgrade)
Maybe this could help http://www.nigeldunn.com/2011/12/11/libevent-2-0-so-5-cannot-open-shared-object-file-no-such-file-or-directory/

Keep us informed. Good luck !

**Comment by fennekbe** [comment]
That link actually worked. Didn't think it would be that easy. Thank you
