### ISSUE TITLE
[sdtdserver] Ability to switch to Alpha games ?

### ISSUE THREAD

**Issue by o-be-one** [dgibbs64/linuxgsm#580]
Hello,

i wanted to know if you can add an option to update to alpha to LGSM ? My players wants 7DTD Alpha and can't wait for final release ...

By the way, i wanted to thank you a lot for the awesome work you did with LGSM :). I'm really happy to use it, i've dropper all my home-made scripts to manager my Steam games for LGSM ^^.

**Comment by UltimateByte** [comment]
Hi there,
Is that a different game ID for the alpha ? If it is, you can change it into the main script, it shoukd work. If it needs a -beta or something like that, it will require a bit of tweaking.

**Comment by o-be-one** [comment]
Well i've tried the latest update, for sdtd it's ok i've the latest alpha :).
Yes i was thinking to edit script to do that, but finally all works how i expect.

Thanks again for this lot and great work :). Happy to see you continuing this awesome project, it's helpful for r0x.fr Steam games :).

**Comment by UltimateByte** [comment]
Perfect, i wish a good road to you !
