### ISSUE TITLE
Ark - Use of different ports in configuration file; still default ports in use

### ISSUE THREAD

**Issue by RogerSik** [dgibbs64/linuxgsm#587]
Hello,

I wanted to change the default ports (7777 / 27015) in the Ark Server Configuration. When I do

    ./arkserver details
    
its show me the new server ports (30000 / 30004)

But I cant connect to the new server ports. The olds are still working and 

     netstat -atunp
shows me still the default ports.

**Comment by jaredballou** [comment]
Did you stop and restart the game? When you run `ps aux` or `pstree` what is the command line the server uses?

**Comment by UltimateByte** [comment]
26 days with no answer for an isolated issue, closing this.
Don't hesitate to comment to give is your fix, hopefully it can help somebody.
Don't hesitate to re-open if it's sitll not solved, or better, to use the general support for what seems not to be a script issue : https://steamcommunity.com/groups/linuxgsm/discussions
