### ISSUE TITLE
[csgoserver] new executable not working

### ISSUE THREAD

**Issue by PhilPhonic** [dgibbs64/linuxgsm#588]
I just updated the csgoserver executable. Now it does not work anymore.
>gs_csgo_ar@X:~$ ./csgoserver
    fetching functions/core_functions.sh...OK
    fetching functions/core_messages.sh...OK
gs_csgo_ar@X:~$ ./csgoserver start
gs_csgo_ar@X:~$ ./csgoserver stop
gs_csgo_ar@X:~$ ./csgoserver details

i also tried to remove all old function files. this also did not help

**Comment by dgibbs64** [comment]
Will test now. Odd as I tested this not long ago

**Comment by dgibbs64** [comment]
https://github.com/dgibbs64/linuxgsm/commit/b293da2bb75ead5da3d2316004a0ccd6d62b696f

**Comment by dgibbs64** [comment]
Try now. should be fixed. For some reason core_getopt.sh was missing

**Comment by dgibbs64** [comment]
issue related to #571

**Comment by PhilPhonic** [comment]
works like a charm! thanks a lot!

**Comment by dgibbs64** [comment]
awesome closing this
