### ISSUE TITLE
Multiple Servers

### ISSUE THREAD

**Issue by JimTR** [dgibbs64/linuxgsm#589]
Just wonder where I need to edit to obtain a tmux session name which includes the port, currently the script produces output like this 'gmod-server: 1 windows (created Sun Dec 27 23:13:01 2015) [130x23]' using the tmux ls command ... what I would like to do is open the tmux session  like so 'gmod-server-xxxxx' where xxxxx is the port ... 
I guess I need to glue the port variable to the end of the servicename variable ... if this is correct the config file would need to be named servicename-port.cfg ? assuming the new servicename is gmod-server-port .. if it all works I guess this may help anyone who wants to run another server off the same install

**Comment by Herover** [comment]
There's a small guide on the [wiki](https://github.com/dgibbs64/linuxgsm/wiki/Multiple-Servers) which does what I think you want.
Idea is to make $servercfg contain the name of the cfg specific to the server you want to start, and have a separate script for each server you want in the installation directory.

In short, if you set servicename to gmod-server-1 then it will exec gmod-server-1.cfg.

**Comment by JimTR** [comment]
I have just used the port variable ... it's easier ... I have done some testing & all options appear to work with the exception of the stop  & restart options with certain game modes when the stop option is sent to the script in the tmux session the command appears as uit  not quit .. perhaps if the tmux session does not close by sending the quit command perhaps  the tmux kill command should be used ?

**Comment by dgibbs64** [comment]
I like the idea of using the port to alter the service name thats a good way to do it :)

**Comment by JimTR** [comment]
I have added the option to my scripts (weather multiple or single) TBF I'm writing some PHP code to give the game manager a web interface having the port added in the service name then makes it easier to query the game using gameq ... lsgm (tmux) has an open session & gameq gets a null response = crashed server :8ball: .. in the above screen shot I used servicename-${port} from a PHP point of view it would be better to use servicename@${port} so PHP can use  the filter_var function or I guess I could use explode (-) but using explode will only work well if the service name does not contain a -

**Comment by jaredballou** [comment]
Does this script not support the symlink method of creating multiple instances in one installed game directory?

**Comment by JimTR** [comment]
not quite sure what you mean can you elaborate ?

**Comment by UltimateByte** [comment]
So in the end, did you figure out how to do this ? Can we close ?
As far as i know, the easiest way is to edit the servicename="" into the game script to include the port variable. Don't forget to manage the game config file accordingly, as it usually has to have the same name as the servicename, at least for srcds servers.

**Comment by JimTR** [comment]
I'll close it .. in the future I may add the code I have written to the project
