### ISSUE TITLE
[gmodserver] libsteam.so fix may no longer required

### ISSUE THREAD

**Issue by dgibbs64** [dgibbs64/linuxgsm#596]
Apparently libsteam.so is no longer required by gmod servers. as per:

https://github.com/Facepunch/garrysmod-issues/issues/180

LGSM has a fix for this issue. Can it be confirmed by a gmod admin if libsteam.so is no longer required. If so I will remove the fix.

**Comment by UltimateByte** [comment]
I can check that after sunday !
I'll just make a manuak server with steamcmd and see !

**Comment by dgibbs64** [comment]
thanks. There are a few fixes on LGSM that I would of thought by now would be OK

**Comment by dgibbs64** [comment]
I have checked and libsteam.so is no longer in the garrys mod files. I will be removing this fix

**Comment by UltimateByte** [comment]
Good to know ! Finally they fixed some aberrations... The next one coming is the "quit" command that is broken, they told me it would be fixed at the next update.
