### ISSUE TITLE
[ts3server] Option to reset adminpassword

### ISSUE THREAD

**Issue by dgibbs64** [dgibbs64/linuxgsm#598]
Had a twitter users confused on how to recover or reset his adminpassword. It may be a good idea to see if the option to reset it could be built in to LGSM

**Comment by UltimateByte** [comment]
Yay, let's talk about this when i go under 1g/l of alcohol ! Happy new year to everyone !!

**Comment by UltimateByte** [comment]
I approve that it'd be great ! I always wondered what would happen if i losed my identity or if an admin could demote me because of a group right security mistake... Never looked anything about it yet, but knowing that lgsm can do it would be comforting according to my experience.
I assume you already know how to do it, or will it require some research ? I can help if needed.

**Comment by dgibbs64** [comment]
Yeah there is a command line parameter for doing this. Im not in a rush to implement this yet but I think its a great idea.

**Comment by UltimateByte** [comment]
I'm very interested in learning about this as i use and administrate a TS server every day, which was installed and is monitored using your script. :p 

If you have a link to provide it'd be great, otherwise i'm gonna make some ressearch in the next few days.
Maybe i could give a hand :)

**Comment by ScottSmudger** [comment]
Agreed! Although it is fairly easy to just edit the ini file

**Comment by dgibbs64** [comment]
@ScottSmudger you for some reason deleted the new wiki page I just added. I have restored it. https://github.com/dgibbs64/linuxgsm/wiki/SteamCMD-Login

Yes it is easy however I had someone who had no idea how to do it and I think it shouldn't be too difficult to do.

**Comment by ScottSmudger** [comment]
@dgibbs64 I made an edit, then the changes took effect straight away, weird.

Or when your script creates the ini file, you could also include the serveradmin_password parameter

**Comment by UltimateByte** [comment]
Found this : https://support.teamspeakusa.com/index.php?/Knowledgebase/Article/View/326/16/how-do-i-change-or-reset-the-password-of-the-serveradmin-server-query-account

The rating of this article is very very low, so i'm not sure if it even works.

Found this article too (in french) http://hawkcreation.com/teamspeak-3-retrouver-mot-de-passe-serveradmin/
That says basically the same thing.

ts3server_minimal_runscript.sh serveradmin_password=newpassword

Should be quite easy to add a function to reset the password.

**Comment by UltimateByte** [comment]
I just made a new ts3 test server.

@dgibbs64 
At install i get an command not found error : 

Creating Configs
=================================
downloading lgsm-default.ini...OK
creating ts3-server.ini config file.
‘/home/serverdev/ts3server/serverfiles/lgsm-default.ini’ -> ‘/home/serverdev/ts3server/serverfiles/ts3-server.ini’
/home/serverdev/ts3server/functions/command_install.sh: line 36: install_ts3db.sh: command not found
    fetching functions/install_complete.sh...OK

**Comment by dgibbs64** [comment]
install_ts3db.sh was not listed in core_functions.sh

**Comment by UltimateByte** [comment]
OK, i had to remove the ini command to get it working, but it works !
https://github.com/UltimateByte/linuxgsm/tree/master/functions
Maybe there is a cleaner way to start up the server while doing it, but for now, this is how i got it working.

**Comment by UltimateByte** [comment]
Escpecially this : https://github.com/UltimateByte/linuxgsm/blob/master/functions/command_serveradmin_password.sh

Not sure about the naming btw.

**Comment by dgibbs64** [comment]
naming is pretty good. However I recommend

command_ts3_serveradmin_password.sh

so its easy to identify its specific to ts3

**Comment by UltimateByte** [comment]
I thought it was a bit too long.
I'll do that tonight ^^

**Comment by dgibbs64** [comment]
yeah it is a little long maybe command_ts3_server_password.sh to shorten it a little

**Comment by UltimateByte** [comment]
I renamed it, should be fine !
Please check the start procedure, i'm pretty sure you could do it better than me. I'm more worried about the logfiles than anything else, as i didn't use any command for them for that procedure. I didn't check the logs after the procedure, but i used no commands, so i guess the procedure doesn't log anything, or uses the last logfile. Not a huge deal though.
Watch out, trying to load the ini file (like default setup) prevents the server from starting, that's why i didn't use the usual start script.

**Comment by UltimateByte** [comment]
Pull request sent.

**Comment by dgibbs64** [comment]
Now been merged. https://github.com/dgibbs64/linuxgsm/pull/614
