### ISSUE TITLE
[gmodserver] can't install libsteam.so bin

### ISSUE THREAD

**Issue by fizidesign** [dgibbs64/linuxgsm#600]
Hi I can't install libsteam.so fix at my server.

Startup of server:
[ FAIL ] Console gmod-server2: Server not running
Do you want to start the server? [y/N]y
[ INFO ] Starting gmod-server2: Applying libsteam.so fix: Garry's Modcp: cannot stat '/home/serwerygier/hl2rp/serverfiles/bin/libsteam.so': No such file or directory
[ FAIL ] Starting gmod-server2: Applying libsteam.so fix: Garry's Mod
[  OK  ] Starting gmod-server2: ***********

./gmodserver details:
Distro Details
================================================================================================================================
Distro:    Ubuntu 14.04 LTS
Arch:      x86_64
Kernel:    2.6.32-042stab108.8
Hostname: ********
tmux:      tmux 1.8
GLIBC:     2.19

Performance
================================================================================================================================
Uptime:    0d, 0h, 5m
Avg Load:  0.07, 0.03, 0.00

Mem:       total   used   free
Physical:  6.0G    249M   5.8G
Swap:      512M    0B     512M

Garry's Mod Server Details
================================================================================================================================
Server name:      ******
Server IP:        *****0:27015
RCON password:    *****
Server password:  NOT SET
Game mode:        hl2rp
Status:           ONLINE

gmodserver2 Script Details
================================================================================================================================
Service name:         gmod-server2
gmodserver2 version:  271215
User:                 serwerygier
GLIBC required:       2.07
Email notification:   off
Update on start:      off
Location:             /home/serwerygier/hl2rp
Config file:          /home/serwerygier/hl2rp/serverfiles/garrysmod/cfg/gmod-server2.cfg

Backups
================================================================================================================================
No Backups created

Command-line Parameters
================================================================================================================================
./srcds_run -game garrysmod -strictportbind -ip ******** -port 27015 +host_workshop_collection 581831866 -authkey *******+clientport 27005 +tv_port 27020 +gamemode hl2rp +map rp_city8_2 +sv_setsteamaccount  +servercfgfile gmod-server2.cfg -maxplayers 32

Ports
================================================================================================================================
Change ports by editing the command-line
parameters in gmodserver2.

Useful port diagnostic command:
netstat -atunp | grep srcds_linux

DESCRIPTION  DIRECTION  PORT   PROTOCOL
> Game/RCON  INBOUND    27015  tcp/udp
> SourceTV   INBOUND    27020  udp
< Client     OUTBOUND   27005  udp

Status: ONLINE

**Comment by dgibbs64** [comment]
Thanks I will check this out

**Comment by dgibbs64** [comment]
Might be related to issue #596. It could be that the file has been removed

**Comment by dgibbs64** [comment]
Closing this issue see #596
