### ISSUE TITLE
Unturned Server

### ISSUE THREAD

**Issue by ThErMiK85** [dgibbs64/linuxgsm#603]
Hi,
Can you add unturned server please ?

Thanks You.

**Comment by UltimateByte** [comment]
I'm gonna check this out for feasibility !

**Comment by UltimateByte** [comment]
Doc : http://unturned.wikia.com/wiki/Hosting_a_Dedicated_Server
"Old Guide(Outdated)
Note: Unfortunately, Patch 2.2.2 broke the dedicated server for Linux. Output before crash is:"

"New Guide
First step : Install Unturned."

I guess it can be problematic.
I'm gonna try to get it via steamcmd anyway, we're gonna see what happens. :)

**Comment by dgibbs64** [comment]
Duplicat of #176
