### ISSUE TITLE
Additional log cleanup

### ISSUE THREAD

**Issue by jaredballou** [dgibbs64/linuxgsm#607]
When I run my servers, I have SourceMod, MetaMod and some other items generating log files. These end up in a few well-defined places. I'd like to look at adding a feature to the LGSM to either auto-detect well-known sources of logging (i.e. SourceMod), or allowing the user to define additional log directories to manage. If I can get some feedback, and other people think it's worthwhile, I'll start hacking away on this next week.

**Comment by jaredballou** [comment]
Just realized this is in line with #354 - not sure if we want to start a new discussion or carry on there?

**Comment by UltimateByte** [comment]
Yep, i was gonna point you to my issue too !
I totally forgot about that !
I guess, for now, it's not in lgsm's philosophy to remove logfiles from addons unless we propose an optional installation. But it's still a good idea to cleanup at least default addons.
I'm gonna need some more BASH knowledge to fixt that. For now i'd rely on @dgibbs64 , or let me some time (maybe a bit long) to go work on that :)

**Comment by dgibbs64** [comment]
Yeah I forgot about this as well. Im happy to support some common mods and it cannot be too difficult. But currently I dont have time. 

in fact I really need to do some code rather that responding to all these issues :/

**Comment by UltimateByte** [comment]
I've seen the gamelogdir variable
https://github.com/dgibbs64/linuxgsm/blob/master/GarrysMod/gmodserver#L83
https://github.com/dgibbs64/linuxgsm/blob/master/CounterStrikeGlobalOffensive/csgoserver
Did you already add support for some of the default gamelog files ? I guess yes ! Which is great.

For addons' logs removal, i can only think of an extension that would be supported by the skeleton directory. Once again :p 
https://github.com/dgibbs64/linuxgsm/issues/585

**Comment by dgibbs64** [comment]
Closing to merge with #354
