### ISSUE TITLE
No backwards compatability

### ISSUE THREAD

**Issue by JimTR** [dgibbs64/linuxgsm#608]
I wanted a fresh copy of the monitor script so I ran deleted the file and ran './server monitor'  
response  loading fn_monitor...Not Found
chmod: cannot access ‘fn_monitor’: No such file or directory
./server: line 92: /usr/games/steam/GarrysMod/functions/fn_monitor: No such file or directory

so running wget -N /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/fn_monitor gives the following response
HTTP request sent, awaiting response... 400 Bad Request
2016-01-06 11:38:00 ERROR 400: Bad Request.

so I guess we are a forced upgrade to the new script format ?

**Comment by UltimateByte** [comment]
Hi, sorry to learn that.

All commands and scripts has been renamed to script_name.sh instead of script_name, even the function listing all other functions, present in your main script (in your case gmodserver).
It concerns core_functions.sh and core_getopt.sh.
I guess that's why you're experiencing the issue. So yeah, compatibility is a bit broken, and it will probably not be fixed, you're gonna have to update. 

If you wanna update from that, i advise you to remove the functions folder ( rm -R functions), then to rename your old gmodserver script, like (mv gmodserver old.gmodserver), get the new one, and transfer your settings to the new gmodserver script. Don't forget to chmod +x it again, and you're ready to go !

Don't complain too much about that, i've got 12 servers to update that way ! But i'm happy about the update :p

**Comment by JimTR** [comment]
As I have made loads of changes to the core scripts, in order for the overall script to be ran remotely, this  is not an option ... My current project has cut out all the coloured responses & non required lines of display so the php web code can read the responses without having to strip out the afore mentioned ... I would guess if , like you, I was running the terminal from a terminal I would have all the 56 servers I have running updated to the new format but I guess if the old code is available I could fork the code and continue develop without any issue

**Comment by UltimateByte** [comment]
Wow, excuse me sir ! Didn't see that coming !
I'm now not sure how you can get that sorted out. Maybe a batch renaming of your functions to match the new system ? You seem like you're very comfortable with programming. What information do you need to figure how to get this solved ?

**Comment by JimTR** [comment]
Just to give you an idea the structure is such -
Web controller sat on a server ... that auth's the linux user (to another server) the web code then runs (as the authed user)   lgsm as that user ... to save disk space there is one installation of each game and when a lgsm server is added to a user some of the game code is symlinked to the users install ... this allows 'update once' across multiple users (there are some pitfalls to this , but I am close to a solution). To fix this I have installed a 'new' server to see what the differences are .. therefore it may be just a quick fix !!
this image is the current web controller of lgsm
![ls](https://cloud.githubusercontent.com/assets/4038510/12147136/45644c52-b48f-11e5-9bf5-cdd4a73b22ba.png)

there is debug code in the r/h lower corner  :)

**Comment by UltimateByte** [comment]
Maybe instead of modifying the script and break compatibility with script updates, something like that would be a better integration in the future : 
https://github.com/dgibbs64/linuxgsm/issues/585

**Comment by JimTR** [comment]
look at 
![ls](https://cloud.githubusercontent.com/assets/4038510/12147889/5154806e-b493-11e5-9acd-788a7be1d9b8.png)

**Comment by JimTR** [comment]
I don't think #585 is quite the same

**Comment by UltimateByte** [comment]
1st post : Do you have the possibility to give rights to certain users to reboot certain servers only ?

2nd post : Woudln't it allow you to add your module without touching the base code ? Or are your modifications too deep for that to be enough ?

**Comment by JimTR** [comment]
Each web user can restart every lgsm server he/she owns ... if you note above each server the user owns opens accordion style which then allows you to run the commands (per button) on the sever noted on it's header line

**Comment by JimTR** [comment]
the mods are too deep

**Comment by UltimateByte** [comment]
How happens ownership ?
How much PHP is under that ? :o))
What's the base of your website ? Custom, or something like Wordpress ?
I'm very interested, as i'm willing to rend servers on my machine. For now, i'm considering leaving SSH access to users, and to create servers manually as i don't plan in making that thing big, just plan to reduce the amount i pay each month for my server.

**Comment by UltimateByte** [comment]
BTW, i don't see how we could give support on your script modifications. It's already hard enough to maintain and improve the base script itself. Make your own branch in the future and you'll be fine.

**Comment by dgibbs64** [comment]
@JimTR yeah I think the best way moving forward is for you to fork LGSM then add your custom code. Then if you want to update your code from the master repo you can without LGSM master updates breaking your existing setup. 

A recent version of LGSM added support for selecting a repo of your choice so you can use your own customized repo.

Hope that helps.

Also impressive work with your web interface!!

**Comment by dgibbs64** [comment]
Also seeing your code may allow me to implement the changes you made in to master repo.

**Comment by JimTR** [comment]
I have coded the interface ... I got hacked off with wordpress/mybb etc & spent the last 18 months coding a framework that does what I wanted ! then someone said 'can you control game servers' hence I'm here and the result is the images you see ... so process wise it works like this :- the web code auth's the user .. the php code then sends code to the game server (different machine & ip) using the Auth that the web code has E.G log into the web site as 'fred' you can see only what 'fred' owns  ... so 'fred' opens his gmod server and clicks the restart button  the web server sends a string to the game server containing '/home/fred/games/garrysmod/gmodserver restart' with the user Auth and other bits to ensure that the server could not be controlled via an intercept

**Comment by UltimateByte** [comment]
Amazing !

**Comment by JimTR** [comment]
@dgibbs64 I will send you the code I have adjusted but perhaps it should not hit github ? & thanks for your feed back on the web stuff ... can you confirm what changes you have made & where so I could perhaps fork master and retro code it .... or is there a repro where the old code lives ?

**Comment by JimTR** [comment]
@UltimateByte  currently the actual php game server code is 11.3kb but this relies on the framework code the size of the framework code depends on how many options but typically 50mb

**Comment by dgibbs64** [comment]
All commits can be found here https://github.com/dgibbs64/linuxgsm/commits/master
So you just need to select the correct commit that you think will work

**Comment by JimTR** [comment]
ok cool

**Comment by JimTR** [comment]
@UltimateByte just thought I could do a mybb plugin that adds the game server to code to mybb ... but I'm not sure mybb is secure .... If I dowonload wordpress again perhaps I could put the code to a plugin but to again it's not as secure as I would like

**Comment by UltimateByte** [comment]
@JimTR  Don't know about mybb, i've always been using phpbb without issues, after setting some anti-robot registrationg ofc. :)
I first had only a phpbb forum, then made a wordpress and integrated the phpbb in it (with user links) thanks to wp-united, which is lovely. I'm not perfectly happy with the integration though, which i find quite ugly, but at least there's not too many CSS issues. I wish i'd know how to make WP addons to add functions to the local or to a remote machine... Maybe i'll follow your tracks one day... I've got more and more reasons to learn PHP these days.

**Comment by JimTR** [comment]
cool do it

**Comment by UltimateByte** [comment]
@JimTR OK let me 10 secs... https://www.youtube.com/watch?v=6vMO3XmNXe4
Doesn't work !

**Comment by JimTR** [comment]
I must have missed the point ... but never mind ... I'm old humour me :100:

**Comment by UltimateByte** [comment]
Is there anything more to develop, or should we close this ?

**Comment by JimTR** [comment]
Learning PHP is easy if you put your mind to it & code for the command line  ... it's not unlike C or Lua

**Comment by jaredballou** [comment]
I think there may be a common ground here we're not seeing. Perhaps something as simple as a "Bare Output Only" flag that disables all the ANSI color codes? I got bit by the same bug, I think it might be worthwhile to just write a script to list all the new files/functions and make a "deprecation script" that maps the old names to the new calls, should be fairly straightforward. Is there anything else in your fork that might be useful in the core scripts, we may be able to break it apart and have you focus on the Web UI and then be able to use the LGSM stock. Cut your workload down quite a bit anyway.

**Comment by JimTR** [comment]
That's a good Idea ... the flag could remove non required CR's as well so you get a 'full' array back and don't have to check for array elements that are empty or contain cr

**Comment by jaredballou** [comment]
Would it be easier to just dump all output to a file (or fifo) and parse it when you ingest it there? I usually don't like relying on others for input sanitation, if you want to show me what you're up to I may be able to lend a hand.

**Comment by UltimateByte** [comment]
Closing this as the main issue has been solved.
For further discussions about a webpanel, please use this : https://github.com/dgibbs64/linuxgsm/issues/642
