### ISSUE TITLE
RCon Support for Ark Survival Evolved

### ISSUE THREAD

**Issue by tivyhosting** [dgibbs64/linuxgsm#612]
I'd just like an option to be added to enable Rcon for ark. I was able to make-shift get it working, but it would be nice for it to be a standard feature.

**Comment by UltimateByte** [comment]
You can already i think so.
http://www.ark-survival.net/en/2015/07/09/rcon-tutorial/

Lines 36-37-39
https://github.com/dgibbs64/linuxgsm/blob/master/ARKSurvivalEvolved/cfg/lgsm-default.ini

**Comment by UltimateByte** [comment]
Is the config file enough to enable rcon, or does it have to be a start parameter ?
I don't own that game so i can't test it out.

**Comment by tivyhosting** [comment]
Checked into config and it is do-able. Thanks.
