### ISSUE TITLE
[Ark] Functions problem on debian

### ISSUE THREAD

**Issue by halozero1530** [dgibbs64/linuxgsm#613]
Hi, 
I've got this with ./arkserver command :
./arkserver
Usage: ./arkserver [option]
ARK: Survivial Evolved - Linux Game Server Manager - Version 271215
http://gameservermanagers.com/arkserver

Commands
/home/arkserver/functions/core_getopt.sh: line 68: column: command not found

./arkserver details   give me that : 
./arkserver details
    fetching functions/command_details.sh...OK
    fetching functions/check_systemdir.sh...OK
    fetching functions/check_logs.sh...OK
    fetching functions/check_ip.sh...OK
    fetching functions/check_config.sh...OK
    fetching functions/info_config.sh...OK
    fetching functions/info_distro.sh...OK
    fetching functions/info_glibc.sh...OK

Distro Details
=======================================================================================================
/home/arkserver/functions/command_details.sh: line 25: column: command not found

Performance
=======================================================================================================
/home/arkserver/functions/command_details.sh: line 35: column: command not found

/home/arkserver/functions/command_details.sh: line 41: column: command not found

ARK: Survivial Evolved Server Details
=======================================================================================================
/home/arkserver/functions/command_details.sh: line 129: column: command not found

arkserver Script Details
=======================================================================================================
/home/arkserver/functions/command_details.sh: line 182: column: command not found

Backups
=======================================================================================================
No Backups created

Command-line Parameters
=======================================================================================================
./ShooterGameServer TheIsland?listen

Ports
=======================================================================================================
Change ports by editing the parameters in
/home/arkserver/serverfiles/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini.

Useful port diagnostic command:
netstat -atunp | grep ShooterGame

/home/arkserver/functions/command_details.sh: line 576: column: command not found

Status: ONLINE

Can you fix it ? 

Thanks for your great job ! 

Julien from France

**Comment by UltimateByte** [comment]
Salut Julien ! :p 

Did you update your server functions recently ?
There was a huge function renaming that could have broken some compatibility. You may have to re-download and re-configure the script (not the whole server don't worry).

**Comment by dgibbs64** [comment]
column: command not found

is the issue. so you need to install column on your server

**Comment by UltimateByte** [comment]
I must be blind ! :p

**Comment by UltimateByte** [comment]
Well, i guess it's sovled, closing this for now, feel free to re-open if neded !
Have a great admin time !

**Comment by halozero1530** [comment]
How can i get column ? I search with apt-get but don't find on my Debian :S
(Nerd on Linux)

**Comment by UltimateByte** [comment]
apt-get update
dpkg --add-architecture i386
apt-get install tmux mailutils postfix ca-certificates curl lib32gcc1 libstdc++6 libstdc++6:i386 
?

BTW
"       The column command is part of the util-linux package and is available
       from ftp://ftp.kernel.org/pub/linux/utils/util-linux/."
http://man7.org/linux/man-pages/man1/column.1.html

So i guess what you need is : apt-get util-linux
Normally it's always installed, i'm not sure why you don't have it.

**Comment by halozero1530** [comment]
I've try this yesterday but it still no working.
Maybe not working with debian 8 ? 

UltimateByte : je ne m'en sort pas avec cette histoire ! j'ai passé 2h hier a essayer de remettre ce qui pouvais manquer mais je ne vois pas pourquoi column n'est aps dans le package...

Tu as d'autres idées ?

**Comment by UltimateByte** [comment]
Except apt-get util-linux , i don't know !

**Comment by halozero1530** [comment]
I've install a fresh debian 7 and column works ! 
I think it's a problem with debian 8...

Thanks for help =D

**Comment by UltimateByte** [comment]
Weird, i'm running Debian 8.2 x64 and never had an issue with column...
Looks more of a problem with a modification, maybe made by your server provider on Debian 8.
BTW, thanks for the feedback ;)
