### ISSUE TITLE
[Question] monitor function

### ISSUE THREAD

**Issue by PhilPhonic** [dgibbs64/linuxgsm#615]
Hi,
I have a quick question about the "monitor" function.
If the server crashes, "monitor" restarts it, right?

What happens, if the server is down because it is updating while "monitor" is running?

**Comment by UltimateByte** [comment]
Hi,

That's where the lockfile joins the party !
When stopping your server properly (like it does automatically when updating), the lockfile is removed, so the monitor function won't restart the server. 
https://github.com/dgibbs64/linuxgsm/blob/master/functions/command_monitor.sh#L62

Try to shutdown your server, then monitor it, you'll see ;)

**Comment by PhilPhonic** [comment]
thanks! :-)
