### ISSUE TITLE
[bb2server] Brain Bread 2 Server request

### ISSUE THREAD

**Issue by dgibbs64** [dgibbs64/linuxgsm#618]
I have been informed Brainbread 2 server is now available in Linux.

**Comment by UltimateByte** [comment]
Seems cool ! ^^

**Comment by dgibbs64** [comment]
Server released just working on compatibility

Libcurl is required and Glibc 2.15
http://serverfault.com/questions/485227/upgrade-curl-to-latest-on-centos-6-3

**Comment by UltimateByte** [comment]
That was fast ! Good job !
I'm gonna test it soon, i tested and liked the game ! :)

**Comment by dgibbs64** [comment]
Fully working. Closing this
