### ISSUE TITLE
[CSGO] 404 on update

### ISSUE THREAD

**Issue by SkippTekk** [dgibbs64/linuxgsm#621]
Hey guys, not sure if this is a huge issue or not, but apparently im getting a 404 on the CSGO update command, is there a way to fix this?

https://t.co/ztdzv8E2FY

**Comment by hyperbolic2346** [comment]
I got this until I synced up with github again. There have been some changes and restructuring recently it seems.

**Comment by SkippTekk** [comment]
Yeah, i have seen that as well in the main files. i just need my server to be able to get updated and running for a stress test that im doing. Worked on it for 3 days and i don't wanna loose my progress.

**Comment by dgibbs64** [comment]
./csgoserver update-functions

**Comment by SkippTekk** [comment]
Works! Thanks you! Please close this now as the server is now updating itself :)
