### ISSUE TITLE
CentOS 7 Downgrade Tmux?

### ISSUE THREAD

**Issue by SaturnsVoid** [dgibbs64/linuxgsm#627]
So my system installed Tmux.x86_64 0:1.8-4.e17 How can i go about downgrading it safely to 1.6 so i can use logs?

**Comment by UltimateByte** [comment]
Hi,

I guess this will help.
https://access.redhat.com/solutions/29617

BTW, the proper way would be to figure out what went wrong with the new tmux so we have a chance to fix it for every CentOS users.

**Comment by UltimateByte** [comment]
BTW, why would you need an upgrade ?
What's the output of
command -v tmux
 ?

**Comment by jaredballou** [comment]
Yeah, the way I did wget or curl in my github fetcher might be helpful.
https://github.com/jaredballou/linuxgsm/blob/master/Insurgency/insserver
might be helpful. Basically I tried to not assume anything, and check all paths where it may be. I'll spin up a Cent7 box today and give this a shot.

**Comment by UltimateByte** [comment]
It could be interesting to know more about that issue that could happen to other people and may be a fixable script issue.
But 11 days without a single answer, I'll close this for now. Re-open if needed.
