### ISSUE TITLE
CentOS 6.6 Tmux

### ISSUE THREAD

**Issue by Nobbyblue** [dgibbs64/linuxgsm#628]
Not sure if this is possible on 6.6 but I'm attempting to start a GMOD server. I get the following error:

[ FAIL ] Starting gmod-server: Tmux not installed
        * Tmux is required to run this server.
        * Please see the the following link.
        * http://gameservermanagers.com/tmux-not-found

But when I attempt to install TMUX it tells me that it is already installed as follows:

Loaded plugins: fastestmirror, refresh-packagekit
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: centos.mirrors.ovh.net
 * extras: centos.mirrors.ovh.net
 * updates: centos.mirrors.ovh.net
No package tmux available.

Is it simply not possible for me or am I being a fool? Thanks for any help.

**Comment by UltimateByte** [comment]
Hi,

Sorry to hear that.
Of course you're not a fool ! It seems like you did everything right to try diagnosing it.

Did you ever have a server running well previously ? If yes,could it possibly be related to this ?
https://github.com/dgibbs64/linuxgsm/issues/627

Could you please give me the output of that command ?
command -v tmux

**Comment by Nobbyblue** [comment]
I didn't actually have a server running before so it's not related to that post you linked. In terms of that command, I'm not sure what that command actually is or how to run it. When it comes to SSH and Linux I'm rather new so I'm unsure what you're talking about, could you perhaps give me the exact command to input?

**Comment by UltimateByte** [comment]
I'll give you a few commands to test, just to see what it answers. These commands are just meant to see if tmux is installed, and are initially runned by LGSM. Maybe LGSM could detect that tmux isn't installed while it is.
All the commands i'll copy/paste you are those at the line of the code i linked, they're looking like that : [ ..test-tmux-code... ] || [ ...test-tmux-2nd-code... ]
You can actually try them in your ssh command prompt and copy/paste here what each one answers. 
If you don't get it i'll give you the commands to try tomorrow but right now i'm on my smartphone so it's pretty hard to do :p

**Comment by jaredballou** [comment]
source /etc/profile
See if you just aren't loading the Bash profile. Then
rpm -qa | grep -i tmux
and see what you have installed. You can use `rpm -ql $PACKAGE` to get a full list of what it installs, which would be your missing executable. If you don't see it, run
yum whatprovides */tmux
See what packages are there.

**Comment by UltimateByte** [comment]
So in the end my question was just : Do you actually have tmux installed ?
As it's been 10 days without an answer, i'm closing this for now. Feel free to re-open if needed, or just post your solution to the issue to hopefully help other poeple.

**Comment by Nobbyblue** [comment]
Sorry for the delayed response been rather busy lately. In the end I couldn't get it to work at all so I just did it the regular way and made a new user installed steamcmd etc and just setup a server through steam commands and managed to get it all working.

**Comment by UltimateByte** [comment]
Your error message sounds like tmux isn't available for you more than already installed. I'd suggest posting in centos forums to get it sorted out.
Could either be a mirror issue or an apt config issue, definitely not a script issue in my opinion.
BTW, have a nice admin time !

**Comment by Nobbyblue** [comment]
Not a clue, all I know is I followed the steps for this and for whatever reason it didn't work but when I did it through steamcmd it did. Thanks for all the support you've provided anyway though :)

**Comment by UltimateByte** [comment]
The only issue with using steamcmd is if you're not using any kind of container as tmux or screen. Then either you won't be able to see your console and to control it, or you will be trapped, not being able to quit your console without closing the server. Hopefully you're using screen.
You're welcome :)
