### ISSUE TITLE
[insserver] Part of fix_ins.sh may no longer be needed

### ISSUE THREAD

**Issue by dgibbs64** [dgibbs64/linuxgsm#629]
# fix for issue #529 - gamemode not passed to debug or start

	if [ "${function_selfname}" == "command_debug.sh" ]; then
	        defaultmap="\"${defaultmap}\""
	else
	        defaultmap="\\\"${defaultmap}\\\""
	fi
	fn_parms

I am using insserver currently and found that using this fix appears to now break debug mode. Can anyone confirm this and I will remove this fix. Maybe an update to Insurgency resolved the issue.

**Comment by PhilPhonic** [comment]
I can confirm this.
:~$ ./insserver debug
> map load failed: \ not found or invalid

If you remove the fix, gamemode won't be passed to ./insserver start or ./insserver debug
./insserver start still works fine with this fix.

I'll try to figure out what's wrong
