### ISSUE TITLE
Ark server wont start

### ISSUE THREAD

**Issue by samosnik** [dgibbs64/linuxgsm#630]
it is a fresh install and it says 
[ .... ] Starting ark-server: arkserversession not found: ark-server
[ FAIL ] Starting ark-server: Unable to start arkserver
Any ideas?

**Comment by UltimateByte** [comment]
Hi,

Can you try to run the "validate" command ?

**Comment by samosnik** [comment]
Thanks for the reply! It sadly Didn't work. Also tried to delete it and install it again. Still same problem.

**Comment by UltimateByte** [comment]
What OS ?
What dos say the script log ?

**Comment by samosnik** [comment]
OS: Debian 7.5 
And the script log just says: 
Jan 16 21:08:52 ark-server: Starting: Unable to start arkserver
Jan 16 21:08:57 ark-server: Starting: arkserver
Jan 16 21:08:58 ark-server: Starting: Rotating log files

**Comment by dgibbs64** [comment]
./arkserver debug will help

**Comment by samosnik** [comment]
Start parameters:
./ShooterGameServer TheIsland?listen

Use for identifying server issues only!
Press CTRL+c to drop out of debug mode.
Warning! If ark-server is already running it will be stopped.

Continue? [Y/n]y
[ INFO ] Debug ark-server: Stopping any running servers
[ FAIL ] Stopping ark-server: arkserver is already stopped
[  OK  ] Debug ark-server: Starting debug
/home/niko/ARK/functions/command_debug.sh: line 60: ./ShooterGameServer: No such file or directory
 This is what came out.

**Comment by dgibbs64** [comment]
I cannot find the executable for the server. Are you sure the files have downloaded? in to serverfiles?

**Comment by samosnik** [comment]
./arkserver validate didn't help. Just for the sake of it i deleted in and re-downloaded it again. It seems to be working now. Thanks for the help and keep up the good work!
