### ISSUE TITLE
CS:GO Server not starting / connecting to steam

### ISSUE THREAD

**Issue by TxS-PRIME** [dgibbs64/linuxgsm#632]
I have just installed the server with the installer, however when I try to start the server it says it has but when I check console, it gives me errors like "Could not establish connection to Steam servers" so I tried: ./csgoserver debug... Here are my results:
csgoserver@server15:~$ ./csgoserver debug
[  OK  ] Debug csgo-server: Applying workshop map fix: Counter Strike: Global Offensive

Counter Strike: Global Offensive Debug
============================

Distro: Ubuntu 14.04.3 LTS
Arch: x86_64
Kernel: 3.19.0-25-generic
Hostname: server15

Start parameters:
./srcds_run -game csgo -usercon -strictportbind -ip 192.168.1.14 -port 27015 +clientport 27005 +tv_port 27020 +sv_setsteamaccount C55BFBC16CA8F7ADDB5EFC7422472AA6 -tickrate 64 +map de_dust2 +servercfgfile csgo-server.cfg -maxplayers_override 16 +mapgroup mg_active +game_mode 1 +game_type 0 +host_workshop_collection  +workshop_start_map  -authkey  -debug

Use for identifying server issues only!
Press CTRL+c to drop out of debug mode.
Warning! If csgo-server is already running it will be stopped.

Continue? [Y/n]y
[ INFO ] Debug csgo-server: Stopping any running servers
[ FAIL ] Stopping csgo-server: ReVenit3 eSports -- CS:GO Team [Practice] is already stopped
[  OK  ] Debug csgo-server: Starting debug
./srcds_run: 32: ./srcds_run: pushd: not found
./srcds_run: 35: ./srcds_run: popd: not found
Enabling debug mode
./srcds_run: 1: ./srcds_run: gdb: not found
WARNING: Please install gdb first.
        goto http://www.gnu.org/software/gdb/
Server will auto-restart if there is a crash.
LD_LIBRARY_PATH=/home/csgoserver/serverfiles/bin:/home/csgoserver/serverfiles:/home/csgoserver/serverfiles/bin:
#
#Console initialized.
Setting breakpad minidump AppID = 740
#Using breakpad minidump system 740/13518.258.DC
Using breakpad crash handler
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
#Loading VPK file hashes for pure server operation.
#Game.dll loaded for "Counter-Strike: Global Offensive"
#CGameEventManager::AddListener: event 'server_pre_shutdown' unknown.
#CGameEventManager::AddListener: event 'game_newmap' unknown.
#CGameEventManager::AddListener: event 'finale_start' unknown.
#CGameEventManager::AddListener: event 'round_start' unknown.
#CGameEventManager::AddListener: event 'round_end' unknown.
#CGameEventManager::AddListener: event 'difficulty_changed' unknown.
#CGameEventManager::AddListener: event 'player_connect' unknown.
#CGameEventManager::AddListener: event 'player_disconnect' unknown.
#GameTypes: missing mapgroupsSP entry for game type/mode (custom/custom).
#GameTypes: missing mapgroupsSP entry for game type/mode (cooperative/cooperative).
Failed to load gamerulescvars.txt, game rules cvars might not be reported to management tools.
Server is hibernating
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
No web api auth key specified - workshop downloads will be disabled.
maxplayers set to 64
ConVarRef cl_embedded_stream_video_playing doesn't point to an existing ConVar
Setting mapgroup to 'mg_active'
Usage: host_workshop_collection <fileid>
Usage: workshop_start_map <fileid>
---- Host_NewGame ----
Host_NewGame on map de_dust2
GameTypes: missing mapgroupsSP entry for game type/mode (custom/custom).
GameTypes: missing mapgroupsSP entry for game type/mode (cooperative/cooperative).
ConVarRef room_type doesn't point to an existing ConVar
bot_autodifficulty_threshold_high - 5.0
bot_autodifficulty_threshold_low - -2.0
bot_chatter - normal
bot_defer_to_human_goals - 0
bot_defer_to_human_items - 1
bot_difficulty - 1
bot_quota - 10
bot_quota_mode - normal
bot_allow_grenades - 1
bot_allow_pistols - 1
bot_allow_sub_machine_guns - 1
bot_allow_shotguns - 1
bot_allow_rifles - 1
bot_allow_snipers - 1
bot_allow_machine_guns - 1
sv_auto_adjust_bot_difficulty - 1
sv_bots_get_easier_each_win - 0
sv_bots_force_rebuy_every_round - 0
sv_bots_get_harder_after_each_wave - 0
mp_playercashawards - 1
cash_player_bomb_defused - 300
cash_player_bomb_planted - 300
cash_player_damage_hostage - -30
cash_player_interact_with_hostage - 150
cash_player_killed_enemy_default - 300
cash_player_killed_enemy_factor - 1
cash_player_killed_hostage - -1000
cash_player_killed_teammate - -300
cash_player_rescued_hostage - 1000
cash_player_respawn_amount - 0
cash_player_get_killed - 0
mp_teamcashawards - 1
cash_team_elimination_bomb_map - 3250
cash_team_elimination_hostage_map_t - 1000
cash_team_elimination_hostage_map_ct - 2000
cash_team_hostage_alive - 0
cash_team_hostage_interaction - 500
cash_team_loser_bonus - 1400
cash_team_loser_bonus_consecutive_rounds - 500
cash_team_planted_bomb_but_defused - 800
cash_team_rescued_hostage - 0
cash_team_terrorist_win_bomb - 3500
cash_team_win_by_defusing_bomb - 3250
cash_team_win_by_hostage_rescue - 3500
cash_team_win_by_time_running_out_bomb - 3250
cash_team_win_by_time_running_out_hostage - 3250
cash_team_survive_guardian_wave - 1000
mp_afterroundmoney - 0
mp_buytime - 90
mp_buy_anywhere - 0
mp_buy_during_immunity - 0
mp_startmoney - 800
mp_maxmoney - 16000
sv_buy_status_override - -1
mp_death_drop_defuser - 1
mp_death_drop_grenade - 2
mp_death_drop_gun - 1
mp_deathcam_skippable - 1
mp_defuser_allocation - 0
mp_give_player_c4 - 1
mp_free_armor - 0
mp_molotovusedelay - 15.0
mp_weapons_allow_zeus - 1
mp_weapons_allow_map_placed - 0
mp_weapons_glow_on_ground - 0
mp_ct_default_melee - weapon_knife
mp_ct_default_secondary - weapon_hkp2000
mp_ct_default_primary -
mp_ct_default_grenades -
mp_t_default_melee - weapon_knife
mp_t_default_secondary - weapon_glock
mp_t_default_primary -
mp_t_default_grenades -
mp_buy_allow_grenades - 1
mp_weapons_allow_typecount - 5
mp_freezetime - 6
mp_force_pick_time - 15
mp_halftime - 0
mp_match_can_clinch - 1
mp_maxrounds - 0
mp_roundtime - 5
mp_roundtime_defuse - 0
mp_roundtime_hostage - 0
mp_timelimit - 5
mp_warmuptime - 30
mp_warmup_pausetimer - 0
mp_halftime_pausetimer - 0
mp_default_team_winner_no_objective - -1
mp_hostagepenalty - 10
mp_solid_teammates - 1
sv_allow_votes - 1
sv_alltalk - 0
sv_auto_full_alltalk_during_warmup_half_end - 1
sv_deadtalk - 0
sv_ignoregrenaderadio - 0
mp_teammates_are_enemies - 0
mp_damage_scale_ct_body - 1.0
mp_damage_scale_ct_head - 1.0
mp_damage_scale_t_body - 1.0
mp_damage_scale_t_head - 1.0
mp_friendlyfire - 0
ff_damage_reduction_bullets - 0.1
ff_damage_reduction_grenade - 0.25
ff_damage_reduction_grenade_self - 1
ff_damage_reduction_other - 0.25
mp_limitteams - 2
spec_freeze_panel_extended_time - 0.0
spec_freeze_time - 2.0
mp_forcecamera - 1
mp_respawn_immunitytime - 4.0
mp_respawn_on_death_t - 0
mp_respawn_on_death_ct - 0
mp_display_kill_assists - 1
mp_use_respawn_waves - 0
mp_respawnwavetime_ct - 10.0
mp_respawnwavetime_t - 10.0
mp_randomspawn - 0
mp_randomspawn_los - 1
mp_radar_showall - 0
mp_force_assign_teams - 0
sv_gravity - 800
sv_accelerate - 5.5
sv_stopspeed - 80
sv_airaccelerate - 12
sv_wateraccelerate - 10
sv_waterfriction - 1
sv_friction - 5.2
sv_bounce - 0
sv_maxvelocity - 3500
sv_maxspeed - 320
mp_ggprogressive_round_restart_delay - 15.0
mp_ggtr_bomb_defuse_bonus - 1.0
mp_ggtr_bomb_detonation_bonus - 1.0
mp_ggtr_bomb_pts_for_flash - 4
mp_ggtr_bomb_pts_for_he - 3
mp_ggtr_bomb_pts_for_molotov - 5
mp_ggtr_bomb_pts_for_upgrade - 2.0
mp_ggtr_bomb_respawn_delay - 0.0
mp_ggtr_end_round_kill_bonus - 1
mp_ggtr_halftime_delay - 0.0
mp_ggtr_last_weapon_kill_ends_half - 0
sv_arms_race_vote_to_restart_disallowed_after - 0
mp_guardian_special_kills_needed - 10
mp_guardian_special_weapon_needed - awp
mp_guardian_player_dist_min - 1300
mp_guardian_player_dist_max - 2000
mp_randomspawn_in_bombsite - -1
bot_custom_strat -
mp_hostages_spawn_force_positions -
mp_hostages_spawn_same_every_round - 1
mp_guardian_bot_money_per_wave - 800
sv_disable_show_team_select_menu - 0
mp_hostages_max - 2
spec_replay_enable - 0
mp_round_restart_delay - 7.0
Executing dedicated server config file
Server logging enabled.
Server logging data to file logs/L192_168_001_014_27016_201601161250_000.log
L 01/16/2016 - 12:50:39: Log file started (file "logs/L192_168_001_014_27016_201601161250_000.log") (game "/home/csgoserver/serverfiles/csgo") (version "6240")
Writing cfg/banned_user.cfg.
Writing cfg/banned_ip.cfg.
L 01/16/2016 - 12:50:39: server_cvar: "cash_player_interact_with_hostage" "300"
L 01/16/2016 - 12:50:39: server_cvar: "cash_team_elimination_hostage_map_t" "3000"
L 01/16/2016 - 12:50:39: server_cvar: "cash_team_elimination_hostage_map_ct" "3000"
L 01/16/2016 - 12:50:39: server_cvar: "cash_team_hostage_interaction" "600"
L 01/16/2016 - 12:50:39: server_cvar: "cash_team_rescued_hostage" "600"
L 01/16/2016 - 12:50:39: server_cvar: "cash_team_win_by_defusing_bomb" "3500"
L 01/16/2016 - 12:50:39: server_cvar: "cash_team_win_by_hostage_rescue" "2900"
L 01/16/2016 - 12:50:39: server_cvar: "mp_freezetime" "15"
L 01/16/2016 - 12:50:39: server_cvar: "mp_friendlyfire" "1"
L 01/16/2016 - 12:50:39: server_cvar: "mp_maxrounds" "30"
L 01/16/2016 - 12:50:39: server_cvar: "mp_roundtime" "1.92"
L 01/16/2016 - 12:50:39: server_cvar: "mp_roundtime_hostage" "1.92"
L 01/16/2016 - 12:50:39: server_cvar: "mp_roundtime_defuse" "1.92"
L 01/16/2016 - 12:50:39: server_cvar: "mp_timelimit" "0"
L 01/16/2016 - 12:50:39: server_cvar: "sv_deadtalk" "1"
exec: couldn't exec gamemode_competitive_server.cfg
Commentary: Could not find commentary data file 'maps/de_dust2_commentary.txt'.
Initializing Steam libraries for secure Internet server
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
FillInMachineIDInfo took a total of 1 milliseconds
Setting breakpad minidump AppID = 730
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Setting breakpad minidump AppID = 740
Logging into Steam gameserver account with logon token 'C55BFBC1xxxxxxxxxxxxxxxxxxxxxxxx'
Could not establish connection to Steam servers.

**Comment by dgibbs64** [comment]
At a guess it may be a firewall issue.

**Comment by TxS-PRIME** [comment]
So how would I clear the issue, I have port forwarded and other services (TeamSpeak, Mumble) are able to access the internet.

**Comment by UltimateByte** [comment]
I would say : 
1) Run the validate command
2) Be sure to open the 3 ports (27005 , 27015, 27020 -tcp/udp-)
3) Make sure no other game server is using those ports, otherwise use alternative ports
Keep us informed.

**Comment by TxS-PRIME** [comment]
I have done all three things, however no luck with any...

I don't know what else to do...

**Comment by UltimateByte** [comment]
Did you set your IP in server config ? It's useful, mostly if you have several interfaces (even virtual ones).

**Comment by jaredballou** [comment]
You have an outbound firewall?
SELinux?
What sort of firewall is between the server and the internet?

**Comment by UltimateByte** [comment]
As it's quite certainly a non-script issue, and i'ts been 5 days since the last answer, i'll close this.
If you need further help, please go to the general support if you're OK. 
https://steamcommunity.com/groups/linuxgsm/discussions
You'd probably have more chances to get help from other experienced admins of steam games about this very specific issue.
Link to this git issue anyway on the thread you will create.
Otherwise you can still re-open this.

**Comment by spot88** [comment]
I get this error now, fresh install on Ubuntu 14.02 - What was the fix?

**Comment by spot88** [comment]
Firewall is not the issue, the same port was just used for another cs:go server. Difference was the other server was not running LGSM script, but a regular bash script.

**Comment by spot88** [comment]
Just tryed the standard update\upgrade, reboot. - Still the same message.

**Comment by spot88** [comment]
Disabled ufw, same result

**Comment by spot88** [comment]
Reinstalled lgsm, same problem.

**Comment by cedarlug** [comment]
2 things, please:

First, read [this](https://github.com/GameServerManagers/LinuxGSM/wiki/Support) before posting.  Pay particular attention to the section titled (in all caps for a reason) [REQUIRED INFORMATION FOR SUPPORT](https://github.com/GameServerManagers/LinuxGSM/wiki/Support#required-information-for-support).

Second. Your issue is different from this CLOSED ticket.  Necro-posting with spam posts will get you very little help here.  Even more so, when you haven't provided any of the required information for support.

 

Please create a new ticket for your issue.
