### ISSUE TITLE
Is sudo needed? It won't work without it, or with it..

### ISSUE THREAD

**Issue by camsn0w** [dgibbs64/linuxgsm#633]
[fofserver@localhost ~]$ chmod +x fofserver
[fofserver@localhost ~]$ ./fofserver install
    fetching functions/install_header.sh...FAIL

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file

**Comment by PhilPhonic** [comment]
perhaps github was "down" or not accessible. did you try again?

**Comment by UltimateByte** [comment]
Is the folder you're writing to writable for fofserver ?

**Comment by camsn0w** [comment]
That was It!!! Thanks.

**Comment by UltimateByte** [comment]
Watch out when you make folders as root, don't forget to make a chown -R username:username folder ;)
