### ISSUE TITLE
Dedicated Server linux 

### ISSUE THREAD

**Issue by Wencik** [dgibbs64/linuxgsm#635]
Hello,

I have a problem on the server it cs:go . Players are sometimes goes back and drops in fps
Debian 7 /64bit  /// I have 3 servers on it 

Procesor : Intel Core i7 4790k 4,00 GHz 4 cores / 8 threads 
RAM 16 GB DDR3 1600MHz 
Hard drive : 2x120GB SSD

**Comment by UltimateByte** [comment]
This is obviously a lag issue, so not giving your network specs seems a bit odd.

Also, how many players does it takes to lag ?
What tickrate ? What rates ?
And most importantly : what connection speed ?

**Comment by Wencik** [comment]
100Mbit/s 
28 slots - 102tr
23 slots - 128tr
19 slots - 128tr
the server has a lag in the form of reverse.

all server use max rate 128000 - min rate 102000

**Comment by UltimateByte** [comment]
Any FastDL hosted on it ? Anything that could fill up some CPU at some point ?
100mbit/s can be filled up pretty fast and could cause that kind of things.
Maybe install brandwidh/CPU monitor tools and watch your CPU/Network use.

**Comment by Wencik** [comment]
yes there is a fastdl.
CPU graph is fine.
I switched off the script on packaging demos

**Comment by UltimateByte** [comment]
Maybe try to limit the fastdl speed if you can ?

"I switched off the script on packaging demos" > I don't get it.

**Comment by Wencik** [comment]
script for archiving demos on the page

**Comment by jaredballou** [comment]
What are the disk stats like?
Have you run top or iostat to keep an eye on performance when the lag happens?
Do all clients experience the same thing, or is it only certain people/locations?
Does it have any correlation to servers loading maps, lots of messages, or full servers?
Is this actually in a colo with dedicated 100Mbps?
Do all instances lag at the same time, or is it only one/two of them?
Have you done net_graph 3 and seen what the traffic consists of?

**Comment by UltimateByte** [comment]
Did you figure this out ?

**Comment by UltimateByte** [comment]
As it's quite certainly a non-script issue, I'd suggest to close this and go to the general support if you're OK.
https://steamcommunity.com/groups/linuxgsm/discussions
You'd probably have more chances to get help from other experienced admins of steam games about this very specific issue.
Link to this git issue anyway on the thread you will create.

**Comment by Wencik** [comment]
Already I worked it out :) Thank you for your time

**Comment by UltimateByte** [comment]
Can you please share your solution in order tl help future people experiencing the same issue ?

**Comment by Wencik** [comment]
script for archiving demos on the page - OFF [ CPU overloads ]
