### ISSUE TITLE
Hurtworld Dedicated - server not appearing in list, ports configured.

### ISSUE THREAD

**Issue by Kainzo** [dgibbs64/linuxgsm#636]
Is there something that I did wrong on the setup? I opened both UDP and TCP for
	Accept	If protocol is UDP and destination port is 12871:12881		
	Accept	If protocol is TCP and destination port is 12871:12881

**Comment by UltimateByte** [comment]
Hi.
Is that supposed to be an iptable rule ?
I think that syntax is outdated by centuries. :p

**Comment by Kainzo** [comment]
@UltimateByte - I think its extremely poor practice to disable the firewall.  I seem to only have issues with the query ports / server listings sometimes and it usually is something on the game server lister that needs to be updated.

This may not be a script issue, I suppose, but was hoping to get some help on the matter. I'll trouble shoot ports =)

**Comment by UltimateByte** [comment]
I've seen both sides about Firewals... For now i assume i'm not having an obvious security breach so it doesn't change anything except it's 100x more convenient to deploy new stuff... I know it's not the best practice, but that's fine for my lvl of service. :p 
As you saw, i'm not an expert of iptables, i messed with it just a little bit, to try it but i won't be more helpful on that one !

Maybe an iptables master hanging out there could give a hand ?

**Comment by Kainzo** [comment]
@UltimateByte  after further testing, this was my issue.  The ports were fine.

It was a gross misunderstanding of where the server pulled slots/name, etc, so I just assumed my server was unfound.  It turns out that the server was found!   It was just named generically so I didn't know.

It brings me to my next issue, which I can create a ticket on and have yet to research.
The colorization of the server list name > http://i.imgur.com/SYggDr2.png

**Comment by UltimateByte** [comment]
Lol ! Finally it was simpler. :p 

Could you copy your exact servername line ?

(default :

**Comment by Kainzo** [comment]
@UltimateByte 
servername="<color=#FF0000>Herocraft - play.hc.to</color> - <color=#FF0232>Texas</color>"

This is what I have.  It seems that single colors work but double colors don't work. I may just be doing it absolutely wrong, though.

**Comment by UltimateByte** [comment]
Would be weird, but you can try to close only the second </color>
If they coded it with feet it may be the solution.
I assume you saw servers with 2 colors in the list right ? I still don't own the game so i can't check myself.

**Comment by jaredballou** [comment]
If you know what the ports are that need to be open I can write out the iptables command you need to run. Then just save your firewall state and be happy. It's really not good to disable it, I ban about 250 attackers a day trying to SSH to my game servers. It's a scary world out there.

**Comment by UltimateByte** [comment]
@jaredballou He solved the firewall issue, that was actually a non-issue.
The only thing now is that color code thing :)

**Comment by Kainzo** [comment]
@UltimateByte, I tried closing only one, yes.  There are definitely servers with multiple colors. I first thought I was just bad at HTML, lol.

**Comment by UltimateByte** [comment]
http://oxidemod.org/threads/colors-in-server-name.13114/

"True <color=#ffa500> MY AWESOME SERVER </color>

False <color=#ffa500>MY AWESOME SERVER</color>"

**Comment by UltimateByte** [comment]
Did you figure this out ?
Closing for now, feel free to re open if needed.

**Comment by Kainzo** [comment]
Its only usable as a single color system. That's fine with me though, thanks!
