### ISSUE TITLE
Port conflict

### ISSUE THREAD

**Issue by fletchette** [dgibbs64/linuxgsm#639]
Hey all
I'm trying to run a second Source server (TF2), but the console is giving me a port unavailable (27005).

The port config is like this - 

**Server 1**
port="27015"
sourcetvport="27020"
clientport="27005"

**Server 2**
port="27017"
sourcetvport="27022"
clientport="27005"

Why is the clientport giving an issue? (isn't that just the port the client connects from?)
Does that mean I should change the client port for the second server?
Can I have the same port and sourcetvport for both servers?

**Comment by UltimateByte** [comment]
Hey dude !
Try changing the client port : surprise ! It works ! :p
Yes you have o change it too !
The first port is the queryport, sourcetv is sourcetv, and client port is used by clients, si it's not only an outgoing port.

**Comment by dgibbs64** [comment]
I believe it is only outgoing. However if one server is already using a port a second server cannot use it as well.

**Comment by fletchette** [comment]
Ok, thanks to both of you.
