### ISSUE TITLE
Insurgency: Not shown in Server Browser

### ISSUE THREAD

**Issue by bisam** [dgibbs64/linuxgsm#640]
Hi and thanks for the great tool you provide :)

I am having trouble getting my Insurgency server to behave. I have a very basic setup, not much changed from the basic settings except sv_lan = 1. I filled in my Servers local IP adress, and the server seems to start properly, says that it is running and so on. But I cannot find it in any of my machines ingame server browser.

I am running a fully updated Debian Wheezy 64bit with all recommended dependencies installed. (except postfix) 

Here is the content of my "./log/console/ins-server-console.log"

Is there something wrong with my setup?

[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
#
#Console initialized.
#Loaded 2725 VPK file hashes from /home/insurgency/serverfiles/insurgency/insurgency_materials.vpk for pure server operation.
#Loaded 2725 VPK file hashes from /home/insurgency/serverfiles/insurgency/insurgency_materials.vpk for pure server operation.
#Loaded 19 VPK file hashes from /home/insurgency/serverfiles/insurgency/insurgency_misc.vpk for pure server operation.
#Loaded 19 VPK file hashes from /home/insurgency/serverfiles/insurgency/insurgency_misc.vpk for pure server operation.
#Loaded 272 VPK file hashes from /home/insurgency/serverfiles/insurgency/insurgency_models.vpk for pure server operation.
#Loaded 272 VPK file hashes from /home/insurgency/serverfiles/insurgency/insurgency_models.vpk for pure server operation.
#Loaded 2 VPK file hashes from /home/insurgency/serverfiles/insurgency/insurgency_particles.vpk for pure server operation.
#Loaded 2 VPK file hashes from /home/insurgency/serverfiles/insurgency/insurgency_particles.vpk for pure server operation.
#Loaded 1483 VPK file hashes from /home/insurgency/serverfiles/insurgency/insurgency_sound.vpk for pure server operation.
#Loaded 1483 VPK file hashes from /home/insurgency/serverfiles/insurgency/insurgency_sound.vpk for pure server operation.
#Game.dll loaded for "Insurgency"
#CGameEventManager::AddListener: event 'server_pre_shutdown' unknown.
#CGameEventManager::AddListener: event 'game_newmap' unknown.
#CGameEventManager::AddListener: event 'round_start' unknown.
#CGameEventManager::AddListener: event 'round_end' unknown.
mode MP, dedicated Yes, ports 27015 SV / 27005 CL
Server is hibernating
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
Parent cvar in server.dll not allowed (ins_bot_arousal_suppression_falloff)
maxplayers set to 16
Unable to remove /home/insurgency/serverfiles/state_crash.txt!
Unable to remove /home/insurgency/serverfiles/state_crash.txt!
Unknown command "joy_name"
Unknown command "joy_advanced"
Unknown command "joy_accelmax"
Unknown command "joy_accelscale"
Unknown command "joy_advaxisx"
Unknown command "joy_advaxisy"
Unknown command "joy_advaxisz"
Unknown command "joy_advaxisr"
Unknown command "joy_advaxisu"
Unknown command "joy_advaxisv"
Unknown command "joy_autoaimdampen"
Unknown command "joy_autoaimdampenrange"
Unknown command "joy_autosprint"
Unknown command "joy_axisbutton_threshold"
Unknown command "joy_circle_correct"
Unknown command "joy_diagonalpov"
Unknown command "joy_display_input"
Unknown command "joy_forwardsensitivity"
Unknown command "joy_forwardthreshold"
Unknown command "joy_inverty"
Unknown command "joy_invertx"
Unknown command "joy_lowend"
Unknown command "joy_lowmap"
Unknown command "joy_movement_stick"
Unknown command "joy_pitchsensitivity"
Unknown command "joy_pitchthreshold"
Unknown command "joy_response_look"
Unknown command "joy_response_move"
Unknown command "joy_sidesensitivity"
Unknown command "joy_sidethreshold"
Unknown command "joy_yawsensitivity"
Unknown command "joy_yawthreshold"
Unknown command "joyadvancedupdate"
Unknown command "joystick"
Unknown command "+jlook"
[PartyTeamMgr] Grace period started.
---- Host_NewGame ----
sv_pure_default set to: 1
trusted_keys.txt not present; pure server using only base trusted key list
Host_NewGame on map ministry
ConVarRef room_type doesn't point to an existing ConVar
Executing dedicated server config file
Executing 'ins-server.cfg' config file
Unknown command "sv_vote_kick_troll_min_ration"
Writing cfg/banned_user.cfg.
Writing cfg/banned_ip.cfg.
Server logging enabled.
Server logging data to file logs/L192_168_000_010_27015_201601210209_000.log
L 01/21/2016 - 02:09:52: Log file started (file "logs/L192_168_000_010_27015_201601210209_000.log") (game "/home/insurgency/serverfiles/insurgency") (version "6221")
Unknown command "sv_vote_kick_troll_min_ration"
Writing cfg/banned_user.cfg.
Writing cfg/banned_ip.cfg.
Server logging enabled.
L 01/21/2016 - 02:09:52: Log file closed
Server logging data to file logs/LMYIP_27015_201601210209_001.log
L 01/21/2016 - 02:09:52: Log file started (file "logs/LMYIP_27015_201601210209_001.log") (game "/home/insurgency/serverfiles/insurgency") (version "6221")
L 01/21/2016 - 02:09:52: server_cvar: "mp_maxrounds" "5"
L 01/21/2016 - 02:09:52: server_cvar: "mp_winlimit" "3"
L 01/21/2016 - 02:09:52: server_cvar: "mp_roundtime" "600"
L 01/21/2016 - 02:09:52: server_cvar: "mp_cp_capture_time" "30"
L 01/21/2016 - 02:09:52: server_cvar: "mp_cp_deteriorate_time" "0"
L 01/21/2016 - 02:09:52: server_cvar: "mp_spawnprotectontime" "10"
L 01/21/2016 - 02:09:52: server_cvar: "mp_supply_rate_losing_team_high" "0"
L 01/21/2016 - 02:09:52: server_cvar: "mp_supply_rate_losing_team_low" "0"
L 01/21/2016 - 02:09:52: server_cvar: "mp_supply_rate_winning_team_high" "0"
L 01/21/2016 - 02:09:52: server_cvar: "mp_supply_rate_winning_team_low" "0"
Loading theater file 'default' on server
L 01/21/2016 - 02:09:52: server_cvar: "sv_maxspeed" "1000.000000"
L 01/21/2016 - 02:09:52: server_cvar: "sv_stopspeed" "75.000000"
exec: couldn't exec skill1.cfg
ConVarRef sk_suitcharger doesn't point to an existing ConVar
PrecacheScriptSound 'Voice_Response_Ins_UnSupp.Lead_CheckFire' failed, no such sound script entry
PrecacheScriptSound 'Voice_Response_Ins_Supp.Lead_CheckFire' failed, no such sound script entry
PrecacheScriptSound 'Voice_Response_Sec_UnSupp.Lead_CheckFire' failed, no such sound script entry
PrecacheScriptSound 'Voice_Response_Sec_Supp.Lead_CheckFire' failed, no such sound script entry
PrecacheScriptSound 'Error' failed, no such sound script entry
PrecacheScriptSound 'bot.insurgent.openfire' failed, no such sound script entry
PrecacheScriptSound 'bot.insurgent.idle' failed, no such sound script entry
PrecacheScriptSound 'bot.insurgent.blinded' failed, no such sound script entry
PrecacheScriptSound 'bot.insurgent.investigateaggressive' failed, no such sound script entry
PrecacheScriptSound 'bot.security_lead.blinded' failed, no such sound script entry
PrecacheScriptSound 'bot.security_sub.blinded' failed, no such sound script entry
PrecacheScriptSound 'bot.security_lead.heardsomething' failed, no such sound script entry
PrecacheScriptSound 'bot.security_sub.heardsomething' failed, no such sound script entry
PrecacheScriptSound 'bot.security_lead.aggressiveinvestigation' failed, no such sound script entry
PrecacheScriptSound 'bot.security_sub.aggressiveinvestigation' failed, no such sound script entry
PrecacheScriptSound 'bot.security_lead.flashlightspotted' failed, no such sound script entry
PrecacheScriptSound 'bot.security_sub.flashlightspotted' failed, no such sound script entry
PrecacheScriptSound 'bot.security_lead.begininvestigate' failed, no such sound script entry
PrecacheScriptSound 'bot.security_sub.begininvestigate' failed, no such sound script entry
PrecacheScriptSound 'bot.security_lead.idle' failed, no such sound script entry
PrecacheScriptSound 'bot.security_sub.idle' failed, no such sound script entry
PrecacheScriptSound 'bot.security_lead.fireweapon' failed, no such sound script entry
PrecacheScriptSound 'bot.security_sub.fireweapon' failed, no such sound script entry
PrecacheScriptSound 'bot.security_lead.suppressenemy' failed, no such sound script entry
PrecacheScriptSound 'bot.security_sub.suppressenemy' failed, no such sound script entry
PrecacheScriptSound 'bot.security_lead.targetdown' failed, no such sound script entry
PrecacheScriptSound 'bot.security_sub.targetdown' failed, no such sound script entry
PrecacheScriptSound 'bot.security_lead.incominggrenade' failed, no such sound script entry
PrecacheScriptSound 'bot.security_sub.incominggrenade' failed, no such sound script entry
PrecacheScriptSound 'bot.insurgent_lead.incominggrenade' failed, no such sound script entry
PrecacheScriptSound 'bot.insurgent_sub.incominggrenade' failed, no such sound script entry
==== calling mapspawn.nut
Direct precache of Player.Security_StartFirefight_Game
Direct precache of Player.Security_StartFirefight_Round
Direct precache of Player.Insurgent_StartFirefight_Game
Direct precache of Player.Insurgent_StartFirefight_Round
Direct precache of Player.Security_TakenPoint_0
Direct precache of Player.Security_LostPoint_0
Direct precache of Player.Security_Contested_0
Direct precache of Player.Security_UnderAttack_0
Direct precache of Player.Security_Attacking_0
Direct precache of Player.Security_TakenPoint_1
Direct precache of Player.Security_LostPoint_1
Direct precache of Player.Security_Contested_1
Direct precache of Player.Security_UnderAttack_1
Direct precache of Player.Security_Attacking_1
Direct precache of Player.Security_TakenPoint_2
Direct precache of Player.Security_LostPoint_2
Direct precache of Player.Security_Contested_2
Direct precache of Player.Security_UnderAttack_2
Direct precache of Player.Security_Attacking_2
Direct precache of Player.Insurgent_TakenPoint_0
Direct precache of Player.Insurgent_LostPoint_0
Direct precache of Player.Insurgent_Contested_0
Direct precache of Player.Insurgent_UnderAttack_0
Direct precache of Player.Insurgent_Attacking_0
Direct precache of Player.Insurgent_TakenPoint_1
Direct precache of Player.Insurgent_LostPoint_1
Direct precache of Player.Insurgent_Contested_1
Direct precache of Player.Insurgent_UnderAttack_1
Direct precache of Player.Insurgent_Attacking_1
Direct precache of Player.Insurgent_TakenPoint_2
Direct precache of Player.Insurgent_LostPoint_2
Direct precache of Player.Insurgent_Contested_2
Direct precache of Player.Insurgent_UnderAttack_2
Direct precache of Player.Insurgent_Attacking_2
Direct precache of Player.Security_AreaClear_0
Direct precache of Player.Insurgent_AreaClear_0
Direct precache of Player.Security_AreaClear_1
Direct precache of Player.Insurgent_AreaClear_1
Direct precache of Player.Security_AreaClear_2
Direct precache of Player.Insurgent_AreaClear_2
Gamerules: entering state 'GR_STATE_PREGAME'
Direct precache of WeaponCache.Explode
Direct precache of WeaponCache.Explode
Direct precache of WeaponCache.Explode
Direct precache of WeaponCache.Explode
Direct precache of WeaponCache.Explode
Direct precache of WeaponCache.Explode
Direct precache of WeaponCache.Explode
Direct precache of WeaponCache.Explode
Direct precache of WeaponCache.Explode
Direct precache of WeaponCache.Explode
Direct precache of WeaponCache.Explode
Direct precache of WeaponCache.Explode
Loaded 3 control points
[PartyTeamMgr] Grace period started.
Failed finding CP area for 0!
Failed finding CP area for 1!
Failed finding CP area for 2!
Initializing Steam libraries for LAN server
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 222880
FillInMachineIDInfo took a total of 0 milliseconds
Logging into anonymous gameserver account.
L 01/21/2016 - 02:09:54: server_cvar: "sv_tags" "nospawnprotection"
L 01/21/2016 - 02:09:54: server_cvar: "sv_tags" "nospawnprotection"
Assigned anonymous gameserver Steam ID [A:1:2665018376(6298)].
VAC secure mode disabled.
CCrashHandler - Attached and ready. (in-process)
cat: cat: No such file or directory
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
#
#Console initialized.
#Loaded 2725 VPK file hashes from /home/insurgency/serverfiles/insurgency/insurgency_materials.vpk for pure server operation.
#Loaded 2725 VPK file hashes from /home/insurgency/serverfiles/insurgency/insurgency_materials.vpk for pure server operation.
#Loaded 19 VPK file hashes from /home/insurgency/serverfiles/insurgency/insurgency_misc.vpk for pure server operation.
#Loaded 19 VPK file hashes from /home/insurgency/serverfiles/insurgency/insurgency_misc.vpk for pure server operation.
#Loaded 272 VPK file hashes from /home/insurgency/serverfiles/insurgency/insurgency_models.vpk for pure server operation.
#Loaded 272 VPK file hashes from /home/insurgency/serverfiles/insurgency/insurgency_models.vpk for pure server operation.
#Loaded 2 VPK file hashes from /home/insurgency/serverfiles/insurgency/insurgency_particles.vpk for pure server operation.
#Loaded 2 VPK file hashes from /home/insurgency/serverfiles/insurgency/insurgency_particles.vpk for pure server operation.
#Loaded 1483 VPK file hashes from /home/insurgency/serverfiles/insurgency/insurgency_sound.vpk for pure server operation.
#Loaded 1483 VPK file hashes from /home/insurgency/serverfiles/insurgency/insurgency_sound.vpk for pure server operation.
#Game.dll loaded for "Insurgency"
#CGameEventManager::AddListener: event 'server_pre_shutdown' unknown.
#CGameEventManager::AddListener: event 'game_newmap' unknown.
#CGameEventManager::AddListener: event 'round_start' unknown.
#CGameEventManager::AddListener: event 'round_end' unknown.
mode MP, dedicated Yes, ports 27015 SV / 27005 CL
Server is hibernating
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
Parent cvar in server.dll not allowed (ins_bot_arousal_suppression_falloff)
maxplayers set to 16
Unable to remove /home/insurgency/serverfiles/state_crash.txt!
Unable to remove /home/insurgency/serverfiles/state_crash.txt!
Unknown command "joy_name"
Unknown command "joy_advanced"
Unknown command "joy_accelmax"
Unknown command "joy_accelscale"
Unknown command "joy_advaxisx"
Unknown command "joy_advaxisy"
Unknown command "joy_advaxisz"
Unknown command "joy_advaxisr"
Unknown command "joy_advaxisu"
Unknown command "joy_advaxisv"
Unknown command "joy_autoaimdampen"
Unknown command "joy_autoaimdampenrange"
Unknown command "joy_autosprint"
Unknown command "joy_axisbutton_threshold"
Unknown command "joy_circle_correct"
Unknown command "joy_diagonalpov"
Unknown command "joy_display_input"
Unknown command "joy_forwardsensitivity"
Unknown command "joy_forwardthreshold"
Unknown command "joy_inverty"
Unknown command "joy_invertx"
Unknown command "joy_lowend"
Unknown command "joy_lowmap"
Unknown command "joy_movement_stick"
Unknown command "joy_pitchsensitivity"
Unknown command "joy_pitchthreshold"
Unknown command "joy_response_look"
Unknown command "joy_response_move"
Unknown command "joy_sidesensitivity"
Unknown command "joy_sidethreshold"
Unknown command "joy_yawsensitivity"
Unknown command "joy_yawthreshold"
Unknown command "joyadvancedupdate"
Unknown command "joystick"
Unknown command "+jlook"
[PartyTeamMgr] Grace period started.
---- Host_NewGame ----
sv_pure_default set to: 1
trusted_keys.txt not present; pure server using only base trusted key list
Host_NewGame on map ministry
ConVarRef room_type doesn't point to an existing ConVar
Executing dedicated server config file
Executing 'ins-server.cfg' config file
Unknown command "sv_vote_kick_troll_min_ration"
Writing cfg/banned_user.cfg.
Writing cfg/banned_ip.cfg.
Server logging enabled.
Server logging data to file logs/LMYIP_27015_201601210209_000.log
L 01/21/2016 - 02:09:52: Log file started (file "logs/LMYIP_27015_201601210209_000.log") (game "/home/insurgency/serverfiles/insurgency") (version "6221")
Unknown command "sv_vote_kick_troll_min_ration"
Writing cfg/banned_user.cfg.
Writing cfg/banned_ip.cfg.
Server logging enabled.
L 01/21/2016 - 02:09:52: Log file closed
Server logging data to file logs/LMYIP_27015_201601210209_001.log
L 01/21/2016 - 02:09:52: Log file started (file "logs/L1MYIP_27015_201601210209_001.log") (game "/home/insurgency/serverfiles/insurgency") (version "6221")
L 01/21/2016 - 02:09:52: server_cvar: "mp_maxrounds" "5"
L 01/21/2016 - 02:09:52: server_cvar: "mp_winlimit" "3"
L 01/21/2016 - 02:09:52: server_cvar: "mp_roundtime" "600"
L 01/21/2016 - 02:09:52: server_cvar: "mp_cp_capture_time" "30"
L 01/21/2016 - 02:09:52: server_cvar: "mp_cp_deteriorate_time" "0"
L 01/21/2016 - 02:09:52: server_cvar: "mp_spawnprotectontime" "10"
L 01/21/2016 - 02:09:52: server_cvar: "mp_supply_rate_losing_team_high" "0"
L 01/21/2016 - 02:09:52: server_cvar: "mp_supply_rate_losing_team_low" "0"
L 01/21/2016 - 02:09:52: server_cvar: "mp_supply_rate_winning_team_high" "0"
L 01/21/2016 - 02:09:52: server_cvar: "mp_supply_rate_winning_team_low" "0"
Loading theater file 'default' on server
L 01/21/2016 - 02:09:52: server_cvar: "sv_maxspeed" "1000.000000"
L 01/21/2016 - 02:09:52: server_cvar: "sv_stopspeed" "75.000000"
exec: couldn't exec skill1.cfg
ConVarRef sk_suitcharger doesn't point to an existing ConVar
PrecacheScriptSound 'Voice_Response_Ins_UnSupp.Lead_CheckFire' failed, no such sound script entry
PrecacheScriptSound 'Voice_Response_Ins_Supp.Lead_CheckFire' failed, no such sound script entry
PrecacheScriptSound 'Voice_Response_Sec_UnSupp.Lead_CheckFire' failed, no such sound script entry
PrecacheScriptSound 'Voice_Response_Sec_Supp.Lead_CheckFire' failed, no such sound script entry
PrecacheScriptSound 'Error' failed, no such sound script entry
PrecacheScriptSound 'bot.insurgent.openfire' failed, no such sound script entry
PrecacheScriptSound 'bot.insurgent.idle' failed, no such sound script entry
PrecacheScriptSound 'bot.insurgent.blinded' failed, no such sound script entry
PrecacheScriptSound 'bot.insurgent.investigateaggressive' failed, no such sound script entry
PrecacheScriptSound 'bot.security_lead.blinded' failed, no such sound script entry
PrecacheScriptSound 'bot.security_sub.blinded' failed, no such sound script entry
PrecacheScriptSound 'bot.security_lead.heardsomething' failed, no such sound script entry
PrecacheScriptSound 'bot.security_sub.heardsomething' failed, no such sound script entry
PrecacheScriptSound 'bot.security_lead.aggressiveinvestigation' failed, no such sound script entry
PrecacheScriptSound 'bot.security_sub.aggressiveinvestigation' failed, no such sound script entry
PrecacheScriptSound 'bot.security_lead.flashlightspotted' failed, no such sound script entry
PrecacheScriptSound 'bot.security_sub.flashlightspotted' failed, no such sound script entry
PrecacheScriptSound 'bot.security_lead.begininvestigate' failed, no such sound script entry
PrecacheScriptSound 'bot.security_sub.begininvestigate' failed, no such sound script entry
PrecacheScriptSound 'bot.security_lead.idle' failed, no such sound script entry
PrecacheScriptSound 'bot.security_sub.idle' failed, no such sound script entry
PrecacheScriptSound 'bot.security_lead.fireweapon' failed, no such sound script entry
PrecacheScriptSound 'bot.security_sub.fireweapon' failed, no such sound script entry
PrecacheScriptSound 'bot.security_lead.suppressenemy' failed, no such sound script entry
PrecacheScriptSound 'bot.security_sub.suppressenemy' failed, no such sound script entry
PrecacheScriptSound 'bot.security_lead.targetdown' failed, no such sound script entry
PrecacheScriptSound 'bot.security_sub.targetdown' failed, no such sound script entry
PrecacheScriptSound 'bot.security_lead.incominggrenade' failed, no such sound script entry
PrecacheScriptSound 'bot.security_sub.incominggrenade' failed, no such sound script entry
PrecacheScriptSound 'bot.insurgent_lead.incominggrenade' failed, no such sound script entry
PrecacheScriptSound 'bot.insurgent_sub.incominggrenade' failed, no such sound script entry
==== calling mapspawn.nut
Direct precache of Player.Security_StartFirefight_Game
Direct precache of Player.Security_StartFirefight_Round
Direct precache of Player.Insurgent_StartFirefight_Game
Direct precache of Player.Insurgent_StartFirefight_Round
Direct precache of Player.Security_TakenPoint_0
Direct precache of Player.Security_LostPoint_0
Direct precache of Player.Security_Contested_0
Direct precache of Player.Security_UnderAttack_0
Direct precache of Player.Security_Attacking_0
Direct precache of Player.Security_TakenPoint_1
Direct precache of Player.Security_LostPoint_1
Direct precache of Player.Security_Contested_1
Direct precache of Player.Security_UnderAttack_1
Direct precache of Player.Security_Attacking_1
Direct precache of Player.Security_TakenPoint_2
Direct precache of Player.Security_LostPoint_2
Direct precache of Player.Security_Contested_2
Direct precache of Player.Security_UnderAttack_2
Direct precache of Player.Security_Attacking_2
Direct precache of Player.Insurgent_TakenPoint_0
Direct precache of Player.Insurgent_LostPoint_0
Direct precache of Player.Insurgent_Contested_0
Direct precache of Player.Insurgent_UnderAttack_0
Direct precache of Player.Insurgent_Attacking_0
Direct precache of Player.Insurgent_TakenPoint_1
Direct precache of Player.Insurgent_LostPoint_1
Direct precache of Player.Insurgent_Contested_1
Direct precache of Player.Insurgent_UnderAttack_1
Direct precache of Player.Insurgent_Attacking_1
Direct precache of Player.Insurgent_TakenPoint_2
Direct precache of Player.Insurgent_LostPoint_2
Direct precache of Player.Insurgent_Contested_2
Direct precache of Player.Insurgent_UnderAttack_2
Direct precache of Player.Insurgent_Attacking_2
Direct precache of Player.Security_AreaClear_0
Direct precache of Player.Insurgent_AreaClear_0
Direct precache of Player.Security_AreaClear_1
Direct precache of Player.Insurgent_AreaClear_1
Direct precache of Player.Security_AreaClear_2
Direct precache of Player.Insurgent_AreaClear_2
Gamerules: entering state 'GR_STATE_PREGAME'
Direct precache of WeaponCache.Explode
Direct precache of WeaponCache.Explode
Direct precache of WeaponCache.Explode
Direct precache of WeaponCache.Explode
Direct precache of WeaponCache.Explode
Direct precache of WeaponCache.Explode
Direct precache of WeaponCache.Explode
Direct precache of WeaponCache.Explode
Direct precache of WeaponCache.Explode
Direct precache of WeaponCache.Explode
Direct precache of WeaponCache.Explode
Direct precache of WeaponCache.Explode
Loaded 3 control points
[PartyTeamMgr] Grace period started.
Failed finding CP area for 0!
Failed finding CP area for 1!
Failed finding CP area for 2!
Initializing Steam libraries for LAN server
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 222880
FillInMachineIDInfo took a total of 0 milliseconds
Logging into anonymous gameserver account.
L 01/21/2016 - 02:09:54: server_cvar: "sv_tags" "nospawnprotection"
L 01/21/2016 - 02:09:54: server_cvar: "sv_tags" "nospawnprotection"
Assigned anonymous gameserver Steam ID [A:1:2665018376(6298)].
VAC secure mode disabled.
CCrashHandler - Attached and ready. (in-process)

**Comment by UltimateByte** [comment]
Am i right to say you properly configured your LAN IP address, and are trying to browse for local servers, and that you have no firewall blocking it even from LAN ?
Also, can you try a command to connect to the server ?
Typically the gameconsole command should be something like : connect 192.168.1.2:27015

**Comment by jaredballou** [comment]
Yeah see if you can connect via console. The server browser is notoriously awful, and even on LAN I believe the server has to check in with the SteamWorks API, and get picked up by the master list. There is not really any thought given to LAN servers with Insurgency, so it might just be a bug. I'll set up a local server on my home network tonight and see what I get.

**Comment by bisam** [comment]
Yes the Machine is properly configured in LAN ans also acting as a file and webserver, so network shouldnt be an issue.
I will try the console commands thank you!

**Comment by UltimateByte** [comment]
You're welcome, keep us informed :)

**Comment by bisam** [comment]
yei, that simply worked :) thanks a lot
