### ISSUE TITLE
CS:S Metamod / Sourcemod safe install

### ISSUE THREAD

**Issue by MaadMax** [dgibbs64/linuxgsm#641]
Is there a safe way to install sourcemod (so metamod too) without doing it with a FTP client ? Because I tried a lot of times to do it but it never works so I would like to know if at least one of you guys has successfully done it on its CSS server (or hl2 game server). I guess it could be an interesting feature of the script btw. I think I'm doing it right but maybe I've missed something...

**Comment by AzaZPPL** [comment]
What doesn't work after uploading them from ftp?

**Comment by MaadMax** [comment]
When i'm doing the recommended command 'meta list' in the server console I've nothing, so I guess the server don't recognize the plugins. And I don't know how to do it because I tried a lot of things but I don't want to break my server so I prefer ask you.

**Comment by UltimateByte** [comment]
You probably put it in the wrong folder, or your FTP transfer failed because of file right issues, or used the windows version on a linux server, but it's definately a non script issue.
Also remember that metamod works with sourcemod.
I can only provide you this doc, as i didn't install it since a while, i can't remember how i did : https://wiki.alliedmods.net/Installing_Metamod:Source

**Comment by MaadMax** [comment]
Yes you're right, and the link you provide is the one I followed. I followed all the steps (all the files in addons folder and so on...) but I never succeeded to make my server list the plugins. And that's why I asked if there is a command in the script or anything else to install game plugins. I'll try it again and I hope it'll work this time ;)

**Comment by UltimateByte** [comment]
A command to add it will probably be added in the future.
https://github.com/dgibbs64/linuxgsm/issues/631
But for now there is not.
Also make sure that you didn't rename folders with uppercase characters and that you're using the latest metamod and sourcemod.
PS : I think those listings commands works only through rcon, but i never tried them on the direct server console. So try them with the ingame console using rcon.

**Comment by AzaZPPL** [comment]
They also work in-game. When uploading try uploading as binary.

**Comment by UltimateByte** [comment]
Isn't it what i said ? When i said rcon i meant using ingame console.
Maybe you can run them directly without login after setting admin right, but you need to set them anyway first.

**Comment by AzaZPPL** [comment]
Oh my bad I meant server console.

**Comment by jaredballou** [comment]
My fork has a 'sourcemod' function that downloads the latest MetaMos and SourceMod and install them in a game server systemdir. Basically just get the two packages and untar them in the serverfiles/csgo directory, they will create addons/metamod and addons/sourcemod. My lgsm fork is radically different than the upstream right now, but you can look at functions/install_sourcemod.sh to see how I do it and just use the same commands. When that's done, run
meta
And you should see the menu. Then list your mods, see if sourcemod is listed. Running
sm
Should show that menu. Let is know what you see.

**Comment by MaadMax** [comment]
@UltimateByte : it'll be so awesome to add it to the main script! 

@jaredballou : I'll take a look at it today and let you know if it works for me too or not (i hope it will! ;) )

**Comment by UltimateByte** [comment]
Related https://github.com/dgibbs64/linuxgsm/issues/631
I'll see if i can start working on this today.
I'm working at home right now, but my job consists in waiting half of the time.. So i should try doing this instead of waiting ! :p

**Comment by MaadMax** [comment]
It will be awesome! I have 3 different dedicated servers so if you need to test the script before don't hesitate to ask me! Haha you're lucky! I think I'll like your job ! :) Yeah that's a good idea if you have a lot of time ;) I always play with colleagues at my agency for the lunch pause so I could test it today too ! :p

**Comment by UltimateByte** [comment]
No worries about that, i'll test it myself, and Daniel will probably test again before merging.
But i can give you the test repo as soon as i think it's pretty much working, if you're in a hurry to try it before it's released !

**Comment by MaadMax** [comment]
Ok that's perfect! Yes we can do this! Thanks a lot! :)

**Comment by UltimateByte** [comment]
Can we close this and use the other issue instead ? #631

**Comment by MaadMax** [comment]
Yes I'll close the issue! Thanks everybody btw!
