### ISSUE TITLE
hope we have webpanel management feature too

### ISSUE THREAD

**Issue by braak0405** [dgibbs64/linuxgsm#642]
First, huge thanks to developer I managed all of my server one by one with many commands but not any more!

I'm running almost 70+ allied servers in asia and when I see all of that terminal makes me sick....
can you make simple webpanel for us? not only for me someone probably needed too!
I'm not good with linux but since sedirector got freeze issue I moved on this it really great
I'm not sure you accept this kind of request but hope you consider about this!

**Comment by UltimateByte** [comment]
Yeah, we've been thinking about that for a while now.
70+ servers, gosh !

For now, we're thinking of a way to allow the implementation of such a thing. The code would need to be redesigned i guess. Would probably go along with a move to python, and be a module for LGSM. But for now we're only trying to think about this well before starting working on it.

JimTR made something similar to what you're asking already btw.
https://github.com/dgibbs64/linuxgsm/issues/608

**Comment by braak0405** [comment]
haha I'm not own 70+@ servers I'm just running 23 servers and other servers are allied with my server lol
thanks for quick and clean answer Mr.handsome from paris bro!!

**Comment by UltimateByte** [comment]
Lol, thanks ! 
23 servers is already pretty decent, i "only" got something like 16... ^^
BTW, i think i'll keep this open to remember working on it some day. Even though it's probably not me who is going to work on it considering the fact that i don't know PHP yet... :o))

**Comment by dgibbs64** [comment]
No plans currently. This is a big maybe. A web panel would have to be done by a dedicated developer. who knows web applications (not me). I would rather focus on LGSM being the best at what it does best. A webpanel that is not rubbish would take a long time.

**Comment by UltimateByte** [comment]
I'm pretty confident it wouldn't be that hard to make it for somebody who knows php well, considering how functions are well separated. The biggest thing to do would probably to seek through the code to find all prompts and make them disappear, then maybe, i say maybe, add a few functions to allow the webpanel to be managed better. The script and the PHP module would then be totally independant afterwards. I actually have a good idea of how it could work, thanks to JimTR.

**Comment by faflfama** [comment]
What happened to the Rokket Interface [https://github.com/dgibbs64/rokket](url), besides it`s not working atm? Couldnt that be used as a base?

**Comment by dgibbs64** [comment]
Unfortunately the developer decided not to continue with it. Its very incomplete and doesnt work well currently. I do not have the skill set or time to develop it myself however any web developer is welcome to have ago. But is is a big project.

The most complete free web panel I have tested so far is BGpanel but even that does not support near as many servers as LGSM and didn't appear to work well with multiple instances. However BGpanel is relatively simple.

**Comment by JimTR** [comment]
I have coded something that has basic functions as a web app .... but there are problems with a user having a hosted space where PHP directives are a bit restrictive ... however I could host some web interfaces (using my code) as long as the web space is on my server. Problems are some servers reject curl or wget requests !
