### ISSUE TITLE
Version number formatting > yy/mm/dd

### ISSUE THREAD

**Issue by UltimateByte** [dgibbs64/linuxgsm#644]
@dgibbs64 Little tweak and low priority : Thought instead of formatting version numbers dd/mm/yy, could be yy/mm/dd , that way the number would be incremental, which would make more sense.

If you think it sucks, just close, otherwise, please assign yourself or me to it.

**Comment by dgibbs64** [comment]
Never thought about it. There is no requirement to do this yet as the version numbers are only for reference currently so doesn't currently matter. However if required in the future we can change it.
