### ISSUE TITLE
integration with serverdensity.io

### ISSUE THREAD

**Issue by vem882** [dgibbs64/linuxgsm#647]
Monitoring plugin for serverdensity.
its will be cool, if you can create plugin for sd-agent for monitoring.

**Comment by UltimateByte** [comment]
Can you be a little more specific ? I don't even get what you're talking about.

**Comment by UltimateByte** [comment]
Wait, you're talking about that scam ? https://www.serverdensity.com/pricing/

**Comment by UltimateByte** [comment]
@dgibbs64 Did you hear about that ? I personally think it could be great... if it was free.
