### ISSUE TITLE
Arma 3 install "does not work

### ISSUE THREAD

**Issue by paulvilla** [dgibbs64/linuxgsm#648]
I followed the installation steps that are very simple and not working.
If i need to configure more files, add you it to the tutorial

PD: SteamCMD if the installation has worked for me

**Comment by UltimateByte** [comment]
I'm sorry but i don't get what you're trying to say

**Comment by UltimateByte** [comment]
Ok i get it.
So first what us working and what is not ? Are you able to start the server and see the console ?

**Comment by paulvilla** [comment]
I'm sorry, me and my server works.
The problem I have is:

SteamAPI initialization failed. Steam features wont's be accessible!

**Comment by UltimateByte** [comment]
Any addon installed ? Check that all your files and folders are lowercase.

And what is your distro ?

**Comment by paulvilla** [comment]
I have installed a3wasteland, but i check newly installed and do not work.
I have CentOS 7 server

PD: all folders are in lower case

**Comment by UltimateByte** [comment]
Anyways, one should never install a mod before getting a blank server up and running.
x86 or x64 ?
Do you have all the required packages ? Could be a missing x86 lib such as one of these : glibc.i686 libstdc++ libstdc++.i686 

 yum install tmux mailx postfix curl glibc.i686 libstdc++ libstdc++.i686

**Comment by paulvilla** [comment]
I followed all the steps of the web and api not working.
This step is one of the first.

**Comment by UltimateByte** [comment]
Will i have to ask all of my question twice ?

x86 or x64 ?

**Comment by paulvilla** [comment]
x64

**Comment by UltimateByte** [comment]
Can you actually screen your console after running the server ? Provide some logs or something ? Some actual relevant materials that would help...

**Comment by UltimateByte** [comment]
Cosling this, re-open if needed.
