### ISSUE TITLE
dpkg --add-architecture i386 for ubuntu ?

### ISSUE THREAD

**Issue by UltimateByte** [dgibbs64/linuxgsm#654]
As seen here with ubuntu 14.04, it may become necessary to add it as a requirement.
(watch out if you come here from email, i updated the link) http://steamcommunity.com/groups/linuxgsm/discussions/0/458606877323400687/

**Comment by dgibbs64** [comment]
It shouldn't be needed I run 14.04 as my main test environment and never
needed to add the command

**Comment by UltimateByte** [comment]
Well, this Steam issue is weird then.

**Comment by UltimateByte** [comment]
http://steamcommunity.com/groups/linuxgsm/discussions/0/359547436750104401/

For the record, somebody else had to dpkg --add-architecture i386
