### ISSUE TITLE
lgsm not working with cronjob

### ISSUE THREAD

**Issue by PhilPhonic** [dgibbs64/linuxgsm#655]
Hi,
I'm having some issues with lgsm when using cronjobs.
This is what I'm trying:
> 0 5 * * * ~/insserver update

This is what it returns:
> /home/inssserver/insserver: line 144: `core_functions.sh': not a valid identifier

If I run this task directly on my shell, it works just fine.

Any ideas?

**Comment by UltimateByte** [comment]
Hi,

Did you try ./insserver update-functions ?

**Comment by PhilPhonic** [comment]
Yep. Doesnt solve the problem

**Comment by UltimateByte** [comment]
What distro ?

PS : Your command should look like this
`0 5 * * *  /home/user/insserver update > /dev/null 2>&1`

**Comment by PhilPhonic** [comment]
Debian Jessie.
I just saw, command works with another user on the Same server.

**Comment by UltimateByte** [comment]
So did you get it working ?

**Comment by PhilPhonic** [comment]
No. The problem still exists.
I just saw that it works on another insurgency server on the same host

**Comment by UltimateByte** [comment]
With the command i gave you ? Only 1 server per user right ? With the right address with no mistake with user spelling ?

Maybe try a root cronjob ?

**Comment by PhilPhonic** [comment]
user1:
name: insserver
crontab -e
> 0 5 * * * ~/insserver update > /dev/null 2>&1

does not work

crontab -e
> 0 5 * * *  /home/insserver/insserver update > /dev/null 2>&1

also does not work

user2:
name: insserver2
crontab -e
> 0 5 * * * ~/insserver update > /dev/null 2>&1

works

**Comment by UltimateByte** [comment]
Did you copy the exact same command from each crontab ?
In the original syntax, there is 2 spaces after the last " * ", but i don't think it's relevant.
Couldn't this be an issue with the cronjob mode you choosed the first time you runned crontab -e in your first user ?

Try to run a root crontjob which will look like this : 
0 5 * * *  su - insserver -c '/home/insserver/insserver update' > /dev/null 2>&1

**Comment by PhilPhonic** [comment]
The root cronjob works.
I also tried deleting all cronjobs for this user (insserver) and re-create them. Didn't help.

**Comment by UltimateByte** [comment]
What shows 
'crontab -l'
After adding a cronjob in your first user ?
Does it show your cronjob ?

**Comment by PhilPhonic** [comment]
yes.
> ~$ crontab -l
0 5 * * * ~/insserver update > /dev/null 2>&1
~$

**Comment by UltimateByte** [comment]
What distro ? 
Maybe try adding some simple quotes between the command ?

**Comment by PhilPhonic** [comment]
Debian Jessie.
Where to put the quotes?

**Comment by UltimateByte** [comment]
I edited my previous message

**Comment by PhilPhonic** [comment]
That leads to:
> /bin/sh: ~/insserver update: No such file or directory

**Comment by UltimateByte** [comment]
Replace ~ by /home/insserver

**Comment by PhilPhonic** [comment]
> /bin/sh: /home/insserver/insserver update: No such file or directory

**Comment by PhilPhonic** [comment]
ps: I always have to remove "> /dev/null 2>&1" to see the output..

**Comment by UltimateByte** [comment]
Crap. Well, i tried.
I see no reason why it would run as root, and not as the user.
BTW, if you got multiple servers, i advise you to manage cronjobs as root, as it's way easier to manage all of them at once.

**Comment by UltimateByte** [comment]
"ps: I always have to remove "> /dev/null 2>&1" to see the output.."
Yeah, because this is meant to remove the output so the command works with no issue. ^^

**Comment by PhilPhonic** [comment]
I know. Just wanted to make clear what I am doing ;-)

**Comment by PhilPhonic** [comment]
I think it's user related issue, because the cronjob on the other user works fine.
I'll migrate the server to another user and try again.

**Comment by UltimateByte** [comment]
ok :)

**Comment by UltimateByte** [comment]
Don't forget to make a 
`chown -R newuser:newuser *`

**Comment by PhilPhonic** [comment]
Migrating the server to another user worked. Cronjobs work fine on this new user.
I have no idea what was wrong with the other user.
