### ISSUE TITLE
Can't update (CSGO)

### ISSUE THREAD

**Issue by alduccino** [dgibbs64/linuxgsm#657]
Hi,
when I try to update my server everything i fine util I have to add the Two-factor code from the  Steam Guard Mobile Authenticator app:
Once the code is entered nothing happens.

Any idea how to fix this ?

I'm using centos 6.7.

**Comment by UltimateByte** [comment]
Hello there !

Why would you use your steam account for CSGO which don't need it ?

PS 1) https://github.com/dgibbs64/linuxgsm/issues/579
PS 2) Also run a validate after an update if you got issues, can help.

**Comment by alduccino** [comment]
I thought we had to with their new policy. But has suggested i removed it and it works fine now.

Many thanks.

**Comment by UltimateByte** [comment]
Nope, it's true that as it is into the script "just in case"  it becomes needed one day, you can easilly be fooled. But gladly, csgo, as many valve games, work as anonymous ! 

You're welcome ! Have a nice one :)

**Comment by dgibbs64** [comment]
You where probably thinking of this https://github.com/dgibbs64/linuxgsm/wiki/Game-Server-Login-Token.
