### ISSUE TITLE
fetching functions/core_functions.sh...FAIL

### ISSUE THREAD

**Issue by Sirecia** [dgibbs64/linuxgsm#658]
fetching functions/core_functions.sh...FAIL

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:06 --:--:--     0curl: (7) Failed to connect to raw.githubusercontent.com port 443: Opkoblingen overskred tidsgrænsen
https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/functions/core_functions.sh

**Comment by UltimateByte** [comment]
Wow, this must be the most detailed issue ever... I'm amazed how your description is able to give us clues about your issue to help you.

1) Have CURL installed
2) If your installation is old, run the "update-functions" command.
3) If it doesn't solve your issue, provide some information.

**Comment by UltimateByte** [comment]
Also : Make sure it's not blocked by a firewall on port 443.

**Comment by jaredballou** [comment]
GitHub was offline 2 days ago. Try again now.
Todo: Add a sanity check to the downloader to validate that the file fetched matches the hash from GitHub, or at least that it's not blank.

**Comment by UltimateByte** [comment]
Well, let's say he figured it out, and that is 100% a non script issue... Re-open if needed.
