### ISSUE TITLE
Start on Boot with Ubuntu (15.10x64)

### ISSUE THREAD

**Issue by faflfama** [dgibbs64/linuxgsm#662]
Hi all,
Like in your "Usage-wiki (https://github.com/dgibbs64/linuxgsm/wiki/Usage)" I used the rc.local to start my servers on Boot. But since Ubuntu 15.10 it didnt work anymore, it started the first server I put in rc.local, but not the other ones (yes I tried to manually enable rc.local again, after they changed to systemd). For that I created a service which then worked. I know it has nothing to do with the script, but since its written down in the wiki I thought it would be nice to inform.

~Flam

[gameserver.txt](https://github.com/dgibbs64/linuxgsm/files/111122/gameserver.txt)
[gameserver_start.txt](https://github.com/dgibbs64/linuxgsm/files/111123/gameserver_start.txt)

**Comment by jaredballou** [comment]
I just use
~/insserver monitor
in my crontab every 5 minutes. Starts at boot, restarts on crash, from one place.

**Comment by UltimateByte** [comment]
Same. As long as you didn't stop the game server manually (so the lockfile still exists).

**Comment by faflfama** [comment]
I know there are functions like monitor, but since it written down in the usage wiki just wanted to point it out. And Just reading the monitor part looks like it only starts the server when it crashes.

**Comment by UltimateByte** [comment]
Updated the wiki. I really advise using the monitor, as when you shutdown a game server, you usually don't want it to boot again after a server reboot. And people are mostly gonna use the monitor function anyway so...

**Comment by faflfama** [comment]
Well I will defenitly look at it now, the version of the scripts I had didnt have the monitor function (or at least I would have to download it manually). But will get the new ones and try it out.

**Comment by UltimateByte** [comment]
LGSM has the monitor function for a while. Consider upgrading your main script, and functions !
After that, you'll be able to run ./gameserver update-functions to get latest updates. :)

**Comment by faflfama** [comment]
Yep, thats what I meant ;) but thanks for also pointing out that Update-function :)

**Comment by UltimateByte** [comment]
You're welcome. I'm adding stuff to the wiki right now, i'll add something about the script-update, which seems very useful to me.

**Comment by UltimateByte** [comment]
Wiki updated a lot, should be clear now.
See https://github.com/dgibbs64/linuxgsm/wiki/Usage#running-on-boot and https://github.com/dgibbs64/linuxgsm/wiki/Boot-Startup
