### ISSUE TITLE
Server wont start - Ubuntu 14.04 (VPS\vultr).

### ISSUE THREAD

**Issue by spot88** [dgibbs64/linuxgsm#664]
[ INFO ] Starting csgo-server: Applying steamclient.so general fix: Counter Strike: Global Offensivecp: cannot stat ‘/home/csgoserver/steamcmd/linux32/steamclient.so’: No such file or directory
	[ FAIL ] Starting csgo-server: Applying steamclient.so general fix: Counter Strike: Global Offensive
	[ FAIL ] Starting csgo-server: Applying botprofile.db fix: Counter Strike: Global Offensive
	[ FAIL ] Starting csgo-server: Applying valve.rc fix: Counter Strike: Global Offensive
	[ INFO ] Update csgo-server: Forcing update to correct issue
	[  OK  ] Update csgo-server: Updating | Retake #1 | 128 Tick | [NL]
	./steamcmd.sh: line 29: /home/csgoserver/steamcmd/linux32/steamcmd: No such file or directory
	[ INFO ] Update csgo-server: Applying steamclient.so general fix: Counter Strike: Global Offensivecp: cannot stat ‘/home/csgoserver/steamcmd/linux32/steamclient.so’: No such file or directory
	[ FAIL ] Update csgo-server: Applying steamclient.so general fix: Counter Strike: Global Offensive
	[ FAIL ] Update csgo-server: Applying botprofile.db fix: Counter Strike: Global Offensive
	[ FAIL ] Update csgo-server: Applying valve.rc fix: Counter Strike: Global Offensive
	[  OK  ] Update csgo-server: Updating  | Retake #1 | 128 Tick | [NL]
	./steamcmd.sh: line 29: /home/csgoserver/steamcmd/linux32/steamcmd: No such file or directory
	[ INFO ] Update csgo-server: Applying steamclient.so general fix: Counter Strike: Global Offensivecp: cannot stat ‘/home/csgoserver/steamcmd/linux32/steamclient.so’: No such file or directory
	[ FAIL ] Update csgo-server: Applying steamclient.so general fix: Counter Strike: Global Offensive
	[ FAIL ] Update csgo-server: Applying botprofile.db fix: Counter Strike: Global Offensive
	[ FAIL ] Update csgo-server: Applying valve.rc fix: Counter Strike: Global Offensive
	[ .... ] Update csgo-server: Checking for update: SteamCMDgrep: : No such file or directory
	./steamcmd.sh: line 29: /home/csgoserver/steamcmd/linux32/steamcmd: No such file or directory
	[ FAIL ] Update csgo-server: Checking for update: SteamCMD: Not returning version info

**Comment by dgibbs64** [comment]
Missing Dependencies i think

**Comment by spot88** [comment]
Okay, thanks! Ill try a full reinstall.

**Comment by UltimateByte** [comment]
Installing missing dependencies would be enough.

**Comment by spot88** [comment]
Reinstall fixed it =)

**Comment by UltimateByte** [comment]
Great to know you got it working !
