### ISSUE TITLE
teamspeak 3

### ISSUE THREAD

**Issue by miso7711** [dgibbs64/linuxgsm#665]
Hello. Teamspeak 3 server not update version 3.0.11.4 to 3.0.12

**Comment by UltimateByte** [comment]
Confirmed.

**Comment by UltimateByte** [comment]
Is it possible that 30114 is detected as inferior to 3012 ?

**Comment by miso7711** [comment]
yes

**Comment by dgibbs64** [comment]
Teamspeak 3 updating has always been a pain becuase of there version numbering. I will figure out how to fix

**Comment by oalaro** [comment]
They changed alot of stuff for 3.0.12.  Downloadable name from linux-amd64 to linux_amd64. They also changed the name of the binary, so you have to have your startscript updated.

**Comment by dgibbs64** [comment]
:+1: Thanks Teamspeak

**Comment by dgibbs64** [comment]
Just looking at this. A right pain in the arse. If Teamspeaks version numbering was a normal number then it would be easy.

**Comment by UltimateByte** [comment]
://
That's the point to get incremental version numbers, no matter what !

**Comment by dgibbs64** [comment]
Fixed. Should hopefully never get this issue again...hopefully
https://github.com/dgibbs64/linuxgsm/commit/9258cc7146ee3711068603f0c51c1b730f7bd50a

**Comment by dgibbs64** [comment]
Still an issue im working on

**Comment by dgibbs64** [comment]
Thats better all working now :)
