### ISSUE TITLE
[bb2server] Needs GSLT support added

### ISSUE THREAD

**Issue by dgibbs64** [dgibbs64/linuxgsm#669]

**Comment by UltimateByte** [comment]
Lol, i just made a new branch to add it, and what do i see ?

https://github.com/dgibbs64/linuxgsm/blob/bb2-gslt/BrainBread2/bb2server#L34

So i don't get it :o))

**Comment by UltimateByte** [comment]
Note : Just make sure that for bb2server its set to optional and that bb2server will display this when installing.

**Comment by UltimateByte** [comment]
GSLT is said required only for cs go : 
https://github.com/dgibbs64/linuxgsm/blob/master/functions/install_gslt.sh#L31

But will be proposed for BB2 : https://github.com/dgibbs64/linuxgsm/blob/master/functions/command_install.sh#L33

This is the current behavior. @dgibbs64 is that enough ? Or do you wish to remove the prompt for GSLT for servers not requiring it ?

**Comment by dgibbs64** [comment]
works now? I think it can be closed
