### ISSUE TITLE
tf2 server wont't start normally but runs in debug

### ISSUE THREAD

**Issue by a5m0** [dgibbs64/linuxgsm#670]
ubuntu 14.04 in lxc container - runs great when started with debug but starting normally just says [ FAIL ] Starting tf2-server: Unable to start servername.

**Comment by UltimateByte** [comment]
What says the logs ? (console and scriptlogs).

**Comment by UltimateByte** [comment]
Do you have tmux installed ? Could be one of the thousands reasons possible for that issue.

**Comment by a5m0** [comment]
Tmux is/was installed.

These are my logs:

cat tf2-server-console.log 
Console logging disabled: Bug in tmux 1.8 breaks logging
http://gameservermanagers.com/tmux-upgrade
Currently installed: tmux 1.8


when run with regular start:
cat tf2-server-script.log 
Feb 02 16:26:14 tf2-server: Starting: Unable to start asmo_server

when run with debug:
cat tf2-server-script.log 
Feb 02 16:26:14 tf2-server: Starting: Unable to start asmo_server
Feb 02 16:26:46 tf2-server: Debug: Starting debug
Feb 02 16:26:46 tf2-server: Debug: Stopping any running servers
Feb 02 16:26:48 tf2-server: Stopping: asmo_server
Feb 02 16:26:49 tf2-server: Stopping: asmo_server is already stopped
Feb 02 16:26:51 tf2-server: Debug: Started debug

**Comment by UltimateByte** [comment]
https://github.com/dgibbs64/linuxgsm/wiki/Tmux

**Comment by a5m0** [comment]
thanks that got me a bit farther to error that was fixed by: usermod -G tty tf2server

but then a new error:

$ ./tf2server start
[ .... ] Starting tf2-server: asmo_vanillafailed to connect to server: No such file or directory
[ FAIL ] Starting tf2-server: Unable to start asmo_vanilla
[ FAIL ] Starting tf2-server: Unable to start asmo_vanilla: Tmux error:


Command
=================================
tmux new-session -d -s "tf2-server" "./srcds_run -game tf -strictportbind -ip xxxx -port 27015 +clientport 27005 +tv_port 27020 +map cp_badlands +sv_setsteamaccount xxxxx +servercfgfile tf2-server.cfg -maxplayers 16"

Error
=================================
sessions should be nested with care, unset $TMUX to force

Fix
=================================
No known fix currently. Please log an issue.

**Comment by UltimateByte** [comment]
sudo apt-get install -y tmux=2.0-1~ppa1~u

**Comment by a5m0** [comment]
Yes I had installed it from the ppa you listed on that link (apt-get install -y tmux=2.0-1~ppa1~t ) the version you listed above is not found

E: Version '2.0-1~ppa1~u' for 'tmux' was not found

# tmux -V
tmux 2.0

**Comment by UltimateByte** [comment]
Well, i don't know about that then, let's ask our local Gaben ! @dgibbs64 Any idea ?

**Comment by a5m0** [comment]
So this appears to be something to do with the fact that I was attached to the lxc container's tty terminal with lxc-attach. Once I ssh'd in, running start and monitor worked fine!
