### ISSUE TITLE
[ts3server] (SOLVED) Installation bug - download name changed

### ISSUE THREAD

**Issue by lnxprof** [dgibbs64/linuxgsm#672]
ts3server's tarball that it downloads changed the format of the extracted directory name.
Symptom:
Installation dies with
`copying to /home/ts3server/serverfiles...FAIL - Exit status 1`

Fix:
From the ts3server login directory, issue:
`sed -i "s/_linux-/_linux_/g" functions/install_ts3.sh`
That will replace the copy line and the line that removes the directory in the install_ts3.sh file.

**Comment by UltimateByte** [comment]
Additional info
http://steamcommunity.com/id/UltimateByte/commentnotifications/
To summ up, update now works, but install doesn't.
I've not been working on that function yet, it's chinese to me, so @dgibbs64 if you could have a look, would be great.

**Comment by UltimateByte** [comment]
Well, i think i fixed it in the end, that was pretty easy. I'll pull request that.

**Comment by UltimateByte** [comment]
Tested, install working... But update fails on a freshly installed ts3server... 

```
serverdev@lrob:~/ts3server2$ ./ts3server update
[ FAIL ] Update ts3-server: Checking for update: teamspeak.com: Not returning version infoserverdev@lrob:~/ts3server2$

```

However, it can sucessfully check for udpates on a previously (and updated) installed server.
It's driving me insane... I'll check that again after some sleep, feel free to have a look and solve it before me.


Other bug detected : Details function

```
ts3server Script Details
===============================================================================================================================================
/home/serverdev/ts3server2/functions/command_details.sh: line 149: [: : integer expression expected
Service name:        ts3-server
ts3server version:   251215
User:                serverdev
GLIBC required:      UNKNOWN
Email notification:  off
Update on start:     off
Location:            /home/serverdev/ts3server2
Config file:         /home/serverdev/ts3server2/serverfiles/ts3-server.ini

Backups
===============================================================================================================================================
No Backups created
/home/serverdev/ts3server2/functions/command_details.sh: line 594: fn_parms: command not found
```

PS : Nothing to do with ts3 issue i guess, i just checked it, seeking for relevant stuff : 
command_update.sh appears to be blank... i don't get it.
https://github.com/dgibbs64/linuxgsm/blob/master/functions/command_update.sh
