### ISSUE TITLE
Multiple Servers 

### ISSUE THREAD

**Issue by spot88** [dgibbs64/linuxgsm#679]
Hello, 

Is there anyone that have made a guide that shows how to use this to manage multiple servers. 
Using Ubuntu 14.04 LTS. 

Or maybe there is a better\easier way then this?
Thanks for reply!

**Comment by UltimateByte** [comment]
https://github.com/dgibbs64/linuxgsm/wiki/Multiple-Servers

Is this enough for you or do you need more help ?

**Comment by spot88** [comment]
A bit more would be appreciated, i'm not so good with linux. I have used Windows on my CS:GO server until now. I'm now thinking about using Ubuntu Server 14.04 to host my servers. 

I have heard it's a lot easier to maintain when you first get it up and running :) 
Game updates and so on.

**Comment by UltimateByte** [comment]
Well, i have a good french tutorial for linux, but didn't find any that tutorial as good as this one in english.
I'd say first : Learn how to make users, login to them, login to root.
Second : Learn how to update your packages (apt-get... )
Third : Learn basic ssh/bash usage : cd, ls, nano cp, rm, rm -R, chmod... 
Fourth: Learn how to secure your SSH, by disableing your root login, and changin port (warning, you must have at least one active user)
Fifth : Learn how to make an FTP server, so it automatically creates a new FTP login going to any new user
Sixth : Eventually learn how to setup a basic HTTP (apache2) server and virtual host files.

Then you'll pretty much be ready to go, and this : https://github.com/dgibbs64/linuxgsm/wiki/Multiple-Servers will make a lot of sense already after the third step. 

However, github is used to report bugs and solve issues, not to babysit you as an admin (which i did anyway). I hope i gave you some keys to start with linux, now you just gotta do your googleing and your homework ! If you're stuck, go for the general help on the steam group : https://steamcommunity.com/groups/linuxgsm/discussions

Closing this, as it has no place on github. I wish you a good linux start, and let you know that i also read the steam group, along with many talented guys, we're all here to help. Just never forget to try learning by yourself, you will find anything about linux on google !

**Comment by spot88** [comment]
Can you link the page in french, google can translate. :D

**Comment by spot88** [comment]
So it's recommended to make a new user for every server you set up? 
Or is it good just to make a csgo user and create folders with the different servers?

**Comment by UltimateByte** [comment]
Google won't translate videos... http://www.tutoriels-video.fr/installation-et-configuration-dun-serveur-dedie-debia/

It's avised to make 1 user per server for safety and reliability reasons.
