### ISSUE TITLE
CS:GO community server list

### ISSUE THREAD

**Issue by Angristan** [dgibbs64/linuxgsm#682]
Hello,

How to get my CS:GO server to be on the public server list ?

Thanks

**Comment by oalaro** [comment]
`http://api.steampowered.com/ISteamApps/GetServersAtAddress/v0001?addr=<SERVER IP HERE>&format=json
`
If your server info shows up with that API request then it's being shown on the public server list.

**Comment by Angristan** [comment]
Thanks !

**Comment by Angristan** [comment]
BTW, do you know how can install a custom gamemode like 1vs1 arena ?

**Comment by UltimateByte** [comment]
For that, use google or ask there : https://steamcommunity.com/groups/linuxgsm/discussions

**Comment by Angristan** [comment]
Ok \o/
