### ISSUE TITLE
How to play a map from the WorkShop on CS:GO

### ISSUE THREAD

**Issue by Angristan** [dgibbs64/linuxgsm#683]
Hello,

I have edited the conf file for CS:GO workshop maps : 
```
# Optional: Workshop Parameters
# https://developer.valvesoftware.com/wiki/CSGO_Workshop_For_Server_Operators
# To get an authkey visit - http://steamcommunity.com/dev/apikey
 authkey="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
 ws_collection_id="249376192"
 ws_start_map="241267905"
```
What to I have to do then to play the map ?

**Comment by UltimateByte** [comment]
Never used that yet, maybe you have to change the defaultmap="de_dust2" to the map you wish too. Also check mapgroup="random_classic".

BTW, Github is for bug report, general support is here : http://gameservermanagers.com/support/

**Comment by Angristan** [comment]
Thanks
