### ISSUE TITLE
[Question] CS:GO How do we use workshop maps when we need to change the startup parameters?

### ISSUE THREAD

**Issue by FrozenBeard** [dgibbs64/linuxgsm#684]
According to this:
https://developer.valvesoftware.com/wiki/CSGO_Workshop_For_Server_Operators

The preferred method to using workshop maps is to use startup parameters, how can we do this with linuxgsm for CS:GO?

**Comment by marvinl97** [comment]
Have a look at the lines:
`# authkey=""`
`# ws_collection_id=""`
`# ws_start_map=""`
(https://github.com/dgibbs64/linuxgsm/blob/master/CounterStrikeGlobalOffensive/csgoserver#L53-L55)

You have to remove the hashtags. Then you have to add your values (like mentioned on your link). 

Here you can create a collection -> http://steamcommunity.com/workshop/editcollection/?appid=730
Here you can get an authkey -> http://steamcommunity.com/dev/apikey

**Comment by FrozenBeard** [comment]
@marvinl97 fantastic! 
Im planning on hosting some Operation maps, I found this collection that looks like its the official one:
http://steamcommunity.com/profiles/76561198082857351/myworkshopfiles

Is this the best way to set maps? There seems to be a few methods, I assume using the workshop is preferred over downloading the maps and putting them in the maps folder.

**Comment by dgibbs64** [comment]
Good write up this should go in the wiki

**Comment by UltimateByte** [comment]
Done !
https://github.com/dgibbs64/linuxgsm/wiki/Workshop

**Comment by UltimateByte** [comment]
@FrozenBeard Yes, the workshop is a very good option, as it syncs the map between client and servers, no version issue... + you don't have to setup a FastDL or stuff like that.

**Comment by dgibbs64** [comment]
Closing
