### ISSUE TITLE
Centos 6 TMUX bug

### ISSUE THREAD

**Issue by aure369** [dgibbs64/linuxgsm#687]
in centos 6 need tmux with libevent install manual.

this was helped for me:

sudo yum install glib2-devel fuse-devel libevent-devel libxml2-devel openssl-devel
rpm -Uvh http://pkgs.repoforge.org/tmux/tmux-1.6-1.el6.rf.x86_64.rpm

**Comment by UltimateByte** [comment]
Similar to this, isn't it ?
http://steamcommunity.com/groups/linuxgsm/discussions/0/412446292777426341/
https://gist.github.com/rothgar/cecfbd74597cc35a6018

**Comment by aure369** [comment]
yeah, it's similar, but to me this your version doesn't work. if doesn't work your version, then my version of this will work 100%, i was tested 

on root, your version work, it's cool. 

but do you try create new user ?

okey, created now user, error... need permision...

okey, new user has permision...

BUT, what need to do, if error if everythink do what allready do what was posted? need to search in the internet. then it's better then is not one way how to fix problem. :)

**Comment by UltimateByte** [comment]
CentOS is chinese to me, and CentOS 6 is old and badly supported in terms of packages.
I'd advise against using that outdated distro.
You might not be the only one in that case, so we may add this to our wiki in the Tmux page. https://github.com/dgibbs64/linuxgsm/wiki/Tmux

BTW, it seems like you installed a hell of a lot of packages for that issue. We'd need a minimal working fix to add reliable info, not making people installing unnecessary packages.

**Comment by dgibbs64** [comment]
I would reccomend installing tmux 1.9 or 2.0 over an older one as per the script I found. Not sure why there is a permissions issue with non root users though

**Comment by JHiemenz** [comment]
CentOS 6.7 64bit
Installed tmux 2.1 with this script:

`# Install tmux on Centos release 6.7

# install deps
yum install gcc kernel-devel make ncurses-devel

# DOWNLOAD SOURCES FOR LIBEVENT AND MAKE AND INSTALL
wget -O libevent-2.0.22-stable.tar.gz http://downloads.sourceforge.net/project/levent/release-2.0.22-stable/libevent-2.0.22-stable.tar.gz
tar -xvzf libevent-2.0.22-stable.tar.gz
cd libevent-2.0.22-stable
./configure --prefix=/usr/local
make
sudo make install

# DOWNLOAD SOURCES FOR TMUX AND MAKE AND INSTALL
wget -O tmux-2.1.tar.gz https://github.com/tmux/tmux/releases/download/2.1/tmux-2.1.tar.gz
tar -xvzf tmux-2.1.tar.gz
cd tmux-2.1
LDFLAGS="-L/usr/local/lib -Wl,-rpath=/usr/local/lib" ./configure --prefix=/usr/local
make
sudo make install

# pkill tmux
# close your terminal window (flushes cached tmux executable)
# open new shell and check tmux version
tmux -V
`

script origination at: [https://gist.github.com/rothgar/cecfbd74597cc35a6018]https://gist.github.com/rothgar/cecfbd74597cc35a6018

modified for my needs
