### ISSUE TITLE
Postfix still listed as unmet dependency when exim4 is installed.

### ISSUE THREAD

**Issue by jejanim** [dgibbs64/linuxgsm#695]
I use exim4 for all my guest systems and thus just copy over a config file to make it work.

The server however, always tells me to do 
`sudo dpkg --add-architecture i386; sudo apt-get install postfix`. 
Mail sending works fine though, and everything else as well.

I know those are just "warning" and "info" messages so nothing is going to break, but 
you might want to consider adding an alternative check for postfix/exim4 unless you really need it somewhere.

**Comment by jaredballou** [comment]
We really ought to just check that the /usr/bin/mailx file exists (or whatever we use for sending mail). As long as that file exists, it ought to be OK regardless of the MTA installed.

**Comment by jejanim** [comment]
Does the "monitor" function attempt to install it?
I am getting sercurity mails because the user that runs the server is not allowed to sudo.
