### ISSUE TITLE
No graceful shutdown for 7days server via telnet.

### ISSUE THREAD

**Issue by jejanim** [dgibbs64/linuxgsm#696]
Probably related to #558 (I am running debian 8.3)

The telnet shutdown function does not seem to work for me, when I add the following code to the first line of the `sdtd_telnet()` function:
`echo "${telnetip}:${telnetport} ${telnetpass}"`

I somehow get a boolean:

`Stopping sdtd-server: Attempting graceful shutdown via telnet127.0.0.1:8081 **true**`
Manually connecting to the server and shutting it down via telnet works fine however...

**Comment by UltimateByte** [comment]
That telnet thing is totally unknown for me, did you set a password as RogerSik did ? Seems to have fixed it for him.

**Comment by jejanim** [comment]
He set his password to "true" which I am sure fixed it for him since the function always enters true regardless of the defined password.

**Comment by UltimateByte** [comment]
@dgibbs64 Any idea ?

**Comment by pix0wl** [comment]
I don't know whether this is intended, but it's working for me since I've added the telnet password plain to the "command_stop.sh" (on line 20).

`"password:"     { send "'"my-telnet-password"'\r" }`
https://i.imgur.com/ImXHQX3.png

**Comment by jejanim** [comment]
It's a legit quickfix, but it does not solve it for all the others out there. The second you get updated functions you'll lose your fix. Provided a fix was not supplied by that time, you'll once again run into the same problem.

**Comment by dgibbs64** [comment]
Should now be fixed :)
