### ISSUE TITLE
Servers conflict with Byobu functionality

### ISSUE THREAD

**Issue by Zer0t3ch** [dgibbs64/linuxgsm#697]
If an LGSM server is running, Byobu will open it, and it's impossible to start a server while Byobu is running. 

It seems the conflict has something to do with tmux sessions. I'll look into it further some time in the next couple days.

**Comment by UltimateByte** [comment]
Byobu is an equivalent to Tmux, right ? Why would you have both ?

**Comment by Zer0t3ch** [comment]
@UltimateByte Byobu isn't an alternative to Tmux, it's more like a frontend. (Though even that isn't the best way to explain it)

Basically, the way I understand it, is that it runs Tmux with a bunch of preset configs of its own for things like the statusbar. For some odd reason, when using Byobu, it opens the LGSM server (regardless of working directory) but opening Tmux doesn't.

Here's a video of what happens: http://sendvid.com/jbv673e4

**Comment by dustinkirkland** [comment]
@Zer0t3ch is exactly correct.  Byobu is a wrapper for tmux, basically a good set of .tmux.conf settings and helpers that turns stock tmux into a richer CLI environment and window manager.

**Comment by dustinkirkland** [comment]
I don't know what an LGSM server is, but if you find the bug is in Byobu, please send me a pull request or a merge proposal.  Thanks.

**Comment by UltimateByte** [comment]
LGSM just creates a tmux session wih a regular tmux command.

LGSM will find create a new session that way : 
https://github.com/dgibbs64/linuxgsm/blob/master/functions/command_start.sh#L117

Find an existing one that way : 
https://github.com/dgibbs64/linuxgsm/blob/master/functions/command_start.sh#L85

And show the session that way : 
https://github.com/dgibbs64/linuxgsm/blob/master/functions/command_console.sh#L30

What changes occurs when using Byobu ? Why would those stop working ?

**Comment by Zer0t3ch** [comment]
@UltimateByte They don't really "stop working" but Byobu and LGSM servers seem to use the session, I guess.

**Comment by dgibbs64** [comment]
hmmm im not sure how to resolve this as you can run many tmux sessions with any name which is what LGSM does it just creates a tmux session. no idea why Byoby would open an existing tmux session.

**Comment by dgibbs64** [comment]
Any updates on this?

**Comment by dgibbs64** [comment]
Closing as no update.
