### ISSUE TITLE
ARK Server + Battleye

### ISSUE THREAD

**Issue by Cuppycake** [dgibbs64/linuxgsm#698]
Now that Battleye is available with ARK on linux I was wondering what the easiest way to add in 
`-BattlEye`

to the start parameters? Is this automatic already with the updates? Is their already a specific spot to put this?

Thanks

**Comment by UltimateByte** [comment]
Hi,

Was it you on Steam community ? Now i think about it, i recently made this : https://github.com/dgibbs64/linuxgsm/wiki/Start-Parms to help with adding custom start parameters.

But as -BattlEye is now native, we may add it by default into the main ARK Server script.

BTW, it seems like it is (or changed to) -UseBattlEye
More info : 
http://steamcommunity.com/games/346110/announcements/detail/852673624835029754

**Comment by Cuppycake** [comment]
ooh nice catch, yeah as of the time of posting it was still -BattlEye.

So if I go ahead and add this now and you release it native into the files it will just over write with no issues later on?

**Comment by UltimateByte** [comment]
Yep, from memory, it wasn't that command when you posted that on steam, so they just changed it.

The self update function of LGSM ( https://github.com/dgibbs64/linuxgsm/wiki/Update#updating-your-lgsm-script ) is able to update everything in the /functions directory but the main script (arkserver) has to be updated manually. As you can already make this change manually, there will be no need for you to update it for that purpose after we added it natively.

**Comment by Cuppycake** [comment]
So assuming this 
`# Start Variables
ip="000.0.00.000"
updateonstart="off"
commands="-UseBattlEye"`

is correct BattlEye should now be running after a restart with nothing else needed to be done after updating ARK itself?

**Comment by UltimateByte** [comment]
And of course add ${commands} to fn_parms, and you're ready to go !

**Comment by Cuppycake** [comment]
Ah right so something like this? 

`fn_parms(){
parms="TheIsland?listen
${commands}"}`

**Comment by UltimateByte** [comment]
Never made an Ark server myself. Their syntax is pretty shitty according to their wiki : http://ark.gamepedia.com/Server_Configuration

Seems like if you add something else, you should put a "?" instead of a space. so would be something more like : 

fn_parms(){
parms="TheIsland?listen?${commands}"
}

**Comment by UltimateByte** [comment]
Did you try that ?

**Comment by Cuppycake** [comment]
Sorry I didn't get back to you sooner. I am using:

fn_parms(){
parms="TheIsland?listen ${commands}"
}

Tested with BattlEye launch option off and can not connect and my server now shows the BattlEye icon in the listing.

**Comment by UltimateByte** [comment]
Did you try with that as suggested ?

```
fn_parms(){
parms="TheIsland?listen?${commands}"
}
```

**Comment by Cuppycake** [comment]
I can at some point I suppose but I have not since its working as shown.

**Comment by UltimateByte** [comment]
Sorry, are you saying that BattleEye is now compulsory ?

**Comment by Cuppycake** [comment]
No I am saying I typed in:

fn_parms(){
parms="TheIsland?listen ${commands}"
}

and BattlEye is now enabled, Showing that with a space in the syntax and not a ? it's working.

**Comment by UltimateByte** [comment]
OK, thanks for the info ! I'm still curious to know if the proper syntax is a space or a "?". Would be nice if you could try this out, as it seems that a "?" is the proper way to do, as i can't test it myself (don't own that game).

**Comment by Cuppycake** [comment]
If I can find a good time to test it out I will do so. For some reason my server can sometimes take hours to sync, showing online with LGSM commands but not on the server lists and I'd hate to inconvenience the player base in peak hours.

**Comment by UltimateByte** [comment]
Yep, i saw your other issue https://github.com/dgibbs64/linuxgsm/issues/699 but i have no clue about this at all. Definately not a script issue though. Why not trying that when your server doesn't show on the list ?

**Comment by Cuppycake** [comment]
Well it only does not show on the list after a restart. Like its taking time to sync or something. Which is still requiring the server to be pulled down and restarted. Once its up and shows on the list it doesn't vanish again at any point.

**Comment by UltimateByte** [comment]
Well, battleeye doesn't seem to be required nor appreciated. Closing this.
