### ISSUE TITLE
./tf2server console doesn't display the console.

### ISSUE THREAD

**Issue by liwanu** [dgibbs64/linuxgsm#7]
Please see attached screenshot. This is all i see after a ./tf2server console command is entered. I'm unable to exit by CTRL+b d, i have to use CTRL+C to return to the command prompt.
![tf2server](https://f.cloud.github.com/assets/5704864/1348021/a95d1544-36bb-11e3-9a6e-1dab0fe45361.png)

**Comment by deliriumbg** [comment]
I just stumbled onto this problem.
The solution is quite simple. I was pressing CTRL+b d without releasing the CTRL (like if using screen). 
You should hold down CTRL and press b, release the CTRL and then press d.
