### ISSUE TITLE
CS:GO server issues

### ISSUE THREAD

**Issue by Cuppycake** [dgibbs64/linuxgsm#703]
My CS:GO server is not showing in the server lists at all.
It's online and running, ports are opened, using 27016.
GameTracker shows the server online but also won't show me in the online
player list after refreshes. 
http://www.gametracker.com/server_info/bloxhub.com:27016/

Sometimes gametracker will randomly report that the server is offline when it is not.

I can connect to the server via console with:
`connect bloxhub.com:27016`
just fine, it shows in my favorites with the same address and nothing local that would surpass firewalls.

I am also running an ARK server through LGSM on the same machine. I am using all default ports for that so I see no reason for any confrontation there.

Is there another port I am missing or something? I have:
`ip="0.0.0.0"`
in csgoserver but if I change it to my Ip address the server refuses to start.
http://pastebin.com/z5FGM1wt

**Comment by UltimateByte** [comment]
You're definitely having an issue with your machine.
Could either be a failing DDoS protection, a failing firewall and port redirect, or bad networking.

As for the IP issue, i should have asked that before : 
Is the IP of your machine the same as your public IP ? Is that a VM ?
What is your distro ?
What kind of server are you using ?
What provider, what location ?

**Comment by Cuppycake** [comment]
This is a home hosted machine. Server grade hardware, Fibre connection, etc.
I feel like if it was a failure in the machine or network then my other servers would be having
some sort of issue as well. 

I'm running CentOS 7.1
Not running any VMs

**Comment by UltimateByte** [comment]
OK
I guess you're using a router ? What router is this ? (for the record)

Weird stuff in your config : 

`port="27016"
sourcetvport="27020"
clientport="27005"`

You increased the server port from 1, but didn't change other ports. I assume you did that because another server is using 27015 port ? Then another server is probably using the default clientport and sourcetv port. One server, one set of ports.
I'd suggest you to read that entirely, i'm pretty sure i didn't write this for nothing :p  https://github.com/dgibbs64/linuxgsm/wiki/Default-Ports
I'm personally using the method 1 to set my port ranges.

**Comment by UltimateByte** [comment]
Also, if your server IP isn't your public IP, then you should use your local IP as ip="YOUR LOCAL IP", then the router will do the job as long as your ports are redirected properly.

BTW, run `./csgoserver details` to know what are the 3 ports you're gonna have to redirect, and to know if it's UDP or TCP. Redirect them all, don't be lazy as some guys that are happy with one port "as long as it works...", be sure that it works entirely.

**Comment by Cuppycake** [comment]
Router is from my ISP its an actiontec.

I increased it because ARK is using 27015 for its Query. 
As fart as I know the sourcetvport and clientport isn't a thing on the ARK side so I left that alone. 
This machine is only running ARK and this one CS:GO server. The other machine in house is running minecraft servers. Yep ran the details and forwarded everything from my router and my firewall, including testing with the firewall off quickly.

If I leave the IP as
`ip="0.0.0.0"` 
when I run details it will say the local IP of the machine.

**Comment by UltimateByte** [comment]
ARK is beginning to bore me like hell... :o))
Make sure it doesn't use the whole 27000 IP range, lol.

So did you redirect those 3 ports to the right local IP ?
Dirty and fast way would be to redirect 27000 to 28999 ports TCP/UDP to that machine. Then temporary remove the firewall of that machine. If it works, then you know it's either a firewall or a port issue. Put the firewall back, test again. If it works, it was a port issue. Then redirect those ports properly.

**Comment by Cuppycake** [comment]
What Im not getting is if I can connect in the console with my IP or bloxhub.com:27016 and can connect to the server, GamTracker sees it, so why can't the public see it? Makes little to no sense to me haha

**Comment by UltimateByte** [comment]
> Yeah I've had those 3 forwarded.

Good

> Should I change the ARK Server query port outside of that range?

If you can, you'd better move it away, yes.

Gametracker sees it, but seems not to be able to know your name while on it. Maybe the query is partially working because of a port being unreachable.

Did you remove CentOS firewall i i suggested ? Just for testing.
(BTW, i'm personally think firewalls are almost useless for most people)

**Comment by Cuppycake** [comment]
yeah I've got it completely off at the moment. Still nothing. Never had this in the past with CS:GO servers I've hosted.

**Comment by Cuppycake** [comment]
output of 
`netstat -atunp | grep srcds_linux`

`tcp        0      0 192.168.1.2:27016       0.0.0.0:*               LISTEN      32322/./srcds_linux
udp        0      0 192.168.1.2:26901       0.0.0.0:*                           32322/./srcds_linux
udp        0      0 192.168.1.2:27005       0.0.0.0:*                           32322/./srcds_linux
udp        0      0 192.168.1.2:27016       0.0.0.0:*                           32322/./srcds_linux
udp        0      0 192.168.1.2:27020       0.0.0.0:*                           32322/./srcds_linux
`

Is that 26901 referring to the CS:GO server? Haven't seen it mentioned anywhere else.

**Comment by UltimateByte** [comment]
OK, no need to look anywhere else, your previous post made me think "He hosted CSGO servers in the past... Maybe he doesn't know about GSLT... Does he have the GSLT... Wait, his scrips looks like it's from a damn while ago... Where is his GSLT setting ?! Oh, there is none...



1) Grab the latest script version
2) Configure the GSLT https://github.com/dgibbs64/linuxgsm/wiki/Game-Server-Login-Token

Solved.

**Comment by UltimateByte** [comment]
I didn't know about that 26901, i don't know what the heck it is. A little googleing seems to indicate that it's the default -steamport 26909 , no idea what the heck it is. Need more googleing.

**Comment by UltimateByte** [comment]
OK, that port might be used for GSLT in the end :)
Not sure if we can and need to change it to run several GSLT servers. I should try it out.

**Comment by Cuppycake** [comment]
Ha ok so something like this in the params?

fn_parms(){
parms="-game csgo -usercon -strictportbind -ip ${ip} -port ${port} +clientport ${clientport} +tv_port ${sourcetvport} +sv_setsteamaccount [Token] -tickrate ${tickrate} +map ${defaultmap} +servercfgfile ${servercfg} -maxplayers_override ${maxplayers} +mapgroup ${mapgroup} +game_mode ${gamemode} +game_type ${gametype} +host_workshop_collection ${ws_collection_id} +workshop_start_map ${ws_start_map} -authkey ${authkey}"
}

**Comment by UltimateByte** [comment]
Something like that.
Just update your script, there is a setting for gslt ;)

**Comment by Cuppycake** [comment]
Is that under ./csgoserver update-functions?

**Comment by UltimateByte** [comment]
No, it's within the csgoserver script !
As i said : 

"1) Grab the latest script version (also remove the /functions directory) wget http://gameservermanagers.com/dl/csgoserver"

**Comment by Cuppycake** [comment]
Yeah just edited my last post as you posted haha. Sorry about that.

**Comment by UltimateByte** [comment]
NP dude ^^

**Comment by Cuppycake** [comment]
Thank God it worked haha. Can see it just fine now! Thanks for all the help and the patience lol

**Comment by UltimateByte** [comment]
I assumed you made a new installation with the latest game script, that's why it took so much time !
Glad it's solved !

GLHF with that csgo server !

**Comment by Cuppycake** [comment]
No I just Copied the script into a new file and edited it up and sent it over. Worked like a charm. 
Figured out my setting and I'ts good to go now. Thanks again. o/
