### ISSUE TITLE
Improved Download Functionality

### ISSUE THREAD

**Issue by dgibbs64** [dgibbs64/linuxgsm#708]
I am currently working on a function that deals with downloads. This will include functions, configs and archives from wither github of other external urls. 

This is a little complicated however once complete will make dealing with files much easier.

**Comment by UltimateByte** [comment]
:+1:

**Comment by dgibbs64** [comment]
Getting back to working on the development branch after some busy times for me. The last main hurdle is the  details function. This needs a overhaul. Once the new more streamlined development branch is released I can focus on adding new features and servers

**Comment by UltimateByte** [comment]
:+1:  :+1:  !
I'll be able to give a hand for testing/debugging if needed, probably in around a week.
