### ISSUE TITLE
Rust support

### ISSUE THREAD

**Issue by UltimateByte** [dgibbs64/linuxgsm#711]
Linux server finally back and working out of the box !

https://twitter.com/garrynewman/status/700658567641231360

I'll first test the standalone server, and if everything works well, add support for it ! Should be pretty similar to Hurtworld, as it's the same engine.

Also, the main mod for it, which is Oxide keeps a well organized repository with the latests builds in it : https://github.com/OxideMod/Snapshots/
Would be great to add native installation command to instlal it for supported games (Rust/Hurtworld, 7Dtd at least). It would be the first addon officially supported by LGSM. (./gameserver install-oxide or ./gameserver oxide , to install and update).

**Comment by UltimateByte** [comment]
Linux server working ! Script incoming !

**Comment by UltimateByte** [comment]
http://www.noelshack.com/

https://github.com/dgibbs64/linuxgsm/blob/rust/Rust/rustserver

**Comment by UltimateByte** [comment]
Related, source of help
http://oxidemod.org/threads/full-list-of-server-arguments-parameters.15998

**Comment by UltimateByte** [comment]
Many fixes,
Default CFG should be fine (not tried yet)
Struggling on server querying.
Once i figured it out, details function, and i'm done :)

**Comment by UltimateByte** [comment]
Well, querying is working. I knew i had to write it down in order to find the fix right away.

**Comment by UltimateByte** [comment]
Well, everything works now.
I'd like to see if -IP start parm is working.
I used the current date as a log name, so that it doesn't get overwritten at every reboot. Sadly, there is no way to change its folder. So i'm gonna add a function into the log manager to move those logs into LGSM log folder, every time it runs.

**Comment by UltimateByte** [comment]
Log management, done !
https://github.com/dgibbs64/linuxgsm/blob/rust/functions/logs.sh#L19

Tested, working. :D

**Comment by UltimateByte** [comment]
Awaiting for merge.

**Comment by UltimateByte** [comment]
Wiki updated (with LGSM in it :p )
https://developer.valvesoftware.com/wiki/Rust_Dedicated_Server

**Comment by UltimateByte** [comment]
Useful link : https://github.com/OxideMod/Snapshots

**Comment by twamp22** [comment]
Great job here guys, i am subscribed

**Comment by UltimateByte** [comment]
OK, one major issue, if the server crashes, even if i stop it, the process won't stop (but the tmux session will). Weird.
Screenshot : http://image.noelshack.com/fichiers/2016/08/1456254829-log-rust.png

**Comment by dgibbs64** [comment]
@UltimateByte I might be worth opening a new issue for the server not being killed issue. If its still a problem

**Comment by UltimateByte** [comment]
@dgibbs64 It happens after trying to put a specific addon that makes the server crash... And, it seems, try to restart itself (and fails) outside of tmux... I'm not sure if we can do anything about it.
