### ISSUE TITLE
[Teamspeak3] Backup via Cronjob

### ISSUE THREAD

**Issue by niklasschaeffer** [dgibbs64/linuxgsm#712]
The Backup via Cronjob is not working in the script are multiple Question-Answer Sections. It seems that at this point the script is waiting for an user input but never gets one. Instead when you schedule the job the script just waits for an answer and proceeds. Can you add an Option to override the answer section ?

My Cronjobs looks exactly like this:

0 5 * * * '/home/ts3server/ts3server backup' > /dev/null 2>&1

**Comment by dgibbs64** [comment]
As per wiki

Note: this is not designed to be an automated backup solution.

https://github.com/dgibbs64/linuxgsm/wiki/Backup

**Comment by niklasschaeffer** [comment]
Didnt answer my question but ok.
For anyone who wanna use it anyways automated.

edit /functions/command_backup.sh

Uncomment:

#while true; do
	#read -p "Continue? [y/N]" yn
	#case $yn in
	#[Yy]* ) break;;
	#[Nn]* ) echo Exiting; return;;
	#* ) echo "Please answer yes or no.";;
#esac
#done

**Comment by dgibbs64** [comment]
I kinda did answer the question. I don't reccomend using the backup feature for automated backups mainly as it backups up everything including users file uploads. This can get pretty big especially as there is no incremental backup I reccomend using your own automated backup solution for your whole server if you want to automate. Rsync to a remote server can be a good solution.
