### ISSUE TITLE
[ Question ] is /serverfiles used as /GarrysMod/(main gmod /garrysmod/)

### ISSUE THREAD

**Issue by EvoLife** [dgibbs64/linuxgsm#715]
is /serverfiles used as /GarrysMod/(main gmod /garrysmod/)

I need to install libmysql.so.16 for mysqloo support and when I install mysqloo it reads it as missing. One of the requirements for mysqloo is libmyslq and I don't believe that it is reading it. is /serverfiles/ directory used as /GarrysMod(serverfiles)/garrysmod/ ?

**Comment by UltimateByte** [comment]
Here is a place for developing and talking about LGSM. This is not an LGSM issue.
I'll answer anyway, but if you need more help with that, please use the steam group. I'm watching it too. https://steamcommunity.com/groups/linuxgsm/discussions

I got it to work with MySQ, and i'm currently using it for 2 DarkRPs.

Don't use the v7, use the v8
https://facepunch.com/showthread.php?t=1220537

Installation is easy, put the .dll in serverfiles/garrysmod/lua/bin , then set your addons accordingly to use MySQL.
Without mysqloo, the SQL database used is sv.db, located in serverfiles/garrysmod if i remember well. If you wanna keep some content in it, you can upload that SQLite DB to the MySQL DB with PHPMyAdmin or an equivalent.
