### ISSUE TITLE
[ARK] Restart script issue/problems

### ISSUE THREAD

**Issue by talpidae** [dgibbs64/linuxgsm#717]
Hello!

We are running an ARK Server on Debian with some issues.
We are trying to automate the daily restarts (Feature request?) with cronjobs.

I tryed both ways:
`55 5 * * * ./arkserver stop`
`57 5 * * * ./arkserver start`

and
`00 6 * * * ./arkserver restart`

In both cases the Gameserver is shutting down but dont came back online.

Maybe i missed some hints? Or there are better ways to solv this?

**Comment by dgibbs64** [comment]
try the full path of the script..I have never see a cronjob ever setup like the way you have attempted

    55 5 * * * /home/arkserver/arkserver stop

**Comment by UltimateByte** [comment]
http://steamcommunity.com/groups/linuxgsm/discussions/0/412448158145862239/

> Your syntax doesn't look like anything we advise.
> Also, if running multiple servers, consider root cronjobs (watch the syntax, it's different)
> 
> https://github.com/dgibbs64/linuxgsm/wiki/Automation
