### ISSUE TITLE
[7 Days to Die] Function Error.

### ISSUE THREAD

**Issue by reesey275** [dgibbs64/linuxgsm#723]
When attempting to restart server getting below error.

Stopping sdtd-server: Attempting graceful shutdown via telnet/home/7dtd/functions/command_stop.sh: line 29: expect: command not found

[K[[0;31m FAIL [0m] Stopping sdtd-server: Attempting graceful shutdown via telnet: Unknown error

**Comment by dgibbs64** [comment]
You are missing a dependency 

    apt-get install expect

**Comment by reesey275** [comment]
Is there a full list of required dependencies for each Game Server type available?

**Comment by dgibbs64** [comment]
yes on the website http://gameservermanagers.com

**Comment by reesey275** [comment]
Thanks for the help. Appears to be functioning properly again.
