### ISSUE TITLE
Get PID of launched server

### ISSUE THREAD

**Issue by men232** [dgibbs64/linuxgsm#726]
Hey guys,  please tell me how to get the server running PID?
I want provide info about server process used memory or cpu. Thanks.

**Comment by UltimateByte** [comment]
The PID is kinda random every time.
For now, as long as i know, LGSM don't provide a way to give the PID.

Could be a good idea to give it in ./gameserver details if the server is started. BTW, there would be 2 PID, one for the tmux session, the other one for the actual server. I'm not sure how we could get them.

For now, just use webmin ;)

**Comment by dgibbs64** [comment]
you could  search for processes for the game server user.

Somthing like:

**Comment by men232** [comment]
I think it's more better :)
`tmux list-panes -F '#{session_name}:#{pane_pid}' | grep "^${servicename}:"`

**Comment by UltimateByte** [comment]
I got no idea what is better as this is unknown to me, but, this would allow to setup a priority level, as some people are asking... Even if i think that if you think about priorities to get your server running better, it's probably that your server isn't powerful enough anyways.
