### ISSUE TITLE
[CSGO] error after editing csgoserver

### ISSUE THREAD

**Issue by OverlOrDGT** [dgibbs64/linuxgsm#728]
HI,
In the begining all working fine, but when i change the setting(gamemode and type) on csgoserver file this error happens

[csgoserver@vps252012 ~]$ ./csgoserver force-update
-bash: ./csgoserver: /bin/bash^M: bad interpreter: No such file or directory

can someone helpme pls?

**Comment by UltimateByte** [comment]
99% sure you messed up with the syntax.

Post your csgoserver script, make sure to hide sensitive information (steam account if any, API Key, and GSLT).

**Comment by OverlOrDGT** [comment]
[csgoserver.txt](https://github.com/dgibbs64/linuxgsm/files/150980/csgoserver.txt)

i change to txt, so i could be able to upload it

**Comment by UltimateByte** [comment]
OK, your script seems good. 

Is that a new install ? Why would you run force-update ?
Are the normal update, and validate functions OK ?
Start function ?

**Comment by OverlOrDGT** [comment]
no command works, and all give the same error
@UltimateByte

**Comment by UltimateByte** [comment]
What distro do you have ?
Looks like an issue with your bash interpreter.

`./csgoserver update-functions`
Try that.

**Comment by UltimateByte** [comment]
Also, did you install all the dependencies ?

**Comment by OverlOrDGT** [comment]
Still the same error, at first time all work fine, but when i change csgoserver settings start give me the same error when i try to start the server @UltimateByte

**Comment by OverlOrDGT** [comment]
tryed the same with rust server, at begin works, but when i change the rustserver file, stop works with the same error

**Comment by UltimateByte** [comment]
What about you answer my 2 questions ?

**Comment by OverlOrDGT** [comment]
yh i installed all

**Comment by UltimateByte** [comment]
If you got trouble counting 2 questions, it's gonna be a pain.
So again, What distro do you have ?
And i'll add one more : What is your VPS provider ? Are they customizing their distros ?

Lastly, can you output your logs in /home/your_user/log/script ?

**Comment by UltimateByte** [comment]
And one more question again : What are you editing your script with ?

**Comment by dgibbs64** [comment]
Looks like the file might be is using windows line endings rather than unix. I recommend deleting the file and re downloading. Your text editor is probably saving the file with windows line ending causing the issue. I recommend using vi, nano, notepadd++ or sublime text.

Just downloaded the text file and was using windows line endings...so yeah thats probably it,

**Comment by OverlOrDGT** [comment]
Thx it worked!
