### ISSUE TITLE
Life is Feudal implementation? 

### ISSUE THREAD

**Issue by mightyBroccoli** [dgibbs64/linuxgsm#731]
I would want to ask if it is possible to implement Life is Feudal Gameserver. 

http://store.steampowered.com/app/290080
http://lifeisfeudal.com/game-info

**Comment by UltimateByte** [comment]
We got no Torque engine games supported yet so... May require a lot of work.
Any doc about Linux Feudal server management to provide ?

**Comment by mightyBroccoli** [comment]
The Game is relativly new so there was no official doc about server management.
There are just community tutorials to start a server but these are not that handy as this script installing way.
[Life is Feudal - VPS/Dedicated Server Setup Guide](https://steamcommunity.com/sharedfiles/filedetails/?id=316928535)

**Comment by UltimateByte** [comment]
https://steamdb.info/app/320850/

Seems like it supports windows only :(
