### ISSUE TITLE
Rust server fails to start

### ISSUE THREAD

**Issue by walliski** [dgibbs64/linuxgsm#732]
Debian Jessie 64bit fails to start Rust server after install. No errors other than "Cant start Rust Server".

When trying to install Rust manually using instructions from https://developer.valvesoftware.com/wiki/Rust_Dedicated_Server it says "Illegal instruction". Missing dependencies in the script?

**Comment by reesey275** [comment]
Have you installed all dependencies? 

sudo dpkg --add-architecture i386; sudo apt-get update; sudo apt-get install tmux mailutils postfix ca-certificates curl lib32gcc1 libstdc++6 libstdc++6:i386

**Comment by UltimateByte** [comment]
Using LGSM, you should get a log.
As always, what does the log say ?
`cat serverfiles/game*.log`

**Comment by walliski** [comment]
Yes I have installed the dependencies. Well not postfix since I have Exim from before.

Logs below:
```
gaben@herderp:~/tmprust$ ls
functions  gsquery.py  log  rustserver  serverfiles  steamcmd
gaben@herpderp:~/tmprust$  cat serverfiles/game*.log
cat: serverfiles/game*.log: No such file or directory
gaben@herpderp:~/tmprust$ 

gaben@mynx:~/tmprust$ ls serverfiles/
Bundles          RustDedicated       server           steamapps
libsteam_api.so  RustDedicated_Data  steam_appid.txt
gaben@mynx:~/tmprust$ 
```

**Comment by UltimateByte** [comment]
Well, it doesn't even create a logfile... Did you at least try the start command after installing that instance ?

This is weird, i'm using Debian 8.3 x64 too so... Are you sure you installed all the 32 bit dependencies ?

If you don't have sudo, just remove "sudo" from the commands and run them as root. (But you don't seem like a noob so i guess you got that).
 
If you got your dependencies as you should, one explaination could be the lack of RAM (Rust, even the server version, is very demanding). 

PS : Nice user ;)

**Comment by walliski** [comment]
```
gaben@herpderp:~/tmprust$ ./rustserver start
[ FAIL ] Starting rust-server: Unable to start Rust
gaben@herpderp:~/tmprust$ 

gaben@herpderp:~/tmprust/serverfiles$ ./RustDedicated
Illegal instruction
gaben@herpderp:~/tmprust/serverfiles$ 

gaben@herpderp:~/tmprust$ free -m
             total       used       free     shared    buffers     cached
Mem:          7837       7707        129        172        168       4131
-/+ buffers/cache:       3406       4430
Swap:         5665         21       5644
gaben@herpderp:~/tmprust$ 
```

All deps listed installed, and the 32 architecture also added. The command that Reesey posted apart from `postfix` since I have `exim4` as MTA... Strange...

**Comment by walliski** [comment]
Tried installing a new VM, and it works on it. Suppose I have something strange going on on the server, have to look into it... If someone finds similar errors we might see a pattern.. I'll just close this issue...

**Comment by walliski** [comment]
Packages that are installed on the VM but not on the server are just some laptop specific ones; WiFi, Bluetooth, smartcard reader etc.

Packages on the server not on the VM I could not find anything interesting...

I think my problem is not software, but HW... I now remembered that I've had problems with CS:GO before also on another, older, server. This was due to missing instruction sets on the CPU, which makes sense taking the error message into consideration :<

Thanks for the help anyways! Hope (or not :D ) that someone else will have use of this..

**Comment by UltimateByte** [comment]
Thanks for your feedback, it might help ! If you could mention your hardware specs, would be perfect to help future people with that issue even more (and i'm a bit curious about it !).

**Comment by walliski** [comment]
AMD Opteron 275 O:)

**Comment by UltimateByte** [comment]
Lol, you're pretty optimistic, Rust server is very demanding !
