### ISSUE TITLE
Pass branch argument to SteamCMD for install/update

### ISSUE THREAD

**Issue by garciabruno** [dgibbs64/linuxgsm#733]
I was hoping to update my Rust server to with "-b prerelease", Is there any way I could do this through gameserver manager? Haven't found any documentation on branching.

Regards

**Comment by UltimateByte** [comment]
In you main script, find appid= , change it to whatever you like and install. Should do the trick.
Thought it was -beta experimental, but it may have changed.
Not sure why anybody would do that btw, but whatever :o))

**Comment by garciabruno** [comment]
I figured that out right after I posted my question, I wanted to do -beta prerelease, I was messing up with the "-b" though.

Thank you.
