### ISSUE TITLE
[Rust] no logs in console

### ISSUE THREAD

**Issue by Twixi45** [dgibbs64/linuxgsm#734]
Hi, 
today i come here because i don't know if this problem or this normal, 
i start my server rust ./rustserver start 
and i go in the console and i see that : 
 
Set current directory to /home/rustserver/serverfiles
Found path: /home/rustserver/serverfiles/RustDedicated

i have Ubuntu 14.04.4  LTS (GNU/Linux 2.6.32-042stab108.2 x86_64)

PS:  sorry for my english i'm french =|

**Comment by UltimateByte** [comment]
Salut ! :p 

Rust doesn't provide any console. Facepunch aka Facepalm...
So yeah, that's "normal". 

However, Rusty is an RCON tool that all Rust admins should use, and will give you the output of what should be the game console.
You can also find the latest log doing
`cat serverfiles/game*.log`
Upon start, the latest previous log is moved to logs/server , so in that folder, you can find all the previous logs.

That's not a problem to be french, watch more stuff in english and you'll be fine. :o))

**Comment by Twixi45** [comment]
Thank you ! i check "Rusty" =)

**Comment by dgibbs64** [comment]
Its a Unity things rather than a rust thing. 7 Days to Die does the same in console

**Comment by UltimateByte** [comment]
And 7DTD has Telnet instead of RCON i guess. That still sucks. ^^
