### ISSUE TITLE
[Codename Cure] Glibc Fix

### ISSUE THREAD

**Issue by medic917** [dgibbs64/linuxgsm#735]
Here is the error I get: http://i.snag.gy/tAvQz.jpg

I am using nmrihserver and tf2server scripts just fine, but for some reason the new script does not run with that error. I checked the glibc version and updated it with apt-get install libc6 but still does not work.

**Comment by dgibbs64** [comment]
Whats the output of ldd -v?

**Comment by medic917** [comment]
Hey Daniel,
Thanks for helping! My output is "ldd: missing file arguments"

I'm running Debian 7, and I'm assuming this error could be due to my glibc not updating?

**Comment by dgibbs64** [comment]
try this instead might give you better info :)
    ldd --version

**Comment by medic917** [comment]
Now it works.
ldd (Debian EGLIBC 2.13-38+deb7u10) 2.13

That is my version, I wonder why it's not updating to 2.15?

**Comment by medic917** [comment]
Any way to run your script with version 2.13? Or is it a Codename Cure requirement?

It seems like on debian I have to use something hacky like this: http://stackoverflow.com/questions/10863613/how-to-upgrade-glibc-from-version-2-13-to-2-15-on-debian

**Comment by medic917** [comment]
Damn, it seems like I have to update to Debian 8...
If you could find a GLIBC FIX like you did for other games, that would be awesome. But for now I think the hacky way to upgrade is not going to work since now the newest version of glibc requires a kernal upgrade...

**Comment by dgibbs64** [comment]
Yeah I recommend upgrading tbh. Game servers require now at min 2.15. I may be able to get a glibc fix in place. I will be reviewing soon but its gunna be some time before that gets released (I have a big update im working on)

**Comment by UltimateByte** [comment]
What would prevent you from upgrading to Debian 8 ?

**Comment by dgibbs64** [comment]
Also good for reference http://gameservermanagers.com/list

**Comment by medic917** [comment]
I'm just afraid to upgrade because of other things I run that "might" be incompatible with debian 8.
It might also take me hours to find a way around any bugs due to the incompatibility.

I'm really thinking about it though. Like daniel said, most games seems to require 2.15 or above.

**Comment by dgibbs64** [comment]
Added support for Codename CURE GLibc fix 70e1e6fbf9f22bb0432a898f03964a2305458fbc
