### ISSUE TITLE
centos tmux non-rpm causes false warnings

### ISSUE THREAD

**Issue by JHiemenz** [dgibbs64/linuxgsm#736]
CentOS 6.7, installed tmux manually, non-rpm version .

tf2server script only checks dependencies by checking for existence of installed RPM, instead of actual binary.

Would there be a way to check if tmux is found in path (tmux -V ?)

This would prevent the following message for every stop/start/update/etc command issued to tf2server:

```
[ WARN ] Stopping tf2-server: Checking dependencies: Dependency missing: tmux

Info! tf2 does not have sudo access. manually install dependencies

yum install tmux
```

**Comment by dgibbs64** [comment]
Good point. I didn't think about that :-P. I will have to address this

**Comment by jaredballou** [comment]
Why did you install outside the RPM? It's bad practice, and if it's installed without RPM it means we can't easily verify the requirements are actually met.

**Comment by JHiemenz** [comment]
The existence of the RPM isn't actually checking the file/program is
actually there and accessible, or correct version.  it is just checking RPM
install log for version installed at some point of history.
One can check if RPM is installed and continue to find another fatal error,
such as the program is missing for some reason.

For an executable program, like tmux, I prefer to check the program is
there (right now) and can be accessed, and what version it is.  Checking
output of 'which' show me the program is present, in my path:
[tf2@tf2 ~]$ which tmux
/usr/local/bin/tmux

checking version shows me I can execute and validate version is recent
enough:
[tf2@tf2 ~]$ tmux -V
tmux 2.1


and therein is the reason I do not use the RPM.  I do not wish to use an
outdated version of tmux.  The RPM version in CentOS epel for 6.7  is way
back at tmux version 1.6.

**Comment by iNilo** [comment]
Removed my RPM, build from source

Aug 06 01:00:03 csgo-server: CHECK: FATAL: Tmux is not installed
Aug 06 01:00:03 csgo-server: CHECK: FATAL: check_tmux.sh exiting with code: 1

**Comment by dgibbs64** [comment]
That's odd the code uses which to check for tmux :-/

**Comment by iNilo** [comment]
When manually executing the check_tmux.sh it seems to detect it. (which it should).

This might be a env/cron problem on my side

**Comment by dgibbs64** [comment]
Could be. Hopefully you can find a solution. Let us know if you think that there is anything we can do to in LGSM to resolve this type of issue.

**Comment by dgibbs64** [comment]
Please can I get feedback. Change to the development branch in your scripts and test for me to ensure this is working for you. Once you are happy I can merge. 

Thanks

**Comment by dgibbs64** [comment]
This is now in master i think i have fixed it :)
