### ISSUE TITLE
Cron csgo server update not work

### ISSUE THREAD

**Issue by rsgua** [dgibbs64/linuxgsm#737]
Hello, not want update server from cron
Cron command:
0 7 * * *  su - zm -c '/home/zm/csgoserver update' > /dev/null 2>&1
I try use user cron but server dont want update too.

**Comment by SM411** [comment]
What user is this cron job set up as? You could log in as zm and then set a cron like this by typing:

crontab -e and enter a line like this:

*/30 * * * * /home/zm/csgoserver update

**Comment by UltimateByte** [comment]
Does a manual update work ?
`./csgoserver update`

**Comment by rsgua** [comment]
Manual update work.
SM411
When i made your crontab. LOGS:
Mar 03 09:40:02 csgo-server: Monitor: SteamCMD is currently checking for updates
Mar 03 09:40:03 csgo-server: Update: Checking for update: SteamCMD
Mar 03 09:40:03 csgo-server: Monitor: When update is complete csgo-server will start
Mar 03 09:40:09 csgo-server: Update: Success! Checking for update: SteamCMD
Mar 03 09:40:10 csgo-server: Update: Current build: 1005716
Mar 03 09:40:11 csgo-server: Update: Available build: 1005716

**Comment by UltimateByte** [comment]
So there is just no update.

**Comment by rsgua** [comment]
yes. buy i run script on updated server...

**Comment by UltimateByte** [comment]
So what makes you think that the cronjob works ? Check your cron logs and script logs. There is absolutely no reason why it wouldn't work. However, if you want a reboot with your update when there is no update, use the force-update command.

**Comment by billndotnet** [comment]
Perhaps prefix your command with 'cd /home/steam' or your local equivalent. It's possible the shell environment under cron is missing some things the script requires to execute, or it calls relative paths to cwd.

**Comment by UltimateByte** [comment]
Assuming it's solved and it was a problem located between the chair and the screen. Re-open if needed.
