### ISSUE TITLE
steam_api_fail on port 27015

### ISSUE THREAD

**Issue by FlashModz** [dgibbs64/linuxgsm#741]
Hello,

My server Ark do not launch ,

Error  [S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
CreateBoundSocket: ::bind couldn't find an open port between 27015 and 27015

My ARKSERVER : 

	#!/bin/bash
	# ARK: Survivial Evolved
	# Server Management Script
	# Author: Daniel Gibbs
	# Website: http://gameservermanagers.com
	if [ -f ".dev-debug" ]; then
		exec 5>dev-debug.log
		BASH_XTRACEFD="5"
		set -x
	fi

	version="271215"

	#### Variables ####

	# Notification Email
	# (on|off)
	emailnotification="off"
	email="email@example.com"

	# Steam login
	steamuser="anonymous"
	steampass=""

	# Start Variables
	ip="149.202.88.144"
	updateonstart="off"

	fn_parms(){
	parms="TheIsland?listen"
	}

	#### Advanced Variables ####

	# Github Branch Select
	# Allows for the use of different function files
	# from a different repo and/or branch.
	githubuser="dgibbs64"
	githubrepo="linuxgsm"
	githubbranch="master"

	# Steam
	appid="376030"

	# Server Details
	servicename="ark-server"
	gamename="ARK: Survivial Evolved"
	engine="unreal4"

	# Directories
	rootdir="$(dirname $(readlink -f "${BASH_SOURCE[0]}"))"
	selfname="$(basename $(readlink -f "${BASH_SOURCE[0]}"))"
	lockselfname=".${servicename}.lock"
	filesdir="${rootdir}/serverfiles"
	systemdir="${filesdir}/ShooterGame"
	executabledir="${systemdir}/Binaries/Linux"
	executable="./ShooterGameServer"
	servercfgdir="${systemdir}/Saved/Config/LinuxServer"
	servercfg="GameUserSettings.ini"
	servercfgfullpath="${servercfgdir}/${servercfg}"
	servercfgdefault="${servercfgdir}/lgsm-default.ini"
	backupdir="${rootdir}/backups"

	# Logging
	logdays="7"
	gamelogdir="${systemdir}/logs"
	scriptlogdir="${rootdir}/log/script"
	consolelogdir="${rootdir}/log/console"

	scriptlog="${scriptlogdir}/${servicename}-script.log"
	consolelog="${consolelogdir}/${servicename}-console.log"
	emaillog="${scriptlogdir}/${servicename}-email.log"

	scriptlogdate="${scriptlogdir}/${servicename}-script-$(date '+%d-%m-%Y-%H-%M-%S').log"
	consolelogdate="${consolelogdir}/${servicename}-console-$(date '+%d-%m-%Y-%H-%M-%S').log"

	##### Script #####
	# Do not edit

	fn_getgithubfile(){
	filename=$1
	exec=$2
	fileurl=${3:-$filename}
	filepath="${rootdir}/${filename}"
	filedir=$(dirname "${filepath}")
	# If the function file is missing, then download
	if [ ! -f "${filepath}" ]; then
		if [ ! -d "${filedir}" ]; then
			mkdir "${filedir}"
		fi
		githuburl="https://raw.githubusercontent.com/${githubuser}/${githubrepo}/${githubbranch}/${fileurl}"
		echo -e "    fetching ${filename}...\c"
		if [ "$(command -v curl)" ]||[ "$(which curl >/dev/null 2>&1)" ]||[ -f "/usr/bin/curl" ]||[ -f "/bin/curl" ]; then
			:
		else	
			echo -e "\e[0;31mFAIL\e[0m\n"
			echo "Curl is not installed!"
			echo -e ""
			exit
		fi
		curl=$(curl --fail -o "${filepath}" "${githuburl}" 2>&1)
		if [ $? -ne 0 ]; then
			echo -e "\e[0;31mFAIL\e[0m\n"
			echo "${curl}"
			echo -e "${githuburl}\n"
			exit
		else
			echo -e "\e[0;32mOK\e[0m"
		fi	
		if [ "${exec}" ]; then
			chmod +x "${filepath}"
		fi
	fi
	if [ "${exec}" ]; then
		source "${filepath}"
	fi
	}

	fn_runfunction(){
		fn_getgithubfile "functions/${functionfile}" 1
	}

	core_functions.sh(){
	# Functions are defined in core_functions.sh.
	functionfile="${FUNCNAME}"
	fn_runfunction
	}

	core_functions.sh

	getopt=$1
	core_getopt.sh

	./arkserver details : 

	Change ports by editing the parameters in
	/home/ark/serverfiles/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini.

	Useful port diagnostic command:
	netstat -atunp | grep ShooterGame

	DESCRIPTION  DIRECTION  PORT   PROTOCOL  INI VARIABLE
	> Game       INBOUND    7777   udp       Port=7777
	> Query      INBOUND    27017  udp

What's the problems ?

Thanks you for help :)

**Comment by dgibbs64** [comment]
Your server cannot bind to the port. there is probably another server already using that port.

    CreateBoundSocket: ::bind couldn't find an open port between 27015 and 27015

**Comment by jeje031** [comment]
OK 

All are used :/

Yet I can assure you it is not used

Using binned.
4.5.1-0+UE4 7038 3077 402 5
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
CreateBoundSocket: ::bind couldn't find an open port between 27300 and 27300
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
CreateBoundSocket: ::bind couldn't find an open port between 27300 and 27300


Using binned.
4.5.1-0+UE4 7038 3077 402 5
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
CreateBoundSocket: ::bind couldn't find an open port between 27020 and 27020
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
CreateBoundSocket: ::bind couldn't find an open port between 27200 and 27020

**Comment by jeje031** [comment]
My console is Blank :/

[  OK  ] Starting ark-server: arkserver
arkserver@ns3030460:~$ ./arkserver console

ARK: Survivial Evolved Console
============================

Press "CTRL+b d" to exit console.
Warning! Do NOT press CTRL+c to exit.

Continue? [y/N]y
[  OK  ] Console ark-server: Starting
Using binned.
4.5.1-0+UE4 7038 3077 402 5
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110

only error Steam wtf

**Comment by jeje031** [comment]
Server Not Listed

arkserver@ns3030460:~$ ./arkserver update-functions
    fetching functions/update_functions.sh...OK
[ .... ] Updating functions
removed ‘/home/arkserver/functions/check_config.sh’
removed ‘/home/arkserver/functions/check_deps.sh’
removed ‘/home/arkserver/functions/check_ip.sh’
removed ‘/home/arkserver/functions/check_logs.sh’
removed ‘/home/arkserver/functions/check_root.sh’
removed ‘/home/arkserver/functions/check.sh’
removed ‘/home/arkserver/functions/check_steamcmd.sh’
removed ‘/home/arkserver/functions/check_systemdir.sh’
removed ‘/home/arkserver/functions/check_tmux.sh’
removed ‘/home/arkserver/functions/command_console.sh’
removed ‘/home/arkserver/functions/command_install.sh’
removed ‘/home/arkserver/functions/command_start.sh’
removed ‘/home/arkserver/functions/command_stop.sh’
removed ‘/home/arkserver/functions/command_validate.sh’
removed ‘/home/arkserver/functions/core_functions.sh’
removed ‘/home/arkserver/functions/core_getopt.sh’
removed ‘/home/arkserver/functions/core_messages.sh’
removed ‘/home/arkserver/functions/fix_glibc.sh’
removed ‘/home/arkserver/functions/fix.sh’
removed ‘/home/arkserver/functions/fix_steamcmd.sh’
removed ‘/home/arkserver/functions/info_config.sh’
removed ‘/home/arkserver/functions/install_complete.sh’
removed ‘/home/arkserver/functions/install_config.sh’
removed ‘/home/arkserver/functions/install_gsquery.sh’
removed ‘/home/arkserver/functions/install_header.sh’
removed ‘/home/arkserver/functions/install_logs.sh’
removed ‘/home/arkserver/functions/install_retry.sh’
removed ‘/home/arkserver/functions/install_serverdir.sh’
removed ‘/home/arkserver/functions/install_serverfiles.sh’
removed ‘/home/arkserver/functions/install_steamcmd.sh’
removed ‘/home/arkserver/functions/logs.sh’
removed ‘/home/arkserver/functions/update_check.sh’
removed ‘/home/arkserver/functions/update_dl.sh’
removed ‘/home/arkserver/functions/update_functions.sh’
[  OK  ] Updating functions
arkserver@ns3030460:~$ ./arkserver force-update
    fetching functions/core_functions.sh...OK
    fetching functions/core_messages.sh...OK
    fetching functions/core_getopt.sh...OK
    fetching functions/update_check.sh...OK
    fetching functions/check.sh...OK
    fetching functions/check_root.sh...OK
    fetching functions/check_systemdir.sh...OK
    fetching functions/check_logs.sh...OK
    fetching functions/check_steamcmd.sh...OK
[ .... ] Update ark-server: Checking for update    fetching functions/command_stop.sh...OK
    fetching functions/check_deps.sh...OK
    fetching functions/check_ip.sh...OK
    fetching functions/check_config.sh...OK
    fetching functions/info_config.sh...OK
[  OK  ] Stopping ark-server: RM-City
    fetching functions/update_dl.sh...OK
[  OK  ] Update ark-server: Updating RM-City
Redirecting stderr to '/home/arkserver/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Created shared memory when not owner SteamController_Shared_mem
OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK
Success! App '376030' already up to date.
    fetching functions/fix.sh...OK
    fetching functions/fix_steamcmd.sh...OK
    fetching functions/command_start.sh...OK
    fetching functions/check_tmux.sh...OK
    fetching functions/logs.sh...OK
[  OK  ] Starting ark-server: RM-City

Error : 

persist 

Using binned.
4.5.1-0+UE4 7038 3077 402 5
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110

**Comment by jeje031** [comment]
Security OK : 

root@ns3030460:~# cat /etc/security/limits.conf
# /etc/security/limits.conf
#
#Each line describes a limit for a user in the form:
#
#<domain>        <type>  <item>  <value>
#
#Where:
#<domain> can be:
#        - a user name
#        - a group name, with @group syntax
#        - the wildcard *, for default entry
#        - the wildcard %, can be also used with %group syntax,
#                 for maxlogin limit
#        - NOTE: group and wildcard limits are not applied to root.
#          To apply a limit to the root user, <domain> must be
#          the literal username root.
#
#<type> can have the two values:
#        - "soft" for enforcing the soft limits
#        - "hard" for enforcing hard limits
#
#<item> can be one of the following:
#        - core - limits the core file size (KB)
#        - data - max data size (KB)
#        - fsize - maximum filesize (KB)
#        - memlock - max locked-in-memory address space (KB)
#        - nofile - max number of open files
#        - rss - max resident set size (KB)
#        - stack - max stack size (KB)
#        - cpu - max CPU time (MIN)
#        - nproc - max number of processes
#        - as - address space limit (KB)
#        - maxlogins - max number of logins for this user
#        - maxsyslogins - max number of logins on the system
#        - priority - the priority to run user process with
#        - locks - max number of file locks the user can hold
#        - sigpending - max number of pending signals
#        - msgqueue - max memory used by POSIX message queues (bytes)
#        - nice - max nice priority allowed to raise to values: [-20, 19]
#        - rtprio - max realtime priority
#        - chroot - change root to directory (Debian-specific)
#
#<domain>      <type>  <item>         <value>
#

#*               soft    core            0
#root            hard    core            100000
#*               hard    rss             10000
#@student        hard    nproc           20
#@faculty        soft    nproc           20
#@faculty        hard    nproc           50
#ftp             hard    nproc           0
#ftp             -       chroot          /ftp
#@student        -       maxlogins       4
* soft nofile 100000
* hard nofile 100000
# End of file

end ----------------------------------------------------------------------------------------------------------

root@ns3030460:~# cat /etc/sysctl.conf
#
# /etc/sysctl.conf - Configuration file for setting system variables
# See /etc/sysctl.d/ for additional system variables.
# See sysctl.conf (5) for information.
#

#kernel.domainname = example.com

# Uncomment the following to stop low-level messages on console
#kernel.printk = 3 4 1 3

##############################################################3
# Functions previously found in netbase
#

# Uncomment the next two lines to enable Spoof protection (reverse-path filter)
# Turn on Source Address Verification in all interfaces to
# prevent some spoofing attacks
#net.ipv4.conf.default.rp_filter=1
#net.ipv4.conf.all.rp_filter=1

# Uncomment the next line to enable TCP/IP SYN cookies
# See http://lwn.net/Articles/277146/
# Note: This may impact IPv6 TCP sessions too
#net.ipv4.tcp_syncookies=1

# Uncomment the next line to enable packet forwarding for IPv4
#net.ipv4.ip_forward=1

# Uncomment the next line to enable packet forwarding for IPv6
#  Enabling this option disables Stateless Address Autoconfiguration
#  based on Router Advertisements for this host
#net.ipv6.conf.all.forwarding=1


###################################################################
# Additional settings - these settings can improve the network
# security of the host and prevent against some network attacks
# including spoofing attacks and man in the middle attacks through
# redirection. Some network environments, however, require that these
# settings are disabled so review and enable them as needed.
#
# Do not accept ICMP redirects (prevent MITM attacks)
#net.ipv4.conf.all.accept_redirects = 0
#net.ipv6.conf.all.accept_redirects = 0
# _or_
# Accept ICMP redirects only for gateways listed in our default
# gateway list (enabled by default)
# net.ipv4.conf.all.secure_redirects = 1
#
# Do not send ICMP redirects (we are not a router)
#net.ipv4.conf.all.send_redirects = 0
#
# Do not accept IP source route packets (we are not a router)
#net.ipv4.conf.all.accept_source_route = 0
#net.ipv6.conf.all.accept_source_route = 0
#
# Log Martian Packets
#net.ipv4.conf.all.log_martians = 1
#
fs.file-max=100000

# Disable IPv6 autoconf
net.ipv6.conf.all.autoconf = 0
net.ipv6.conf.default.autoconf = 0
net.ipv6.conf.eth0.autoconf = 0
net.ipv6.conf.all.accept_ra = 0
net.ipv6.conf.default.accept_ra = 0
net.ipv6.conf.eth0.accept_ra = 0

Not Change 

------------------------------------------------------------------------------------------------------------

Tested port : 

30015
20020
20030
20050
20060
45015
46015
47015
50015
60015
Not Work

Libc it's OK ( No Update package )
Debian 8 x64

**Comment by jeje031** [comment]
I try to place the GMOD LGSM server I have on the 50015 port and it works but with the ark even configs does not work: /

**Comment by jeje031** [comment]
this error continues

Using binned.
4.5.1-0+UE4 7038 3077 402 5
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110

But the server is running!
why this error is in the console and blocks console?

**Comment by UltimateByte** [comment]
Sorted this out ?
What about login to root, and run
`netstat -tulpn | grep :27015` ?
What about check your firewall rules ?

**Comment by UltimateByte** [comment]
Re-open if you still need help.
Otherwise, you can also post here : http://steamcommunity.com/groups/linuxgsm/discussions/

However, if you find a bug or a feature request related to this issue, feel free to re-open it.
