### ISSUE TITLE
[ts3server] Bugs showing in details command

### ISSUE THREAD

**Issue by faflfama** [dgibbs64/linuxgsm#744]
Hi,
I just created a new TS3 Server and the "details" command is showing 2 non working lines.

1. 
`ts3server Script Details`
`=========================================`
`/home/lgsm/ts3_TZF/functions/command_details.sh: line 149: [: : integer expression expected`
`Service name:        ts3-server`

2. 
`Backups`
`=================================`
`No Backups created`
`/home/lgsm/ts3_TZF/functions/command_details.sh: line 640: fn_parms: command not found`

I removed all functions and fetched them again, but nothing changed.

~Flam

**Comment by dgibbs64** [comment]
thanks for reporting this. The details command is going to have a massive spring clean in the next couple of months. Im gunna make the code a lot cleaner and simpler than it currently is. So these sort of errors should be reduced. So I will iron out this issue then :)

**Comment by faflfama** [comment]
Always happy if I can help ;)

**Comment by UltimateByte** [comment]
Yep, thanks for reporting..

2. is fixed
`./ts3server update-functions`

1. is on the todo list. https://github.com/dgibbs64/linuxgsm/blob/19f978e33032d71d76fa5d6d138707334ba78c89/functions/command_details.sh#L149

**Comment by faflfama** [comment]
Yep, The BackUp Line works now :)

**Comment by oalaro** [comment]
```
=================================
Teamspeak 3
Linux Game Server Manager
by Daniel Gibbs
http://gameservermanagers.com
Contributors: http://gameservermanagers.com/contib
=================================
    fetching functions/install_serverdir.sh...OK

Server Directory
=================================

/home/ts3server

Continue [y/N]y
mkdir: created directory `/home/ts3server/serverfiles'
    fetching functions/check_deps.sh...OK

Checking Dependecies
=================================
curl
ca-certificates
libstdc++6:i386
    fetching functions/install_ts3.sh...OK
    fetching functions/info_distro.sh...OK
downloading teamspeak3-server_linux_amd64-3.0.12.tar.bz2...OK
extracting teamspeak3-server_linux_amd64-3.0.12.tar.bz2...OK

```

When doing a fresh install it downloads 3.0.12 . Can be easily fixed by just updating after install

**Comment by UltimateByte** [comment]
@oalaro Thanks for reporting. You're telling me that i fixed the update number but forgot about the installer version check ?
We definitely need to make that in one unique function.
I'll check that out.

**Comment by UltimateByte** [comment]
@oalaro , The fix has been made for that, pull request done. Will be fixed soon. Thanks for reporting, i wouldn't have noticed otherwise.

**Comment by UltimateByte** [comment]
Fixed both :)
