### ISSUE TITLE
[mumbleserver] Stop doesnt work|Missing parameter in script

### ISSUE THREAD

**Issue by faflfama** [dgibbs64/linuxgsm#745]
Hi,
I just installed a new mumble Server and came up with 2 errors.

1. I have multiple IPs on my system so the script ofc asks me to set it to one. But there is no IP line in the script for it. If I insert it by myself it works.

2. If I try to stop the server with the script its says "OK" but the server wont shut down and I have to kill the process manually. 

Additionally When I saw it right, the source for the Linux Static Server files moved to github (https://github.com/mumble-voip/mumble/) instead of Sourceforge
~Flam

**Comment by UltimateByte** [comment]
Confirmed.

**Comment by dgibbs64** [comment]
I will need to do a major update to mumble server. Including adding an installer and update. I will address mumble issues all in one

**Comment by UltimateByte** [comment]
I'm on it currently, will take a lot of time to rework, but it's a challenge i wanna take. :)

**Comment by UltimateByte** [comment]
OK, i fixed everything, added install, update, monitoringfunctions, fixed start, stop and details functions...
Gosh, i need some sleep now ! :o))

The last thing to do is managing IP through the details function. I'll pull request after that.
