### ISSUE TITLE
valve.rc fail

### ISSUE THREAD

**Issue by radiumx3** [dgibbs64/linuxgsm#748]
Redirecting stderr to '/home/csgoserver/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Created shared memory when not owner SteamController_Shared_mem
OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK
Success! App '740' already up to date.
[ FAIL ] Update csgo-server: Applying valve.rc fix: Counter Strike: Global Offensive
[  OK  ] Update csgo-server: Applying workshop map fix: Counter Strike: Global Offensive
[ FAIL ] Starting csgo-server: Applying valve.rc fix: Counter Strike: Global Offensive
[  OK  ] Starting csgo-server: http://skins.zone Dedicated server

Is that error revelant ?

**Comment by UltimateByte** [comment]
@dgibbs64 May know more about that ?

**Comment by UltimateByte** [comment]
Did you solved this ?

**Comment by radiumx3** [comment]
Nope... still waiting for an update:/

**Comment by UltimateByte** [comment]
./csgoserver details ?

**Comment by UltimateByte** [comment]
Doesn't the server work ?
./csgoserver debug
and ls -al /home/csgoserver

**Comment by dgibbs64** [comment]
The "error" is just LGSM applying a fix for the server and does not tell me what the issue is.
Please provide all relevant info
http://steamcommunity.com/groups/linuxgsm/discussions/0/458604254471755996/

**Comment by dgibbs64** [comment]
closing as no update
