### ISSUE TITLE
Trying to modify UT2004.ini

### ISSUE THREAD

**Issue by cggit** [dgibbs64/linuxgsm#749]
Sorry for the stupid question...

I've been trying to get TAM installed and it seems like none of my changes to ut2004.ini are being recognized.

The files are in my users home directory in ~/serverfiles/system/ut2004.ini

Im restarting the server after every change but nothing happens... even if i delete all the contents of the file everything continues the same. 

Can someone please tell me what im missing?

not sure if its relevant but I'm running centos 6.7 and get a TMUX not installed warning even though I've installed it a number of different ways including the methods shown here https://github.com/dgibbs64/linuxgsm/issues/687.

**Comment by cggit** [comment]
Of course as soon as i post i find ut2k4server.ini which seems to be overriding ut2004.ini Im sorted but that would be good thing to have in the docs.

**Comment by FlashModz** [comment]
No trying install TMUX to Centos : 

http://steamcommunity.com/groups/linuxgsm/discussions/0/412446292777426341/

Install correctly TMUX and Enjoy ;)

**Comment by UltimateByte** [comment]
If you need more help, please post to the general support which is here : http://steamcommunity.com/groups/linuxgsm/discussions/

However, if you find a bug or a feature request related to this issue, feel free to re-open it.
