### ISSUE TITLE
[ FAIL ] Starting arma3-server: Applying steamclient.so general fix: ARMA 3

### ISSUE THREAD

**Issue by Hovercrafter** [dgibbs64/linuxgsm#753]
Hey i just install a arma3 Server on my Debian Linux Server and get this fail command. So can anyone help me?

Kind Regardes
Hovercrafter

**Comment by UltimateByte** [comment]
@dgibbs64 has been checking LGSM fixes recently, in order to make a huge revision. Might know why it could happen.

**Comment by dgibbs64** [comment]
Looks like an issue with applying the fix. so its probably a permissions issue

**Comment by UltimateByte** [comment]
No update on this ?

If you need more help, please post to the general support which is here : http://steamcommunity.com/groups/linuxgsm/discussions/

However, if you find a bug or a feature request related to this issue, feel free to re-open it.
