### ISSUE TITLE
I can't find the file sudoers (for a csgo server)

### ISSUE THREAD

**Issue by UnTizioACaso** [dgibbs64/linuxgsm#756]
I can't find the file sudoers
please help me i'm not an expert.
PC: Raspberry pi
OS: Raspbian 32bit

And i can't add the user csgoserver on the file
if you know the right commands please tell me this.
                                                                                                                                Thanks,UnTizioACaso

**Comment by UltimateByte** [comment]
Never heard of "sudoers"

For the permission issue you seem to have : 
chown -R csgoserver:csgoserver /home/csgoserver

**Comment by UltimateByte** [comment]
If you need more help, please post to the general support which is here : http://steamcommunity.com/groups/linuxgsm/discussions/

However, if you find a bug or a feature request related to this issue, feel free to re-open it.
