### ISSUE TITLE
error in installation on left 4 dead 2 linux server

### ISSUE THREAD

**Issue by edinamarca** [dgibbs64/linuxgsm#760]
Hello friends
I am writing to report them that appeared me an error during installation server left 4 dead 2 on my machine VPS with Ubuntu 15.10    (GNU/Linux 4.2.0-30-generic i686) , I hope someone of a solution or tell me if I pass the same as ah my
the error is as follows:

Error! App '222860' state is 0x602 after update job.

**Comment by UltimateByte** [comment]
https://github.com/dgibbs64/linuxgsm/wiki/Installer#failing-installations

**Comment by UltimateByte** [comment]
If you need more help, please ask here : http://steamcommunity.com/groups/linuxgsm/discussions/
