### ISSUE TITLE
check_permissions.sh : add a check framework

### ISSUE THREAD

**Issue by UltimateByte** [dgibbs64/linuxgsm#761]
check_permissions.sh : add a check framework
So that we can check a file or folder before trying to write on/in it.
https://github.com/dgibbs64/linuxgsm/blob/development/lgsm/functions/check_permissions.sh

**Comment by dgibbs64** [comment]
I have updated check_permissions.sh that it checks all files in rootdir. On my tests this took no time at all.

**Comment by UltimateByte** [comment]
Mh... Couldn't be problematic for non SSD + many files combo ?

**Comment by dgibbs64** [comment]
I tested on my main server that uses a HDD and completed almost instantly :)

**Comment by dgibbs64** [comment]
[ FAIL ] Update LGSM nmrih-server-7: Permissions issues found
	Infomation! The current user (nmrihserver) does not have ownership of the following files:
	User  Group  File
	root         root  /var/home/nmrihserver/skel
	root         root  /var/home/nmrihserver/skel/serverfiles
	root         root  /var/home/nmrihserver/skel/serverfiles/nmrih
	root         root  /var/home/nmrihserver/skel/serverfiles/nmrih/cfg
	root         root  /var/home/nmrihserver/skel/serverfiles/nmrih/cfg/nmrih-server.cfg
	root         root  /var/home/nmrihserver/skel/serverfiles/nmrih/cfg/sourcemod
	root         root  /var/home/nmrihserver/skel/serverfiles/nmrih/cfg/sourcemod/mapchooser.cfg
	root         root  /var/home/nmrihserver/skel/serverfiles/nmrih/cfg/sourcemod/funcommands.cfg
	root         root  /var/home/nmrihserver/skel/serverfiles/nmrih/cfg/sourcemod/plugin.motdgd_adverts.cfg
	root         root  /var/home/nmrihserver/skel/serverfiles/nmrih/cfg/sourcemod/rtv.cfg
	root         root  /var/home/nmrihserver/skel/serverfiles/nmrih/cfg/sourcemod/randomcycle.cfg
	root         root  /var/home/nmrihserver/skel/serverfiles/nmrih/cfg/motd_text.txt
	root         root  /var/home/nmrihserver/skel/serverfiles/nmrih/cfg/server.cfg
	root         root  /var/home/nmrihserver/skel/serverfiles/nmrih/cfg/motd.txt
	root         root  /var/home/nmrihserver/skel/serverfiles/nmrih/addons
	root         root  /var/home/nmrihserver/skel/serverfiles/nmrih/addons/sourcemod
	root         root  /var/home/nmrihserver/skel/serverfiles/nmrih/addons/sourcemod/plugins
	root         root  /var/home/nmrihserver/skel/serverfiles/nmrih/addons/sourcemod/plugins/motdgd_adverts.smx
	root         root  /var/home/nmrihserver/skel/serverfiles/nmrih/addons/sourcemod/scripting
	root         root  /var/home/nmrihserver/skel/serverfiles/nmrih/addons/sourcemod/scripting/motdgd_adverts.sp
	root         root  /var/home/nmrihserver/skel/serverfiles/nmrih/addons/sourcemod/scripting/include
	root         root  /var/home/nmrihserver/skel/serverfiles/nmrih/addons/sourcemod/scripting/include/SteamWorks.inc
	root         root  /var/home/nmrihserver/skel/serverfiles/nmrih/addons/sourcemod/configs
	root         root  /var/home/nmrihserver/skel/serverfiles/nmrih/addons/sourcemod/configs/admins_simple.ini
	root         root  /var/home/nmrihserver/skel/serverfiles/nmrih/addons/sourcemod/configs/maplists.cfg
	root         root  /var/home/nmrihserver/nmrihservermonitor
	root         root  /var/home/nmrihserver/serverfiles/nmrih/cfg/nmrih-server.cfg
	root         root  /var/home/nmrihserver/serverfiles/nmrih/addons/sourcemod/plugins/disabled/rockthevote.smx
	root         root  /var/home/nmrihserver/serverfiles/nmrih/addons/sourcemod/plugins/disabled/randomcycle.smx
	root         root  /var/home/nmrihserver/serverfiles/nmrih/addons/sourcemod/plugins/disabled/nominations.smx
	root         root  /var/home/nmrihserver/serverfiles/nmrih/addons/sourcemod/plugins/disabled/mapchooser.smx
	root         root  /var/home/nmrihserver/serverfiles/nmrih/addons/sourcemod/scripting/include/SteamWorks.inc
	root         root  /var/home/nmrihserver/serverfiles/nmrih/addons/sourcemod/bin/sourcemod.2.bms.so
	root         root  /var/home/nmrihserver/serverfiles/nmrih/addons/sourcemod/extensions/sdktools.ext.2.bms.so
	root         root  /var/home/nmrihserver/serverfiles/nmrih/addons/sourcemod/extensions/sdkhooks.ext.2.bms.so
	root         root  /var/home/nmrihserver/serverfiles/nmrih/addons/sourcemod/gamedata/core.games/engine.bms.txt
	root         root  /var/home/nmrihserver/serverfiles/nmrih/addons/sourcemod/gamedata/sdkhooks.games/game.bms.txt
	root         root  /var/home/nmrihserver/serverfiles/nmrih/addons/sourcemod/gamedata/sdktools.games/game.bms.txt
	    fetching core_exit.sh...OK

Output I just did fyi

**Comment by UltimateByte** [comment]
Well, why not then. ^^

**Comment by dgibbs64** [comment]
The only issue I had with my update to check_permissions.sh was I am unable to check group permissions as you can have multiple groups per user. Really complicates the checked but if a user has multiple groups then the admin is probably advanced enough not to need to check. 

Unless you think anything more needs to be added I think we can close this one

**Comment by UltimateByte** [comment]
Well i had the same issue with multiple groups, so if you used the same method as my initial code, it makes sense. There might be a way but i don't have a great idea on how to check multiple groups.
Framework isn't needed if it checks the whole folder btw, so yeah, we can close this. ^^
