### ISSUE TITLE
Serious Sam 3 :BFE ... steamclient.so missing

### ISSUE THREAD

**Issue by hurdad** [dgibbs64/linuxgsm#763]
Getting this error however steamclient.so is copied to ~/.steam/sdk32 and ~/.steam/bin32

I am running this directly from /home/ss3server/serverfiles/Bin/Sam3_DedicatedServer

[ss3server2@localhost Bin]$ ./Sam3_DedicatedServer 
cat: /etc/debian_version: No such file or directory
LOG:  Loaded "/home/ss3server/serverfiles/Bin/GameEnv_Steam.so".
INF:  GameEnv API: Steam
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
dlopen failed trying to load:
steamclient.so
with error:
steamclient.so: cannot open shared object file: No such file or directory
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.

**Comment by UltimateByte** [comment]
Hey there,
Did you try to copu steamclient.so to  /home/ss3server/serverfiles/Bin/ ?

**Comment by hurdad** [comment]
yes, it is already there when you install the game

**Comment by dgibbs64** [comment]
I had an issue with this recently when testing out the server again. I was unable to figure it out though. :-/ maybe an update the game dev made broke the server.

**Comment by hurdad** [comment]
this is working now with latest steam update
