### ISSUE TITLE
Backup function: exclude backups directory

### ISSUE THREAD

**Issue by pix0wl** [dgibbs64/linuxgsm#764]
Hi,

the backup function includes per default the backups dir.
So every new backup includes the old backups and is growing unnecessarily.

**Comment by UltimateByte** [comment]
Hi,
For now, the backup hasn't been designed to be run multiple times, it's something that you should use once to transfer your server.
However, i wish to improve it, and i could code your suggestion before anything else.

Here is an idea of what i've got in mind afterwards : 
https://github.com/dgibbs64/linuxgsm/issues/716

**Comment by UltimateByte** [comment]
OK, after having a look at the code, the backup directory should already be excluded from the backup.
https://github.com/dgibbs64/linuxgsm/blob/master/functions/command_backup.sh#L56

So are you sure that you're experiencing that issue ?
With what game ? And what version of LGSM ? Can you try

**Comment by dgibbs64** [comment]
yeah i designed the code with not backing up the backups in mind. Would be pretty dumb to backup the backups :P

**Comment by UltimateByte** [comment]
@pix0wl You sir were actually right, so thanks ! :)
It's fixed, and you gained an improved display with file size information.

To get the update : 
`./gameserver update-functions`
or
`./gameserver uf`
