### ISSUE TITLE
Security: Rust server sends RCON password insecurely with e-mail

### ISSUE THREAD

**Issue by Flightkick** [dgibbs64/linuxgsm#766]
`./rustserver test-email` sends the command line argumens along with the e-mail, this includes the RCON password.

This means an attacker could use a MITM attack and other methods to retrieve the password.

Solution: Either don't send the command line arguments with the e-mails or replace the password by a mask.

EDIT: Just checked the code and it seems to be more secure to remove the executable + args from the script. Also this issue is related to all email notifications for servers with an (RCON) password in the arguments, not only test e-mails and not only applicable to Rust.

**Comment by UltimateByte** [comment]
You're right, thanks :)

**Comment by dgibbs64** [comment]
The development version has some major updates to sending email. However I will take this on board :). Thanks
