### ISSUE TITLE
Rust autoupdate

### ISSUE THREAD

**Issue by Slyvester1** [dgibbs64/linuxgsm#774]
How can I autoupdate my rust server? I know just about every thursday the server needs an update, so Is there something i can do to update without having to do /rustserver update command manually?

**Comment by marvinl97** [comment]
You can use a crontab. It is an automated job. Type "crontab -e"  into your shell (a text editor should be opened). Then add this line at the end of the file:
`0 6 * * 4 /home/rustserver/rustserver update > /dev/null 2>&1 >/dev/null 2>&1`
This will update your server on every thursday at 6am. I don't know if the path is right. And you probably want another time. The first number defines the minute and the second the hour. You could also search for a "crontab generator" on the internet. Don't forget to save the file in the end. You maybe have to restart your whole server or run the following command as root to make it work:
`service cron restart`
I'm not totally sure. I hope I could help and what I said isn't wrong. ^^

**Comment by UltimateByte** [comment]
Yeah, i rewrote like 70% of the wiki so that all the little things like that are explained. ^^
