### ISSUE TITLE
Required package : util-linux

### ISSUE THREAD

**Issue by phytopius** [dgibbs64/linuxgsm#777]
When i use the ./csgoserver command i get the error

/opt/csgoserver/functions/core_getopt.sh: line 68: column: command not found

Same goes for ./csgoserver status
Also when i enter ./csgoserver details i get no information except for the command-line parameters. 
Everything else says command not found.

I installed the server today with    wget http://gameservermanagers.com/dl/csgoserver

**Comment by UltimateByte** [comment]
"The column command is part of the util-linux-ng package and is available from ftp://ftp.kernel.org/pub/linux/utils/util-linux-ng/."
http://linux.die.net/man/1/column

`apt-get install util-linux`

**Comment by UltimateByte** [comment]
What distro are you using for the record ?
That may be something we need to add to the dependencies.

**Comment by phytopius** [comment]
Thanks I will try that.
I use Debian 8.4 Jessie.

**Comment by phytopius** [comment]
Hello. Now it is working
I installed   bsdmainutils with
apt-get install bsdmainutils

**Comment by dgibbs64** [comment]
how odd maybe bsdmainutils is what is required in debian however util-linux in Ubuntu and CentOS. Need this confirming then I will update the instructions

**Comment by UltimateByte** [comment]
For the record, we had similar issues, probably with minimal OS installs.
https://github.com/dgibbs64/linuxgsm/issues/613
https://github.com/dgibbs64/linuxgsm/issues/864

**Comment by dgibbs64** [comment]
bsdmainutils is now a requirement for LGSM
