### ISSUE TITLE
Arma 3 28706 Segmentation fault

### ISSUE THREAD

**Issue by DevenDoes** [dgibbs64/linuxgsm#779]
I have looked around, and there seems to be no solution.

Here is my details.

http://pastebin.com/mSqV0Y8V

**Comment by UltimateByte** [comment]
Please, use pastebing for logs.
I'm not a specialist of ARMA, but i'll look for 2 things first. Missing stuff : 

0:20:38 Arma 3 DLC Bundle | dlcbund le | true | NOT FOUND | | |
0:20:38 Arma 3 | A3 | true | NOT FOUND | |

And "/home/armadiv/altislife/server files/cfg/arma3-server.server.cfg"

Should probably be "home/armadiv/altislife/serverfiles/cfg/arma3-server.server.cfg"

**Comment by lnxprof** [comment]
@DevenDoes: Have you [created this missing directory?](http://steamcommunity.com/groups/linuxgsm/discussions/0/490121928340799753/#c490121928346957463)  It looks from your pastebin that you're directory should be:

`mkdir -p /home/armadiv/altislife/.local/share/Arma\ 3`

**Comment by UltimateByte** [comment]
OP, did you solve this ? Closing, re-open if needed.
