### ISSUE TITLE
bzip2 requirement

### ISSUE THREAD

**Issue by UltimateByte** [dgibbs64/linuxgsm#780]
bzip2 is required at least for ts3server
We should add this to the requirements on the website.
We can also make a package check for it.

**Comment by dgibbs64** [comment]
bzip2 will be the default for all archives moving forward and is currently implemented in the dev branch. So this will be done then :)....Also I just got my internet back yay so should be able to get back to development in the next few days

**Comment by UltimateByte** [comment]
@dgibbs64 I forgot about this issue :o))
I guess time has come !

**Comment by dgibbs64** [comment]
see #977
