### ISSUE TITLE
DSTsever connection refused

### ISSUE THREAD

**Issue by romanzdan** [dgibbs64/linuxgsm#787]
Hi, i have such issue
![jn4xjsw](https://cloud.githubusercontent.com/assets/14034898/14750349/0616170a-08cd-11e6-9e4e-b2da9067ac0c.png)

**Comment by UltimateByte** [comment]
Hi,
Logs ?

**Comment by romanzdan** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/14034898/14752440/ee885c46-08d7-11e6-83a9-356432ab2f5c.png)
I've install gcc, but get error `wget ftp://gd.tuwien.ac.at/gnu/gcc/releases/gcc-4.6.2/gcc-4.6.2.tar.gz
tar xzf gcc-4.6.2.tar.gz
cd gcc-4.6.2
./contrib/download_prerequisites
cd ..
mkdir objdir
cd objdir
$PWD/../gcc-4.6.2/configure --prefix=/opt/gcc-4.6.2
make
make install`
![screenshot_4](https://cloud.githubusercontent.com/assets/14034898/14752473/21cdad72-08d8-11e6-8464-b26968f905e2.png)

**Comment by UltimateByte** [comment]
OK but you didn't answer.
BTW, Distro and logs ? It's the minimum to give when you make any issue about anything and hope for a relevant answer.

**Comment by romanzdan** [comment]
CentOS-6-amd64-ispmgr5
Logs - https://drive.google.com/file/d/0B89Sb2bYzD9ocGphNjVEVnU0UWs/view?usp=sharing

**Comment by UltimateByte** [comment]
"/usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ./dontstarve_dedicated_server_nullrenderer)"

"Recommended Distos :  CentOS 7 or greater."
https://gameservermanagers.com/lgsm/dstserver/

https://github.com/dgibbs64/linuxgsm/wiki/Glibc

**Comment by romanzdan** [comment]
THX, how to install Glibc Fix?

**Comment by UltimateByte** [comment]
I guess we can close. Keys to answer that are into the wiki.
