### ISSUE TITLE
teamspeak install issue

### ISSUE THREAD

**Issue by DChrilz** [dgibbs64/linuxgsm#794]
I'm at the install part and i get this:
ts3server@ChristianH3:~$ ./ts3server install
mkdir: cannot create directory '/home/ts3server/functions': Permission denied
    fetching functions/core_functions.sh...FAIL

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file
Warning: /home/ts3server/functions/core_functions.sh: No such file or
Warning: directory
curl: (23) Failed writing body (0 != 5177)
https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/functions/core_functions.sh

I did the chmod +x and followed the other steps on the site.

then i tried since it said permision denied to run it as root and got this:

root@ChristianH3:/home/ts3server# ./ts3server install
    fetching functions/core_functions.sh...OK
    fetching functions/core_messages.sh...OK
    fetching functions/core_getopt.sh...OK
    fetching functions/command_install.sh...OK
    fetching functions/check.sh...OK
    fetching functions/check_root.sh...OK
[ FAIL ] Do NOT run this script as root!

**Comment by dgibbs64** [comment]
you cannot run as root as per FAQ. you have not setup your user correctly or you are having a permissions issue. If you are unsure about users and permissions I highly recommend learning as its one of the basics of Linux and will help you resolve many issues. I recommend running ls -al on /home/ts3server/functions/

**Comment by UltimateByte** [comment]
Yep, your ts3server don't seem to own its folder.
Definitely learn chmod, chown, user management and so on. And please, don't try to run a teamspeak or a game server (which are not good security example) as root, don't even think about it, unless you want your server to get rekt by a 12yo hacker.

Running this as root might help : 
`chown -R ts3server:ts3server /home/ts3server`

**Comment by DChrilz** [comment]
Thanks for the respond guys, pure stupidity didn't make me consider the fact that i'd need to set the permissions on the account for the folder. I just assumed the setup guide on the page would work..

Again thanks.

**Comment by UltimateByte** [comment]
It would have worked if you logged to the user before downloading and running the script.

Good you got it solved. Have fun with it ;)
