### ISSUE TITLE
I can not install CS GO server

### ISSUE THREAD

**Issue by SMOKE23REG** [dgibbs64/linuxgsm#796]
I can not install CS GO server writes just such a mistake. What to do?

csgoserver@debian-7-32bit:~$  wget http://gameservermanagers.com/dl/csgoserver
--2016-04-26 02:39:33--  http://gameservermanagers.com/dl/csgoserver
Resolving gameservermanagers.com (gameservermanagers.com)... 104.31.92.238, 104.31.93.238, 2400:cb00:2048:1::681f:5dee, ...
Connecting to gameservermanagers.com (gameservermanagers.com)|104.31.92.238|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://gameservermanagers.com/dl/csgoserver [following]
--2016-04-26 02:39:34--  https://gameservermanagers.com/dl/csgoserver
Connecting to gameservermanagers.com (gameservermanagers.com)|104.31.92.238|:443... connected.
GnuTLS: A TLS fatal alert has been received.
Unable to establish SSL connection.
csgoserver@debian-7-32bit:~$

**Comment by SMOKE23REG** [comment]
And if I myself take off the file on the ftp server and am trying to say, while setting all libs and all that is needed, I wrote this:
Checking Dependecies
=================================
grep: The -P option is not supported: libpcre.so.3 is not available
curl
grep: The -P option is not supported: libpcre.so.3 is not available
ca-certificates
grep: The -P option is not supported: libpcre.so.3 is not available
tmux
grep: The -P option is not supported: libpcre.so.3 is not available
libstdc++6:i386
[ WARN ] Checking dependencies: Dependency missing: curl ca-certificates tmux libstdc++6:i386

Info! csgoserver does not have sudo access. manually install dependencies

sudo dpkg --add-architecture i386; sudo apt-get install curl ca-certificates tmux libstdc++6:i386

**Comment by UltimateByte** [comment]
This github is made for developers. For general support, please use the steam group.

Obviously, your server can't make a TLS connection. So i'd verrify the date or anything that can prevent a secure connection to occur.

Secondly, you didn't install required dependencies.

In the end, i'll be a bit rude, i'd suggest you to move your head away from your butt and solve your 2 first issues, then to try again.

If you need further help, please come up here.
http://steamcommunity.com/groups/linuxgsm/discussions/0/
