### ISSUE TITLE
unable to start csgo-server (using docker)

### ISSUE THREAD

**Issue by jffz** [dgibbs64/linuxgsm#799]
Hi, just trying your scripts but seems to fail without any input to help me debuggin it :+1: 

./csgoserver start
[ FAIL ] Starting csgo-server: Applying botprofile.db fix: Counter Strike: Global Offensive
[ FAIL ] Starting csgo-server: Applying valve.rc fix: Counter Strike: Global Offensive
[ FAIL ] Starting csgo-server: Unable to start csgo-server

Nothing more in logs

**Comment by UltimateByte** [comment]
Hi,

Really ? Nothing in log/console ?

**Comment by jffz** [comment]
cat log/console/csgo-server-console.log
Console logging disabled: Bug in tmux 1.8 breaks logging
http://gameservermanagers.com/tmux-upgrade
Currently installed: tmux 1.8

**Comment by UltimateByte** [comment]
Well you got your answer. Too old TMUX version.

What's your distro ?

**Comment by jffz** [comment]
ubuntu 14.04, i'm currently trying wiht fix in the previous url

**Comment by UltimateByte** [comment]
We'd need @dgibbs64 who is more likely to know more about Ubuntu than me !
(Debian for the win !!)

**Comment by jffz** [comment]
I'm used to run csgo servers on debian but triied ubuntu for lgsm, i'm gonna try on debian just to be sure (i sent you a mail through your website)

**Comment by UltimateByte** [comment]
Works flawlessly on Debian for me, no workaround crap to do.
I don't get how the heck ubuntu can still use tmux 1.8...
About your mail, i think there's no need to PM outside of Github, and as i'm making a lot of things currently, i won't be any faster using another communication method. And on top of that, i'm not using ubuntu, and i can't recommend using dockers with LGSM from the feedbacks i've read.

**Comment by jffz** [comment]
OK, i will do it on debian without lgsm then. Could have saved me some times :p 

I just fast looked at issues and found 1 topic talking about docker, could you give me those feedbacks url to check what's wrong please ?

**Comment by UltimateByte** [comment]
I don't get it. If you go on debian you can use LGSM without any trouble. It's supposed to work fine with ubuntu too, as the creator of this script is mainly using it, so he did most of the testing with ubuntu. 
Why would you need dockers ?

**Comment by jffz** [comment]
Still having the same issue with debian (on docker) so maybe it's docker related, i'm actally looking into what's locking lgsm into docker.

Why i want to use docker ? Because of a little project :D

**Comment by UltimateByte** [comment]
As i said, dockers are untested, so not advised for now. The problem isn't the OS, it's the docker.
Try it without a docker and it should work.
Unless you got suggestions on how to fix LGSM in order for it to work with it, then either forget dockers or forget LGSM.

**Comment by jffz** [comment]
Yes i know, i'm doin it without lgsm for now but i'll check later what's wrong with docker + lgsm adn tell you if i find something interesting.

**Comment by UltimateByte** [comment]
Yup, can be interesting, you're not the first one willing to use dockers ! :)

**Comment by dgibbs64** [comment]
I tried docker a few times but I personally dont have the time or need to learn it currently. I do welcome users to submit bug fixes for docker if required.
