### ISSUE TITLE
Webgui - enhancement

### ISSUE THREAD

**Issue by spot88** [dgibbs64/linuxgsm#800]
Maybe merge it with this project: http://www.bgpanel.net/
Would be awesome to just have a webgui that controlled the servers. 

Should not be hard to implement since most of it it's done already.

**Comment by m0gL1** [comment]
hi there,
just join our ts3 and lets have a small talk containing a small demo, because we´re working on a common webinterface solution for lgsm. If you like it, may we should think/work on together?!

kind regards
m0gL1

**Comment by JimTR** [comment]
I wrote one but never mind :8ball:

**Comment by faflfama** [comment]
Also wanna share it @JimTR?

**Comment by spot88** [comment]
x2

**Comment by dgibbs64** [comment]
I have no plans for a web interface however i welcome attempts for other developers to create one. I am also willing to assist in getting it work if LGSM requires some tweaking.

**Comment by JimTR** [comment]
It will require tweaks as my dev code is using the pre .sh version ... this also gives me some problems with how to call a script from a local/remote server (has it got an extension of sh or not). The web interface, which there are some screen shoots still uses the older non .sh setup so I guess it would not be good to share

**Comment by UltimateByte** [comment]
Ideally, the interface would be able to handle LGSM updates. 
But even more importantly, can a PHP interface work with user based servers as we got currently ?

**Comment by spot88** [comment]
Here is almost a perfekt version, just need some tweaking so it works with you. 
https://github.com/warhawk3407/bgpanelv2

**Comment by dgibbs64** [comment]
@JimTR if you want to create a specific issue for your web interface that we could use to work together that woudl be helpful. Best to include all the info about the web interface and links to the GitHub repo. You can also outline what would be required to help you do this. The same applies to bgpanel. I am happy to help were I can to get LGSM working with your web interface projects and am happy to accept pull requests related to the web interface as well. 

So yeah create a single issue for your web interfaces and will see what happens :)
