### ISSUE TITLE
Don't Starve: Configuration files incomplete / incorrect

### ISSUE THREAD

**Issue by Flightkick** [dgibbs64/linuxgsm#801]
Just installed a DST dedicated server, the config files generated are in the wrong place (documentation on their website is also outdated).

DST now uses clusters i.e.: DoNotStarve/Cluster_X

The settings.ini is generated inside .klei/DoNotStarve but contains cluster specific settings which should be generated in .klei/DoNotStarve/Cluster_X/cluster.ini

Also, to host a public dedicated server an Steam Authentication code should be generated and placed in .klei/DoNotStarve/Cluster_X/cluster_token.ini (this is also cluster specific).

With the files currently generated you can not launch a DST public dedicated server out of the box.

**Comment by dgibbs64** [comment]
Yeah DST is pretty broken current as the developers made major changes to the way the server works. I have not had any time to resolve this. However if you are willing to make the fixes I will merge them in to LGSM as its gunna take me a long time get resolve.

see https://github.com/dgibbs64/linuxgsm/issues/693

**Comment by dgibbs64** [comment]
Closing this as dst does work with LGSM I have updated a link to installation instructions for configuration that the admin will need to complete. DST is one of the most complicated dedi servers I have come across
