### ISSUE TITLE
Login with account rather than anonymous

### ISSUE THREAD

**Issue by DeadIntermediate** [dgibbs64/linuxgsm#804]
How can I have GSM login with an account than anonymous?

Reason is because CSGO server require an account that has the game.

**Comment by UltimateByte** [comment]
As far as i remember, csgo doesn't require a login other than anonymous.
On the other hand, it requires GSLT. https://github.com/dgibbs64/linuxgsm/wiki/Game-Server-Login-Token

But if you're asking this question, you probably didn't know that many of the settings are set within the csgoserver script itself. So take a moment to see what's inside of it. ;)
