### ISSUE TITLE
[ARK] stop/update user notification 

### ISSUE THREAD

**Issue by TOXid** [dgibbs64/linuxgsm#805]
How to implement an alert gamers about upcoming shutdown for restart/update?

**Comment by UltimateByte** [comment]
Would be hard to implement. Just plan a reboot per week using cronjobs and put the reboot date and time of that reboot in your server description. Works fine for a guy i host a server for. If your server is good enough, one reboot per week is enough.

**Comment by TOXid** [comment]
Unfortunately restarts plan does not apply to this game. Developers often release updates that are not scheduled. 
The mechanics of this game is that during sudden shutsown server players can lose game progress on which they worked for months.
I supose it is possible to make notice through Rkon, like in this tool https://github.com/FezVrasta/ark-server-tools

**Comment by UltimateByte** [comment]
Well, i agree it would benefit Ark to have such a functionality, but until one has time to get into it, you can still make manual updates and talk to your players before updating. Or, have auto update every hour and get some work fucked, but blame ark team for unplanned update when it happens. :o))

**Comment by UltimateByte** [comment]
How does official ark servers manage this ?

**Comment by UltimateByte** [comment]
Well, closing this, as the true feature would be to implement RCON into LGSM.
