### ISSUE TITLE
[Rust] console bash script

### ISSUE THREAD

**Issue by Liberateur** [dgibbs64/linuxgsm#811]
Hey, hi guys !

I see the issue of multiple for Rust console, so i have no hope... But, have you another way to send the console command with a bash script ? ( No oxide )

Have a nice day !

**Comment by UltimateByte** [comment]
Heya
"multiple for Rust console"
I'm sorry but it doesn't mean anything for me.

You might have an issue running multiple rust servers, as explained here (with the fix) in the 10) part.
http://oxidemod.org/threads/setting-up-a-rust-server-with-linux-and-lgsm.16528/

And for sending console commands to the server, as Rust doesn't offer a proper console, the only way is to use RCON, either ingame, or a tool like Rusty. However, those solutions are manual ones.
LGSM won't support RCON until we find an efficient, reliable, "updatable" way to do so. Afterwards, it'll allow us to add interesting functions before the "stop" function for example, like running a "save" command. It could also allow checking the amount of connected players before a reboot.
