### ISSUE TITLE
CSGO plugin support?

### ISSUE THREAD

**Issue by DeadIntermediate** [dgibbs64/linuxgsm#812]
Does LGSM support plugins for CSGO? Lets say like a surf server?

**Comment by jaredballou** [comment]
As in SourceMod plugins?

**Comment by UltimateByte** [comment]
LGSM is neutral to game plugins. It won't prevent you from installing them.

**Comment by UltimateByte** [comment]
If you were talking about workshop, it also supports workshop natively, you have to edit csgoserver file for that.

I think i answered your question.
We plan adding optional and automated sourcemod installation after the next major update https://github.com/dgibbs64/linuxgsm/issues/631

I think i answered your question, but feel free to re-open if needed.
