### ISSUE TITLE
Rust server start, but with no connectivity !

### ISSUE THREAD

**Issue by Groumf44** [dgibbs64/linuxgsm#813]
Hi,

After one hour of search, i didn't found any help to my issue. I apology in advance for my very bad english (i'm french).

My issue is : I start the server with the commande ./rustserver start. It seems good, but the server is unreachable.

The command ./rustserver monitor says this : 

`[ FAIL ] Monitor rust-server: Querying port: 62.210.146.8:28015 : ERROR: Unable to receive``

The command ./rustserver details | sed -e 's/password "[^"]*/password "--stripped--/'
says :
```
Distro Details
=====================================================================================================================
Distro:    Debian GNU/Linux 8.4 (jessie)
Arch:      x86_64
Kernel:    3.16.0-4-amd64
Hostname:  mdagorne.fr
tmux:      tmux 1.9
GLIBC:     2.19

Performance
=====================================================================================================================
Uptime:    0d, 0h, 43m
Avg Load:  0,25, 0,22, 0,17

Mem:       total   used   free
Physical:  31G     2,1G   29G
Swap:      976M    0B     976M

Storage
=====================================================================================================================
Filesystem:   Sys.
/dev/sda4
Total:        de
1,6T
Used:         fichiers
79G
Available:    Taille
1,4T
Serverfiles:  3,0G

Rust Server Details
=====================================================================================================================
Server name:  Rust
Server IP:    62.210.146.8:28015
Tick rate:    30
Status:       ONLINE

rustserver Script Details
=====================================================================================================================
Service name:        rust-server
rustserver version:  230215
User:                rustserver
GLIBC required:      2.15
Email notification:  off
Update on start:     off
Location:            /home/rustserver
Config file:         /home/rustserver/serverfiles/server/rust-server/cfg/server.cfg

Backups
=====================================================================================================================
No Backups created

Command-line Parameters
=====================================================================================================================
./RustDedicated -batchmode +server.ip 62.210.146.8 +server.port 28015 +server.tickrate 30 +server.hostname "Rust" +server.identity "rust-server"  +server.maxplayers 50 +server.worldsize 4000 +server.saveinterval 300 +rcon.ip 62.210.146.8 +rcon.port 28016 +rcon.password "--stripped--" -logfile "gamelog-2016-05-11-19-42-28.log"

Ports
=====================================================================================================================
Change ports by editing the parameters in
rustserver script

Useful port diagnostic command:
netstat -atunp | grep Rust

DESCRIPTION   DIRECTION  PORT   PROTOCOL
> Game/Query  INBOUND    28015  tcp/udp
> RCON        INBOUND    28016  tcp


Status: ONLINE
```

I also check if the port was listening with the command netstat -atunp | grep Rust with no success. My ports are open on iptables.

Does someone have an idea ?

Thank you very much in advance.
Groumf44

**Comment by reesey275** [comment]
Is this machine on your local network or on a remote network?  Are you 100% sure that you have opened the ports in the firewall?

iptables -A INPUT -m state --state NEW -m tcp -p tcp --dport 28015 -j ACCEPT
iptables -A INPUT -m state --state NEW -m udp -p udp --dport 28015 -j ACCEPT
iptables -A INPUT -m state --state NEW -m tcp -p tcp --dport 28016 -j ACCEPT
service iptables save 

I've had problems in the past with getting the server to show up in the game browser as well. 

Have you tried to connect directly to the server?

**Comment by Groumf44** [comment]
Thanks a lot for your answer.

I'm 100% sure that the ports are open. I tried your iptables commands, but it don't change anything.

It is a remote machine hosted by online.net (Debian 8, Xeon E3 1230v3 and 32 Gb of RAM).

I also tried to connect directly to the server ingame, but as you imagine, it don't works :'(

**Comment by UltimateByte** [comment]
And the logs dude ?
What does the logs say ?
cat serverfiles/game*.log

**Comment by reesey275** [comment]
^
What he said!

Is this a clean server or did you copy saved game files over from another machine?  

I ran a test to see if I was able to connect as well and it looks like those ports are either still blocked or the server is not actually running.

**Comment by Groumf44** [comment]
Here are the logs : http://pastebin.com/7d0NcP0S

(Sorry, i've forgotten it)

**Comment by UltimateByte** [comment]
Put back an rcon password.
90% chances it'll solve the issue.
Rust doesn't like you to remove the rcon password and will fuckup at boot if you remove it.

**Comment by UltimateByte** [comment]
I'm pretty sure it's solved, re-open if needed.

**Comment by PuggerHugger** [comment]
Have the exact same issue. Also debian 8.4, no idea what to do.

**Comment by UltimateByte** [comment]
@PuggerHugger Then go post your own thread in the appropriate location : http://steamcommunity.com/groups/linuxgsm/discussions/0/

**Comment by Skyborder** [comment]
iptables: No chain/target/match by that name.
