### ISSUE TITLE
Arma 3 Server segfaults on start-up

### ISSUE THREAD

**Issue by dr-waterstorm** [dgibbs64/linuxgsm#815]
Hi,

first I wanted to thank you for your effort in creating all those game-server managers :-)

Regarding my found "bug": I just wanted to install an Arma 3 Server on my Linux dedicated machine and it segfaulted on startup. It took me some time to figure out what happened and I have to say the good old segfault is not very meaningful.

The problem is:
You have a script called "fix_arma.sh", which creates an Arma 3 profile folder in {$rootdir}/.local/share/. However here are multiple issues here, first your script creates (at least on ubuntu 14.04) a folder called "Arma\ 3" instead of "Arma 3" and second Arma needs to have an additional folder called "Arma 3 - Other Profiles" and third Arma needs to have those folder in the home dir of the user running the game server instead of the root of the gameserver itself. 

So the command creating those folders should be:

`mkdir -p ~/".local/share/Arma 3" && mkdir -p ~/".local/share/Arma 3 - Other Profiles"`
 
This created the Arma 3 folders in my home dir and everything started to work.

It would be nice if you can fix your script to make the game server manager work right out of the box again. 

I hope this will help other people trying to use the gameservermanager on Linux :). And thanks again for your efforts!!

**Comment by dgibbs64** [comment]
Should be easy to resolve. I will fix on the development branch as it will be released soon

**Comment by igeighty** [comment]
Thanks Daniel. it took me a while to track where that "Arma\ 3" folder was coming from :)

**Comment by UltimateByte** [comment]
@dgibbs64 So was it released with the last major update ?

**Comment by igeighty** [comment]
i just did a reinstall using the arma3server script, and the folder `.local/share/Arma\ 3/` is still present.

on the first run of the server is did create the required folders..
`/.local/share/Arma 3`
`/.local/share/Arma 3 - Other Profiles`

i did not have to create these manually using
`mkdir -p ~/".local/share/Arma 3" && mkdir -p ~/".local/share/Arma 3 - Other Profiles"` 
the server had created a default player.armaprofile when was initially run in the folder
`.local/share/Arma 3 - Other Profiles/Player/player.armaprofile` this default profile does not contain many variables, and needs to be edited manually to suit the individual server.

I then went through and edited the default to contain a more detailed profile containing settings for the difficulty and other parameters. from this example https://community.bistudio.com/wiki/server.armaprofile#Linux

As far as i can see the .armaprofile file is created by default in 
`.local/share/Arma 3 - Other Profiles/Player/`
on initial startup when no `-NAME` value is specified in the startup parameters.

This default player.armaprofile is being created when using `./arma3server start` as there is none specified in the parms value in the arma3server script ?
`parms="-netlog -ip=${ip} -port=${port} -cfg=${networkcfgfullpath} -config=${servercfgfullpath} -mod=${mods} -servermod=${servermods} -bepath=${bepath} -autoinit -loadmissiontomemory"`

this default .profile is still being loaded by the server on startup, which is the same behaviour when running the server executable without any parameters manually.

i am sorry if i am not explaining it properly, i am more a point to a diagram guy than a wordsmith :)

cheers for your ongoing work guys.
please feel free to contact me if you need testing done,

**Comment by dgibbs64** [comment]
I have hopefully made the required changes. Please let me know if this does what is required or anymore changes are needed

**Comment by igeighty** [comment]
Thanks Daniel, the new script does not create the `.local/share/Arma\ 3/`directory.
and the correct
`/.local/share/Arma 3
/.local/share/Arma 3 - Other Profiles`
are created. now i just have to get my head around the -name parameter in the arma server startup line and see how this can be incorporated into your script to get the correct .Arma3Profile file to load.

the other main stumbling block is the documentation from bohemia on these linux servers :)

i have install github onto my mac at home, and will try and contribute as best as i can.

thanks again, ill keep hunting the gremlins :)
