### ISSUE TITLE
[ARK] New Dedicated 4GB install uses a new STEAM ID?

### ISSUE THREAD

**Issue by bagobones** [dgibbs64/linuxgsm#818]
https://www.reddit.com/r/playark/comments/4jxbh9/anonymous_dedicated_server_package_is_now_only_4gb/

Apparently they have setup a new steam ID for the smaller dedicated server package? Should I change it in my ./arckserver script directly or will this get over ridden in the future?

**Comment by bagobones** [comment]
Never mind it appears that the script already uses the correct ID.

**Comment by UltimateByte** [comment]
Ark development seems to be really smooth, that's cool. Couldn't say the same with Rust even though it's the same engine. :)
