### ISSUE TITLE
[RUST] edit config.cfg

### ISSUE THREAD

**Issue by VirusGamers** [dgibbs64/linuxgsm#819]
Hi all,
I'm french and my english is bad, sorry for my incorrect english language.

I have been looking for two days to edit the config.cfg file to change my password Rcon , the size of the map and other settings and i can not find solution.

Is it possible to help a French lost ? :).

Thank you.

**Comment by TheDouglife** [comment]
Hey VirusGamers, let me see if I can help out.

First, you'll want to be in the "rustserver" file, not a .cfg.

It should be in the /rustserver/ folder.

Open that file up, and you'll see #Server Settings which contains your RCON information, and below that, the #Advanced contains Seed and World Size.

Make your changes and save, then restart the server.

**Comment by UltimateByte** [comment]
+1, the things you wanna set are all set within the rustserver file. The one of the main goals of LGSM is to allow this easy configuration of stuff that has to be set at server boot, and those are set withing the script itself.

**Comment by VirusGamers** [comment]
Thank you for fast reply :).
Just for info i use ubuntu 14.04 LTS and i connect on my server with putty.
i look the folder /rustserver/ and i don't have the file. I must create it ?
screen /rustserver: http://prntscr.com/b6byx6
in /rustserver/ i have one folder "serverfiles" and in "server" and in "rust-server".
I view video and the dude use this command: "nano rustserver" for edit the file. It's ok or not ?
@TheDouglife your french is good 93% :+1:

**Comment by UltimateByte** [comment]
What the fuck is that interface you're using ?
You're hurting yourself and hurting my eyes.

The "dude" in the video is me ;)

**Comment by UltimateByte** [comment]
I i always say : before making a server even with a wonderful script such as LGSM, learn the basics of Linux.
If you don't even know what "nano" or "vi" is, stop it right now, take the time to learn Linux, and come back afterwards. You wouldn't even ask those questions if you did your homework.

**Comment by VirusGamers** [comment]
I managed myself otherwise...
i said "dude" because I know that word (sorry for offence).
I have some knowledge in Linux. But I can go looking elsewhere for help if it bothers you ... (google translate sorry).

**Comment by TheDouglife** [comment]
VirusGamers, je peux voir de la printscreen vous avez le fichier "rustserver", mais il est répertorié comme Disque local dans la colonne de type. C'est le fichier que vous souhaitez modifier. - http://i.imgur.com/3D9ayM5.png

**Comment by UltimateByte** [comment]
We can help you explaining how the script works. We can teach you some things about linux. We can't but we can't babyssit you with linux.
Whatever thing you're using on your screenshot, http://prnt.sc/b6byx6 : windows icons "local disk", it's all wrong information... for your own sake, stop using that thing ! Stick to SSH (putty) and optionally (not even needed) with FTP (Filezilla).

**Comment by VirusGamers** [comment]
@UltimateByte "mastic" is putty, sorry ^^.
@TheDouglife i'm stupid ... :(. thank you. 
Is possible to add other ip for "iprcon" ?
I add a new line with a new variable " iprcon " to add a different IP from that of iprcon
Screen: http://prntscr.com/b6dh59
And i edit the line 45:
Screen: http://prntscr.com/b6dez8

And my server is not referenced in rust...

**Comment by UltimateByte** [comment]
""mastic" is putty, sorry" > what the heck ? http://www.hobby-maquettes.com/images/produits/880/TAM-87053-large.JPG this ?

When i made this Rust script, there was no such thing as rcon.ip, that was an old variable, not used anymore in Rust.
I tested it, it didn't work, so i didn't put it in the final script. My guess is that it could be the reason for your crashing server. So try it clean first, then customize. 

BTW, nobody has to set a different IP for RCON. Unless you've got a multiple IP server and are very paranoïd, it's useless.

Your syntax is good however, at least you understood how variable works, (some don't) and you understood where the logs are too. But maybe you shouldn't try to add stuff to the script if you don't even know what nano is.

I'm not trying to be mean here, I could sound like i'm in a bad mood talking like that, but i'm not, i'm actually in a perfect day... But come on... Go step by step. The default install is supposed to work out of the box, the only thing you may have to set is your IP. So try it blank first.


Before anything else, can we know if your server is 32 or 64 bits, and how much RAM it has ?

**Comment by VirusGamers** [comment]
Before ubuntu 14.04 and now Linux Debian 8.0 X86 64 Minimal Gen2 V1.
- 6C-HG: https://www.proxgroup.fr/serveurs-virtuels-hg.php
Stop saying that I not know linux and nano. i'm noob in linux ok i accept. after look the doc nano I know.
I watch the videos and nothing works . I 've got a têteête.
Do not waste your time because of a stupid French who know nothing about linux . I turn on windows .

**Comment by UltimateByte** [comment]
Well, enjoy windows then, bye.

**Comment by VirusGamers** [comment]
i have serveur 2 . Un VPS et decicated.
my dedicated server: Core Xeon dual core 32Go ram and hosting microsoft azur.
My VPS for the test install and my best server ( microsoft azur ) my initial server.
The problem is similar in 2 serveur.
I look the vidéo: https://www.youtube.com/watch?v=eFH9Qj-hUOM it's you no ?
Do not waste your time. i don't know linux.
PS: tu es parisien ?

**Comment by UltimateByte** [comment]
Nice franglish. Didn't get half of what you're saying.
But if you don't know linux, i've got a job and a life, so go back learn the basics on your own, it will take you 3 days maximum, then come back.

**Comment by dgibbs64** [comment]
@UltimateByte feel free to use French if you feel its required. You could always add an English translation at the bottom if you like.

For your setup I recommend Ubuntu, putty ssh client and nano text editor. Also WinSCP is great for checking out files on the server.

as per @UltimateByte make sure you know some of the basics of Linux to make your life easy. Otherwise you are "trying to run before you can walk". There is nothing wrong with being a Linux newbie or French...Trying to setup a game server before your know Linux basics is like trying to use MS paint before you know what the start menu is. Look up a Linux cheatsheet that will help and also Google your Linux issues when stuck and you will find the solution (that is how I learnt and ended up with a Linux job).

@UltimateByte video tutorials are very good at showing the basics of how to install LGSM so i recommend following them exactly. 

So yeah take your time and have some fun learning Linux. Its a brilliant tool when your get used to it.

**Comment by UltimateByte** [comment]
@dgibbs64 +1000 , thanks for your pedagogy. 

@VirusGamers J'ai appris les bases de Linux avec cette série de tutos : http://www.tutoriels-video.fr/installation-et-configuration-dun-serveur-dedie-debia/
Il m'aura fallu 3 jours pour arriver à mettre un serveur en place avec un forum et un nom de domaine, le tout sous ESXI/Debian. (Oui, je m'étais un peu compliqué la vie pour un début mais ESXI permettait de faire des rollbacks si nécessaire).
Ça marche aussi bien pour Debian qu'Ubuntu, les deux systèmes sont similaires. Debian sera plus "light", ubuntu aura un support un poil mieux (bien que celui de debian soit déjà bien). Si tu bloques : Google est ton meilleur ami, mais tu as plus de chances de trouver des réponses si tu cherches en anglais.

Seul défaut de cette série de tutos : C'est long pour ce qu'on y apprend, et difficile de tout capter du premier coup. Et plus gênant encore : C'est vieux, et certaines choses ne se mettent pas en place tout à fait pareil. Mais si tu regardes attentivement ses vidéos dans l'ordre, tu devrais déjà avoir de bonnes bases de comment ça marche et comment l'utiliser. ;)

**Comment by VirusGamers** [comment]
@UltimateByte Je suis une personne déterminé et aimant l'informatique. Me dire que je connais pas linux est un peut abuser du fait que cela fait 2 semaine que je li les documentation d'ubuntu concernant iptables, UFW, les commandes basique, m'informé sur la sécurité avec PortSentry etc. J'ai lu, j'ai visionné j'ai apprit au cours de ses 2 semaines ( j'assimile assez vite les choses et les enregistre assez rapidement ). Je ne suis pas le genre de mec qui publie quelque chose à chaque problème rencontré, j'utilise google en copiant collant les erreurs éventuelle que me retourne la console et par moment j'ai une réponse par moment non donc je fouille et je trouve. Mon sujet a été créer parce que je ne trouvé pas de solution sur internet et que je pensé qu'il fallait édité  directement le fichier config.cfg, une erreur de débutant, mais qui peuvent en aidé certain si une personnes comme que moi utilise google pour répondre à sa question. Inutile de "clash" le premier débutant venu en lui disant vas apprendre linux. C'est ce genre de réponse qui démoralise les 3/4 des personnes souhaitant apprendre sur linux.

Sinon, concernant mon problème, j'ai changer de distribution et je suis passer sur debian  et le problème est résolu. Je ne sais pour quel raison sous ubuntu cela ne fonctionne pas ( même avec une installation neuve).

Je te souhaite un bon développement de LGSM et encore merci pour tes réponse qui m'ont lancé sur une piste.

**Comment by UltimateByte** [comment]
Ubuntu comme CentOS sont remplis de merdes et provoquent des comportements inattendus. Pour cette raison, je recommande Debian :)
Content que tu aies pu apprendre des choses et résoudre tes problèmes !
2 semaines ça reste très court, mais je sais comment c'est quand tu essaies de faire marcher un truc et que tu bloques, ça peut être très frustrant, il n'y a eu aucune animosité de mon côté ;)
Je te souhaite une bonne aventure Linux !
