### ISSUE TITLE
Unknown Tmux error

### ISSUE THREAD

**Issue by TarantelTM** [dgibbs64/linuxgsm#824]
May 22 07:09:45 rust-server: Starting: Unable to start Rusty Bitch MAP/SKILLS/HOMES/TRADING
May 22 07:09:47 rust-server: Starting: Tmux error
tmux new-session -d -s "rust-server" "./RustDedicated -batchmode +server.ip 185.101.92.134 +server.port 28015 +server.tickrate 100 +server.hostname "Rusty Bitch MAP/SKILLS/HOMES/TRADING" +server.identity "rust-server" +server.seed 0 +server.maxplayers 50 +server.worldsize 8000 +server.saveinterval 300 +rcon.ip 185.101.92.134 +rcon.port 28016 +rcon.password "****" -logfile "gamelog-2016-05-22-07-09-42.log""
create session failed: ./RustDedicated -batchmode +server.ip 185.101.92.134 +server.port 28015 +server.tickrate 100 +server.hostname "Rusty Bitch MAP/SKILLS/HOMES/TRADING" +server.identity "rust-server" +server.seed 0 +server.maxplayers 50 +server.worldsize 8000 +server.saveinterval 300 +rcon.ip 185.101.92.134 +rcon.port 28016 +rcon.password "****" -logfile "gamelog-2016-05-22-07-09-42.log": No such file or directory
May 22 07:09:47 rust-server: Starting: No known fix currently. Please log an issue.
May 22 07:09:47 rust-server: Starting: https://gameservermanagers.com/issues
May 22 07:11:58 rust-server: Starting: Rusty Bitch MAP/SKILLS/HOMES/TRADING
May 22 07:11:59 rust-server: Starting: Rotating log files

**Comment by UltimateByte** [comment]
Don't you feel like it would be relevant to give distro info, and tmux version info ?
We're not wizards

**Comment by UltimateByte** [comment]
Closing as this issue is damn pointless.
