### ISSUE TITLE
Rust Server Not Working

### ISSUE THREAD

**Issue by neondiamonds** [dgibbs64/linuxgsm#825]
I've been trying to set up a Rust server on Ubuntu 14.04.4 x64 and Can't seem to get it to work. I followed every step on the LGSM site and have also made a completely new server and reinstalled it.

Whenever I do `./rustserver start` I get 

> ./rustserver start
> /home/rustserver/lgsm/functions/logs.sh: line 22: fn_printinfo: command not found
> 
> [  OK  ] Starting rust-server: Rust

And then when I do `./rustserver monitor` I get 

> ./rustserver monitor
> /home/rustserver/lgsm/functions/logs.sh: line 22: fn_printinfo: command not found
> 
> [ FAIL ] Monitor rust-server: Checking session: FAIL
> [  OK  ] Starting rust-server: Rust
> 

If anyone can help that'd be great. Thank you in advanced.

**Comment by UltimateByte** [comment]
I need to investigate through that

I tried to replicate, full log here : http://pastebin.com/H4LPBNMM

**Comment by UltimateByte** [comment]
Maybe try to run update-functions twice. Seemed to fix some stuff for me.
Is this a new server.

**Comment by UltimateByte** [comment]
I just fixed the core_function errors.

**Comment by neondiamonds** [comment]
Yes This Is A New Server, Let me Try What You Did

**Comment by neondiamonds** [comment]
Just Tried It, Same Problem.
http://pastebin.com/vKC6HDVM

**Comment by UltimateByte** [comment]
Maybe try the manual way.

```
./rustserver stop
rm -R functions/ lgsm/
./rustserver start
```

**Comment by neondiamonds** [comment]
Removed it and still have the same problem...

**Comment by neondiamonds** [comment]
Any info I can give you to help you help me?

**Comment by UltimateByte** [comment]
OK i'ved been able to replicate the issue. Hold on.

**Comment by UltimateByte** [comment]
OK, missing fn_printinfo fixed (was renamed with fn_print_info ), just need to prevent monitor function from moving logs to the logs folder, as this should only happen upon start.

**Comment by UltimateByte** [comment]
btw, Monitor rust-server: Checking session: FAIL > not related to the script.
Those errors are not harmful. So there might be another issue for you.

**Comment by neondiamonds** [comment]
Alright, that fixed the problem. However, now when I do `./rustserver start` I get 

> ./rustserver start
> -su: fork: Cannot allocate memory

**Comment by neondiamonds** [comment]
I've also gotten 

> ./rustserver start
/home/rustserver/lgsm/functions/check_permissions.sh: fork: Cannot allocate memory

**Comment by UltimateByte** [comment]
OK, everything's fixed for me.
`./rustserver uf`

Now if you still have errors like that, it's more likely that the issue comes from your system.
`free -m`
Output ?

**Comment by UltimateByte** [comment]
Just committed the fix, so if you've been too fast, update your functions right now :p

**Comment by neondiamonds** [comment]
> free -m
>              total       used       free     shared    buffers     cached
> Mem:           993        934         59          5          0         18
> -/+ buffers/cache:        914         79
> Swap:            0          0          0
>

**Comment by neondiamonds** [comment]
> ./rustserver uf
-su: fork: Cannot allocate memory

**Comment by neondiamonds** [comment]
I'll try to delete this server and try it on a new machine. Thank you for your help so far, I'll let you know if I have issues on the new machine. What OS Do you recommend I Use?

**Comment by UltimateByte** [comment]
It doesn't explain the "cannot allocate memory" error upon update-functions, but are your seriously trying to run a rust server with a 1GB RAM machine ?
What's your weed ? I want the same.

**Comment by neondiamonds** [comment]
The thing is, It worked before, very well infact. After I tried to mod it, it broke so I attempted to reinstall and It didn't work at all

**Comment by UltimateByte** [comment]
Well, maybe watch my full tutorial on oxide forum, it's a sticky post, there's even a video, it might help. It also gives a way to automate Oxide updates.

I recommend Debian 8, 64 bits. Simple, efficient, no crapware, best way to go for me ;) @dgibbs64  would probably recommend Ubuntu, but i like him anyways :p  
But Rust takes up 4 to 7GB RAM with a 4000 units map, so keep that in mind.

Thank you for reporting those small bugs !
If you need more help, afterwards, please use the steam group, we'll be glad to help as long as you give some logs and relevant info.

Cheers ! :)

**Comment by UltimateByte** [comment]
http://oxidemod.org/threads/setting-up-a-rust-server-with-linux-and-lgsm.16528/
