### ISSUE TITLE
fn_print_ok error and script version

### ISSUE THREAD

**Issue by GliderHacker** [dgibbs64/linuxgsm#826]
Performed the update-functions command.. I got all the messages about removed functions/ files but in the last there was a message about fn_print_ok functions not available. Additional LGSM version ( ./insserver details) is still the previous one

**Comment by UltimateByte** [comment]
Did you try to re-run the update-function ?

**Comment by GliderHacker** [comment]
insserver@hades:~$ ./insserver update-function
/home/insserver/functions/core_functions.sh: line 17: [: missing `]'
/home/insserver/functions/core_functions.sh: line 20: [: missing `]'
/home/insserver/functions/core_functions.sh: line 23: [: missing `]'

**Comment by GliderHacker** [comment]
Tried to re-run the update-function...got the message above

**Comment by GliderHacker** [comment]
Ops...my fault the right command was update-functions, not update-function ( without 'a'), performed again the command...the version is still the old one

**Comment by UltimateByte** [comment]
Now this core_functions errors is solved. After updating again, you shouldn't get that error anymore. It was just a matter of missing spaces in the code. (Bash can be mean sometimes :p )

**Comment by GliderHacker** [comment]
Just the script version is the old one in ./insserver details

**Comment by UltimateByte** [comment]
This is normal. The version displayed in details is the "main" script's version. Update-function only updates functions. If you want the newer one, you'll have to wget the new script, and manually re-add your settings to it. Then i'd remove functions/ and lgsm/ folders to start over.

**Comment by GliderHacker** [comment]
Ok, so I'm fine with the updated functions did so far. Thanks for the support and great script

**Comment by UltimateByte** [comment]
The 2 main things you'd get by updating the main script is the support for pushbullet (notifications on crash or update), and faster fetching for functions (using curl instead of wget). You'd also get rid of the "functions" folder that is now contained into the "lgsm" folder, which is a step further for future updates :)

**Comment by GliderHacker** [comment]
Mah...there is a core_functions file into the insserver/functions folder, can I delete it?

**Comment by GliderHacker** [comment]
And into the lgsm folder there are two sub folders: bin and functions, can I remove the lgsm folder as stated above? Sorry for asking, just to avoid issues

**Comment by UltimateByte** [comment]
functions/core_functions is required to maintain compatibility if you're still using the old insserver script.
You can remove functions/ and lgsm/ folders as much as you want, LGSM will download them back if needed.

**Comment by UltimateByte** [comment]
I guess it's fixed, closing for now :)
