### ISSUE TITLE
Monitor function doesn't work

### ISSUE THREAD

**Issue by GliderHacker** [dgibbs64/linuxgsm#829]
I've updated LGSM to latest version ( just functions, main script is previous version) 
The monitor function cannot check and restart server, failed cecking session and restart

**Comment by UltimateByte** [comment]
Which game ?? Come on, details dude !

**Comment by GliderHacker** [comment]
Sorry for poor info
Insurgency game, performed validation, no issues. Don't know if log could come in handy

**Comment by JimTR** [comment]
maybe related i get this issue when running the monitor command on gmod & fof

> games/fof/fofserver monitor
    fetching functions/command_monitor.sh...FAIL

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/functions/command_monitor.sh

for some reason github is returning a 404 - not found error

**Comment by GliderHacker** [comment]
Just to see if the issue was due to old script, I've updated the insserver script to latest version.
Got the same error trying to perform the monitor function:
`insserver@hades:~$ ./insserver monitor
[ FAIL ] Monitor ins-server: Checking session: FAIL
[ .... ] Starting ins-server: Bradipi Urlanti Serverfailed to connect to server: Connection refused
[ FAIL ] Starting ins-server: Unable to start Bradipi Urlanti Server
`

**Comment by UltimateByte** [comment]
`./gameserver uf`

**Comment by UltimateByte** [comment]
If you got 2 servers using the same port, your server might stop for that reason.

Do this on your first server (same for @JimTR )
`./gameserver uf`

**Comment by GliderHacker** [comment]
Mhh...even trying tos tart the server failed...
`insserver@hades:~$ ./insserver start
[ .... ] Starting ins-server: Bradipi Urlanti Serverfailed to connect to server: Connection refused
[ FAIL ] Starting ins-server: Unable to start Bradipi Urlanti Server
`

**Comment by UltimateByte** [comment]
If you got 2 servers using the same port, your server might stop for that reason.

**Comment by GliderHacker** [comment]
Performed the update functions...no issue, and I'm sure there is just one server running on my linuxbox

`insserver@hades:~$ ./insserver uf
    fetching command_update_functions.sh...OK
[ .... ] Updating functions
removed ‘/home/insserver/lgsm/functions/alert.sh’
removed ‘/home/insserver/lgsm/functions/check_config.sh’
removed ‘/home/insserver/lgsm/functions/check_deps.sh’
removed ‘/home/insserver/lgsm/functions/check_glibc.sh’
removed ‘/home/insserver/lgsm/functions/check_ip.sh’
removed ‘/home/insserver/lgsm/functions/check_logs.sh’
removed ‘/home/insserver/lgsm/functions/check_permissions.sh’
removed ‘/home/insserver/lgsm/functions/check_root.sh’
removed ‘/home/insserver/lgsm/functions/check.sh’
removed ‘/home/insserver/lgsm/functions/check_status.sh’
removed ‘/home/insserver/lgsm/functions/check_steamcmd.sh’
removed ‘/home/insserver/lgsm/functions/check_system_dir.sh’
removed ‘/home/insserver/lgsm/functions/check_tmux.sh’
removed ‘/home/insserver/lgsm/functions/command_monitor.sh’
removed ‘/home/insserver/lgsm/functions/command_start.sh’
removed ‘/home/insserver/lgsm/functions/command_stop.sh’
removed ‘/home/insserver/lgsm/functions/command_update_functions.sh’
removed ‘/home/insserver/lgsm/functions/command_validate.sh’
removed ‘/home/insserver/lgsm/functions/core_dl.sh’
removed ‘/home/insserver/lgsm/functions/core_functions.sh’
removed ‘/home/insserver/lgsm/functions/core_getopt.sh’
removed ‘/home/insserver/lgsm/functions/core_messages.sh’
removed ‘/home/insserver/lgsm/functions/fix_glibc.sh’
removed ‘/home/insserver/lgsm/functions/fix_ins.sh’
removed ‘/home/insserver/lgsm/functions/fix.sh’
removed ‘/home/insserver/lgsm/functions/fix_steamcmd.sh’
removed ‘/home/insserver/lgsm/functions/info_config.sh’
removed ‘/home/insserver/lgsm/functions/info_distro.sh’
removed ‘/home/insserver/lgsm/functions/info_glibc.sh’
removed ‘/home/insserver/lgsm/functions/logs.sh’
removed ‘/home/insserver/lgsm/functions/update_check.sh’
[  OK  ] Updating functions
`

monitor and start function failed to restart the server...

**Comment by GliderHacker** [comment]
First of all thanks for your invaluable help.
I really don't think there are two server running on my linuxbox.
In any case..is there a way to check this?
In any case I've performed the 
`.\insserver uf`
command.
After that both monitor and start the server failed

**Comment by UltimateByte** [comment]
If start function doesn't work, monitor will report a down server.
I'd check for duplicate processes.
I'm not using insserver, but if you run `./insserver details`, it will give you the command to check if there are processes listening. 
Something like : 
netstat -atunp | grep srcds_linux
But srcds_linux will be different accordingly to insserver.

**Comment by GliderHacker** [comment]
Mhh...I checked `details` function several times....

`insserver@hades:~$ ./insserver details
    fetching command_details.sh...OK
    fetching info_parms.sh...OK

Distro Details
======================================================================================================================================
Distro:    Debian GNU/Linux 8.4 (jessie)
Arch:      x86_64
Kernel:    4.5.0-x86_64-linode65
Hostname:  hades
tmux:      tmux 1.9
GLIBC:     2.19

Performance
======================================================================================================================================
Uptime:    9d, 8h, 44m
Avg Load:  0.00, 0.03, 0.07

Mem:       total   used   free
Physical:  2.0G    1.5G   461M
Swap:      255M    16M    239M

Storage
======================================================================================================================================
Filesystem:   /dev/root
Total:        48G
Used:         8.9G
Available:    36G
Serverfiles:  8.0G

Insurgency Server Details
======================================================================================================================================
Server name:      Bradipi Urlanti Server
Server IP:        139.162.185.198:27015
Server password:  NOT SET
RCON password:    XXXXXXX
Tick rate:        64
Status:           OFFLINE

insserver Script Details
======================================================================================================================================
Service name:       ins-server
insserver version:  210516
User:               insserver
GLIBC required:     2.15
Email alert:        off
Update on start:    off
Location:           /home/insserver
Config file:        /home/insserver/serverfiles/insurgency/cfg/ins-server.cfg

Backups
======================================================================================================================================
No Backups created

Command-line Parameters
======================================================================================================================================
./srcds_linux -game insurgency -strictportbind -ip 139.162.185.198 -port 27015 +clientport 27005 +tv_port 27020 -tickrate 64 +map sinjar_coop +servercfgfile ins-server.cfg -maxplayers 36 +sv_workshop_enabled 0

Ports
======================================================================================================================================
Change ports by editing the parameters in:
insserver

Useful port diagnostic command:
netstat -atunp | grep srcds_linux

DESCRIPTION  DIRECTION  PORT   PROTOCOL
> Game/RCON  INBOUND    27015  tcp/udp
> SourceTV   INBOUND    27020  udp
< Client     OUTBOUND   27005  udp

Status: OFFLINE

insserver@hades:~$
`

**Comment by JimTR** [comment]
running the command fixed gmod  & fof servers  ... is there a command where by when a critical update is made this is tested out ?

**Comment by UltimateByte** [comment]
@GliderHacker Then the command to check for other listening servers is `netstat -atunp | grep srcds_linux`

@JimTR So it's fixed for you ? What is your question ? I don't get it.

**Comment by GliderHacker** [comment]
The command returned no infos ...
`insserver@hades:~/serverfiles$ sudo netstat -atunp | grep srcds_linux
insserver@hades:~/serverfiles$
`

**Comment by GliderHacker** [comment]
About log file...this is the latest script log file:
`May 23 18:53:08 ins-server: Starting: Unable to start Bradipi Urlanti Server
May 23 18:54:01 ins-server: Monitor: Bradipi Urlanti Server
May 23 18:54:02 ins-server: Monitor: Checking session: CHECKING
May 23 18:54:03 ins-server: Monitor: Checking session: FAIL
May 23 18:54:03 ins-server: Monitor: Sending restart alert: ./srcds_linux process not running
May 23 18:54:03 ins-server: Monitor: Monitor is starting Bradipi Urlanti Server
May 23 18:54:04 ins-server: Starting: Bradipi Urlanti Server
May 23 18:54:05 ins-server: Starting: Rotating log files
`

**Comment by JimTR** [comment]
it was not a question ... I added the comment 'possible related' and did not ask a question

**Comment by UltimateByte** [comment]
@GliderHacker Those logs aren't helpful, it tells us what we already know : Unable to start.
In order to know why, a game log (console log) would help. You can also try the debug start and look what the console tells you.
`./insserver debug`

**Comment by UltimateByte** [comment]
`dpkg --add-architecture i386`
`apt-get update; apt-get install tmux ca-certificates curl lib32gcc1 libstdc++6 libstdc++6:i386 `

**Comment by UltimateByte** [comment]
I've also spotted this
http://steamcommunity.com/app/222880/discussions/2/618457398958286048/#p1

**Comment by GliderHacker** [comment]
Thanks for feedback....I got the same discussion about LD_LIBRARY_PATH...
SInce before the updat the server was running fine I think the issue it's not due to a missing library or dependency......about LD_LIBRARY_PATH I'm wondering if I can add that line to the insserver script safely.
What do you suggest?

**Comment by GliderHacker** [comment]
Performed the installation command...all  libraries are already there:
`Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
ca-certificates is already the newest version.
curl is already the newest version.
lib32gcc1 is already the newest version.
libstdc++6 is already the newest version.
tmux is already the newest version.
libstdc++6:i386 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
`

**Comment by GliderHacker** [comment]
Now I'm totally lost...following the thread above I've added, into the insserver script, after appid=""237410", the following line:
`export LD_LIBRARY_PATH=/home/inscoop/serverfiles:/home/inscoop/serverfiles/bin:{$LD_LIBRARY_PATH}`

The monitor commadn provide the following message:
`[  OK  ] Stopping ins-server: Bradipi Urlanti Server is already stopped
[ .... ] Starting ins-server: Bradipi Urlanti Serverfailed to connect to server: Connection refused
[ FAIL ] Starting ins-server: Unable to start Bradipi Urlanti Server
`
Same rror as before

**Comment by JimTR** [comment]
'Connection refused' sort of gives the idea that the setup is not perfect .... does this game require a valid steam user rather than not ?

**Comment by GliderHacker** [comment]
Mhhh...but previous version was running fine with anonymous user.
And the debug command still provide the same error:
`./srcds_linux: error while loading shared libraries: libtier0_srv.so: cannot open shared object file: No such file or directory
`

**Comment by GliderHacker** [comment]
Fixed!
I have replaced the following insserver script line:

`executable="./srcds_linux"`

with

`executable="./srcds_run"`

Don't know exactly what happened ( I'd like to understand in any case...suggestions are welcome ), but now the server is up.
Reverted the modified line in insserver script...let's hope

**Comment by JimTR** [comment]
you are 100% right ... I just ran the script an hit the same errors as you ... changing the executable does fix it :+1:

**Comment by UltimateByte** [comment]
So the executable name needs to be changed through lgsm. Well, sorry about that, thanks for your time.

**Comment by GliderHacker** [comment]
No needs to say sorry! Honestly I don't know if changing executable file into insserver script is the best and definitive fix for the issue: previous installation worked fine without changing executable name.
Ciao and thx again for support and great script


Inviato da iPhone

**Comment by UltimateByte** [comment]
OK, issue confirmed, fix works as intended.
In the end, srcds_run is the default name for SRCDS, so insserver just came back to the default srcds management. I'll fix that in a minute.

**Comment by UltimateByte** [comment]
Fixed ;)
