### ISSUE TITLE
Monitor arma3-server Fail

### ISSUE THREAD

**Issue by igeighty** [dgibbs64/linuxgsm#830]
```
arma3server@droid118:~$ ./arma3server start
[  OK  ] Starting arma3-server: “[AUS]droid118.halawanlabs.local“
arma3server@droid118:~$ ./arma3server monitor
    fetching command_monitor.sh...OK
[  OK  ] Monitor arma3-server: Checking session: OK
    fetching monitor_gsquery.sh...OK
    fetching gsquery.py...OK
[ FAIL ] Monitor arma3-server: Querying port: 192.168.1.118:2302 : 60/5 : FAIL
    fetching alert.sh...OK
[  OK  ] Stopping arma3-server: “[AUS]droid118.halawanlabs.local“
[  OK  ] Starting arma3-server: “[AUS]droid118.halawanlabs.local“
arma3server@droid118:~$ 
```

G'day,
On a fresh installation of arma3server on Debian 8.4 (hosted here at home), I am unable to get the monitor to query my server.

Is there something in the scripts that needs to be edited in order for it to function ? 
Is the fact it is reading a local network address the problem and it should be querying the public address.

i have had a bit of a look through the scripts however i will admit it is a bit beyond me.
I can live without the feature, as i usually run `./arma3server console` to visually catch the servers progress.

using your script i also notice i can't see the server listed the server browser in LAN, only Internet.

when i use the server using the default linux setup here.https://community.bistudio.com/wiki/Arma_3_Dedicated_Server#Installation_2
i am able to see it locally and internet, is anything to do with the `-ip=` in the start line ?

i have not adjusted anything in arma3server in these lines.

`# Start Variables
ip="0.0.0.0"
port="2302"
updateonstart="off"

fn_parms(){
parms="-netlog -ip=${ip} -port=${port}.............`

i am using what i think is the latest version of your arma3server script (fresh install tonight just to be sure)

Thanks of the scripts, i am learning a lot from this setup.

**Comment by UltimateByte** [comment]
I'm no Arma3 expert, but there might be something for us to fix in order for it to work.
See that https://github.com/dgibbs64/linuxgsm/issues/815

**Comment by igeighty** [comment]
Something i have noticed, related or no..

when running `./arma3server details` the port is being reported as port 0

http://pastebin.com/7mnxacBf

yet when running `./arma3server debug` the port is being loaded correctly 2302

http://pastebin.com/fussnnTq

I have done another fresh install without changing any of the scripts on a different machine to check, with the same results, (just different LAN IP) the only exception from default install was to change steam username and pass in `arma3server.sh`

This occurs whether i have uncommented or not `port = 2302` in the `arma3-server.server.cfg`
Ports are no longer handled by a server.cfg file, they are specified in the servers command line `-port=`

at the end of the day the server is running and users are able to join both on LAN and from outside the LAN via the internet server browser, so ports are working, and being forwarded through my router ok,
I was curios as to why they are not being shown correctly in the details with of arma3server script.

any other logs you need sing out :)

**Comment by UltimateByte** [comment]
So in the end, the details function doesn't report the correct port, is that it ?
That's something i could fix easilly. :)

**Comment by igeighty** [comment]
I think so, i tried to trace it through but got lost.

it was just a theory as to why the monitor function fails, its not a show stopper though, as the server functions as it should :)

happy to test any theories :)

**Comment by UltimateByte** [comment]
Well, we'd need to investigate the code in the first place, got no time right now, but i'll try to get back to it at some point :o))

**Comment by FliesWithWind** [comment]
Hey guys,

I had the same problem and found the solution. Basically Arma 3 needs to be scanned on +1 port, at least in my case.

I solved it by changing this in file lgsm/functions/monitor_gsquery.sh 
if [ "${engine}" == "unreal" ]||[ "${engine}" == "unreal2" ]; then
		port=$((port + 1))
	elif [ "${engine}" == "spark" ]; then
		port=$((port + 1))
	fi

to

if [ "${engine}" == "unreal" ]||[ "${engine}" == "unreal2" ]; then
		port=$((port + 1))
if [ "${engine}" == "virtualreality" ]; then
		port=$((port + 1))
elif [ "${engine}" == "spark" ]; then
		port=$((port + 1))
fi

**Comment by igeighty** [comment]
G'Day @FliesWithWind ,
would you please be able to paste the  monitor_gsquery.sh file to pastebin ?
when i make the change you propose above, i end up with error from the script.

`arma3server@droid118:~$ ./arma3server m`
`[  OK  ] Monitor arma3-server: Checking session: OK`
`/home/arma3server/lgsm/functions/monitor_gsquery.sh: line 92: syntax error: unexpected end of file`

sorry i haven't been able to test this sooner.
i am obviously not doing it right :)

regards.
Doug

**Comment by igeighty** [comment]
hold that, it was my bad,
i had 'if' not 'elif' 

monitor now works as you suggested.

http://pastebin.com/W2MEg0xe

`arma3server@droid118:~$ ./arma3server m`
`[  OK  ] Monitor arma3-server: Checking session: OK`
`[  OK  ] Monitor arma3-server: Querying port: 192.168.1.118:2303 : 1 : OK`

**Comment by FliesWithWind** [comment]
Glad it works ;)

However if someone specifies different steam query port in server config file, this might no longer work.

**Comment by igeighty** [comment]
the base port is specified in line 35 of arma3server, and without uncommenting any lines in the arma3-server.server.cfg it works a treat.
as i think that the value for port is taken from arma3server and not the server.cfg. (bohemia recommends not using port in server config anymore) thats where i was going wrong :)

**Comment by JHulsmans** [comment]
Great to hear you got it resolved @igeighty. If you want you can have this issue closed now.

**Comment by UltimateByte** [comment]
Well, it should be closed once we're sure that it's fixed into LGSM's code :)

**Comment by igeighty** [comment]
no worries guys, ill keep my eyes out for the LGSM master.
i have a few days to play around with the server again. and to learn how to use gut hub desktop :)
cheers.

**Comment by JHulsmans** [comment]
@UltimateByte True that, I may have jumped the gun here. :smile:

**Comment by UltimateByte** [comment]
@igeighty Github desktop is kind of a pain, but it's useful when you start doing some more complicated stuff, so that's a good thing to get used to it. ^^

I've re-read the issue, there was already a fix to report the right port in the details function, from Cedar https://github.com/dgibbs64/linuxgsm/commit/2d2d8941c33f872994ad29631ae865a772494584

So @JHulsmans Hehe Actually, you're right, because now the only issue that remains is the monitor function, and igeighty already made a pull request for that and an issue for the fix !
https://github.com/dgibbs64/linuxgsm/issues/865

I'll close this one, but as always, feel free to re-open if needed, otherwise, let's discuss on #865 !
