### ISSUE TITLE
not installed

### ISSUE THREAD

**Issue by alex31bel** [dgibbs64/linuxgsm#837]
extracting steamcmd_linux.tar.gz.../home/alex31/lgsm/functions/core_dl.sh: line 55: file: command not found

File command missing

**Comment by UltimateByte** [comment]
You're lacking the command "file".
I guess it's in util-linux
`apt-get install util-linux`

What is your distro so that we can add this to the requirements ?

**Comment by cedarlug** [comment]
Same problem posted [here today](http://steamcommunity.com/groups/linuxgsm/discussions/0/364042703854173416/), but it looks like a different user based on the logs.  They were running CentOS and missing `yum install file`.

**Comment by alex31bel** [comment]
**UltimateByte**

> root@31bel:~# apt-get install util-linux
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> util-linux is already the newest version.
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

OS ubuntu-14.04-x86_64-minimal

**Comment by UltimateByte** [comment]
`apt-get install file ` ?

**Comment by alex31bel** [comment]
**UltimateByte**
Thanks, it worked.

**Comment by UltimateByte** [comment]
Thank Cedar too, he gave me the way : 
So my guess is that it was due to the ubuntu minimal version not including that package.
@dgibbs64 "file" should be into the dependencies documentation.

**Comment by dgibbs64** [comment]
File added as a requirement and added to the site https://github.com/dgibbs64/linuxgsm/commit/ee13687dbbfc64a3de57215e08ce9bbef6e9fb99
