### ISSUE TITLE
[l4d1-server] Server wont be shut down by script

### ISSUE THREAD

**Issue by faflfama** [dgibbs64/linuxgsm#841]
Hi, 
with the newest script the l4d1-server wont be shut down (functions are updated). The output shows:
```
xxx@xxx:~/l4d_TZF-Apoc$ ./l4dserver stop
[  OK  ] Stopping tzfl4d: Graceful: rcon quit: 2: OK
```

Also the ./details command shows its offline. But the server stays online and the process isnt killed.

Distro: Ubuntu 15.10 x64

~Flam

**Comment by UltimateByte** [comment]
Thx for info.
@dgibbs64 Any clue ? Didn't check rcon qui yet. Are those real rcon commands, or commands sent into the console ?

**Comment by UltimateByte** [comment]
@faflama Could you please try to go into the console and input `quit` and see what happens ?
That way we'd have a clue if it's a script issue or a L4D issue;

**Comment by faflfama** [comment]
I tried and got the following:

quit in console: Server shuts down (script recognizes the shutdown)
quit over rcon: Server shuts down (script stil "thinks" its online)

~Flam

**Comment by faflfama** [comment]
Got sick, so couldnt test. Will try to do today.

~Flam

**Comment by faflfama** [comment]
Checked again, works now. I the old logs, I only found one time, where sth else was in the same line as the "quit".

~Flam

**Comment by UltimateByte** [comment]
Well, i guess this is not a confirmed bug then. Re-open if you got some news about it :)

**Comment by ssamjh** [comment]
I am having this issue.
It refuses to quit with rcon after about 20 seconds.

**Comment by UltimateByte** [comment]
@ssamjh More info, logs, useful stuff ?
