### ISSUE TITLE
Starttup command ark server

### ISSUE THREAD

**Issue by spitap** [dgibbs64/linuxgsm#843]
hello,
I have an ark server. And a new map (TheCenter) is release. So, I want to change startup command to load TheCenter in instead of TheIsland. Does there's a file where we can change this command-line?
Thanks

**Comment by JHulsmans** [comment]
Perhaps there's an easier way but you can edit it here at line 37 change TheIsland with the name of the new map TheCenter

https://github.com/dgibbs64/linuxgsm/blob/master/ARKSurvivalEvolved/arkserver

**Comment by UltimateByte** [comment]
Did it answer your question ?

**Comment by UltimateByte** [comment]
Well, closing, re-open if needed. But prefer the steam group for usage questions.
