### ISSUE TITLE
GLIBC_2.15 problem

### ISSUE THREAD

**Issue by tontondemon** [dgibbs64/linuxgsm#845]
problem with GLIBC_2.15 problem I want to do a gmod server but its not want
help me

**Comment by UltimateByte** [comment]
How can we help you if you don't give any information ?

Read this first, it might answer your questions : https://github.com/dgibbs64/linuxgsm/wiki/Glibc

**Comment by UltimateByte** [comment]
Well, closing, re-open if you need further information.
