### ISSUE TITLE
Arma 3 Unable to update

### ISSUE THREAD

**Issue by AznoYT** [dgibbs64/linuxgsm#849]
![6ad6f844dffb5c32206aac62d882b789](https://cloud.githubusercontent.com/assets/19228581/15670328/1f1a8864-2725-11e6-80d6-3bb1496e27fd.png)
Hello everyone, I'm sorry in advance for my English because I am French, I wanted to perform the update of Arma 3 is he told me that it is not possible here is what I have to show 

Thank you in advance for your assistance

**Comment by UltimateByte** [comment]
You're lacking the required function, and the function structure changed. You need the newer LGSM version.

./arma3server update-functions

**Comment by UltimateByte** [comment]
One more duplicate from this kind of issues : 
https://github.com/dgibbs64/linuxgsm/issues/836
https://github.com/dgibbs64/linuxgsm/issues/831

"Oh thanks, all problems solved !"

You're welcome ;)
Of course, re-open this issue if it's not 100% solved ;)
