### ISSUE TITLE
ARMA3 info_status.sh command not found

### ISSUE THREAD

**Issue by igeighty** [dgibbs64/linuxgsm#850]
Gday,
When doing an update to grab the newer version of arma3 server today, i noticed an error thrown by update_check.sh

`arma3server@droid118:~$ ./arma3server u`
    `fetching update_check.sh...OK`
`[  OK  ] Update arma3-server: Checking for update: SteamCMD`

`Update available:`
	`Current build: 1100267`
	`Available build: 1154214`

	`https://steamdb.info/app/233780/`

`Applying update...`
`/home/arma3server/lgsm/functions/update_check.sh: line 172: info_status.sh: command not found`

The file update_status.sh doesn't exist. I am part way through the update with no other obvious problems however.

just thought id let you know.
Cheers.
Doug

**Comment by UltimateByte** [comment]
Thanks for info.
Corrected with https://github.com/dgibbs64/linuxgsm/commit/b321f33ea8a98bddc8b86c70ebdcdaffd38d0218

Please, run `./arma3server update-functions` and try again.
Let me know if the issue is solved.

**Comment by igeighty** [comment]
no problem, i have another linux box that needs updating, ill update the script before doing the server update, report back in 20 mins or so :)

**Comment by igeighty** [comment]
All good now,
my second server fetched the updated functions and performed the arma3 update from steam with error message.
cheers mate, have a good one

**Comment by igeighty** [comment]
also, sorry i didn't think to check in the closed issues, i now see i created a duplicate :)

**Comment by UltimateByte** [comment]
np, thanks for your report :)
