### ISSUE TITLE
Arma 3 Could not start the server

### ISSUE THREAD

**Issue by AznoYT** [dgibbs64/linuxgsm#851]
Re Hi, I come to you because after you perform the actual commands, the problem that posse and I can not demarer my server when I get the order ./arma3server st
nothing is happening

Here is a Screen

![4d02cf9e3fa7399018c9bb623a785f2b](https://cloud.githubusercontent.com/assets/19228581/15675484/7fe03226-2742-11e6-8d87-c5ca8a05b9c2.png)

**Comment by UltimateByte** [comment]
Obviously, nothing happened since your "monitor" function. As you can see, no output at all. So i'd first check what a "top" command outputs, and eventually disconnect and reconnect from SSH.
I'd then check my files ownership and rights.

```
ls -al /home/arma3server
ls -al /home/arma3server/functions
ls -al /home/arma3server/lgsm/functions
```

**Comment by AznoYT** [comment]
thank you problem solve

**Comment by UltimateByte** [comment]
Allright.
Feel free to add up what solved the issue for the record.
I'll close that as it's solved but it won't prevent you from commenting.

Enjoy LGSM :)
