### ISSUE TITLE
Garry's mod, error with FastDL [fn_printok: command not found]

### ISSUE THREAD

**Issue by DefaltNF** [dgibbs64/linuxgsm#852]
Hello,
When I want to start FastDL on my server I have this : 
`/home/hl2rp/lgsm/functions/command_fastdl.sh: line 107: fn_printdots: command not found`

**Comment by dgibbs64** [comment]
./gmodserver update-functions

**Comment by DefaltNF** [comment]
Not work : 

`[  OK  ] Updating functions
hl2rp@TheLast-Community:~$ ./gmodserver fd
    fetching functions/core_functions.sh...OK
    fetching core_functions.sh...OK
    fetching core_messages.sh...OK
    fetching core_dl.sh...OK
    fetching core_getopt.sh...OK
    fetching command_fastdl.sh...OK
    fetching check.sh...OK
    fetching check_root.sh...OK
    fetching check_permissions.sh...OK
    fetching check_system_dir.sh...OK
/home/hl2rp/lgsm/functions/command_fastdl.sh: line 42: fn_printok: command not found`

**Comment by dgibbs64** [comment]
Thanks. Will need.to fix this

**Comment by UltimateByte** [comment]
Oh boy, printok has been renamed by print_ok if i remember well ?

**Comment by UltimateByte** [comment]
Well, all "printsomething" must be renamed accordingly here
https://github.com/dgibbs64/linuxgsm/blob/master/lgsm/functions/command_fastdl.sh
According to : https://github.com/dgibbs64/linuxgsm/blob/master/lgsm/functions/core_messages.sh

**Comment by dgibbs64** [comment]
Should be fixed now :)

**Comment by DefaltNF** [comment]
@dgibbs64 Are you sure it's fixed ?
I have already this : 
/home/hl2rp/lgsm/functions/command_fastdl.sh: line 28: fn_printinfo: command not found

**Comment by dgibbs64** [comment]
have you updated your functions?

**Comment by UltimateByte** [comment]
`./gmodserver uf`

**Comment by DefaltNF** [comment]
Yes I have updated the functions with the commands : http://pastebin.com/hGkNaQK8

**Comment by UltimateByte** [comment]
@dgibbs64 Nothing has been fixed ! I'll do it, got 10 minutes right now. https://github.com/dgibbs64/linuxgsm/blob/master/lgsm/functions/command_fastdl.sh

**Comment by UltimateByte** [comment]
OK, please update one more time your functions, should really be fixed now.
Please, let me know if it's totally fine now.

**Comment by dgibbs64** [comment]
forgot to press sync. Ouphs

**Comment by UltimateByte** [comment]
Well, now it's been fixed twice :p

**Comment by DefaltNF** [comment]
Now it's work, thank's :)
