### ISSUE TITLE
Cant join rust server

### ISSUE THREAD

**Issue by PuggerHugger** [dgibbs64/linuxgsm#857]
#It looks fine when i start my rust server, but when I join it on the rust client nothing happens.
I installed the server using [UltimateBytes video](https://www.youtube.com/watch?v=eFH9Qj-hUOM).
I am running debian 8.4.

I am editing the server over SSH because it is my friends. Could it be a problem with the ports?

**Here are my logs:**
http://pastebin.com/42P4CW40

**Comment by UltimateByte** [comment]
Edit your post using pastebing, and maybe i'll read it.

**Comment by PuggerHugger** [comment]
Here are my **./rustserver details**

http://pastebin.com/ugFceZSe

**Comment by UltimateByte** [comment]
Seems like an OVH Game server ? Got the same :)
There is a firewall to setup in your OVH interface. It's enabled by default and will block this. It's pretty hard to find the first time. Call OVH for support if needed, otherwise i may make some screenshots for you.

**Comment by PuggerHugger** [comment]
Okay, my friend owns the server. I will ask him about this OVH thing. Thank you.

**Comment by PuggerHugger** [comment]
Could you make some screenshots for me? it may help.

**Comment by UltimateByte** [comment]
Good server choice. Best server choice actually. :)
You're welcome :)

**Comment by PuggerHugger** [comment]
Its his own dedicated server and its at his house.

**Comment by UltimateByte** [comment]
Well, bad port redirection then ?

**Comment by JHulsmans** [comment]
Hi @PuggerHugger

Could you execute the following command in an ssh session on sparky:
> curl http://icanhazip.com/
This will return an IPv6 or IPv4 address. That's your public IP address. Currently the server is starting on a private IP address so you won't be able to connect to it whatever you do. (Your friend should be able to if he's on the same subnet.)

I don't know what you're planning with your Rust server but the Atom C2750 isn't exactly a powerhouse. You'll soon run in performance issues if you're going to go bigger than a few players.

**Comment by UltimateByte** [comment]
@JHulsmans Didn't even see that.
Actually, if it's a self hosted server, it should use a private IP, but then the router has to have the right port redirection.
