### ISSUE TITLE
ARK server not starting

### ISSUE THREAD

**Issue by surfarcher** [dgibbs64/linuxgsm#858]
Raised this a week ago on the steam forum but no help :-( Hoping I have better luck on here.

Port forwarding all looks 100%. I believe my debian config has been tweaked appropriately, regarding file limits, etc.

But no luck. Running through debug it seems to hang at a Steam API. I know this theoretically might not be an issue but no amount of waiting seems to have the server up and netstat doesn't have anything running on a port in the 777X range.

Info as outlined in the sticky thread...

Game server: arkserver

Distro: Debian
> Linux cerebro 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u2 (2016-01-02) x86_64 GNU/Linux

Logs:
./arkserver debug	http://pastebin.com/FtfXbDte
./arkserver details	http://pastebin.com/EPc12971
ark-server-console.log	http://pastebin.com/uV4bGjWm
ark-server-script.log	http://pastebin.com/9AwYy554

Starting the server, waiting 10 seconds and running "netstat -nap | grep Shoot" only gives ...

> udp      768      0 0.0.0.0:27015           0.0.0.0:*                           2078/ShooterGameSer

And ./serverfiles/ShooterGame/Saved/Logs/ShooterGame.log is zero length at this point :-(

Any assistance would be greatly appreciated!

**Comment by UltimateByte** [comment]
Hi,
There is no console output for Ark, and the steam API happens in any steam game, that's a non-issue, so look elsewhere.

Netstat should look like this : 

```
arkserver@game:~$ netstat -nap | grep Shoot
tcp        0      0 0.0.0.0:27625           0.0.0.0:*               LISTEN      538/ShooterGameServ
udp        0      0 0.0.0.0:7778            0.0.0.0:*                           538/ShooterGameServ
udp        0      0 0.0.0.0:27015           0.0.0.0:*   
```

I don't see a lot in my logs

```
cat ShooterGame-backup-2016.06.04-13.35.08.log
[2016.06.03-09.01.32:697][  0]Log file open, 06/03/16 11:01:32
[2016.06.03-09.01.32:697][  0]Primal Game Data Took 3.62 seconds
[2016.06.03-09.03.25:497][  0]Commandline:  TheIsland?listen
[2016.06.03-09.03.25:497][  0]Full Startup: 117.19 seconds (BP compile: 0.00 seconds)
[2016.06.03-09.03.25:497][  0]Number of cores 4
```

What's the output of your iptables ?
`iptables -L`

**Comment by UltimateByte** [comment]
http://steamcommunity.com/groups/linuxgsm/discussions/0/364042703857868173/

Go back to it, i'll try to help there, along with Cedar.
Github is used for development, and this is obviously a user/distro/firewall/whatever configuraiton issue.
