### ISSUE TITLE
TMUX Server cannot create a session?!

### ISSUE THREAD

**Issue by k1ll3ry0** [dgibbs64/linuxgsm#859]
![image](https://cloud.githubusercontent.com/assets/19755099/15803043/8b881b3a-2a98-11e6-8c3f-03f0d13cf4b5.png)
Tried everything, anyone have some guidance?????

**Comment by UltimateByte** [comment]
1) User issues are supported within the steam group.
2) If you're hoping any help, at least give some relevant information (distro, logs, tmux version, stuff like that). 
3) Github is not Twitter, you can write more than 1 line.

**Comment by k1ll3ry0** [comment]
Ubuntu 16.04 LTS
TMUX 2.1
Install went flawless, I go to initiate the server and it comes up with the above error. As far as logs nothing really presents itself.

**Comment by UltimateByte** [comment]
Never seen this issue, seems like a tmux one, i agree with ya but i can't be sure with so few clues. Further investigation required. Maybe first try the debug start ? It won't use tmux that way.
./insserver debug
(i'll be very busy for the next 24h, i wish you good luck to find somebody else to follow up the issue.

**Comment by k1ll3ry0** [comment]
Thank you for your insight, I will dig deeper and report back.

**Comment by cedarlug** [comment]
I've seen this issue before when you've started a tmux session and then upgraded the system tmux.  If that's the issue, the easiest fix is to reboot.

**Comment by UltimateByte** [comment]
Good idea, but reboot is lame :p 
Another way would probably be to find the PID and kill it.

**Comment by k1ll3ry0** [comment]
No luck as far as rebooting. I'm fairly certain it may actually lie in the permissions of Ubuntu 16.04. I have actually reinstalled the system to attempt to fix it, no luck with 16.04. I plan on giving 14.04 a good ole college try as I believe it's less "set up" and more minimalist in installation with regards to security. If all else fails I'm certain it'll run on Centos 7 which will probably be my final attempt.

**Comment by JHulsmans** [comment]
Before you do a reinstall. Have you tried out the ./insserver debug ?

Could you give us your logs etc. as well. (I know you said that "nothing really presents itself" but still I'd like to go through them either way.) 

If you wish to reinstall your OS anyway just give us a heads up and we can close this issue in that case.

**Comment by UltimateByte** [comment]
If you wish to reinstall before trying the debug console, you're a bit foolish, but even more if you quit Ubuntu for CentOS. Lol. If you want a stable and simple OS with minimum stupid stuff pre-installed, go for Debian. If you want nice web features but loads of knowledge required and a huge loss of time, go for CentOS.

**Comment by cedarlug** [comment]
A bit of relevant Linux history is in order!
Did you know....
<details> 
  <summary>"Ubuntu" is an historic word of African entymology, whose meaning translates to: </summary>
   Definition: _Ubuntu_ **One who cannot configure Debian.**

   Betcha didn't know that!
</details>

**Comment by UltimateByte** [comment]
Haha :p 
I knew it sounded like an urban dictionary definition. Google confirmed. ^^
Let's say Ubuntu is to Debian what Windows XP Media Center is to Windows XP. :o))
