### ISSUE TITLE
[Arma 3] Unable to start

### ISSUE THREAD

**Issue by AznoYT** [dgibbs64/linuxgsm#863]
Hello everyone, I add mods to my server and when I retre start command it shows me this

![252804966ace1737bd77fffc5c109779](https://cloud.githubusercontent.com/assets/19228581/15831539/6816ad4c-2c1e-11e6-8a49-4e1c1662a097.png)

here is my file arma3server

![9633853206427553072816a7e41be762](https://cloud.githubusercontent.com/assets/19228581/15831577/946b92e0-2c1e-11e6-842e-098e25ea89c9.png)

Thank you in advance for your assistance

**Comment by UltimateByte** [comment]
Hi,

Weird error. Please, run
./arma3server uf
If it doesn't fix the issue, please post your full arma3server file to pastebin (strip sensitive information if there is any) and share the link here.

**Comment by AznoYT** [comment]
here is my arma3server file

http://pastebin.com/EiK85r5h

**Comment by dgibbs64** [comment]
Delete your wastebin file now!!! And update your steam login!!!!

**Comment by AznoYT** [comment]
http://pastebin.com/EiK85r5h

**Comment by igeighty** [comment]
hi @AznoYT ,

first try to start the server with no mods, does that start ?

is it possible you can pastebin the result of `./arma3server details` and `./arma3server debug` ?
don't forget to remove passwords from the result of debug

ill have a look and see if anything jumps out.

**Comment by AznoYT** [comment]
Hi, I've managed to settle my problem, it was that there was a capital in one of my mods, ben shot from the server does not start

**Comment by igeighty** [comment]
Yes Linux arma3 will stall if there are any capitols in the mid folder name or contents. Good you got it working

**Comment by UltimateByte** [comment]
Just like gmod. Thanks for the feedback :)
