### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by Gucccii** [dgibbs64/linuxgsm#866]
Last login: Tue Jun  7 19:56:00 UTC 2016 on pts/1
Linux Gucci 3.2.0-4-amd64 #1 SMP Debian 3.2.78-1 x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
server@Gucci:~$ wget https://gameservermanagers.com/dl/csgoserver
--2016-06-07 20:03:07--  https://gameservermanagers.com/dl/csgoserver
Resolving gameservermanagers.com (gameservermanagers.com)... 104.31.92.238, 104.31.93.238, 2400:cb00:2048:1::681f:5cee, ...
Connecting to gameservermanagers.com (gameservermanagers.com)|104.31.92.238|:443... connected.
GnuTLS: A TLS fatal alert has been received.
Unable to establish SSL connection.
server@Gucci:~$

I have used this before and it worked just fine but now it will not work.

**Comment by cedarlug** [comment]
Debian 7's wget has an issue negotiating ECC ciphers.

Use curl instead as workaround.
```bash
curl -L --output csgoserver https://gameservermanagers.com/dl/csgoserver
```
See [this discussion on the issue](http://steamcommunity.com/groups/linuxgsm/discussions/0/364041517010932228/#c364041517010974903) for more details.

**Comment by Gucccii** [comment]
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100  4922  100  4922    0     0   3805      0  0:00:01  0:00:01 --:--:--  3805
When I input that command all I get is this.

**Comment by UltimateByte** [comment]
Also,
ca-certificates installed ?

**Comment by Gucccii** [comment]
okay well it installed the script but now when I install steamcmd there are a lot of errors.
server@Gucci:~$ ./csgoserver install
    fetching core_dl.sh...OK
    fetching core_functions.sh...OK
    fetching core_messages.sh...OK
    fetching core_getopt.sh...OK
    fetching command_install.sh...OK
    fetching check.sh...OK
    fetching check_root.sh...OK
    fetching check_permissions.sh...OK
    fetching check_glibc.sh...OK
    fetching info_glibc.sh...OK
    fetching info_distro.sh...OK
    fetching install_header.sh...OK
=================================
Counter Strike: Global Offensive
Linux Game Server Manager
by Daniel Gibbs
Contributors: http://goo.gl/qLmitD
https://gameservermanagers.com
=================================
    fetching install_server_dir.sh...OK

Server Directory
=================================

/home/server

Continue [Y/n]y
mkdir: created directory `/home/server/serverfiles'
    fetching install_logs.sh...OK

Creating log directories
=================================
mkdir: created directory `/home/server/log'
mkdir: created directory `/home/server/log/script'
mkdir: created directory `/home/server/log/console'
`/home/server/log/server' -> `/home/server/serverfiles/csgo/logs'
    fetching check_deps.sh...OK

Checking Dependecies
=================================
curl
ca-certificates
file
tmux
lib32gcc1
libstdc++6:i386
[ WARN ] Install csgo-server: Checking dependencies: missing: tmux lib32gcc1 libstdc++6:i386

Infomation! server does not have sudo access. Please manually install dependencies

sudo dpkg --add-architecture i386; sudo apt-get install tmux lib32gcc1 libstdc++6:i386

    fetching install_steamcmd.sh...OK

Installing SteamCMD
=================================
    fetching check_steamcmd.sh...OK
mkdir: created directory `/home/server/steamcmd'
    fetching steamcmd_linux.tar.gz...OK
extracting steamcmd_linux.tar.gz...OK
    fetching install_server_files.sh...OK

Installing Counter Strike: Global Offensive Server
=================================
./steamcmd.sh: line 29: /home/server/steamcmd/linux32/steamcmd: No such file or directory
Warning! SteamCMD did not complete the download, retrying: Attempt 2
./steamcmd.sh: line 29: /home/server/steamcmd/linux32/steamcmd: No such file or directory
Warning! SteamCMD did not complete the download, retrying: Attempt 3
./steamcmd.sh: line 29: /home/server/steamcmd/linux32/steamcmd: No such file or directory
Warning! SteamCMD did not complete the download, retrying: Attempt 4
./steamcmd.sh: line 29: /home/server/steamcmd/linux32/steamcmd: No such file or directory
Warning! SteamCMD did not complete the download, retrying: Attempt 5
./steamcmd.sh: line 29: /home/server/steamcmd/linux32/steamcmd: No such file or directory
Warning! SteamCMD did not complete the download, retrying: Attempt 6
./steamcmd.sh: line 29: /home/server/steamcmd/linux32/steamcmd: No such file or directory
Warning! SteamCMD did not complete the download, retrying: Attempt 7
Removing
./steamcmd.sh: line 29: /home/server/steamcmd/linux32/steamcmd: No such file or directory
Warning! SteamCMD did not complete the download, retrying: Attempt 8
Removing
./steamcmd.sh: line 29: /home/server/steamcmd/linux32/steamcmd: No such file or directory
Warning! SteamCMD did not complete the download, retrying: Attempt 9
Removing
mkdir: created directory `/home/server/steamcmd'
extracting steamcmd_linux.tar.gz...OK
/home/server/lgsm/functions/install_server_files.sh: line 63: ./steamcmd.sh: No such file or directory
Warning! SteamCMD did not complete the download, retrying: Attempt 10
Removing
mkdir: created directory `/home/server/steamcmd'
extracting steamcmd_linux.tar.gz...OK
/home/server/lgsm/functions/install_server_files.sh: line 63: ./steamcmd.sh: No such file or directory
Failure! SteamCMD did not complete the download, too many retrys

**Comment by cedarlug** [comment]
You went off the tracks with the installation instructions.

Follow the [instructions starting with adding the i386 architecture](https://gameservermanagers.com/lgsm/csgoserver/) and fetching the requisite packages before pulling the trigger on the `./csgoserver install` command.  Be sure to select your correct OS for the corresponding instructions.

**Comment by UltimateByte** [comment]
The dude can't read, calls his user "server". I'm out.

**Comment by cedarlug** [comment]
Close?
