### ISSUE TITLE
[StarsOne] server request

### ISSUE THREAD

**Issue by FlashModz** [dgibbs64/linuxgsm#867]
do you think it would be possible to integrate the latest games survival and construction?

StarsOne

Thanks You :)

**Comment by UltimateByte** [comment]
Is there a linux dedicated server for it ? Any documentation ?
Can't find it on SteamDB.
https://steamdb.info/search/?a=app&q=StarsOne

**Comment by JHulsmans** [comment]
It's Linux compatible. Ubuntu 10.10 and upwards, last time I checked the multiplayer was really buggy though as is to be expected from an Alpha.

If enough people get behind it or it's really no work at all someone will surely implement it. :)

**Comment by FlashModz** [comment]
Yes a lot of steam talking Linux dedicated server including but not much information leak on the subject

**Comment by UltimateByte** [comment]
If there is no linux server, then there's nothing we can do atm.

**Comment by dgibbs64** [comment]
If there is not Linux server please close this. However re-open if it becomes available.
