### ISSUE TITLE
Arma 3 port issue

### ISSUE THREAD

**Issue by koekblik2** [dgibbs64/linuxgsm#870]
hello, so i wanted to make a arma 3 server with ubuntu and i have a big issue which i couldn't find anywhere i searched for some hours and still didn't find/fix it maybe some of you could help?

so first if i get the server details i get this: https://gyazo.com/caea244b225eb2501e3491bea94ed73a
and that is after a fresh install.. if i do the monitor command it says: https://gyazo.com/3a25ca191482e328268da9e1dffa0a7e

i really don't know what to do anymore i port forwarded the ingoing and outgoing and i really am lost.. 

thank you or your time to help if you have any questions ask me :)

**Comment by UltimateByte** [comment]
Seems like there are some issues with the monitor function, don't worry about it for now. What's in your .cfg file about ports ?

**Comment by koekblik2** [comment]
hi, i didn't change much in it here's the server.server.cfg

`// ArmA 3 Server Config File
//
// More info about parameters:
// https://community.bistudio.com/wiki/server.cfg


// PORTS
// please specify the serverport as a parameter in arma3server executable
// it will automatically use the serverport including the next 3 for steam query & steam master.
// the fourth port ist not documented in https://community.bistudio.com/wiki/Arma_3_Dedicated_Server#Port_Forwarding
// Server Port
//  default: 2302.
// serverport=2302;

// Steam Master Port
//  default: 2304.
// steamport=2304;

// Steam Query Port
//  default: 2303.
//steamqueryport=2303;


// GENERAL SETTINGS

// Server Name
hostname = "[EN/EU]gaming.basickiwi.com Tanoa Life";

// Server Password
//password = "arma3pass";

// Admin Password
passwordAdmin = "*************";

// Server Slots
maxPlayers = 32;

// Logfile
logFile = "arma3server.log";

// Minimum Required Client Build
//requiredBuild = 95691

// Message of the Day (MOTD)
motd[]={
    "Welcome to My Arma 3 Server",
    "TS3 Server:     teamspeak.somewhere.com",
    "Web:            www.example.com"
};

// MOTD Interval (Seconds)
motdInterval = 30;


// VOTING

// Server Mission Start
//  minimum number of clients before server starts mission
voteMissionPlayers = 1;

// Accepted Vote Threshold
//  0.33 = 33% clients.
voteThreshold = 0.33;

// INGAME SETTINGS

// Disable Voice over Net (VoN)
//  0 = voice enabled.
//  1 = voice disabled.
disableVoN = 0;

// VoN Codec Quality
//  0-10 = 8kHz (narrowband).
//  11-20 = 16kHz (wideband).
//  21-30 = 32kHz (ultrawideband).
vonCodecQuality = 3;

//Persistent Battlefield
//  0 = disable.
//  1 = enable.
persistent = 1;

// Time Stamp Format
//  none, short, full
timeStampFormat = "short";


// SERVER SECURITY/ANTI HACK

// Verify Signitures for Client Addons
//  0 = off.
//  1 = weak protection (depricated).
//  2 = full protection.
verifySignatures = 2;

// Secure Player ID
//  1 = Server warning message.
//  2 = Kick client.
requiredSecureId = 2;

// Kick Duplicate Player IDs
kickDuplicate = 1;

// BattlEye Anti-Cheat
//  0 = disable
//  1 = enable
BattlEye = 1;

// Allowed File Extentions
allowedLoadFileExtensions[] = {"hpp","sqs","sqf","fsm","cpp","paa","txt","xml","inc","ext","sqm","ods","fxy","lip","csv","kb","bik","bikb","html","htm","biedi"};
allowedPreprocessFileExtensions[] = {"hpp","sqs","sqf","fsm","cpp","paa","txt","xml","inc","ext","sqm","ods","fxy","lip","csv","kb","bik","bikb","html","htm","biedi"};
allowedHTMLLoadExtensions[] = {"htm","html","xml","txt"};

// SCRIPTING ISSUES
onUserConnected = "";					//
onUserDisconnected = "";				//
doubleIdDetected = "";					//

// SIGNATURE VERIFICATION
// kick = kick (_this select 0)
// ban = ban (_this select 0)
onUnsignedData = "kick (_this select 0)";
onHackedData = 	"kick (_this select 0)";
onDifferentData = "";

// HEADLESS CLIENT SUPPORT
// specify ip-adresses of allowed headless clients
// if more than one:
// headlessClients[]={"127.0.0.1", "192.168.0.1"};
// localClient[]={"127.0.0.1", "192.168.0.1"};
headlessClients[]={"127.0.0.1"};
localClient[]={"127.0.0.1"};
battleyeLicense=1;`

**Comment by UltimateByte** [comment]
Please, use pastebin (i edited your post).
I've never made an arma3 server, but maybe uncomment those : 
serverport=2302;
steamport=2304;
steamqueryport=2303;

And try again.

Also, have a read at this https://github.com/dgibbs64/linuxgsm/issues/865

**Comment by koekblik2** [comment]
ye i tried that what it says in the post but it still didn't work for me was still doing the same weird thing even though i port forwarded the ports..

but its pretty weird it just starts up normally but never shows up in the server browser of arma (not even with direct connect) https://gyazo.com/fb129327f0211fd22874f39069dae005

**Comment by UltimateByte** [comment]
Is this a server in your home ?

**Comment by koekblik2** [comment]
no its a dedicated server i use with other friends

**Comment by UltimateByte** [comment]
What kind of server is this ?
Do this dedicated server host other servers ?
Isn't there any kind of a firewall behind it ? OVH "game" server for example have a firewall you have to set before anything works.

**Comment by koekblik2** [comment]
no we just bought a dedicated server and put game servers (like ark and rust etc) on it.

**Comment by UltimateByte** [comment]
There is no such a thing as port forward on a dedicated server.

**Comment by JHulsmans** [comment]
Alright @koekblik2. Answer this question to the best of your ability. (I know it's been asked before.)

If I were to buy the exact same server as you? Where do I go? Did you purchase a dedicated server and had it shipped to one of your friends homes? (It's a home hosted server then.)

Does someone else (OVH, Hetzner) for example have the hardware and do you "lease" it every month/whatever period?

Can you provide us with the specifications of said server.

And last but not least. Do Ark and Rust work? As in can you log on and play on them?

If we get all that from you we'll try to guide you.

PS. As UltimateByte already said there's currently a problem with the monitor function.

**Comment by koekblik2** [comment]
@JHulsmans its a leased server one of my friends pays for it every month so ye its dedicated somewhere else. and yes the (2) ark servers and (1) rust server are working like they should like the specs of the server itself i don't know that if you really need it i can ask

**Comment by UltimateByte** [comment]
A merge happened 2 days ago, should fix the monitor function.
./arma3server update-functions
Please, keep us tuned.

**Comment by igeighty** [comment]
the fix in #865 works to resolve the monitor problem,

i have just tried starting server with the ports commented and not commented in arma3-server.server.cfg
and there is no difference to the server functioning. so in short no need to uncomment the lines in the config if you are running just the default server setup.

the changes you made to `lgsm/functions/info_parms.sh ` do fix the reporting of the correct ports when you run 'details'

**Comment by UltimateByte** [comment]
Yeah, the merge actually fixes the details function but not the port ! 
Let's close this as #865 summs it up all !

As always, feel free to re-open if needed, otherwise, let's discuss about it on #865 
@koekblik2 follow #865 to know when it's fixed :)
