### ISSUE TITLE
Review having required and optional dependencies

### ISSUE THREAD

**Issue by dgibbs64** [dgibbs64/linuxgsm#873]
There are a couple of dependencies that are required and a couple that are now optional postfix for example. 

Will need to investigate if postfix for example will need to be listed as optional.

**Comment by cedarlug** [comment]
It would be good to have libncurses5 or lib32tinfo5 (or their RPM equivalents) listed as optional packages.  These packages provide tmux console functionality for console control and navigation - ctrl-a (beginning of line), ctrl-e (end of line).

**Comment by dgibbs64** [comment]
This is now the case with postfix.  I am closing this as I dont think any more work is required

**Comment by UltimateByte** [comment]
What about an optional category on the website ?

**Comment by dgibbs64** [comment]
@cedarlug I didn't realise thats what libncurses5 did. @UltimateByte I will be leaving them as they are so it doesnt add any confusion to users. If they know what they are doing they will just remove the packages they dont want :)
