### ISSUE TITLE
rules iptables

### ISSUE THREAD

**Issue by romaricboufatis** [dgibbs64/linuxgsm#883]
Hello guys i'm just wondering if someone has the IPTABLES rules for csgoserver.

I using lxc so I need to DNAT to my container but if is not possible I just need the iptables rules for authorize the client to request my server ;)... 

Don't see anything on the web for this... 

I know the IPTABLES give by steam for csgo but don't work here... 

Regards.

**Comment by UltimateByte** [comment]
./csgoserver details
Will give you informations about used ports.
If afterwards you don't know how to set iptables, then i'd suggest you to flush iptables and don't use it. There is 99% chances it's useless in your case anyways.

Github is about LGSM development. For issues or questions, please use the steam group.
http://steamcommunity.com/groups/linuxgsm/discussions/0/

**Comment by UltimateByte** [comment]
Hi there
./csgoserver details
Will give you informations about used ports (port n° and protocol).
Also, LGSM don't officially support containers, so if you wanna use them, it's up to you to figure out how.

Github is about LGSM development. For issues or questions, please use the steam group.
http://steamcommunity.com/groups/linuxgsm/discussions/0/

**Comment by Skyborder** [comment]
Is not works
iptables -A INPUT -p udp -m udp --dport 27015 -m state --state NEW -m recent --set --name DEFAULT --rsource
iptables: No chain/target/match by that name.
