### ISSUE TITLE
LGSM Ark Survial Server Center map save problems start script overiding?

### ISSUE THREAD

**Issue by shadowkillerButton** [dgibbs64/linuxgsm#887]
Hello I am using  LGSM server manager for Ark Survial 

 I am having lots of problems after that I changed my map in the start file 

everytime after saving the world in game and restarting the server it start over again from day one all buildings and stuff are removed player profiles are still the level they where but they don't have any items in there inventory does somone know this problem ? I think the script is keep loading up  the new map and overiding my save files.

edit i changed my map in the arkserver start script under fn_parms() I don't know if this is the problem why the server is doing so strange
greetz

**Comment by Scarsz** [comment]
Do you have any steps we could use to reproduce this?

**Comment by Scarsz** [comment]
Closing to lack of response
