### ISSUE TITLE
Debian CSGO Installation

### ISSUE THREAD

**Issue by YannickFricke** [dgibbs64/linuxgsm#89]
I think there is a huge error :/
# 

Counter Strike: Global Offensive
Linux Game Server Manager
by Daniel Gibbs
# http://danielgibbs.co.uk
# Installing SteamCMD

mkdir: Verzeichnis „steamcmd“ angelegt
--2014-05-09 17:42:04--  http://media.steampowered.com/client/steamcmd_linux.tar.gz
Auflösen des Hostnamen »media.steampowered.com (media.steampowered.com)«... 87.248.217.253, 87.248.217.254
Verbindungsaufbau zu media.steampowered.com (media.steampowered.com)|87.248.217.253|:80... verbunden.
HTTP-Anforderung gesendet, warte auf Antwort... 200 OK
Länge: 3170982 (3,0M) [application/octet-stream]
In »»steamcmd_linux.tar.gz«« speichern.

100%[==========================================================================================================================================>] 3.170.982   --.-K/s   in 0,05s

2014-05-09 17:42:04 (58,3 MB/s) - »»steamcmd_linux.tar.gz«« gespeichert [3170982/3170982]

linux32/
linux32/libstdc++.so.6
linux32/steamcmd
steamcmd.sh
steam.sh
„steamcmd_linux.tar.gz“ entfernt
# Installing Counter Strike: Global Offensive Server

mkdir: Verzeichnis „/home/frickx/csgo/serverfiles“ angelegt
./steamcmd.sh: Zeile 29: /home/frickx/csgo/steamcmd/linux32/steamcmd: Datei oder Verzeichnis nicht gefunden
# 

Was the install successful? [y/N]

**Comment by WillHaskell** [comment]
A bit late, but you need to install libc6:i386 and lib32stdc++6
