### ISSUE TITLE
Error starting the server

### ISSUE THREAD

**Issue by Andres-S** [dgibbs64/linuxgsm#891]
I can not install this package on my linux server; It appears this error!

![err](https://cloud.githubusercontent.com/assets/19987031/16210469/889cb0bc-3712-11e6-95d9-ddaf3f50ca74.JPG)

**Comment by dgibbs64** [comment]
You need root access to install a dependency. This is Linux 101. I suggest learning how to install dependencies ;-)

**Comment by Andres-S** [comment]
But even as root I can not

![afsd](https://cloud.githubusercontent.com/assets/19987031/16213415/8c5b4d68-3725-11e6-9a01-c1c0f4c45c28.JPG)

**Comment by dgibbs64** [comment]
...Wekk thats different then. I need to know your distro for a start. Im guessing CentOS?

**Comment by cedarlug** [comment]
Amazon Linux.

**Comment by UltimateByte** [comment]
Amazon Linux, here is your issue.
Install a true distro and try again.

**Comment by dgibbs64** [comment]
Closing. Please re open if required
