### ISSUE TITLE
ArmA 3 not listening on TCP

### ISSUE THREAD

**Issue by Graymanflo** [dgibbs64/linuxgsm#894]
Hey everyone.

I am having an issue with allowing traffic to my ArmA 3 server, it doesn't appear in the Multiplayer server list and direct connect isn't resolving the host aswell as [yougetsignal.com/tools/open-ports/](url). It also appears as the server doesn't listen on any TCP port.
![screenshot_2](https://cloud.githubusercontent.com/assets/17147562/16236984/ae017752-37da-11e6-8bcf-24a3d26272da.png)

In above screenshot only UDP is listed, here are my system details:
- Dedicated server running Debian 8.4 Jessie.
- Network: 1gbps.
- No firewalls, iptables are uninstalled.
- IP and port (2302) are defined in arma3server.

Please let me know if anyone knows what's wrong :)!

**Comment by igeighty** [comment]
Have you opened udp ports 2302,2303,2304,2305 in the router ?

**Comment by UltimateByte** [comment]
@igeighty Seems like he's got a gigabit network, so it's probably a dedicated server, so no router. + not forwarding ports doesn't prevent the machine from listening to it.

Any mods installed ?
Any logs to provide ? (strip any sensitive information)
Also, please use the steam group for general support http://steamcommunity.com/groups/linuxgsm/discussions/0/

**Comment by igeighty** [comment]
agreed, 
not port forwarding would only disable the server from appearing in the online server browser.
on my own installation which is a linux machine connected to a local network via an apple time capsule router. when using arma3server script i can see my server in the online browser, but not the LAN browser (weird) yet i am able to use the direct connect feature to manually connect to the local address 192.168.1.118:2302 <- in my case.

also, arma uses UDP rather than TCP for the a3 server,

**Comment by UltimateByte** [comment]
So there is no TCP port listening for Arma ?
So everything is normal for him in the end ?
So there might be another firewall, like OVH game servers have. :)

**Comment by igeighty** [comment]
Yes correct, no TCP for arma 3 (except 2344 and 2345 for battleeye which is not required for the game to function)
![screen shot 2016-06-22 at 1 47 48 pm](https://cloud.githubusercontent.com/assets/19503471/16254094/ee381bbe-387f-11e6-9241-ccd97f771191.jpg)
But for the game itself and its query ports all traffic is on UDP

https://community.bistudio.com/wiki/Arma_3_Dedicated_Server#Port_Forwarding

this is how i have mine configured on both servers, one running arma3server script, the other just running install from bohemia with no fancy scripting for testing,

**Comment by Graymanflo** [comment]
Thanks for all the wonderful replies guys! I also went over to the Steam group.

@igeighty 
> Have you opened udp ports 2302,2303,2304,2305 in the router ?
I am using a dedicated server like @UltimateByte said, however my host does not filter any ports or use any backend firewalls such as the one which OVH provide.


@UltimateByte 
> Any mods installed ?
> Any logs to provide ? (strip any sensitive information)
> OR, the process is launched 2 times or one of the ports is used by another process
> OR, iptables isn't correctly disabled
Here's the log file, I don't see anything abnormal in it [http://pastebin.com/iSfJJsEz](url), also no mods are installed.
![screenshot_3](https://cloud.githubusercontent.com/assets/17147562/16264662/1d6c419e-387b-11e6-9d0e-4fdcd68fc5cd.png)
The process should be launched correctly and iptables are gone for good:
$ apt-get remove --purge --auto-remove iptables && apt-get update


Here is arma3server config:
http://pastebin.com/xteU0xQ6

My host provider says that this is a software related issue, I'm unsure about that as it works for you guys.

**Comment by igeighty** [comment]
Delete your pastebin and change your steam password :)
Best to remove that info from your pastes

**Comment by Graymanflo** [comment]
@igeighty 
> Delete your pastebin and change your steam password :)
> Best to remove that info from your pastes

I accidentally left it there, thanks for mentioning that :)
**I posted this discussion here as suggested! http://steamcommunity.com/groups/linuxgsm/discussions/0/358415738180885929/**

**Comment by igeighty** [comment]
i notice this line in your arma3server script 
`ip="my.ipv4.is.specified.here"`

my installation i have this
`# Start Variables`
`ip="0.0.0.0"`
`port="2302"`
`updateonstart="off"`

i am running debian on a local machine though and the using port forward in my router to translate my outside IP. users are able to connect to my real world ip and through the server browser even though i have a LOCAL address in my config line


`./arma3server -netlog -ip=192.168.1.118 -port=2302 -cfg=/home/arma3server/serverfiles/cfg/arma3-server.network.cfg -config=/home/arma3server/serverfiles/cfg/arma3-server.server.cfg -mod= -servermod= -bepath= -autoinit -loadmissiontomemory`

it is just a thought, but try edit you IP to be 0,0,0,0 and see how she goes ?

**Comment by Graymanflo** [comment]
@igeighty 
> it is just a thought, but try edit you IP to be 0,0,0,0 and see how she goes ?
I have no clue why this isn't working, any other service on the machine got a public port with no further issues. Like I said in the steam group, I tried that and it didn't solve the issue but thanks anyway!

**Comment by igeighty** [comment]
this issue wasn't a script issue, it was solved by the hosting company.
This can be closed
