### ISSUE TITLE
"Set current directory to ..." & "Found path: ..."

### ISSUE THREAD

**Issue by MPNull** [dgibbs64/linuxgsm#895]
Trying to run a server won't start it up. I've been trying to run server via everything including a Wine until I discovered the "GameServerManager" thing.

I had no problems at all when installing. All required parts was installed successfully, but when I start the server it says:

> [ OK ]Starting rust-server: Rust

If I run the server in debug mode the console looks like this:

![](https://i.gyazo.com/cc00d51d0e8bbb79b650de97430f3282.png)

Using a Debian 8.
Installed the server exactly like instructions says excluding the rustserver name which is replaced with sysadmin account. I've also tried it with rustserver account. No matter.

**Comment by dgibbs64** [comment]
I believe that is all that Rust displays on its console. So it may be working

**Comment by UltimateByte** [comment]
Normal behavior. Rust console has nothing to show.
I wrote this that answers pretty much any question you could have about a Rust server : http://oxidemod.org/threads/setting-up-a-rust-server-with-linux-and-lgsm.16528/

**Comment by MPNull** [comment]
It's normal behavior when server doesn't start?

Normal result is this:

![](http://i.imgur.com/iMibni8.png)

**Comment by UltimateByte** [comment]
Normal result is the first picture you showed.
The second one is probably the Windows version.
To get a relevant output, you gotta use RCON with for example Rusty.
