### ISSUE TITLE
[Arma 3] Bepath for Battleye

### ISSUE THREAD

**Issue by AznoYT** [dgibbs64/linuxgsm#896]
Hello everyone, I turn to you today because I wanted to use the EPM Rcon software to administer my server correctly, suddenly here's what I get into the rcon bepath:
![39c13a421e5922943418b4bea7d2c27d](https://cloud.githubusercontent.com/assets/19228581/16265102/bcafca94-387d-11e6-90ad-945527ac91eb.png)
but when I go into my software EPM Rcon, I get all the right information, it shows me this:
![aa132a4f1d426fb51306fd1c966ae064](https://cloud.githubusercontent.com/assets/19228581/16265146/f683b44c-387d-11e6-9c94-5b763d928192.png)

thank you in advance for your help

**Comment by igeighty** [comment]
have you created a beserver.cfg file ?

**Comment by AznoYT** [comment]
Yes

**Comment by igeighty** [comment]
have you specified a port in that file ?

my beserver.cfg
`RConPort 2301`
`RConPassword 123456`
`MaxPing 500`

i have port forwarded port 2301 tcp and ump in router.
beserver.cfg resides in ./serverfiles/battleye (with chmod 775)
my arma3server script battle eye entry is 

`# Path to BattlEye`
`# leave empty for default`
`bepath=""`

**Comment by AznoYT** [comment]
es Do I have to put any thing in bepath?

**Comment by igeighty** [comment]
i would leave `bepath=""`
restart server and see how that goes ? i did have issues when specifying a path in that value.
as long as you place beserver.cfg in /home/arma3server/serverfiles/battleye/

**Comment by AznoYT** [comment]
it is normal that after the file is called beserver_active_xxxxxxxx.cfg ?

**Comment by igeighty** [comment]
it seems that is a security measure, the battleye client adds random letters to it as an anti-hack measure, 
what it does show is that battle eye is reading the file :)

when the server is stopped you can safely rename it back to beserver.cfg make any changes. and once the server starts again, you'll notice the file is then renamed to beserver_active_xxxxxxxx.cfg.

are you hosting from home or a dedicated ? as you may have to have the port forwarded ?

**Comment by AznoYT** [comment]
My server is hosted by OVH is the game port is 2302

**Comment by igeighty** [comment]
not sure about hosted setups, sorry, i use a dedicated linux machine on my local network with ports forwarded through my router so it can be connected to from the outside, 
my local address for server is 192.168.1.118 and it appears in the server browser as 211.28.215.135

did OVH have to open your UDP ports 2302,2303,2304,2305 ? if they did, you will have to ask them to open 2301 (or whatever port you specify in beserver.cfg) on both TCP and UDP. battleye uses TCP and UDP as far as i can tell.. whereas arma3 server uses UDP only

**Comment by AznoYT** [comment]
I'm on a dedicated machine OVH and my machine to unlock all ports

**Comment by igeighty** [comment]
netstat -atunp | grep arma3server 

you should see similar to this (mine is local address)

`udp        0      0 192.168.1.118:2301      0.0.0.0:*                           5459/arma3server` _<-- battleye port_
`udp        0      0 192.168.1.118:2302      0.0.0.0:*                           5459/arma3server`
`udp        0      0 192.168.1.118:2303      0.0.0.0:*                           5459/arma3server`
`udp        0      0 192.168.1.118:2304      0.0.0.0:*                           5459/arma3server`
`udp        0      0 192.168.1.118:2305      0.0.0.0:*                           5459/arma3server`

**Comment by AznoYT** [comment]
I have this:

![434e822f5f92b87ff95c34c0114718ce](https://cloud.githubusercontent.com/assets/19228581/16268899/73a01936-3890-11e6-8383-c2223e4fec09.png)

**Comment by igeighty** [comment]
could you post your beserver.cfg (overwrite your password)

from the screen shot i am guessing that 53434 is your battleye port maybe

**Comment by AznoYT** [comment]
http://pastebin.com/nQYP5rGi

**Comment by igeighty** [comment]
found it,

`RConPassword *****`
`RConPort 2302`  <--cant use game port :)
`MaxPing 350`

change to `RConPort 2301`

**Comment by igeighty** [comment]
since v1.58 as per bohemia...
_RconPort must avoid reserved ARMA3server port range (gameport *+0,+1,+2,+3))
default reserved ports are 2302 - 2305 (to clarify the reserved ports can't be used for BattlEye's RCON).
example for default server setting, RconPort 2301_
https://community.bistudio.com/wiki/BattlEye#RCon

**Comment by AznoYT** [comment]
I'm testing

**Comment by UltimateByte** [comment]
If you got an OVH "Game" series server, make sure your OVH firewall (not iptables) doesn't block those ports.

**Comment by AznoYT** [comment]
it's good it works, and for information when they rent a dedicated server at OVH all ports are already open

**Comment by igeighty** [comment]
thats good, so the problem was the wrong port in beserver.cfg ?

glad its working now. may as well close the ticket as it is now fixed

have fun.
