### ISSUE TITLE
[GMOD] Server crashing Debian 8.4 Stable

### ISSUE THREAD

**Issue by FlashModz** [dgibbs64/linuxgsm#910]
Hello everyone,

My server GMOD Crash.
Validate ( Not resolve my problems )
Force-update ( Not resolve my problems )
update-functions ( Not resolve my problems )
Fresh install ( not resolve my problems )

logs : 

./srcds_run: line 372: 29319 Segmentation fault      $HL_CMD
Add "-debug" to the ./srcds_run command line to generate a debug.log to help with solving this problem
Fri  1 Jul 19:15:39 CEST 2016: Server restart in 10 seconds
FIND [/home/srcds/css/cstrike/*.vpk]
ADDING [/home/srcds/css/cstrike/cstrike_pak_000.vpk]
Adding Path: [/home/srcds/css/cstrike]
Couldn't load shader dll: game_shader_generic_garrysmod_srv.soConVarRef mat_dxlevel doesn't point to an existing ConVar
Game_srv.so loaded for "Garry's Mod"
Setting breakpad minidump AppID = 4000
Initializing Steam libraries for Workshop..
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Fetching Workshop Addons..
Calling GetCollectionDetails
Collection has 138 Addons
Connection to Steam servers successful.

Please Help Me

All Package are up to date.

**Comment by dgibbs64** [comment]
This if not related to LGSM

you are experiencing the infamous "Segmentation fault" that is hard to diagnose. If your just using a VPS I would personally reload it with Ubuntu. However there maybe something someone else could advise. I reccomend having a good google around as quite a few people get this kind of error.

**Comment by UltimateByte** [comment]
Try to unmount css content, try to validate your files, try to find the addon that fucks your server up, but it's definitely not LGSM related.

**Comment by FlashModz** [comment]
Problems OVH Game firewall

**Comment by UltimateByte** [comment]
OVH's "Game" firewall generate bad kernel checksum which fucks up server's motherboard and is causing this issue. OVH is now working on it thanks to @FlashModz. Good work.
