### ISSUE TITLE
Ark Server: Start Online and then Offline

### ISSUE THREAD

**Issue by danaidk** [dgibbs64/linuxgsm#911]
I don't know this error effect or not.

**_[ WARN ] Validate ark-server: Validating may overwrite some customised files._**
https://developer.valvesoftware.com/wiki/SteamCMD#Validate
[  OK  ] Validate ark-server: Checking server filesERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/coreutils/libstdbuf.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Redirecting stderr to '/home/arkserver/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Created shared memory when not owner SteamController_Shared_mem
OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x5) validating, progress: 1.96 (73945674 / 3775295108)
 Update state (0x5) validating, progress: 7.80 (294285477 / 3775295108)
 Update state (0x5) validating, progress: 16.77 (633011403 / 3775295108)
 Update state (0x5) validating, progress: 25.75 (972303104 / 3775295108)
 Update state (0x5) validating, progress: 32.06 (1210224936 / 3775295108)
 Update state (0x5) validating, progress: 42.90 (1619477349 / 3775295108)
 Update state (0x5) validating, progress: 49.30 (1861138191 / 3775295108)
 Update state (0x5) validating, progress: 54.51 (2058041917 / 3775295108)
 Update state (0x5) validating, progress: 60.52 (2284975546 / 3775295108)
 Update state (0x5) validating, progress: 64.44 (2432885266 / 3775295108)
 Update state (0x5) validating, progress: 71.08 (2683537146 / 3775295108)
 Update state (0x5) validating, progress: 77.14 (2912095124 / 3775295108)
 Update state (0x5) validating, progress: 82.76 (3124430789 / 3775295108)
 Update state (0x5) validating, progress: 88.42 (3338061056 / 3775295108)
 Update state (0x5) validating, progress: 91.92 (3470071500 / 3775295108)
 Update state (0x5) validating, progress: 94.06 (3551185573 / 3775295108)
 Update state (0x5) validating, progress: 98.79 (3729530692 / 3775295108)
Success! App '376030' fully installed.

**Comment by UltimateByte** [comment]
Let me guess... CentOS ?
Please, use this topic as you got a similar issue http://steamcommunity.com/groups/linuxgsm/discussions/0/358415738209532113/

**Comment by UltimateByte** [comment]
Quote from CedarLUG : 
> the stdbuf warning is benign (to remove it, install 'expect'). So if the stdbuf warning isn't fatal, then you've provided nothing to indicate any insight as to where your issue is.

**Comment by danaidk** [comment]
My server is Ubuntu 14.04.

**Comment by danaidk** [comment]
ARK: Survivial Evolved Debug
=================================

Distro: Ubuntu 14.04.4 LTS
Arch: x86_64
Kernel: 4.4.0-28-generic
Hostname: ARKserver

Start parameters:
./ShooterGameServer TheIsland?listen?MultiHome=xxx.xx.xxx.xx?SessionName=“ARK-server”?MaxPlayers=50?QueryPort=27015?RCONPort=32330?Port=7778?ServerAdminPassword=

Use for identifying server issues only!
Press CTRL+c to drop out of debug mode.
Warning! If ark-server is already running it will be stopped.

Continue? [Y/n]y
[ INFO ] Debug ark-server: Stopping any running servers
    fetching command_stop.sh...OK
[  OK  ] Stopping ark-server: “ARK-server-by-VisualGamer” is already stopped
[  OK  ] Debug ark-server: Starting debug
Using binned.
4.5.1-0+UE4 7038 3077 402 5
**_[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110_**
/home/arkserver/lgsm/functions/command_debug.sh: line 59:  9164 Killed                  ${executable} ${parms}

**Comment by cedarlug** [comment]
My magic wand is all out of clairvoyance dust at the moment.  I keep shaking it and curmudgeon dust is all that falls out.   It might be broken.  Where's a repair bench when you need one!

The good news is that I can craft more clairvoyance dust in-game.  Clairvoyance dust just requires crafting using logs (but not the wooden variety), details output, 4 jars of boars fat, and tongue placed firmly in cheek.   I have plenty of the latter two ingredients.  Could you help out with the first 2?

Follow the helpful tips on posting found [in the Steam discussion forum](http://steamcommunity.com/groups/linuxgsm/discussions/0/458604254471755996/) (which was suggested by @UltimateByte earlier), including the recommendation that console output be posted to pastebin.

**Comment by MastricX** [comment]
**[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110**

^ That is expected

/home/arkserver/lgsm/functions/command_debug.sh: line 59: 9164 Killed ${executable} ${parms}

^ This normally means you ran out of memory, ensure you have 4GB or swap space for Ark.

**Comment by danaidk** [comment]
Thank you so much

**Comment by UltimateByte** [comment]
Too few RAM.
