### ISSUE TITLE
Starting Server: NOT SET

### ISSUE THREAD

**Issue by Hackmastr** [dgibbs64/linuxgsm#912]
Hello, using LGSM for 2 servers, so far so good! 
However, I wanted to add another server, it installs just fine, configuration alright... But when I try to start-stop... it, it shows NOT SET...

Distro: Debian 8 64
Game: CSGO
Screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/9281515/16642008/b6f68a0e-4406-11e6-921d-b4e6b382b0e7.PNG)

**./csgoserver debug**  shows nothing usefull? I just start the server and shows the console

**Comment by cedarlug** [comment]
post your script to pastebin.
post your config to pastebin.

(optional!) Delete your server and rcon passwords.

My bet is that you have an extra quotation mark, spurrious single quote, or some really convoluted server name that's expanding in ways that you don't want it to.

**Comment by Hackmastr** [comment]
@cedarlug, wow, so fast, thanks.

By config You mean server.cfg? Its as it comes, default.

Script:

http://pastebin.com/SvWUKS5K

**Comment by igeighty** [comment]
your paste has been removed @Hackmastr 
`This page is no longer available. It has either expired, been removed by its creator, or removed by one of the Pastebin staff`

**Comment by cedarlug** [comment]
Perhaps that's because there was "... an extra quotation mark, spurrious single quote, or some really convoluted server name that (was) expanding in ways that (he didn't) want it to."

But just to follow up, @Hackmastr, the standard server config is modified during installation based on your input during the installation.  So if your server name was "!!H@ckm@$ter's ''DOG ##POUND##'' 'S'e'r'v'e'r''", that would make it into your default server config (and would likely be problematic).  Which was why I requested it.

**Comment by cedarlug** [comment]
Close?

**Comment by Hackmastr** [comment]
@cedarlug , sorry I was busy, here is the input again, and no, there's nothing weird
http://pastebin.com/MWt7Vzwz

cfg:
http://pastebin.com/8uCtYDBQ

**Comment by cedarlug** [comment]
Page removed (again).  What gives with your pastebin posts getting removed?

I guess we can close this under "Too busy, doesn't really want help?"

**Comment by UltimateByte** [comment]
Probably too busy hacking the CIA.

**Comment by Hackmastr** [comment]
@cedarlug, I'm still wondering why did it get deleted.
Here's the csgoserver again:
http://www.heypasteit.com/clip/2S8V

**Comment by UltimateByte** [comment]
Start by setting an IP, and 
`servicename=""`
to its original value and let's see again.

Can't say for the rest right now, i had a bit too much pints of beer. :o))

**Comment by Hackmastr** [comment]
@UltimateByte Thanks, I have another server(2 actualy) running fine with that IP var, servicename doesnt fix

**Comment by cedarlug** [comment]
Is there a reason your "+"'s were removed from your parms line?

`clientport ${clientport}` and all of the other should be `+clientport ${clientport}`

The options with a dash prefix are still in tact.  If your "+"'s are indeed missing and not stripped by some heypasteit parsing error, I'd recommend pulling down the script and starting over.

**Comment by Hackmastr** [comment]
@cedarlug, it's removed by heypasteit :stuck_out_tongue:

**Comment by cedarlug** [comment]
Could you please post a full interaction output from where your original post's error is generated?

Specifically, the console output (the entire thing, to pastebin) where you see the "`starting fun_serv`" in the output.

**Comment by Hackmastr** [comment]
@cedarlug, here:
http://pastebin.com/hTknCfyv

The script:

http://pastebin.com/hAL38FaX

**Comment by cedarlug** [comment]
Can you repost your server config without it going away?  For some reason your server's name is expanding to fun_serv, and you're only giving pieces to the puzzle (and then removing them).

This is not at all fun, @Hackmastr.  You're certainly making it "difficult" to solve your issue.

**Comment by Hackmastr** [comment]
@cedarlug, I removed nothing.

Here: 
http://pastebin.com/965mv12s

**Comment by cedarlug** [comment]
Take the pipe out of the hostname "|" in the config.

Just set the hostname to "test" and start the server.

**Comment by Hackmastr** [comment]
@cedarlug, nope, not working. BTW, if I stop it, it shows that too.

**Comment by UltimateByte** [comment]
You got another server (glad you finally mention this after 4 days...), so you made another user for the second server, right ?
And you made sure you were not using the same ports for the second server ?
https://github.com/dgibbs64/linuxgsm/wiki/Multiple-Servers

**Comment by UltimateByte** [comment]
servicename="fun_serv" is a bad idea btw.
You don't have to change this damn servicename if you got 2 users. And i'd avoid underscores for that kind of stuff.

Then, even if your server doesn't have a password, put back this sv_password "" variable inside your config. There's a little chance that it messes up with the config detection script (if so, we'd have to fix it).

Here is the code that says "NOT SET" https://github.com/dgibbs64/linuxgsm/blob/master/lgsm/functions/info_config.sh#L147

**Comment by UltimateByte** [comment]
Ultimately, why didn't we ask you post the output of `./csgoserver details` already ?
Please do it, and make sure your link doesn't expire 2 minutes later.

**Comment by Hackmastr** [comment]
@UltimateByte thanks for showing the code. If You read closely the OP you'd know I said I've got 2 servers already. 

Ports, they're different for each server. 

I removed the sv_password because I thought pastebin is removing the pastes for that reason, it's set inside the server config. & I dont make them expire.

No, I'm not using different users.

Details Pastebin:

http://pastebin.com/fmMPA5cU

It's weird to show not when everything is set.

**Comment by cedarlug** [comment]
> EDIT: so, when the installation is done, the servFun.cfg executes csgo-server.cfg, was I supposed to put vars inside csgo-server? 
Now I'm editing servFun directly and it's showing everything just fine.

That makes no sense at all - neither grammatically nor in the context of lgsm management.

Regardless, I'm glad that it's now working for you so this teeth-grating thread of disappearing and dynamically-changing content can be closed.

**Comment by Hackmastr** [comment]
@cedarlug ,

servFun.cfg contained this:

```
exec csgo-server.cfg
```

So I put all the stuff inside csgo-server.cfg

That's why it was showing NOT SET

**Comment by cedarlug** [comment]
@Hackmastr 

It was showing "NOT SET" because you're bastardizing lsgm in ways it was not intended to be.

**Comment by UltimateByte** [comment]
Your cfg file has to be named as your servicename, otherwise, lgsm has no way to know which file it is.
I guessed the issue was there, but for the wrong reason.

```
servercfg="${servicename}.cfg"
servercfgfullpath="${servercfgdir}/${servercfg}"
```

GLHF
