### ISSUE TITLE
Error 7 Days to Die

### ISSUE THREAD

**Issue by kestouf** [dgibbs64/linuxgsm#917]
Hi
Y have proble when start server: 

Kestouf@ns3554546:~/7daytodie$ ./sdtdserver start
[ .... ] Starting sdtd-server: session not found: sdtd-server
[ FAIL ] Starting sdtd-server: Unable to start
[ FAIL ] Starting sdtd-server: Unable to start : Tmux error:

Command
=================================
tmux new-session -d -s "sdtd-server" "./7DaysToDieServer.x86 -logfile /home/Kestouf/7daytodie/log/server/output_log__2016-07-03__18-58-44.txt -quit -batchmode -nographics -dedicated -configfile=/home/Kestouf/7daytodie/serverfiles/sdtd-server.xml"

Error
=================================
create session failed: ./7DaysToDieServer.x86 -logfile /home/Kestouf/7daytodie/log/server/output_log__2016-07-03__18-58-44.txt -quit -batchmode -nographics -dedicated -configfile=/home/Kestouf/7daytodie/serverfiles/sdtd-server.xml: Exec format error

Fix
=================================
No known fix currently. Please log an issue.
https://gameservermanagers.com/issues

On forum of steam :

https://steamcommunity.com/groups/linuxgsm/discussions/0/358416640397539877/

Have you idea?

Thx

**Comment by UltimateByte** [comment]
Please, go back to Steam forum, but provide relevant information following those instructions http://steamcommunity.com/groups/linuxgsm/discussions/0/458604254471755996/
