### ISSUE TITLE
7 Days to Die erro when start server

### ISSUE THREAD

**Issue by kestouf** [dgibbs64/linuxgsm#918]
Hi 
first of all : 
GAME SERVER use: sdtdserver
DISTRO : Debian 8
LOGS  AND gameserver details :  http://pastebin.com/H7J5RX69

-----------------------------------------------------------------------------------------------------------------

When start server i have this error:

Kestouf@ns3554546:~/7daytodie$ ./sdtdserver start
[ .... ] Starting sdtd-server: session not found: sdtd-server
[ FAIL ] Starting sdtd-server: Unable to start
[ FAIL ] Starting sdtd-server: Unable to start : Tmux error:

Command
=================================
tmux new-session -d -s "sdtd-server" "./7DaysToDieServer.x86 -logfile /home/Kestouf/7daytodie/log/server/output_log__2016-07-14__14-10-22.txt -quit -batchmode -nographics -dedicated -configfile=/home/Kestouf/7daytodie/serverfiles/sdtd-server.xml"

Error
=================================
create session failed: ./7DaysToDieServer.x86 -logfile /home/Kestouf/7daytodie/log/server/output_log__2016-07-14__14-10-22.txt -quit -batchmode -nographics -dedicated -configfile=/home/Kestouf/7daytodie/serverfiles/sdtd-server.xml: Exec format error

Fix
=================================
No known fix currently. Please log an issue.
https://gameservermanagers.com/issues
Kestouf@ns3554546:~/7daytodie$

Have you got an idea?

Thx

**Comment by cedarlug** [comment]
Your system lacks i386 support, as indicated by this output when attempting to run the x86 binary:
` Exec format error`
Did you add the i386 architecture support and dependencies as per the Debian instructions for sdtdserver?

This is the first step:
`sudo dpkg --add-architecture i386; sudo apt-get update; sudo apt-get install tmux mailutils postfix ca-certificates curl file lib32gcc1 libstdc++6 libstdc++6:i386 telnet expect`

Have you done the above steps, and were they successful?

**Comment by kestouf** [comment]
I managed to solve the problem by stopping L4D2 servers (also server manager using games) There was a session with conflie Tmux.

**Comment by UltimateByte** [comment]
Solution was probably here then : https://github.com/dgibbs64/linuxgsm/wiki/Multiple-Servers
Good it's solved.
