### ISSUE TITLE
Trying to Run an Exile Server I get this

### ISSUE THREAD

**Issue by TheRealRag** [dgibbs64/linuxgsm#919]
attached is the problem I get when trying to launch my server
[problem.txt](https://github.com/dgibbs64/linuxgsm/files/365115/problem.txt)

**Comment by igeighty** [comment]
you need to lowercase your mod folder
convert all your mod folders and contents to lower case..

#`find . -depth -exec rename 's/(.*)\/([^\/]*)/$1\/\L$2/' {} \;`
https://community.bistudio.com/wiki/Arma_3_Dedicated_Server#Case_sensitivity_.26_Mods

**Comment by UltimateByte** [comment]
"-cfg=/home/arma3server/serverfiles/cfg/Bandit Punisher Exile.network.cfg "
Very bad idea to put spaces in filenames.
And very bad idea to use uppercase addons for any game under linux.

**Comment by UltimateByte** [comment]
I guess we can close as it's a non script issue, but feel free to re-open the issue if you feel like it's needed. Please note that non script issues are preferably discussed on the steam group in the general support section https://steamcommunity.com/groups/linuxgsm/discussions
