### ISSUE TITLE
File missing from github

### ISSUE THREAD

**Issue by taavipost** [dgibbs64/linuxgsm#920]
Applying update...
    fetching update_dl.sh...FAIL

https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/lgsm/functions/update_dl.sh

That file is missing from repo

**Comment by Scarsz** [comment]
Removed as a part of https://github.com/dgibbs64/linuxgsm/commit/5437c55c04cc88958942783017a191532b323910, delete your functions folder to redownload LGSM's core scripts
