### ISSUE TITLE
[svencoopserver] SteamCMD install loop

### ISSUE THREAD

**Issue by Scarsz** [dgibbs64/linuxgsm#924]
![](http://i.imgur.com/tRsqGlS.png)

**Comment by UltimateByte** [comment]
Thanks for mentioning. Please, follow the discussion here https://github.com/dgibbs64/linuxgsm/issues/915

**Comment by UltimateByte** [comment]
Might be a different issue than #915, keeping open until we investigated this.

**Comment by dgibbs64** [comment]
Goldsrc servers will loop several times for SteamCMD becuase of how badly SteamCMD failed with these games. Does the loop eventually finish? I believe is runs up to 10 times.

**Comment by UltimateByte** [comment]
@Scarsz Is this reproductible ?

**Comment by Scarsz** [comment]
Haven't touched it, will try reinstalling it and see if it closes after 10 tries

**Comment by UltimateByte** [comment]
A good thing to enlight would be why it loops in the first place. Maybe some logs would help.

**Comment by Scarsz** [comment]
Nope, not reproducible. Was good after 5 validations. Message that it's going to validate a couple times could be more prominent, hadn't seen it the first time but I did this one.
