### ISSUE TITLE
Issue with Linux Killing Floor Server (Debian 8 64bit)

### ISSUE THREAD

**Issue by LemonGames7** [dgibbs64/linuxgsm#927]
Hello. Doing this tutorial [click here](https://gameservermanagers.com/lgsm/kfserver/#gettingstarted) i've got this problem when i starting and stopping my server - http://prntscr.com/bvcyba I'm using Debian 8 64bit OS. Is this normal or what? Thanks for helping me.

**Comment by UltimateByte** [comment]
Hi,
Just install the missing dependencies as the script is asking you to do.

**Comment by LemonGames7** [comment]
What is the code line? I'm new at this, please help me ;)

2016-07-21 0:02 GMT+03:00 UltimateByte <notifications@github.com>:

**Comment by LemonGames7** [comment]
Ok, just fixed it. Thanks for helping me !

2016-07-21 0:58 GMT+03:00 Ceon_ <lemongames7@gmail.com>:

**Comment by UltimateByte** [comment]
You just hard to read the console message mate :p 
NP, we've all been new at some point ;)
HF, and please, use the steam forum if you need further help with script usage.
