### ISSUE TITLE
Tmux 2.2 console logging

### ISSUE THREAD

**Issue by Ninn0x4F** [dgibbs64/linuxgsm#931]
We are running tmux 2.2 and it's still not logging to console.log only shows that we need to update tmux.
It also shows that the tmux version currently installed is 1.8.
"tmux -V
tmux 2.2"
So what's the deal?

**Comment by igeighty** [comment]
using Debian GNU/Linux 8.2, if i run `./arma3server dt` it does report that i am using tux 1.9
doing `tmux -V` shows version 1.9
`/log/console/arma3-server-console.log` is being created for me.
it doesn't solve your issue, but shows at least on my system that it is functioning. at the moment, tux 1.9 is the latest stable for debian,

what OS are you using ?

**Comment by Ninn0x4F** [comment]
Using CentOS 7 but it seems like my problem is obsolete now, was still using an older version of LGSM it couldnt even fetch the functions since the folder on github dont exist anymore. Updating it fixed everything. Stupid moment of writing first then thinking.

**Comment by igeighty** [comment]
nice :)
