### ISSUE TITLE
[StarBound]  LGSM doenst work after 1.0 release

### ISSUE THREAD

**Issue by DSDV** [dgibbs64/linuxgsm#932]
Hi,
today 1.0 version of Starbound released and its out of EarlyAcess / BETA now.

But i have the feeling they changed the server because after the update it cant start anymore

as you can see in my Screenshot:

http://www2.pic-upload.de/img/31274938/Zwischenablage02.jpg
![zwischenablage02](https://cloud.githubusercontent.com/assets/5504857/17068449/545f811e-5051-11e6-8b21-7e1c03750629.jpg)

`[ WARN ] Starting sb-server: Configuration file missing!
/home/steamcmd/serverfiles/linux64/sbboot.config
/home/steamcmd/lgsm/functions/command_start.sh: Zeile 82: cd: /home/steamcmd/serverfiles/linux64: Datei oder Verzeichnis nicht gefunden
[ FAIL ] Starting sb-server: Unable to start
`

these are the errors.

with best +DS_DV+

PS:

`
#!/bin/bash
# Starbound
# Server Management Script
# Author: Daniel Gibbs
# Website: https://gameservermanagers.com
if [ -f ".dev-debug" ]; then
        exec 5>dev-debug.log
        BASH_XTRACEFD="5"
        set -x
fi

version="210516"
`

**Comment by Trael** [comment]
Getting the same - The directory where it is looking for the sbboot.config file is empty. (serverfiles/linux64/)

**Comment by marvinl97** [comment]
I'm working at it at the moment. I'll send a pull request if I was able to fix it.

**Comment by UltimateByte** [comment]
Hi,

Hopefully they didn't screw with linux support and it's just obsolete start parameters or config file..
Can't find relevant info on SteamDB.
Can you try a clean install of an instance of this game on a different user ? Would help diagnose this.
Gamelogs if any would help too.
Also, a `./sbserver debug` could lead us to the way of what's causing this.

**Comment by Trael** [comment]
sbserver@ip-172-31-16-14:~$ ./sbserver debug
    fetching command_debug.sh...OK
[ WARN ] Debug sb-server: Configuration file missing!
/home/sbserver/serverfiles/linux64/sbboot.config

Starbound Debug
=================================

Distro: Ubuntu 14.04.4 LTS
Arch: x86_64
Kernel: 3.13.0-92-generic
Hostname: ip-172-31-16-14

Start parameters:
./starbound_server

Use for identifying server issues only!
Press CTRL+c to drop out of debug mode.
Warning! If sb-server is already running it will be stopped.

Continue? [Y/n]y
[ INFO ] Debug sb-server: Stopping any running servers
    fetching command_stop.sh...OK
[ WARN ] Stopping sb-server: Configuration file missing!
/home/sbserver/serverfiles/linux64/sbboot.config
[ INFO ] Stopping sb-server:  is already stopped
[  OK  ] Debug sb-server: Starting debug
/home/sbserver/lgsm/functions/command_debug.sh: line 75: ./starbound_server: No such file or directory
sbserver@ip-172-31-16-14:~$

**Comment by Trael** [comment]
Also, that's based off a fresh install, I started this up today with the intent to finally get into the game - Fresh Ubuntu server running in AWS, all dependencies accurate.

**Comment by UltimateByte** [comment]
Obviously, executable path or name changed :p 
You can experiment things by changing those variables inside your sbserver script. :)
Feel free to pull request it if you find the correct modifications required, because I can't work on it right now.

**Comment by Trael** [comment]
I think the part I'm finding odd is that I can't seem to locate the sbboot.config file in any of the directories that are pulled in by LGSM, even though I can see it on the main code page.

**Comment by UltimateByte** [comment]
I don't know, didn't work on sb yet. That path may have changed too ?

**Comment by marvinl97** [comment]
Just a few information:
- linux32 and linux64 are apparently merged
- sbboot.config is probably deprecated (new file is sbinit.config but should stay untouched)
Instead the "starbound_server.config" in /serverfiles/storage/ should be edited.

Workaround/fixed variables:
```
executabledir="${filesdir}/linux"

servercfg="starbound_server.config"
servercfgdir="${filesdir}/storage"


gamelogdir="${filesdir}/storage"
```

**Comment by Trael** [comment]
^ This did work to at least get the server to start. However, my "storage" folder does not have starbound_server.config - Did you create a new config file?

**Comment by marvinl97** [comment]
It should be there when you started the server once.

If not just create it and take the content from here: http://pastebin.com/EuSpAnRi
I uploaded the default config.

**Comment by Trael** [comment]
Awesome@ Thanks so much @marvinl97
