### ISSUE TITLE
[Server Request] Minecraft

### ISSUE THREAD

**Issue by dgibbs64** [dgibbs64/linuxgsm#935]
Minecraft vanilla shouldn't be too difficult however I know there are loads of mods and addons etc. I know nothing about these currently so will need assistance in learning what they are and how they work etc. Plus which ones are important. My other issue is that I don't own a copy of Minecraft so I anyone is willing to donate me a copy to assist me in development (my son might enjoy it as well).

**Comment by UltimateByte** [comment]
https://github.com/dgibbs64/linuxgsm/issues/333 :p

**Comment by dgibbs64** [comment]
Thanks I thought there was an issue raised previously. I will close this and re open that one.
