### ISSUE TITLE
Gmod updater is broken

### ISSUE THREAD

**Issue by tenten8401** [dgibbs64/linuxgsm#937]
![image](https://cloud.githubusercontent.com/assets/6174343/17078866/fe03b476-50cc-11e6-944a-f7080b42d8b0.png)
For the reference I did try replacing the gmodserver executable.

**Comment by dgibbs64** [comment]
./gmodserver update-functions

**Comment by tenten8401** [comment]
Thanks. Terribly sorry for wasting your time.
