### ISSUE TITLE
install and update error message?

### ISSUE THREAD

**Issue by mattdinsdale** [dgibbs64/linuxgsm#940]
hi i got his message when installing and updating Rust

ERROR: ld.so: object '/usr/lib/coreutils/libstdbuf.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

system is debian jessie 64 bit 8gb ram

**Comment by UltimateByte** [comment]
Please, see this https://github.com/dgibbs64/linuxgsm/issues/915

**Comment by Scarsz** [comment]
Closing, see #915 as @UltimateByte said
