### ISSUE TITLE
Permission :(

### ISSUE THREAD

**Issue by MickaelPedro** [dgibbs64/linuxgsm#948]
Hello, I have this error could you help me ? thank you

Infomation! The current user (darkrp) does not have ownership of the following files:
User  Group  File
root  root   /home/darkrp/serverfiles/garrysmod/gamemodes/darkrp

**Comment by dgibbs64** [comment]
The file/directory is not owned by user darkrp

chown  darkrp: darkrp /home/darkrp/serverfiles/garrysmod/gamemodes/darkrp
