### ISSUE TITLE
[CSGO] Tmux resume delay while hibernating (fix)

### ISSUE THREAD

**Issue by jach11** [dgibbs64/linuxgsm#949]
I've noticed a long time ago that when you attach to any tmux sessions that are being used by csgo there will be a delay on input in that session. I figured out that this is caused by the default configuration files setting `sv_hibernate_when_empty ` to `1`,  which may annoy other people who haven't figured this out yet. You can also modify how many milliseconds to sleep per frame by using `sv_hibernate_ms`, if users want to keep the server in hibernation if there are no active players, but still be able to interact with console normally they should set `sv_hibernate_ms` to `5`. I think by default lgsm-default.cfg for csgo should include `sv_hibernate_when_empty 0` for ease of use.

**Comment by UltimateByte** [comment]
Hi,
Server hibernation by default is a good thing to keep in my opinion to save some CPU power in a lot of cases.
But, sv_hibernate_ms sounds like a good idea.
However "sv_hibernate_ms x # of milliseconds to sleep per frame while hibernating" > what the hell do they mean ? Does it hibernate more if you increase the value ? Is it useless under a certain value ? Is it freezing over a certain value ?

**Comment by jach11** [comment]
It looks like it reduces the amount of ticks per second that the server handles as you increase the latency. If you set `sv_hibernate_when_empty` to `1` and `sv_hibernate_ms` to `0` it seems like it uses the same amount of CPU as if you had `sv_hibernate_when_empty` set to `0`. So you have to assign a value to `sv_hibernate_ms` in order to decrease the amount of ticks that are updated per second, which should in turn lower CPU usage but it's almost negligible how much it actually saves. It seems like even adding an entire 100ms between each tick update, the process uses only about 1% less of CPU usage compared to having `sv_hibernate_when_empty` set to `0`.

**Comment by UltimateByte** [comment]
OK, so that's what i thought.
Do you know what's the default sv_hibernate_ms then ? So that we can lower it accordingly.

**Comment by jach11** [comment]
The default `sv_hibernate_ms` is `20`

**Comment by UltimateByte** [comment]
And between `sv_hibernate_ms 5` and `sv_hibernate_ms 20`, console still doesn't work ?

**Comment by jach11** [comment]
Having it set to `sv_hibernate_ms 5` allows acceptable interaction with the console. Anything higher is extremely annoying.

**Comment by UltimateByte** [comment]
Well
https://github.com/dgibbs64/linuxgsm/commit/83492ed57cf665f762162d9fb1c2994d1cdc7df9

Should do the trick then. :)

**Comment by UltimateByte** [comment]
I'm noticing that csgo config is quite empty. Do you think about anything else that would be worth adding ?

**Comment by jach11** [comment]
It might also be worth adding `host_info_show 2` to allow game-trackers to query the server and `host_players_show 2` to show what players are playing on that server, as well as `host_name_store 1` to show the host name in queries as well. Most community servers will usually want to have this ability by default. There are quite a few other things that could also be included, but it would require input from the user during installation.

**Comment by UltimateByte** [comment]
Found some doc about it.
I'll add those with a comment.
https://www.gametracker.com/games/csgo/forum.php?thread=91691

**Comment by jach11** [comment]
That looks good, it's sad that official documentation from valve is usually either outdated or hidden somewhere on an obscure page and people have to spend alot of time to figure things out.

**Comment by UltimateByte** [comment]
From what i know, there is no actual official documentation from valve. It's a wiki, so anyone can write it, as i did for Rust, because when i needed it, i found information in it to be quite poor.
https://developer.valvesoftware.com/wiki/Rust_Dedicated_Server
