### ISSUE TITLE
Feature Request: Backup without prompt 

### ISSUE THREAD

**Issue by gjdunga** [dgibbs64/linuxgsm#951]
Would you folks be willing to create a backup command that will skip the prompt? 
Perhaps something like gameserver bn ??

Thanks!

**Comment by cedarlug** [comment]
If you wish to do this using cron, see the extended discussion here:

http://steamcommunity.com/groups/linuxgsm/discussions/0/371919771743473258/

**Comment by gjdunga** [comment]
I am not using it in the cron, I'm actually using something called zip-updater that updates the Oxide plugin for RUST. I've created some functions in that program like so in bash, so that I can use the zip-updater to call lgsm to stop the server, back it up, then update it, then update oxide, and allow zip-updater to do it's own backup and restart the server..   

I am not a experienced bash scripting guru. I'm learning as I go.  How would you execute the echo in this instance.  I am not quite sure why the backup procedure on lgsm has a confirmation prompt. I would make changes to the lgsm backup function script to skip the prompt but then any time it would be updated, I would lose those changes. 

Example Code:


```
`fn_stop_server(){
# Stop Server
bash "${lgsmdir}"rustserver "sp"
}

fn_start_server(){
# Start server

bash "${lgsmdir}"rustserver "st"
}

fn_update_server(){
bash "${lgsmdir}"rustserver "u"
}

fn_backup_server(){
bash "${lgsmdir}"rustserver "b"
}`

```

**Comment by UltimateByte** [comment]
@gjdunga Somebody followed my tutorial :D Glad you like the Zip Updater :p 
I wish to find a way to add those functions to LGSM. :)

The backup function would need some enhancements anyways, so that you can set a backup amount to keep for example, and eventually automate an upload to a backup server.

Waiting for that, Cedar gave you the way even if you're not using cronjobs for that , here is an example: 
`cd /home/tsgo/ts3 && printf "yes\nno\n"  |./ts3server backup >/dev/null 2>&1`

**Comment by gjdunga** [comment]
@UltimateByte , I've pondered that myself, that is combining the two. I know that when you do that, your having to do that for many games, so it's going to be a pain in the logistical arse. 

BTW. Thank you for making Zip-Updater!  

Please excuse my ignorance, but let's say write this as ?
```
fn_backup_server(){
bash cd "${lgsmdir}"&& printf "yes\nno\n" |./rustserver backup >/dev/null 2>&1 
}`
```
Off to go test it.. May be a few hours.. Groceries don't get themselves !!

**Comment by UltimateByte** [comment]
Yeah, i think it might work.
Where are you putting those functions by the way ? If you're using ${lgsmdir} it means you integrated it in lgsm, right ?

**Comment by cedarlug** [comment]
If you're running this (or invoking the function running) as the "rustserver" user and outside of cron, this shorter version would likely work just as well:
`printf "yes\nno\n" | ~/rustserver backup >/dev/null 2>&1`

(In the original Steam discussion, the user and the installation directory weren't LGSM defaults.)

**Comment by UltimateByte** [comment]
Yeah @cedarlug that's exactly why i'm asking that. If he's within the LGSM environment, no need to cd. :)

**Comment by cedarlug** [comment]
Close?

**Comment by UltimateByte** [comment]
Yup. We will have to have a look at the backup function at some point btw.

**Comment by gjdunga** [comment]
Wanted to say, that the function as I wrote it above, is working well. 
@UltimateByte  No, all of these changes are in zip-updater. 

See full zip-updater code here: 
`#!/bin/bash
# Zip-Updater
# Allows you to easilly download, extract, and update zip content
# Author: UltimateByte
# Website: http://www.lrob.fr
version="160310"

#####################
###   Variables   ###
### Configuration ###
#####################

# Target directory in which you want your exctracted zip folders
# Please use /home/username/path/to/directory
targetdir="/home/steam/Games/serverfiles/"

# Do you want to keep every instance of zipfiles you download for reverting to a previous version ?
backupzips="on"

# Prompt for continue ? (Turn off for cronjob use)
promptmode="off"

# To come - Convert folders to lowercase (default on to correct windows devs' ignorance)
lowercase="off"

# Paste links of zip files you want to download line by line
# Example :
# ziplinks="https://github.com/wiremod/advdupe2/archive/master.zip
# https://github.com/wiremod/advduplicator/archive/master.zip
# https://github.com/nrlulz/ACF/archive/master.zip"

ziplinks="https://github.com/OxideMod/Snapshots/raw/master/Oxide-Rust_Linux.zip"


#####################
###    Program    ###
### Do Not Change ###
#####################

rootdir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
zipsdir="${rootdir}/tempzipfiles"
extractdir="${rootdir}/exctracted-zipfiles"
backupdir="${rootdir}/backup-zipfiles"
lgsmdir="/home/steam/Games/"

fn_stop_server(){
# Stop Server
bash "${lgsmdir}"rustserver "sp"
}

fn_start_server(){
# Start server

bash "${lgsmdir}"rustserver "st"
}

fn_update_server(){
bash "${lgsmdir}"rustserver "u"
}

fn_backup_server(){
bash cd "${lgsmdir}"&& printf "yes\nno\n" |./rustserver backup >/dev/null 2>&1 
#bash "${lgsmdir}"rustserver "b"
}

fn_error_check(){
# Check if targetdir is set
if [ -z "${targetdir}" ]; then
	echo "Please, set a target directory using targetdir variable first"
	local errortargetdir="1"
fi
# Check if zip links are provided
if [ -z "${ziplinks}" ]; then	
	echo ""
	echo "Please, set something do download !"
	local errorziplinks="1"
fi
# Check if backupzips is set correctly
if [ "${backupzips}" != "on" ] && [ "${backupzips}" != "off" ]; then
	echo ""
	echo "Please, set backupzips to on or off"
	local errorbackupzips="1"
fi
# Check if promptmode is set correctly 
if [ "${promptmode}" != "on" ] && [ "${promptmode}" != "off" ]; then
	echo ""
	echo "Please, set promptmode to on or off"
	local errorpromptmode="1"
fi
if  [ "$errortargetdir" == "1" ] || [ "$errorziplinks" == "1" ] || [ "$errorbackupzips" == "1" ] || [ "$errorpromptmode" == "1" ]; then
	echo ""
	echo "Exiting";	exit
fi
}

fn_create_dirs(){
echo "Creating required folders..."
sleep 1
# Check if dirs exist, create if if not
if [ ! -d "${targetdir}" ]; then
	mkdir -v "${targetdir}"
fi

if [ ! -d "${zipsdir}" ]; then
	mkdir -v "${zipsdir}"
fi

if [ ! -d "${extractdir}" ]; then
	mkdir -v "${extractdir}"
fi

if [ ! -d "${backupdir}" ]; then
	mkdir -v "${backupdir}"
fi
}

fn_dl_zip(){
while IFS= read -r line
do 
	echo "Downloading ${line}"
	wget --content-disposition -q "${line}" -P "${zipsdir}"
done <<< "${ziplinks}"
}

fn_extract_zip(){
# Recursively extract zip files 
echo ""
echo "Extracting zipfiles..."
echo ""
sleep 1
find "${zipsdir}" -name "*.zip" | while read filename; do unzip -o "$filename" -d "${extractdir}"; done;
}

fn_lowercase(){
# Converting foldernames to lowercase
if [ "${lowercase}" == "on" ]; then
	echo "Converting uppercase folders to lowercase"
	sleep 2
find "${extractdir}" -exec readlink -e '{}' \; | rename  'y/A-Z/a-z/'
fi
}

fn_copy(){
# Copying extractions to targetdir
echo "Copying Extracted zips to desired directory..."
sleep 2
cp -Rfv "${extractdir}"/* "${targetdir}"/
echo ""
echo "Files copied to desired directory"
}

fn_rm_extractdir(){
echo "Removing temp folder"
sleep 1
rm -vR "${extractdir}"
}

fn_getdate(){
# Get current date into a variable
thedate=$(date +"%y-%m-%d-%Hh%Mm%Ss")
}

fn_backup(){
# No backup, remove zip files
if [ "${backupzips}" == "off" ]; then
	echo ""
	echo "No zip backup"
	echo ""
	sleep 1
elif [ "${backupzips}" == "on" ]; then
# Backup, move files to a current date folder in backupdir
	fn_getdate
	echo ""
	echo "Backuping zips to ${backupdir}/${thedate}"
	echo ""
	sleep 1
	mkdir -v "${backupdir}"/"${thedate}"
	mv -v "${zipsdir}"/* "${backupdir}"/"${thedate}"
fi
}

fn_rm_zipsdir(){
echo "Clearing temp zip folder"
rm -vR "${zipsdir}"
}

fn_prompt_continue(){
if [ "${promptmode}" == "on" ]; then
	while true; do
		read -p "Continue ? [y/N]" yn
		case $yn in
		[Yy]* ) break;;
		[Nn]* ) echo Exiting; exit;;
		* ) echo "Please answer yes or no.";;
	esac
	done
fi
}

fn_complete(){
echo ""
echo "Operations complete"
echo "Hope you enjoy this script ;)"
echo "Cheers !"
echo ""
}

# Running functions
echo ""
echo "Thanks for using this script made by UltimateByte"
fn_error_check
echo ""
echo "Start downloading or updating zips ?"
fn_prompt_continue
fn_stop_server
fn_backup_server
fn_update_server
fn_create_dirs
fn_dl_zip
fn_extract_zip
fn_lowercase
fn_copy
fn_rm_extractdir
fn_backup
fn_rm_zipsdir
fn_complete
fn_start_server
`

**Comment by gjdunga** [comment]
I could pull lgsm and tinker to get zip-updater in there. However It would only be the rust side, I have not looked how you change code for the other games. 

Gabriel

**Comment by UltimateByte** [comment]
Well, we'd need a smart way to implement additional functions such as this to LGSM.
It's already on its way https://github.com/dgibbs64/linuxgsm/issues/602
