### ISSUE TITLE
server update is unable to login to steam - Starbound

### ISSUE THREAD

**Issue by Naliath** [dgibbs64/linuxgsm#955]
When ever I run the update to force-update command on the server it hangs on the login. I have steam guard enabled and I figure this has something to do with it. As a temp solution I just run the install command every time since that can get through the steam login for some reason.

**Comment by UltimateByte** [comment]
So you're saying that "install" will log to your steam account but "update" won't ?

**Comment by Naliath** [comment]
yup, update will just keep hanging on login into 'username' public steam account. No idea what is going on in the back but install shows the same message and just moves on

**Comment by UltimateByte** [comment]
Install https://github.com/dgibbs64/linuxgsm/blob/master/lgsm/functions/install_server_files.sh#L58
Update https://github.com/dgibbs64/linuxgsm/blob/master/lgsm/functions/update_steamcmd.sh#L29

Update check (i think it's the one that can't work with user logging) : https://github.com/dgibbs64/linuxgsm/blob/master/lgsm/functions/update_steamcmd.sh#L157

@dgibbs64 What do you think ?

**Comment by marvinl97** [comment]
## Distro Details (1x dedicated server and 1x local vm)
Distro:    Ubuntu 16.04.1 LTS
Arch:      x86_64
Kernel:    4.4.0-31-generic
tmux:      tmux 2.1
GLIBC:     2.23

Fresh server installs

## ./sbserver validate (same for force-update)
```
~$ ./sbserver validate
[ .... ] Validate sb-server: Validating files:

[ .... ] Validate sb-server: Validating files: SteamCMD

        * Validating may overwrite some customised files.
        * https://developer.valvesoftware.com/wiki/SteamCMD#Validate
ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/coreutils/libstdbuf.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Redirecting stderr to '/home/sbserver/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Created shared memory when not owner SteamController_Shared_mem
OK.

Logging in user 'username' to Steam Public...
```

When pressing ENTER:

```
Enter the current code from your Steam Guard Mobile Authenticator app
Two-factor code:FAILED with result code 85
ERROR! Failed to request AppInfo update, not online or not logged in to Steam.
[  OK  ] Validate sb-server: Validating files: SteamCMD
```

When pressing ENTER after I entered my current code (I just wrote the code):

```
Logging in user 'username' to Steam Public...2kfg5

Enter the current code from your Steam Guard Mobile Authenticator app
Two-factor code:Logged in OK
Waiting for license info...
```

after waiting 30-35s.. (I tested it 5+ times, everytime in this span) | just ~5s for force-update

```
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x5) validating, progress: 3.41 (60753582 / 1780209757)
 Update state (0x5) validating, progress: 10.22 (181884100 / 1780209757)
 Update state (0x5) validating, progress: 17.17 (305670158 / 1780209757)
 Update state (0x5) validating, progress: 23.08 (410855080 / 1780209757)
 Update state (0x5) validating, progress: 29.57 (526401334 / 1780209757)
 Update state (0x5) validating, progress: 35.49 (631870104 / 1780209757)
 Update state (0x5) validating, progress: 43.15 (768184984 / 1780209757)
 Update state (0x5) validating, progress: 51.04 (908694168 / 1780209757)
 Update state (0x5) validating, progress: 57.14 (1017221784 / 1780209757)
 Update state (0x5) validating, progress: 64.31 (1144912104 / 1780209757)
 Update state (0x5) validating, progress: 70.83 (1260919016 / 1780209757)
 Update state (0x5) validating, progress: 77.36 (1377113129 / 1780209757)
 Update state (0x5) validating, progress: 84.02 (1495664461 / 1780209757)
 Update state (0x5) validating, progress: 91.22 (1623866102 / 1780209757)
 Update state (0x5) validating, progress: 93.84 (1670496742 / 1780209757)
 Update state (0x5) validating, progress: 98.40 (1751664019 / 1780209757)
Success! App '211820' fully installed.
[  OK  ] Validate sb-server: Validating files: SteamCMD
```

## ./sbserver update
hanging forever (@local vm) or for ~8s (@dedicated server) at:
~$ ./sbserver update
`[ .... ] Update sb-server: Checking for update: SteamCMD`

When pressing ENTER:

`[ FAIL ] Update sb-server: Checking for update: SteamCMD: Not returning version info
`

**Comment by UltimateByte** [comment]
I guess we could re open this
https://github.com/dgibbs64/linuxgsm/issues/579

**Comment by Naliath** [comment]
FYI for others trying to work around this, just do install every time there is an update and when it asks if the steam content was installed correctly (after update) just close the process.

**Comment by dgibbs64** [comment]
Relevant? https://github.com/dgibbs64/linuxgsm/wiki/SteamCMD#steamcmd-login

**Comment by Naliath** [comment]
you are correct, it seems I just need to learn to read. Unfortunate that it is not supported though

**Comment by dgibbs64** [comment]
Yup there is no way around it. I recommend using a separate login for your server if possible so your main account is protected.
