### ISSUE TITLE
Garry's Mod Server - No Permissions

### ISSUE THREAD

**Issue by Sh0rk** [dgibbs64/linuxgsm#959]
Hi!

Now, after a few weeks i want to start my Garry's Mod Server again.
The first what i did was searching for updates (./gmodserver update).
The server try to update but then he shows me everthing of my custom stuff of the server:
- Maps
- Weapons
- Custom HUD
...

What i read: No permissions?

I try something didn't work.... so i reinstall the complete server.
After the complete install of  the server i move the backup files from my old server (Maps, Weapons..)
to the folder of my new server. But after i put the files in the new server folder the same error?

What thaa fuck?

Please help!
Sorry for my english,
greetings from Germany!

**Comment by marvinl97** [comment]
Please post the output of: ls -l
What exactly does the error say? Please post more information/details/logs.

You could also try this command (if your user is gmodserver):
`chown -R /home/gmodserver gmodserver:gmodserver`

( chown -R /home/csgoserver username:group )

**Comment by Sh0rk** [comment]
The output of "ls- l"

> total 28
drwxrwxr-x 8 ttt-garrysmod ttt-garrysmod 4096 Jul 30 15:51 Steam
-rwxrwxr-x 1 ttt-garrysmod ttt-garrysmod 4476 Jul 30 15:44 gmodserver
drwxrwxr-x 5 ttt-garrysmod ttt-garrysmod 4096 Jul 30 15:51 lgsm
drwxrwxr-x 4 ttt-garrysmod ttt-garrysmod 4096 Jul 30 15:45 log
drwxrwxr-x 8 ttt-garrysmod ttt-garrysmod 4096 Jul 30 15:52 serverfiles
drwxrwxr-x 5 ttt-garrysmod ttt-garrysmod 4096 Jul 30 15:45 steamcmd

When I try the "chown":

chown -R /home/ttt-garrysmod ttt-garrysmod:ttt-garrysmodchown: invalid user: '/home/ttt-garrysmod'

**Comment by marvinl97** [comment]
Ups. Sorry:
chown -R ttt-garrysmod:ttt-garrysmod /home/ttt-garrysmod

**Comment by Sh0rk** [comment]
First thanks for the really fast answers!

Now the command works but:

`chown: changing ownership of '/home/ttt-garrysmod/serverfiles/garrysmod/materials': Operation not permitted
`

**Comment by marvinl97** [comment]
`chown -R ttt-garrysmod:ttt-garrysmod /home/ttt-garrysmod/serverfiles/garrysmod/materials`
as root. Give it a try if you didn't use root before.

**Comment by Sh0rk** [comment]
It works!

Thanks for your fast and working support :)

**Comment by marvinl97** [comment]
You're welcome!
Also greetings from Germany! :D

**This issue can be closed now.**
