### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by m8wtf** [dgibbs64/linuxgsm#967]
This picture shows my problem http://i.imgur.com/aIjgsXd.png

Despite setting execute permission on the file it still won't run unless I use sudo or the root account. I had it all running fine yesterday so I don't know what's happened :cry:

**Comment by marvinl97** [comment]
Could you please post the output of `ls -a` ?

**Comment by m8wtf** [comment]
:scream: ls: cannot open directory .: Permission denied

**Comment by marvinl97** [comment]
Please run
`chown -R csgoserver:csgoserver /home/csgoserver`
and test if it helps.

Your csgoserver user doesn't seem to have access to his user dir at all.

**Comment by m8wtf** [comment]
I got http://i.imgur.com/uBF1mMU.png

So I ran it as root and the error didn't come up however it hasn't changed anything.

**Comment by marvinl97** [comment]
`sudo chmod -R 755 /home/csgoserver`
Does that work?

**Comment by m8wtf** [comment]
It ran but I'm still getting Permission denied, I have tried rebooting server, shall I try again?

**Comment by marvinl97** [comment]
I don't really know but could you please post the outputs of:
`sudo ls -ld /home/csgoserver`
and
`sudo ls -l /home/csgoserver`
and 
`groups csgoserver`

This should give us/me a better overview.

**Comment by m8wtf** [comment]
http://lew.la/fin/s/Z.png

Thanks for your replies

**Comment by marvinl97** [comment]
The only difference compared to mine is the group "wheel".

Mine:
```
kilo062:/home# ls -ld /home/csgoserver
drwxr-xr-x 9 csgoserver csgoserver 4096 Aug  3 21:01 /home/csgoserver
kilo062:/home# ls -l /home/csgoserver
total 28
-rwxr-xr-x 1 csgoserver csgoserver 5030 Aug  3 20:57 csgoserver
drwxr-xr-x 4 csgoserver csgoserver 4096 Aug  3 20:01 lgsm
drwxr-xr-x 4 csgoserver csgoserver 4096 Jul 26 05:00 log
drwxr-xr-x 7 csgoserver csgoserver 4096 Aug  3 20:53 serverfiles
drwxr-xr-x 8 csgoserver csgoserver 4096 Aug  3 20:52 Steam
drwxr-xr-x 5 csgoserver csgoserver 4096 Aug  3 20:02 steamcmd
kilo062:/home# groups csgoserver
csgoserver : csgoserver
```
Sorry.  I don't know why it doesn't work. We will have to wait for others.

**Comment by UltimateByte** [comment]
The wheel thing must be related to how he gained sudo acces.

Did you try loging at root to chown ? Maybe your sudo access have insufficient permissions to change some ownerships.

As root : 
chown -R csgoserver:csgoserver /home/csgoserver

**Comment by m8wtf** [comment]
Yes, I tried that - http://i.imgur.com/rpX06E1.png

**Comment by dgibbs64** [comment]
try su - csgoserver looks like your in the /root dir

**Comment by m8wtf** [comment]
you said "As root:" 

I switch on the second line of the screenshot.

**Comment by m8wtf** [comment]
OOh shit, it worked, thank you :dancer: 


silly me.

**Comment by UltimateByte** [comment]
Protip : When you switch user, input "cd", in most distros, it'll take you to the user's home directory. :)

**Comment by dgibbs64** [comment]
:-P at least you know for next time. su user changes user but stays in the current dir. su - user changes user and moves to the users home dir.

**Comment by UltimateByte** [comment]
Huhu, didn't know that one @dgibbs64 , thanks :D
