### ISSUE TITLE
what happened to check_update.sh?

### ISSUE THREAD

**Issue by hurdad** [dgibbs64/linuxgsm#973]
missing in https://github.com/dgibbs64/linuxgsm/tree/master/lgsm/functions

**Comment by UltimateByte** [comment]
It's not needed anymore ;)
Since almost 1 month https://github.com/dgibbs64/linuxgsm/commit/462e54542f6cfbf4ff23e8d56d7fa48ae35e93c8#diff-75d83c196c84d4930862a52dfdd14628

https://github.com/dgibbs64/linuxgsm/blob/master/lgsm/functions/command_update.sh



If needed : `./gameserver uf`
