### ISSUE TITLE
CS:1.6 Server - generated configfiles are not used

### ISSUE THREAD

**Issue by Niedes** [dgibbs64/linuxgsm#975]
recently (in july 2016) i created a cs:1.6 from scratch (on an ubuntu 14.04 LTS server).
lsgm generated a cfg folder with the 3 .cfg files (cs-server.cfg, lsgm-default.cfg and server.cfg).
but these .cfg files are not used.
the server.cfg file in the parent cstrike folder is used

**Comment by UltimateByte** [comment]
We need to investigate, maybe gold source doesn't accept (anymore) forced cfg files.

**Comment by marvinl97** [comment]
Just tested it. CS1.6 isn't using a /serverfiles/cstrike/cfg directory for configs like CS:GO or CS:S. They are directly in /serverfiles/cstrike. Should be a easy fix? We just need to adjust the path in the main script.

**Comment by marvinl97** [comment]
Fixed in 220a720790d71477da8a9abd38ccae0eba339069
