### ISSUE TITLE
[Website Dependencies] bzip2

### ISSUE THREAD

**Issue by UltimateByte** [dgibbs64/linuxgsm#977]
Teamspeak and all .tar.bz2 exctracted servers (if any) require bzip2.
This needs to be added to the website.

**Comment by dgibbs64** [comment]
steamcmd.tar.gz is also used on all servers. So i think that all servers may require bzip2

**Comment by jach11** [comment]
Isn't .gz used by gzip?

**Comment by dgibbs64** [comment]
Thanks for confirming this for me. This would mean that gzip should be a required dependency.

**Comment by UltimateByte** [comment]
.tar.gz is gzip
.tar.bz2 is bzip2

If gzip is usually pre-installed, gzip2 is usually not. However, they are still both requirement for either steamcmd games or external .tar.bz2 server files such as ts3.

**Comment by jach11** [comment]
I found that gzip is usually always pre-installed, with bzip2 not always being installed by default, but it's definitely a good idea to have both as dependencies. It's also very useful to have bzip2 for people who use their server as a web host for FastDL and want to compress their files.

**Comment by UltimateByte** [comment]
That's it, everything has been said :)

**Comment by dgibbs64** [comment]
The website and the functions are now updated in dev branch.
