### ISSUE TITLE
an update check way

### ISSUE THREAD

**Issue by LiberBear** [dgibbs64/linuxgsm#978]
Is steam web api will be faster then steamcmd?
https://wiki.teamfortress.com/wiki/WebAPI/UpToDateCheck#Method-specific_parameters

**Comment by UltimateByte** [comment]
Well, that's a cool find and must-have to know. 
However : 
- It seems like it cannot support custom arguments or branches;
- Available build check is currently only one line of code : 
https://github.com/dgibbs64/linuxgsm/blob/master/lgsm/functions/update_steamcmd.sh#L157
- As steamcmd needs to be installed anyways and is in my opinion fast enough, i don't know if it'd be worth it. Maybe as a backup solution if steamcmd fails, but if it fails, chances are the update would fail too.

**Comment by dgibbs64** [comment]
I have seen this before. But decided that the SteamCMD opton works well enough and only takes a few seconds. I dont belive that it is worth developing this in to LGSM,

Thanks for the suggestion
