### ISSUE TITLE
Arma 3 Server GLIBC requirements up to 2.20

### ISSUE THREAD

**Issue by dgibbs64** [dgibbs64/linuxgsm#986]
LGSM currently sets GLIBC requirements at 2.13 however after investigating this in light og the gmod glibcfix issue is appears its gone up to 2.17. I am trying to get this working however I am getting seg faults. It may simply not be possible to get Arma 3 working with a GLIBC fix anymore. I will make further attempts however I may change the requirements and have ARMA 3 no longer supported on the likes of CentOS 6 with GLIBC fixes.

**Comment by jach11** [comment]
Users shouldn't expect to be able to run a 4 year old release of an OS and not run into any issues. Either install the new OS to meet the minimum requirements or start using a rolling distro.

**Comment by dgibbs64** [comment]
It used to work in CentOS 6 with the Glibc fix however it appears nto to anymore. I have just tested on Ubuntu 14.04 that uses Glibc 2.19 as well. That also failed with a seg fault. Can anyone confirm what version of Glibc is the min requirement for Arma 3 as I cannot confirm due to crappy documentation.

**Comment by jach11** [comment]
It looks like Glibc 2.20 is required but i haven't tested it yet.

**Comment by dgibbs64** [comment]
It's looking that way. Which means it's by far the highest requirement mist being 2.15. Once confirmed 2.20 I will attempt a glibc fix.

**Comment by jach11** [comment]
I tested it on Debian 9 with Glibc 2.23 and it works just fine.

**Comment by dgibbs64** [comment]
I have contacted Bohemia. Hopefully they will 100% confirm this for me as the only distro I can find using 2.20 is an old fedora build. I can confirm works on Ubunut 16.04 as well. However I would prefer confirm 2.20 is accurate rather than just guess.

**Comment by dgibbs64** [comment]
Just tested on Fedora 24. Gettign seg faults. Arma 3 server is a right pain.

**Comment by jach11** [comment]
I have gotten it to run on Cent OS 6.8 with Glibc-2.20 installed.

**Comment by dgibbs64** [comment]
I have figured out the issue on my end. My Test VPS RAM wasnt enough. Ouphs...I have added the system requirements to 1GB min so there is now a warning should the server have less that 1GB Glibc Requirements are still correct :)

**Comment by jach11** [comment]
Hah. That'll explain it.
