### ISSUE TITLE
Add Fedora alongside CentOS

### ISSUE THREAD

**Issue by dgibbs64** [dgibbs64/linuxgsm#988]
I am looking at adding fedora on to the website along side CentOS and add support for it as well. The only difference I can see so far is that is uses dnf instead of yum. Since CentOS will work with fewer servers over time I think its work adding fedora as a more "up-to-date" red hat distro.

**Comment by UltimateByte** [comment]
You're so tolerant about Red Hat distros... I admire you ! :p

**Comment by dgibbs64** [comment]
Thanks :P
