### ISSUE TITLE
Backup Command keeps failing

### ISSUE THREAD

**Issue by kbgvirus** [dgibbs64/linuxgsm#995]
Hi, I need some help as why when i run a backup on my arkserver it keeps failing.

```
if [ $? != 0 ]; then
	fn_print_ok_nl "Backup created: ${backupname}.tar.gz is $(du -sh "${backupdir}/${backupname}.tar.gz" | awk '{print $1}') size"
	fn_script_log_pass "Backup created: ${backupdir}/${backupname}.tar.gz is $(du -sh "${backupdir}/${backupname}.tar.gz" | awk '{print $1}') size"
else
	fn_print_error_nl "Backup failed: ${backupname}.tar.gz"
	fn_script_log_error "Backup failed: ${backupname}.tar.gz"
fi
sleep 1
echo ""
core_exit.sh
```

I changed the bash file to read

```

if [ $? == 0 ]; then
	fn_print_ok_nl "Backup created: ${backupname}.tar.gz is $(du -sh "${backupdir}/${backupname}.tar.gz" | awk '{print $1}') size"
	fn_script_log_pass "Backup created: ${backupdir}/${backupname}.tar.gz is $(du -sh "${backupdir}/${backupname}.tar.gz" | awk '{print $1}') size"
else
	fn_print_error_nl "Backup failed: ${backupname}.tar.gz"
	fn_script_log_error "Backup failed: ${backupname}.tar.gz"
fi
sleep 1
echo ""
core_exit.sh

```
and after that change it passes.

Thanks

**Comment by UltimateByte** [comment]
So you just changed `[ $? != 0 ]` to `[ $? == 0 ]` from this line ? https://github.com/dgibbs64/linuxgsm/blob/master/lgsm/functions/command_backup.sh#L50 ?

Yeah, makes more sense to me, as successful exit codes are generally 0. :p 
@dgibbs64 I'll commit directly this fix to master. :)

**Comment by UltimateByte** [comment]
Thanks for your notice.
Committed https://github.com/dgibbs64/linuxgsm/commit/2ad8b671a24ff019cd893a04b7e126bd5888e62d#diff-851d67b1a2d0860c529888143842a283
